<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.551">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Macroeconomic Principles - 10&nbsp; Economic Growth</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./ch11-AggregateDemandAggregateSupply.html" rel="next">
<link href="./ch9-ProductionFullEmployment.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script src="site_libs/quarto-contrib/glightbox/glightbox.min.js"></script>
<link href="site_libs/quarto-contrib/glightbox/glightbox.min.css" rel="stylesheet">
<link href="site_libs/quarto-contrib/glightbox/lightbox.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./ch5-MacroPerspective.html"><strong>Macroeconomics Part I</strong></a></li><li class="breadcrumb-item"><a href="./ch10-Growth.html"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Economic Growth</span></a></li></ol></nav>
        <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Macroeconomic Principles</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
 <span class="menu-text"><strong>Introduction</strong></span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ch1-Introduction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ch2-MathIntro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">The Use of Mathematics in Principles of Economics</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ch3-ChoiceScarcity.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Choice in a World of Scarcity</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ch4-DemandSupply.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Demand and Supply</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">
 <span class="menu-text"><strong>Macroeconomics Part I</strong></span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ch5-MacroPerspective.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Intro Macro Perspective</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ch6-InternationalTrade.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">International Trade</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ch7-Unemployment.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Unemployment</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ch8-Inflation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Inflation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ch9-ProductionFullEmployment.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Production Technology and Full Employment</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ch10-Growth.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Economic Growth</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ch11-AggregateDemandAggregateSupply.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Aggregate Demand and Aggregate Supply</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">
 <span class="menu-text"><strong>Macroeconomics Part II</strong></span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ch12-FiscalPolicy.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Government Budgets and Fiscal Policy</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ch13-IncomeExpenditureModel.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">The Income Expenditure Model</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ch14-InvestmentsFinancialMarkets.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Investments and Financial Markets</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ch15-MoneyAndBanking.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Money and Banking</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ch16-MonetaryPolicy.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Monetary Policy</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ch17-ShortToLong.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">From Short-Run to Long-Run</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendix-PythonBasics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">First Steps in Python</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#the-relatively-recent-arrival-of-economic-growth" id="toc-the-relatively-recent-arrival-of-economic-growth" class="nav-link active" data-scroll-target="#the-relatively-recent-arrival-of-economic-growth"><span class="header-section-number">10.1</span> The Relatively Recent Arrival of Economic Growth</a>
  <ul class="collapse">
  <li><a href="#rule-of-law-and-economic-growth" id="toc-rule-of-law-and-economic-growth" class="nav-link" data-scroll-target="#rule-of-law-and-economic-growth"><span class="header-section-number">10.1.1</span> Rule of Law and Economic Growth</a></li>
  </ul></li>
  <li><a href="#labor-productivity-and-economic-growth" id="toc-labor-productivity-and-economic-growth" class="nav-link" data-scroll-target="#labor-productivity-and-economic-growth"><span class="header-section-number">10.2</span> Labor Productivity and Economic Growth</a>
  <ul class="collapse">
  <li><a href="#sources-of-economic-growth-the-aggregate-production-function" id="toc-sources-of-economic-growth-the-aggregate-production-function" class="nav-link" data-scroll-target="#sources-of-economic-growth-the-aggregate-production-function"><span class="header-section-number">10.2.1</span> Sources of Economic Growth: The Aggregate Production Function</a></li>
  <li><a href="#components-of-the-aggregate-production-function" id="toc-components-of-the-aggregate-production-function" class="nav-link" data-scroll-target="#components-of-the-aggregate-production-function"><span class="header-section-number">10.2.2</span> Components of the Aggregate Production Function</a></li>
  <li><a href="#measuring-productivity" id="toc-measuring-productivity" class="nav-link" data-scroll-target="#measuring-productivity"><span class="header-section-number">10.2.3</span> Measuring Productivity</a></li>
  <li><a href="#the-new-economy-controversy" id="toc-the-new-economy-controversy" class="nav-link" data-scroll-target="#the-new-economy-controversy"><span class="header-section-number">10.2.4</span> The “New Economy” Controversy</a></li>
  <li><a href="#the-power-of-sustained-economic-growth" id="toc-the-power-of-sustained-economic-growth" class="nav-link" data-scroll-target="#the-power-of-sustained-economic-growth"><span class="header-section-number">10.2.5</span> The Power of Sustained Economic Growth</a></li>
  </ul></li>
  <li><a href="#components-of-economic-growth" id="toc-components-of-economic-growth" class="nav-link" data-scroll-target="#components-of-economic-growth"><span class="header-section-number">10.3</span> Components of Economic Growth</a>
  <ul class="collapse">
  <li><a href="#capital-deepening" id="toc-capital-deepening" class="nav-link" data-scroll-target="#capital-deepening"><span class="header-section-number">10.3.1</span> Capital Deepening</a></li>
  <li><a href="#growth-accounting-studies" id="toc-growth-accounting-studies" class="nav-link" data-scroll-target="#growth-accounting-studies"><span class="header-section-number">10.3.2</span> Growth Accounting Studies</a></li>
  <li><a href="#a-healthy-climate-for-economic-growth" id="toc-a-healthy-climate-for-economic-growth" class="nav-link" data-scroll-target="#a-healthy-climate-for-economic-growth"><span class="header-section-number">10.3.3</span> A Healthy Climate for Economic Growth</a></li>
  </ul></li>
  <li><a href="#economic-convergence" id="toc-economic-convergence" class="nav-link" data-scroll-target="#economic-convergence"><span class="header-section-number">10.4</span> Economic Convergence</a>
  <ul class="collapse">
  <li><a href="#arguments-favoring-convergence" id="toc-arguments-favoring-convergence" class="nav-link" data-scroll-target="#arguments-favoring-convergence"><span class="header-section-number">10.4.1</span> Arguments Favoring Convergence</a></li>
  <li><a href="#arguments-that-convergence-is-neither-inevitable-nor-likely" id="toc-arguments-that-convergence-is-neither-inevitable-nor-likely" class="nav-link" data-scroll-target="#arguments-that-convergence-is-neither-inevitable-nor-likely"><span class="header-section-number">10.4.2</span> Arguments That Convergence Is neither Inevitable nor Likely</a></li>
  <li><a href="#the-slowness-of-convergence" id="toc-the-slowness-of-convergence" class="nav-link" data-scroll-target="#the-slowness-of-convergence"><span class="header-section-number">10.4.3</span> The Slowness of Convergence</a></li>
  </ul></li>
  <li><a href="#growth-rates" id="toc-growth-rates" class="nav-link" data-scroll-target="#growth-rates"><span class="header-section-number">10.5</span> Growth Rates</a></li>
  <li><a href="#the-solow-growth-model" id="toc-the-solow-growth-model" class="nav-link" data-scroll-target="#the-solow-growth-model"><span class="header-section-number">10.6</span> The Solow Growth Model</a></li>
  <li><a href="#numerical-implementation-of-the-solow-growth-model" id="toc-numerical-implementation-of-the-solow-growth-model" class="nav-link" data-scroll-target="#numerical-implementation-of-the-solow-growth-model"><span class="header-section-number">10.7</span> Numerical Implementation of the Solow Growth Model</a></li>
  <li><a href="#python-code-for-plotting-capital-law-of-motion-and-steady-state" id="toc-python-code-for-plotting-capital-law-of-motion-and-steady-state" class="nav-link" data-scroll-target="#python-code-for-plotting-capital-law-of-motion-and-steady-state"><span class="header-section-number">10.8</span> Python Code for Plotting Capital Law of Motion and Steady State</a></li>
  <li><a href="#advanced-the-balanced-growth-path" id="toc-advanced-the-balanced-growth-path" class="nav-link" data-scroll-target="#advanced-the-balanced-growth-path"><span class="header-section-number">10.9</span> Advanced: The Balanced Growth Path</a>
  <ul class="collapse">
  <li><a href="#the-production-function" id="toc-the-production-function" class="nav-link" data-scroll-target="#the-production-function"><span class="header-section-number">10.9.1</span> The Production Function</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./ch5-MacroPerspective.html"><strong>Macroeconomics Part I</strong></a></li><li class="breadcrumb-item"><a href="./ch10-Growth.html"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Economic Growth</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Economic Growth</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<!--Economic Growth {{{1-->
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Chapter Learning Objectives
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>The Relatively Recent Arrival of Economic Growth</li>
<li>Labor Productivity and Economic Growth</li>
<li>Components of Economic Growth</li>
<li>Economic Convergence</li>
</ul>
</div>
</div>
<div id="a3be9337" class="cell" data-execution_count="1">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> os</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> seaborn <span class="im">as</span> sns</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>titleSize <span class="op">=</span> <span class="dv">18</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>legendSize <span class="op">=</span> <span class="dv">14</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>ylabelSize <span class="op">=</span> <span class="dv">14</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>tickSize <span class="op">=</span> <span class="dv">14</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>sns.set_style(<span class="st">"whitegrid"</span>, {<span class="st">'grid.linestyle'</span>: <span class="st">':'</span>})</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="co"># -----------------------------------------------------------------------------</span></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Load data</span></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>df_a <span class="op">=</span> pd.read_csv(<span class="st">'Graphs/Annual_FRED.csv'</span>, header<span class="op">=</span><span class="dv">0</span>, index_col<span class="op">=</span><span class="dv">0</span>, parse_dates<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>df_q <span class="op">=</span> pd.read_csv(<span class="st">'Graphs/Quarterly_FRED.csv'</span>, header<span class="op">=</span><span class="dv">0</span>, index_col<span class="op">=</span><span class="dv">0</span>, parse_dates<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>df_m <span class="op">=</span> pd.read_csv(<span class="st">'Graphs/Monthly_FRED.csv'</span>, header<span class="op">=</span><span class="dv">0</span>, index_col<span class="op">=</span><span class="dv">0</span>, parse_dates<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a><span class="co"># -----------------------------------------------------------------------------</span></span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>df_q[<span class="st">'ExportsTrill'</span>] <span class="op">=</span> df_q[<span class="st">'Exports'</span>]<span class="op">/</span><span class="dv">1000000</span></span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a>df_q[<span class="st">'ImportsTrill'</span>] <span class="op">=</span> df_q[<span class="st">'Imports'</span>]<span class="op">/</span><span class="dv">1000000</span></span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a>df_q[<span class="st">'GDPTrill'</span>] <span class="op">=</span> df_q[<span class="st">'GDP'</span>]<span class="op">/</span><span class="dv">1000</span></span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a>df_q[<span class="st">'GNPTrill'</span>] <span class="op">=</span> df_q[<span class="st">'GNP'</span>]<span class="op">/</span><span class="dv">1000</span></span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a>df_q[<span class="st">'realGDPTrill'</span>] <span class="op">=</span> df_q[<span class="st">'rGDP'</span>]<span class="op">/</span><span class="dv">1000</span></span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a>df_q[<span class="st">'ExportsGDP'</span>] <span class="op">=</span> (df_q[<span class="st">'Exports'</span>]<span class="op">/</span><span class="dv">1000</span>)<span class="op">/</span>df_q[<span class="st">'GDP'</span>]<span class="op">*</span><span class="dv">100</span></span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a>df_q[<span class="st">'ImportsGDP'</span>] <span class="op">=</span> (df_q[<span class="st">'Imports'</span>]<span class="op">/</span><span class="dv">1000</span>)<span class="op">/</span>df_q[<span class="st">'GDP'</span>]<span class="op">*</span><span class="dv">100</span></span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a>df_q[<span class="st">'TradeBalance'</span>] <span class="op">=</span> ((df_q[<span class="st">'Exports'</span>]<span class="op">-</span>df_q[<span class="st">'Imports'</span>])<span class="op">/</span><span class="dv">1000</span>)<span class="op">/</span>df_q[<span class="st">'GDP'</span>]<span class="op">*</span><span class="dv">100</span></span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a><span class="co"># -----</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>/tmp/ipykernel_552979/2094105227.py:17: UserWarning:

Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
</code></pre>
</div>
</div>
<p>Every country worries about economic growth. In the United States and other high-income countries, the question is whether economic growth continues to provide the same remarkable gains in our standard of living as it did during the twentieth century. Meanwhile, can middle-income countries like Brazil, Egypt, or Poland catch up to the higher-income countries, or must they remain in the second tier of per capita income? Of the world’s population of roughly 7.5 billion people, about 1.1 billion are scraping by on incomes that average less than $2 per day, not that different from the standard of living 2,000 years ago. Can the world’s poor be lifted from their fearful poverty?</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>As the 1995 Nobel laureate in economics, Robert E. Lucas Jr., once noted: “The consequences for human welfare involved in questions like these are simply staggering: Once one starts to think about them, it is hard to think about anything else.”</p>
</div>
</div>
<p>Dramatic improvements in a nation’s standard of living are possible. After the Korean War in the late 1950s, the Republic of Korea, often called South Korea, was one of the poorest economies in the world. Most South Koreans worked in peasant agriculture. According to the British economist Angus Maddison, who devoted life’s work to measuring GDP and population in the world economy, GDP per capita in 1990 international dollars was $854 per year. From the 1960s to the early twenty-first century, a time period well within the lifetime and memory of many adults, the South Korean economy grew rapidly. Over these four decades, GDP per capita increased by more than 6% per year. According to the World Bank, GDP for South Korea now exceeds $30,000 in nominal terms, placing it firmly among high-income countries like Italy, New Zealand, and Israel. Measured by total GDP in 2015, South Korea is the eleventh-largest economy in the world. For a nation of 50 million people, this transformation is extraordinary.</p>
<p>South Korea is a standout example, but it is not the only case of rapid and sustained economic growth. Other East Asian nations, like Thailand and Indonesia, have seen very rapid growth as well. China has grown enormously since it enacted market-oriented economic reforms around 1980. GDP per capita in high-income economies like the United States also has grown dramatically albeit over a longer time frame. Since the Civil War, the U.S. economy has transformed from a primarily rural and agricultural economy to an economy based on services, manufacturing, and technology.</p>
<p><a href="#fig-nomrealgdp" class="quarto-xref">Figure&nbsp;<span>10.1</span></a> and shows nominal and real GDP over time for the US economy and <a href="#fig-nomreal-gdp-growth" class="quarto-xref">Figure&nbsp;<span>10.2</span></a> shows the respective annual growth rates.</p>
<div id="cell-fig-nomrealgdp" class="cell" data-execution_count="2">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>df_q[[<span class="st">'GDPTrill'</span>, <span class="st">'realGDPTrill'</span>]].plot(style <span class="op">=</span> [<span class="st">'-'</span>, <span class="st">'--'</span>])</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Nominal and Real US-GDP'</span>, fontsize<span class="op">=</span>titleSize)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'in Trillion US $'</span>)</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<div id="fig-nomrealgdp" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-nomrealgdp-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="ch10-Growth_files/figure-html/fig-nomrealgdp-output-1.png" class="lightbox" data-glightbox="description: .lightbox-desc-1" data-gallery="quarto-lightbox-gallery-1"><img src="ch10-Growth_files/figure-html/fig-nomrealgdp-output-1.png" width="582" height="453" class="figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-nomrealgdp-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;10.1: Nominal vs.&nbsp;Real GDP
</figcaption>
</figure>
</div>
</div>
</div>
<div id="cell-fig-nomreal-gdp-growth" class="cell" data-execution_count="3">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>(df_q[[<span class="st">'rGDP'</span>, <span class="st">'GDP'</span>]].loc[<span class="st">'1960'</span>::].pct_change(periods<span class="op">=</span><span class="dv">4</span>)<span class="op">*</span><span class="dv">100</span>).plot(style <span class="op">=</span> [<span class="st">'-'</span>, <span class="st">'--'</span>])</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'U.S. GDP Annual Growth Rates'</span>, fontsize<span class="op">=</span>titleSize)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>plt.axhline(y<span class="op">=</span><span class="dv">0</span>, xmin<span class="op">=</span><span class="dv">0</span>, xmax<span class="op">=</span><span class="dv">2020</span>, linewidth<span class="op">=</span><span class="dv">1</span>, linestyle<span class="op">=</span><span class="st">'--'</span>, color<span class="op">=</span><span class="st">'black'</span>)</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'%'</span>)</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<div id="fig-nomreal-gdp-growth" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-nomreal-gdp-growth-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="ch10-Growth_files/figure-html/fig-nomreal-gdp-growth-output-1.png" class="lightbox" data-glightbox="description: .lightbox-desc-2" data-gallery="quarto-lightbox-gallery-2"><img src="ch10-Growth_files/figure-html/fig-nomreal-gdp-growth-output-1.png" width="582" height="453" class="figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-nomreal-gdp-growth-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;10.2: Nominal vs.&nbsp;Real GDP Growth Rates
</figcaption>
</figure>
</div>
</div>
</div>
<p>We observe a steady increase in GDP over time with an average growth rate of about 3 percent over last 80 or so years. The growth rate fluctuates quite a bit with a large negative spike in 2020 due to the COVID pandemic.</p>
<div id="fig-G_000" class="align-center quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-G_000-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="Graphs/Growth/CNX_Econ_C20_000.jpg" class="lightbox" data-glightbox="description: .lightbox-desc-3" data-gallery="quarto-lightbox-gallery-3"><img src="Graphs/Growth/CNX_Econ_C20_000.jpg" class="align-center img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-G_000-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;10.3: Not only has the number of calories that people consume per day increased, so has the amount of food calories that people are able to afford based on their working wages. (Credit: modification of work by Lauren Manning/Flickr Creative Commons)
</figcaption>
</figure>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>CALORIES AND ECONOMIC GROWTH</p>
<p>On average, humans need about 2,500 calories a day to survive, depending on height, weight, and gender. The economist Brad DeLong estimates that the average worker in the early 1600s earned wages that could afford him 2,500 food calories. This worker lived in Western Europe. Two hundred years later, that same worker could afford 3,000 food calories. However, between 1800 and 1875, just a time span of just 75 years, economic growth was so rapid that western European workers could purchase 5,000 food calories a day. By 2012, a low skilled worker in an affluent Western European/North American country could afford to purchase 2.4 million food calories per day.</p>
<p>What caused such a rapid rise in living standards between 1800 and 1875 and thereafter? Why is it that many countries, especially those in Western Europe, North America, and parts of East Asia, can feed their populations more than adequately, while others cannot? We will look at these and other questions as we examine long-run economic growth.</p>
</div>
</div>
<!--The Relatively Recent Arrival of Economic Growth {{{2-->
<section id="the-relatively-recent-arrival-of-economic-growth" class="level2" data-number="10.1">
<h2 data-number="10.1" class="anchored" data-anchor-id="the-relatively-recent-arrival-of-economic-growth"><span class="header-section-number">10.1</span> The Relatively Recent Arrival of Economic Growth</h2>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Chapter Learning Objectives
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>Explain the conditions that have allowed for modern economic growth in the last two centuries</li>
<li>Analyze the influence of public policies on an economy's long-run economic growth</li>
</ul>
</div>
</div>
<p>Let’s begin with a brief overview of spectacular economic growth patterns around the world in the last two centuries. We commonly refer to this as the period of modern economic growth. (Later in the chapter we will discuss lower economic growth rates and some key ingredients for economic progress.) Rapid and sustained economic growth is a relatively recent experience for the human race. Before the last two centuries, although rulers, nobles, and conquerors could afford some extravagances and although economies rose above the subsistence level, the average person’s standard of living had not changed much for centuries.</p>
<p>Progressive, powerful economic and institutional changes started to have a significant effect in the late eighteenth and early nineteenth centuries. According to the Dutch economic historian Jan Luiten van Zanden, slavery-based societies, favorable demographics, global trading routes, and standardized trading institutions that spread with different empires set the stage for the Industrial Revolution to succeed. The Industrial Revolution refers to the widespread use of power-driven machinery and the economic and social changes that resulted in the first half of the 1800s. Ingenious machines—the steam engine, the power loom, and the steam locomotive—performed tasks that otherwise would have taken vast numbers of workers to do. The Industrial Revolution began in Great Britain, and soon spread to the United States, Germany, and other countries.</p>
<p>The jobs for ordinary people working with these machines were often dirty and dangerous by modern standards, but the alternative jobs of that time in peasant agriculture and small-village industry were often dirty and dangerous, too. The new jobs of the Industrial Revolution typically offered higher pay and a chance for social mobility. A self-reinforcing cycle began: New inventions and investments generated profits, the profits provided funds for more new investment and inventions, and the investments and inventions provided opportunities for further profits. Slowly, a group of national economies in Europe and North America emerged from centuries of sluggishness into a period of rapid modern growth. During the last two centuries, the average GDP growth rate per capita in the leading industrialized countries has been about 2% per year. What were times like before then? Read the following Clear It Up feature for the answer.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>WHAT WERE ECONOMIC CONDITIONS LIKE BEFORE 1870?</p>
<p>Angus Maddison, a quantitative economic historian, led the most systematic inquiry into national incomes before 1870. Economists recently have refined and used his methods to compile GDP per capita estimates from year 1 C.E. (Note: C.E. stands for "Common Era" it's the religion free expression for A.D. which stands for "Anno Domini") to 1348. Table <a href="#tbl-G_001" class="quarto-xref">Table&nbsp;<span>10.1</span></a> is an important counterpoint to most of the narrative in this chapter. It shows that nations can decline as well as rise. A wide array of forces, such as epidemics, natural and weather-related disasters, the inability to govern large empires, and the remarkably slow pace of technological and institutional progress explain declines in income. Institutions are the traditions and laws by which people in a community agree to behave and govern themselves. Such institutions include marriage, religion, education, and laws of governance. Institutional progress is the development and codification of these institutions to reinforce social order, and thus, economic growth.</p>
<p>One example of such an institution is the Magna Carta (Great Charter), which the English nobles forced King John to sign in 1215. The Magna Carta codified the principles of due process, whereby a free man could not be penalized unless his peers had made a lawful judgment against him. The United States in its own constitution later adopted this concept. This social order may have contributed to England’s GDP per capita in 1348, which was second to that of northern Italy.</p>
<p>In studying economic growth, a country’s institutional framework plays a critical role. <a href="#tbl-G_001" class="quarto-xref">Table&nbsp;<span>10.1</span></a> also shows relative global equality for almost 1,300 years. After this, we begin to see significant divergence in income (not in the table).</p>
<div id="tbl-G_001" class="quarto-float anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-G_001-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;10.1: GDP Per Capita Estimates in Current International Dollars from AD 1 to 1348 (Source: Bolt and van Zanden. The First Update of the Maddison Project. Re-Estimating Growth Before 1820. 2013)
</figcaption>
<div aria-describedby="tbl-G_001-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="table">
<thead>
<tr class="header">
<th style="text-align: left;">Year</th>
<th style="text-align: left;">North-Italy</th>
<th style="text-align: left;">Spain</th>
<th style="text-align: left;">England</th>
<th style="text-align: left;">Holland</th>
<th style="text-align: left;">Byzantium</th>
<th style="text-align: left;">Iraq</th>
<th style="text-align: left;">Egypt</th>
<th style="text-align: left;">Japan</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1</td>
<td style="text-align: left;">$800</td>
<td style="text-align: left;">$600</td>
<td style="text-align: left;">$600</td>
<td style="text-align: left;">$600</td>
<td style="text-align: left;">$700</td>
<td style="text-align: left;">$700</td>
<td style="text-align: left;">$700</td>
<td style="text-align: left;">-</td>
</tr>
<tr class="even">
<td style="text-align: left;">730</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">$920</td>
<td style="text-align: left;">$730</td>
<td style="text-align: left;">$402</td>
</tr>
<tr class="odd">
<td style="text-align: left;">1000</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">$600</td>
<td style="text-align: left;">$820</td>
<td style="text-align: left;">$600</td>
<td style="text-align: left;">-</td>
</tr>
<tr class="even">
<td style="text-align: left;">1150</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">$580</td>
<td style="text-align: left;">$680</td>
<td style="text-align: left;">$660</td>
<td style="text-align: left;">$520</td>
</tr>
<tr class="odd">
<td style="text-align: left;">1280</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">$670</td>
<td style="text-align: left;">$527</td>
</tr>
<tr class="even">
<td style="text-align: left;">1300</td>
<td style="text-align: left;">$1,588</td>
<td style="text-align: left;">$864</td>
<td style="text-align: left;">$892</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">$610</td>
<td style="text-align: left;">-</td>
</tr>
<tr class="odd">
<td style="text-align: left;">1348</td>
<td style="text-align: left;">$1,486</td>
<td style="text-align: left;">$907</td>
<td style="text-align: left;">$919</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>Another fascinating and underreported fact is the high levels of income, compared to others at that time, attained by the Islamic Empire Abbasid Caliphate—which was founded in present-day Iraq in 730 C.E. At its height, the empire spanned large regions of the Middle East, North Africa, and Spain until its gradual decline over 200 years.</p>
</div>
</div>
<p>The Industrial Revolution led to increasing inequality among nations. Some economies took off, whereas others, like many of those in Africa or Asia, remained close to a subsistence standard of living. General calculations show that the 17 countries of the world with the most-developed economies had, on average, 2.4 times the GDP per capita of the world’s poorest economies in 1870. By 1960, the most developed economies had 4.2 times the GDP per capita of the poorest economies.</p>
<p>However, by the middle of the twentieth century, some countries had shown that catching up was possible. Japan’s economic growth took off in the 1960s and 1970s, with a growth rate of real GDP per capita averaging 11% per year during those decades. Certain countries in Latin America experienced a boom in economic growth in the 1960s as well. In Brazil, for example, GDP per capita expanded by an average annual rate of 11.1% from 1968 to 1973. In the 1970s, some East Asian economies, including South Korea, Thailand, and Taiwan, saw rapid growth. In these countries, growth rates of 11% to 12% per year in GDP per capita were not uncommon. More recently, China, with its population of nearly 1.4 billion people, grew at a per capita rate 9% per year from 1984 into the 2000s. India, with a population of 1.3 billion, has shown promising signs of economic growth, with growth in GDP per capita of about 4% per year during the 1990s and climbing toward 7% to 8% per year in the 2000s.</p>
<p>These waves of catch-up economic growth have not reached all shores. In certain African countries like Niger, Tanzania, and Sudan, for example, GDP per capita at the start of the 2000s was still less than $300, not much higher than it was in the nineteenth century and for centuries before that. In the context of the overall situation of low-income people around the world, the good economic news from China (population: 1.4 billion) and India (population: 1.3 billion) is, nonetheless, astounding and heartening.</p>
<p>Economic growth in the last two centuries has made a striking change in the human condition. Richard Easterlin, an economist at the University of Southern California, wrote in 2000:</p>
<p>By many measures, a revolution in the human condition is sweeping the world. Most people today are better fed, clothed, and housed than their predecessors two centuries ago. They are healthier, live longer, and are better educated. Women’s lives are less centered on reproduction and political democracy has gained a foothold. Although Western Europe and its offshoots have been the leaders of this advance, most of the less developed nations have joined in during the 20th century, with the newly emerging nations of sub-Saharan Africa the latest to participate. Although the picture is not one of universal progress, it is the greatest advance in the human condition of the world’s population ever achieved in such a brief span of time.</p>
<section id="rule-of-law-and-economic-growth" class="level3" data-number="10.1.1">
<h3 data-number="10.1.1" class="anchored" data-anchor-id="rule-of-law-and-economic-growth"><span class="header-section-number">10.1.1</span> Rule of Law and Economic Growth</h3>
<p>Economic growth depends on many factors. Key among those factors is adherence to the rule of law and protection of property rights and contractual rights by a country’s government so that markets can work effectively and efficiently. Laws must be clear, public, fair, enforced, and equally applicable to all members of society. Property rights, as you might recall from Environmental Protection and Negative Externalities are the rights of individuals and firms to own property and use it as they see fit. If you have $100, you have the right to use that money, whether you spend it, lend it, or keep it in a jar. It is your property. The definition of property includes physical property as well as the right to your training and experience, especially since your training is what determines your livelihood. Using this property includes the right to enter into contracts with other parties with your property. Individuals or firms must own the property to enter into a contract.</p>
<p>Contractual rights, then, are based on property rights and they allow individuals to enter into agreements with others regarding the use of their property providing recourse through the legal system in the event of noncompliance. One example is the employment agreement: a skilled surgeon operates on an ill person and expects payment. Failure to pay would constitute property theft by the patient. The theft is property the services that the surgeon provided. In a society with strong property rights and contractual rights, the terms of the patient–surgeon contract will be fulfilled, because the surgeon would have recourse through the court system to extract payment from that individual. Without a legal system that enforces contracts, people would not be likely to enter into contracts for current or future services because of the risk of non-payment. This would make it difficult to transact business and would slow economic growth.</p>
<p>The World Bank considers a country’s legal system effective if it upholds property rights and contractual rights. The World Bank has developed a ranking system for countries’ legal systems based on effective protection of property rights and rule-based governance using a scale from 1 to 6, with 1 being the lowest and 6 the highest rating. In 2013, the world average ranking was 2.9. The three countries with the lowest ranking of 1.5 were Afghanistan, the Central African Republic, and Zimbabwe. Their GDP per capita was $679, $333, and $1,007 respectively. The World Bank cites Afghanistan as having a low standard of living, weak government structure, and lack of adherence to the rule of law, which has stymied its economic growth. The landlocked Central African Republic has poor economic resources as well as political instability and is a source of children used in human trafficking. Zimbabwe has had declining and often negative growth for much of the period since 1998. Land redistribution and price controls have disrupted the economy, and corruption and violence have dominated the political process. Although global economic growth has increased, those countries lacking a clear system of property rights and an independent court system free from corruption have lagged far behind.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Key Concepts and Summary
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>Since the early nineteenth century, there has been a spectacular process of long-run economic growth during which the world’s leading economies—mostly those in Western Europe and North America—expanded GDP per capita at an average rate of about 2% per year.</li>
<li>In the last half-century, countries like Japan, South Korea, and China have shown the potential to catch up. The Industrial Revolution facilitated the extensive process of economic growth, that economists often refer to as modern economic growth.</li>
<li>This increased worker productivity and trade, as well as the development of governance and market institutions.</li>
</ul>
</div>
</div>
<div class="callout callout-style-default callout-caution callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-7-contents" aria-controls="callout-7" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Self-Check Questions
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-7" class="callout-7-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ul>
<li>Explain what the Industrial Revolution was and where it began.</li>
<li>Explain the difference between property rights and contractual rights. Why do they matter to economic growth?</li>
<li>How did the Industrial Revolution increase the economic growth rate and income levels in the United States?</li>
<li>How much should a nation be concerned if its rate of economic growth is just 2% slower than other nations?</li>
<li>Over the past 50 years, many countries have experienced an annual growth rate in real GDP per capita greater than that of the United States. Some examples are China, Japan, South Korea, and Taiwan. Does that mean the United States is regressing relative to other countries? Does that mean these countries will eventually overtake the United States in terms of the growth rate of real GDP per capita? Explain.</li>
</ul>
</div>
</div>
</div>
<!--Labor Productivity and Economic Growth {{{2-->
</section>
</section>
<section id="labor-productivity-and-economic-growth" class="level2" data-number="10.2">
<h2 data-number="10.2" class="anchored" data-anchor-id="labor-productivity-and-economic-growth"><span class="header-section-number">10.2</span> Labor Productivity and Economic Growth</h2>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Section Learning Objectives
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>Identify the role of labor productivity in promoting economic growth</li>
<li>Analyze the sources of economic growth using the aggregate production function</li>
<li>Measure an economy’s rate of productivity growth</li>
<li>Evaluate the power of sustained growth</li>
</ul>
</div>
</div>
<p>Sustained long-term economic growth comes from increases in worker productivity, which essentially means how well we do things. In other words, how efficient is your nation with its time and workers? Labor productivity is the value that each employed person creates per unit of his or her input. The easiest way to comprehend labor productivity is to imagine a Canadian worker who can make 10 loaves of bread in an hour versus a U.S. worker who in the same hour can make only two loaves of bread. In this fictional example, the Canadians are more productive. More productivity essentially means you can do more in the same amount of time. This in turn frees up resources for workers to use elsewhere.</p>
<p>What determines how productive workers are? The answer is pretty intuitive. The first determinant of labor productivity is human capital. Human capital is the accumulated knowledge (from education and experience), skills, and expertise that the average worker in an economy possesses. Typically the higher the average level of education in an economy, the higher the accumulated human capital and the higher the labor productivity.</p>
<p>The second factor that determines labor productivity is technological change. Technological change is a combination of invention—advances in knowledge—and innovation, which is putting those advances to use in a new product or service. For example, the transistor was invented in 1947. It allowed us to miniaturize the footprint of electronic devices and use less power than the tube technology that came before it. Innovations since then have produced smaller and better transistors that are ubiquitous in products as varied as smart-phones, computers, and escalators. Developing the transistor has allowed workers to be anywhere with smaller devices. People can use these devices to communicate with other workers, measure product quality or do any other task in less time, improving worker productivity.</p>
<p>The third factor that determines labor productivity is economies of scale. Recall that economies of scale are the cost advantages that industries obtain due to size. (Read more about economies of scale in Production, Cost and Industry Structure.) Consider again the case of the fictional Canadian worker who could produce 10 loaves of bread in an hour. If this difference in productivity was due only to economies of scale, it could be that the Canadian worker had access to a large industrial-size oven while the U.S. worker was using a standard residential size oven.</p>
<p>Now that we have explored the determinants of worker productivity, let’s turn to how economists measure economic growth and productivity.</p>
<section id="sources-of-economic-growth-the-aggregate-production-function" class="level3" data-number="10.2.1">
<h3 data-number="10.2.1" class="anchored" data-anchor-id="sources-of-economic-growth-the-aggregate-production-function"><span class="header-section-number">10.2.1</span> Sources of Economic Growth: The Aggregate Production Function</h3>
<p>To analyze the sources of economic growth, it is useful to think about a production function, which is the technical relationship by which economic inputs like labor, machinery, and raw materials like goods and services that consumers use.</p>
<p>A microeconomic production function describes a firm's or perhaps an industry's inputs and outputs. In macroeconomics, we call the connection from inputs to outputs for the entire economy an aggregate production function.</p>
</section>
<section id="components-of-the-aggregate-production-function" class="level3" data-number="10.2.2">
<h3 data-number="10.2.2" class="anchored" data-anchor-id="components-of-the-aggregate-production-function"><span class="header-section-number">10.2.2</span> Components of the Aggregate Production Function</h3>
<p>Economists construct different production functions depending on the focus of their studies. <a href="#fig-G_001" class="quarto-xref">Figure&nbsp;<span>10.4</span></a> presents two examples of aggregate production functions. In the first production function in <a href="#fig-G_001" class="quarto-xref">Figure&nbsp;<span>10.4</span></a> (a), the output is GDP. The inputs in this example are workforce, human capital, physical capital, and technology. We discuss these inputs further in the module, Components of Economic Growth.</p>
<div id="fig-G_001" class="align-center quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-G_001-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="Graphs/Growth/CNX_Econ_C20_003.jpg" class="lightbox" data-glightbox="description: .lightbox-desc-4" data-gallery="quarto-lightbox-gallery-4"><img src="Graphs/Growth/CNX_Econ_C20_003.jpg" class="align-center img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-G_001-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;10.4: An aggregate production function shows what goes into producing the output for an overall economy. (a) This aggregate production function has GDP as its output. (b) This aggregate production function has GDP per capita as its output. Because we calculate it on a per-person basis, we already figure the labor input into the other factors and we do not need to list it separately.
</figcaption>
</figure>
</div>
</section>
<section id="measuring-productivity" class="level3" data-number="10.2.3">
<h3 data-number="10.2.3" class="anchored" data-anchor-id="measuring-productivity"><span class="header-section-number">10.2.3</span> Measuring Productivity</h3>
<p>An economy’s rate of productivity growth is closely linked to the growth rate of its GDP per capita, although the two are not identical. For example, if the percentage of the population who holds jobs in an economy increases, GDP per capita will increase but the productivity of individual workers may not be affected. Over the long term, the only way that GDP per capita can grow continually is if the productivity of the average worker rises or if there are complementary increases in capital.</p>
<p>A common measure of U.S. productivity per worker is dollar value per hour the worker contributes to the employer’s output. This measure excludes government workers, because their output is not sold in the market and so their productivity is hard to measure. It also excludes farming, which accounts for only a relatively small share of the U.S. economy. <a href="#fig-G_002" class="quarto-xref">Figure&nbsp;<span>10.5</span></a> shows an index of output per hour, with 2009 as the base year (when the index equals 100). The index equaled about 106 in 2014. In 1972, the index equaled 50, which shows that workers have more than doubled their productivity since then.</p>
<div id="fig-G_002" class="align-center quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-G_002-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="Graphs/Growth/CNX_Econv1-2_C20_03.jpg" class="lightbox" data-glightbox="description: .lightbox-desc-5" data-gallery="quarto-lightbox-gallery-5"><img src="Graphs/Growth/CNX_Econv1-2_C20_03.jpg" class="align-center img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-G_002-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;10.5: Output per hour worked is a measure of worker productivity. In the U.S. economy, worker productivity rose more quickly in the 1960s and the mid-1990s compared with the 1970s and 1980s. However, these growth-rate differences are only a few percentage points per year. Look carefully to see them in the changing slope of the line. The average U.S. worker produced over twice as much per hour in 2014 than he did in the early 1970s. (Source: U.S. Department of Labor, Bureau of Labor Statistics.)
</figcaption>
</figure>
</div>
<p>According to the Department of Labor, U.S. productivity growth was fairly strong in the 1950s but then declined in the 1970s and 1980s before rising again in the second half of the 1990s and the first half of the 2000s. In fact, the rate of productivity measured by the change in output per hour worked averaged 3.2% per year from 1950 to 1970; dropped to 1.9% per year from 1970 to 1990; and then climbed back to over 2.3% from 1991 to the present, with another modest slowdown after 2001. <a href="#fig-G_003" class="quarto-xref">Figure&nbsp;<span>10.6</span></a> shows average annual rates of productivity growth averaged over time since 1950.</p>
<div id="fig-G_003" class="align-center quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-G_003-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="Graphs/Growth/CNX_Econ2e_C20_04.jpg" class="lightbox" data-glightbox="description: .lightbox-desc-6" data-gallery="quarto-lightbox-gallery-6"><img src="Graphs/Growth/CNX_Econ2e_C20_04.jpg" class="align-center img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-G_003-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;10.6: U.S. growth in worker productivity was very high between 1950 and 1970. It then declined to lower levels in the 1970s and the 1980s. The late 1990s and early 2000s saw productivity rebound, but then productivity sagged a bit in the 2000s. Some think the productivity rebound of the late 1990s and early 2000s marks the start of a “new economy” built on higher productivity growth, but we cannot determine this until more time has passed. (Source: U.S. Department of Labor, Bureau of Labor Statistics.)
</figcaption>
</figure>
</div>
</section>
<section id="the-new-economy-controversy" class="level3" data-number="10.2.4">
<h3 data-number="10.2.4" class="anchored" data-anchor-id="the-new-economy-controversy"><span class="header-section-number">10.2.4</span> The “New Economy” Controversy</h3>
<p>In recent years a controversy has been brewing among economists about the resurgence of U.S. productivity in the second half of the 1990s. One school of thought argues that the United States had developed a “new economy” based on the extraordinary advances in communications and information technology of the 1990s. The most optimistic proponents argue that it would generate higher average productivity growth for decades to come. The pessimists, alternatively, argue that even five or ten years of stronger productivity growth does not prove that higher productivity will last for the long term. It is hard to infer anything about long-term productivity trends during the later part of the 2000s, because the steep 2008-2009 recession, with its sharp but not completely synchronized declines in output and employment, complicates any interpretation. While productivity growth was high in 2009 and 2010 (around 3%), it has slowed down since then.</p>
<p>Productivity growth is also closely linked to the average level of wages. Over time, the amount that firms are willing to pay workers will depend on the value of the output those workers produce. If a few employers tried to pay their workers less than what those workers produced, then those workers would receive offers of higher wages from other profit-seeking employers. If a few employers mistakenly paid their workers more than what those workers produced, those employers would soon end up with losses. In the long run, productivity per hour is the most important determinant of the average wage level in any economy. To learn how to compare economies in this regard, follow the steps in the following Work It Out feature.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>COMPARING THE ECONOMIES OF TWO COUNTRIES</p>
<p>The Organization for Economic Co-operation and Development (OECD) tracks data on the annual growth rate of real GDP per hour worked. You can find these data on the OECD data webpage “Growth in GDP per capita, productivity and ULC” at this website.</p>
<dl>
<dt>Step 1.</dt>
<dd>
<p>Visit the OECD website given above and select two countries to compare.</p>
</dd>
<dt>Step 2.</dt>
<dd>
<p>On the drop-down menu “Subject,” select ” GDP per capita, constant prices,” and under “Measure,” select “Annual growth/change.” Then record the data for the countries you have chosen for the five most recent years.</p>
</dd>
<dt>Step 3.</dt>
<dd>
<p>Go back to the drop-down “Subject” menu and select “GDP per hour worked, constant prices,” and under “Measure” again select “Annual growth/change.” Select data for the same years for which you selected GDP per capita data.</p>
</dd>
<dt>Step 4.</dt>
<dd>
<p>Compare real GDP growth for both countries. The following tables provide an example of a comparison between Belgium and Canada.</p>
</dd>
</dl>
<table class="table">
<thead>
<tr class="header">
<th style="text-align: left;">Australia</th>
<th style="text-align: left;">2011</th>
<th style="text-align: left;">2012</th>
<th style="text-align: left;">2013</th>
<th style="text-align: left;">2014</th>
<th style="text-align: left;">2015</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Real GDP/Capita Growth (%)</td>
<td style="text-align: left;">2.3%</td>
<td style="text-align: left;">1.5%</td>
<td style="text-align: left;">1.3%</td>
<td style="text-align: left;">1.4</td>
<td style="text-align: left;">0.1%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Real GDP Growth/Hours Worked (%)</td>
<td style="text-align: left;">1.7%</td>
<td style="text-align: left;">−0.1%</td>
<td style="text-align: left;">1.4%</td>
<td style="text-align: left;">2.2%</td>
<td style="text-align: left;">−0.2%</td>
</tr>
</tbody>
</table>
<table class="table">
<thead>
<tr class="header">
<th style="text-align: left;">Belgium</th>
<th style="text-align: left;">2011</th>
<th style="text-align: left;">2012</th>
<th style="text-align: left;">2013</th>
<th style="text-align: left;">2014</th>
<th style="text-align: left;">2015</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Real GDP/Capita Growth (%)</td>
<td style="text-align: left;">0.9</td>
<td style="text-align: left;">−0.6</td>
<td style="text-align: left;">−0.5</td>
<td style="text-align: left;">1.2</td>
<td style="text-align: left;">1.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Real GDP Growth/Hours Worked (%)</td>
<td style="text-align: left;">−0.5</td>
<td style="text-align: left;">−0.3</td>
<td style="text-align: left;">0.4</td>
<td style="text-align: left;">1.4</td>
<td style="text-align: left;">0.9</td>
</tr>
</tbody>
</table>
<dl>
<dt>Step 5.</dt>
<dd>
<p>For both measures, growth in Canada is greater than growth in Belgium for the first four years. In addition, there are year-to-year fluctuations. Many factors can affect growth. For example, one factor that may have contributed to Canada’s stronger growth may be its larger inflows of immigrants, who generally contribute to economic growth.</p>
</dd>
</dl>
</div>
</div>
</section>
<section id="the-power-of-sustained-economic-growth" class="level3" data-number="10.2.5">
<h3 data-number="10.2.5" class="anchored" data-anchor-id="the-power-of-sustained-economic-growth"><span class="header-section-number">10.2.5</span> The Power of Sustained Economic Growth</h3>
<p>Nothing is more important for people’s standard of living than sustained economic growth. Even small changes in the rate of growth, when sustained and compounded over long periods of time, make an enormous difference in the standard of living. Consider Table, in which the rows of the table show several different rates of growth in GDP per capita and the columns show different periods of time. Assume for simplicity that an economy starts with a GDP per capita of 100. The table then applies the following formula to calculate what GDP will be at the given growth rate in the future:</p>
<p><span class="math display">\[\text{GDP at starting date} \times (1 + \text{growth rate of GDP})^{\text{years}} = \text{GDP at end date}\]</span></p>
<p>For example, an economy that starts with a GDP of 100 and grows at 3% per year will reach a GDP of 209 after 25 years; that is,</p>
<p><span class="math display">\[100 \times (1.03)^25 = 209.\]</span></p>
<p>The slowest rate of GDP per capita growth in the table, just 1% per year, is similar to what the United States experienced during its weakest years of productivity growth. The second highest rate, 3% per year, is close to what the U.S. economy experienced during the strong economy of the late 1990s and into the 2000s. Higher rates of per capita growth, such as 5% or 8% per year, represent the experience of rapid growth in economies like Japan, Korea, and China.</p>
<p><a href="#tbl-G_002" class="quarto-xref">Table&nbsp;<span>10.2</span></a> shows that even a few percentage points of difference in economic growth rates will have a profound effect if sustained and compounded over time. For example, an economy growing at a 1% annual rate over 50 years will see its GDP per capita rise by a total of 64%, from 100 to 164 in this example.</p>
<p>However, a country growing at a 5% annual rate will see (almost) the same amount of growth—from 100 to 163—over just 10 years. Rapid rates of economic growth can bring profound transformation. (See the following Clear It Up feature on the relationship between compound growth rates and compound interest rates.) If the rate of growth is 8%, young adults starting at age 20 will see the average standard of living in their country more than double by the time they reach age 30, and grow nearly sixfold by the time they reach age 45.</p>
<div id="tbl-G_002" class="quarto-float anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-G_002-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;10.2: Growth of GDP over Different Time Horizons
</figcaption>
<div aria-describedby="tbl-G_002-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="table">
<thead>
<tr class="header">
<th style="text-align: left;">Growth Rate</th>
<th style="text-align: left;">Value of 100 in 10 Years</th>
<th style="text-align: left;">Value of 100 in 25 Years</th>
<th style="text-align: left;">Value of 100 in 50 Years</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1%</td>
<td style="text-align: left;">110</td>
<td style="text-align: left;">128</td>
<td style="text-align: left;">164</td>
</tr>
<tr class="even">
<td style="text-align: left;">3%</td>
<td style="text-align: left;">134</td>
<td style="text-align: left;">209</td>
<td style="text-align: left;">438</td>
</tr>
<tr class="odd">
<td style="text-align: left;">5%</td>
<td style="text-align: left;">163</td>
<td style="text-align: left;">339</td>
<td style="text-align: left;">1,147</td>
</tr>
<tr class="even">
<td style="text-align: left;">8%</td>
<td style="text-align: left;">216</td>
<td style="text-align: left;">685</td>
<td style="text-align: left;">4,690</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>HOW ARE COMPOUND GROWTH RATES AND COMPOUND INTEREST RATES RELATED?</p>
<p>The formula for GDP growth rates over different periods of time, as Figure shows, is exactly the same as the formula for how a given amount of financial savings grows at a certain interest rate over time, as presented in Choice in a World of Scarcity. Both formulas have the same ingredients:</p>
<ul>
<li>an original starting amount, in one case GDP and in the other case an amount of financial saving;</li>
<li>a percentage increase over time, in one case the GDP growth rate and in the other case an interest rate;</li>
<li>and an amount of time over which this effect happens.</li>
</ul>
<p>Recall that compound interest is interest that is earned on past interest. It causes the total amount of financial savings to grow dramatically over time. Similarly, compound rates of economic growth, or the compound growth rate, means that we multiply the rate of growth by a base that includes past GDP growth, with dramatic effects over time.</p>
<p>For example, in 2013, the Central Intelligence Agency's World Fact Book reported that South Korea had a GDP of $1.67 trillion with a growth rate of 2.8%. We can estimate that at that growth rate, South Korea’s GDP will be $1.92 trillion in five years. If we apply the growth rate to each year’s ending GDP for the next five years, we will calculate that at the end of year one, GDP is $1.72 trillion. In year two, we start with the end-of-year one value of $1.72 and increase it by 2.8%. Year three starts with the end-of-year two GDP, and we increase it by 2.8% and so on, as <a href="#tbl-G_002" class="quarto-xref">Table&nbsp;<span>10.2</span></a> depicts.</p>
<div id="tbl-g_002" class="quarto-float anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-g_002-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;10.3: Growth Rates
</figcaption>
<div aria-describedby="tbl-g_002-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="table">
<thead>
<tr class="header">
<th style="text-align: left;">Year</th>
<th style="text-align: left;">Starting GDP</th>
<th style="text-align: left;">Growth Rate 2%</th>
<th style="text-align: left;">Year-End Amount</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1</td>
<td style="text-align: left;">$1.67 Trillion ×</td>
<td style="text-align: left;">(1+0.028)</td>
<td style="text-align: left;">$1.72 Trillion</td>
</tr>
<tr class="even">
<td style="text-align: left;">2</td>
<td style="text-align: left;">$1.72 Trillion ×</td>
<td style="text-align: left;">(1+0.028)</td>
<td style="text-align: left;">$1.76 Trillion</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3</td>
<td style="text-align: left;">$1.76 Trillion ×</td>
<td style="text-align: left;">(1+0.028)</td>
<td style="text-align: left;">$1.81 Trillion</td>
</tr>
<tr class="even">
<td style="text-align: left;">4</td>
<td style="text-align: left;">$1.81 Trillion ×</td>
<td style="text-align: left;">(1+0.028)</td>
<td style="text-align: left;">$1.87 Trillion</td>
</tr>
<tr class="odd">
<td style="text-align: left;">5</td>
<td style="text-align: left;">$1.87 Trillion ×</td>
<td style="text-align: left;">(1+0.028)</td>
<td style="text-align: left;">$1.92 Trillion</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>Another way to calculate the growth rate is to apply the following formula:</p>
<p><span class="math display">\[\text{Future Value} = \text{Present Value} \times (1 + g)^n\]</span></p>
<p>Where “future value” is the value of GDP five years hence, “present value” is the starting GDP amount of $1.67 trillion, “g” is the growth rate of 2.8%, and “n” is the number of periods for which we are calculating growth.</p>
<p><span class="math display">\[\text{Future Value} = 1.67 × (1+0.028)^5 = \$1.92 \text{trillion}\]</span></p>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Key Concepts and Summary
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>We can measure productivity, the value of what is produced per worker, or per hour worked, as the level of GDP per worker or GDP per hour. The United States experienced a productivity slowdown between 1973 and 1989. Since then, U.S. productivity has rebounded for the most part, but annual growth in productivity in the nonfarm business sector has been less than one percent each year between 2011 and 2016. It is not clear what productivity growth will be in the coming years. The rate of productivity growth is the primary determinant of an economy’s rate of long-term economic growth and higher wages. Over decades and generations, seemingly small differences of a few percentage points in the annual rate of economic growth make an enormous difference in GDP per capita. An aggregate production function specifies how certain inputs in the economy, like human capital, physical capital, and technology, lead to the output measured as GDP per capita.</li>
<li>Compound interest and compound growth rates behave in the same way as productivity rates. Seemingly small changes in percentage points can have big impacts on income over time.</li>
</ul>
</div>
</div>
<div class="callout callout-style-default callout-caution callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-12-contents" aria-controls="callout-12" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Self-Check Questions
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-12" class="callout-12-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ul>
<li>Are there other ways in which we can measure productivity besides the amount produced per hour of work?</li>
<li>Assume there are two countries: South Korea and the United States. South Korea grows at 4% and the United States grows at 1%. For the sake of simplicity, assume they both start from the same fictional income level, $10,000. What will the incomes of the United States and South Korea be in 20 years? By how many multiples will each country’s income grow in 20 years?</li>
<li>How is GDP per capita calculated differently from labor productivity?</li>
<li>How do gains in labor productivity lead to gains in GDP per capita?</li>
<li>Labor Productivity and Economic Growth outlined the logic of how increased productivity is associated with increased wages. Detail a situation where this is not the case and explain why it is not.</li>
<li>Change in labor productivity is one of the most watched international statistics of growth. Visit the St.&nbsp;Louis Federal Reserve website and find the data section (<a href="http://research.stlouisfed.org" class="uri">http://research.stlouisfed.org</a>). Find international comparisons of labor productivity, listed under the FRED Economic database (Growth Rate of Total Labor Productivity), and compare two countries in the recent past. State what you think the reasons for differences in labor productivity could be.</li>
<li>Refer back to the Work It Out about Comparing the Economies of Two Countries and examine the data for the two countries you chose. How are they similar? How are they different?</li>
</ul>
</div>
</div>
</div>
<!--Components of Economic Growth {{{2-->
</section>
</section>
<section id="components-of-economic-growth" class="level2" data-number="10.3">
<h2 data-number="10.3" class="anchored" data-anchor-id="components-of-economic-growth"><span class="header-section-number">10.3</span> Components of Economic Growth</h2>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Section Learning Objectives
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>Discuss the components of economic growth, including physical capital, human capital, and technology</li>
<li>Explain capital deepening and its significance</li>
<li>Analyze the methods employed in economic growth accounting studies</li>
<li>Identify factors that contribute to a healthy climate for economic growth</li>
</ul>
</div>
</div>
<p>Over decades and generations, seemingly small differences of a few percentage points in the annual rate of economic growth make an enormous difference in GDP per capita. In this module, we discuss some of the components of economic growth, including physical capital, human capital, and technology.</p>
<p>The category of physical capital includes the plant and equipment that firms use as well as things like roads (also called infrastructure). Again, greater physical capital implies more output. Physical capital can affect productivity in two ways: (1) an increase in the quantity of physical capital (for example, more computers of the same quality); and (2) an increase in the quality of physical capital (same number of computers but the computers are faster, and so on). Human capital refers to the skills and knowledge that make workers productive. Human capital and physical capital accumulation are similar: In both cases, investment now pays off in higher productivity in the future.</p>
<p>The category of technology is the “joker in the deck.” Earlier we described it as the combination of invention and innovation. When most people think of new technology, the invention of new products like the laser, the smartphone, or some new wonder drug come to mind. In food production, developing more drought-resistant seeds is another example of technology. Technology, as economists use the term, however, includes still more. It includes new ways of organizing work, like the invention of the assembly line, new methods for ensuring better quality of output in factories, and innovative institutions that facilitate the process of converting inputs into output. In short, technology comprises all the advances that make the existing machines and other inputs produce more, and at higher quality, as well as altogether new products.</p>
<p>It may not make sense to compare the GDPs of China and say, Benin, simply because of the great difference in population size. To understand economic growth, which is really concerned with the growth in living standards of an average person, it is often useful to focus on GDP per capita. Using GDP per capita also makes it easier to compare countries with smaller numbers of people, like Belgium, Uruguay, or Zimbabwe, with countries that have larger populations, like the United States, the Russian Federation, or Nigeria.</p>
<p>To obtain a per capita production function, divide each input in [link](a) by the population. This creates a second aggregate production function where the output is GDP per capita (that is, GDP divided by population). The inputs are the average level of human capital per person, the average level of physical capital per person, and the level of technology per person—see [link](b). The result of having population in the denominator is mathematically appealing. Increases in population lower per capita income. However, increasing population is important for the average person only if the rate of income growth exceeds population growth. A more important reason for constructing a per capita production function is to understand the contribution of human and physical capital.</p>
<section id="capital-deepening" class="level3" data-number="10.3.1">
<h3 data-number="10.3.1" class="anchored" data-anchor-id="capital-deepening"><span class="header-section-number">10.3.1</span> Capital Deepening</h3>
<p>When society increases the level of capital per person, we call the result capital deepening. The idea of capital deepening can apply both to additional human capital per worker and to additional physical capital per worker.</p>
<p>Recall that one way to measure human capital is to look at the average levels of education in an economy. <a href="#fig-G_004" class="quarto-xref">Figure&nbsp;<span>10.7</span></a> illustrates the human capital deepening for U.S. workers by showing that the proportion of the U.S. population with a high school and a college degree is rising. As recently as 1970, for example, only about half of U.S. adults had at least a high school diploma. By the start of the twenty-first century, more than 80% of adults had graduated from high school.</p>
<p>The idea of human capital deepening also applies to the years of experience that workers have, but the average experience level of U.S. workers has not changed much in recent decades. Thus, the key dimension for deepening human capital in the U.S. economy focuses more on additional education and training than on a higher average level of work experience.</p>
<div id="fig-G_004" class="align-center quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-G_004-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="Graphs/Growth/CNX_Econ_C20_010.jpg" class="lightbox" data-glightbox="description: .lightbox-desc-7" data-gallery="quarto-lightbox-gallery-7"><img src="Graphs/Growth/CNX_Econ_C20_010.jpg" class="align-center img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-G_004-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;10.7: Rising levels of education for persons 25 and older show the deepening of human capital in the U.S. economy. Even today, under one-third of U.S. adults have completed a four-year college degree. There is clearly room for additional deepening of human capital to occur. (Source: US Department of Education, National Center for Education Statistics)
</figcaption>
</figure>
</div>
<p><a href="#fig-G_005" class="quarto-xref">Figure&nbsp;<span>10.8</span></a> shows physical capital deepening in the U.S. economy. The average U.S. worker in the late 2000s was working with physical capital worth almost three times as much as that of the average worker of the early 1950s.</p>
<div id="fig-G_005" class="align-center quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-G_005-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="Graphs/Growth/CNX_Econ_C20_008.jpg" class="lightbox" data-glightbox="description: .lightbox-desc-8" data-gallery="quarto-lightbox-gallery-8"><img src="Graphs/Growth/CNX_Econ_C20_008.jpg" class="align-center img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-G_005-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;10.8: The value of the physical capital, measured by plant and equipment, used by the average worker in the U.S. economy has risen over the decades. The increase may have leveled off a bit in the 1970s and 1980s, which were, not coincidentally, times of slower-than-usual growth in worker productivity. We see a renewed increase in physical capital per worker in the late 1990s, followed by a flattening in the early 2000s. (Source: Center for International Comparisons of Production, Income and Prices, University of Pennsylvania)
</figcaption>
</figure>
</div>
<p>Not only does the current U.S. economy have better-educated workers with more and improved physical capital than it did several decades ago, but these workers have access to more advanced technologies. Growth in technology is impossible to measure with a simple line on a graph, but evidence that we live in an age of technological marvels is all around us—discoveries in genetics and in the structure of particles, the wireless internet, and other inventions almost too numerous to count. The U.S. Patent and Trademark Office typically has issued more than 150,000 patents annually in recent years.</p>
<p>This recipe for economic growth—investing in labor productivity, with investments in human capital and technology, as well as increasing physical capital—also applies to other economies. South Korea, for example, already achieved universal enrollment in primary school (the equivalent of kindergarten through sixth grade in the United States) by 1965, when Korea’s GDP per capita was still near its rock bottom low. By the late 1980s, Korea had achieved almost universal secondary school education (the equivalent of a high school education in the United States). With regard to physical capital, Korea’s rates of investment had been about 15% of GDP at the start of the 1960s, but doubled to 30–35% of GDP by the late 1960s and early 1970s. With regard to technology, South Korean students went to universities and colleges around the world to obtain scientific and technical training, and South Korean firms reached out to study and form partnerships with firms that could offer them technological insights. These factors combined to foster South Korea’s high rate of economic growth.</p>
</section>
<section id="growth-accounting-studies" class="level3" data-number="10.3.2">
<h3 data-number="10.3.2" class="anchored" data-anchor-id="growth-accounting-studies"><span class="header-section-number">10.3.2</span> Growth Accounting Studies</h3>
<p>Since the late 1950s, economists have conducted growth accounting studies to determine the extent to which physical and human capital deepening and technology have contributed to growth. The usual approach uses an aggregate production function to estimate how much of per capita economic growth can be attributed to growth in physical capital and human capital. We can measure these two inputs at least roughly. The part of growth that is unexplained by measured inputs, called the residual, is then attributed to growth in technology. The exact numerical estimates differ from study to study and from country to country, depending on how researchers measured these three main factors and over what time horizons. For studies of the U.S. economy, three lessons commonly emerge from growth accounting studies.</p>
<p>First, technology is typically the most important contributor to U.S. economic growth. Growth in human capital and physical capital often explains only half or less than half of the economic growth that occurs. New ways of doing things are tremendously important.</p>
<p>Second, while investment in physical capital is essential to growth in labor productivity and GDP per capita, building human capital is at least as important. Economic growth is not just a matter of more machines and buildings. One vivid example of the power of human capital and technological knowledge occurred in Europe in the years after World War II (1939–1945). During the war, a large share of Europe’s physical capital, such as factories, roads, and vehicles, was destroyed. Europe also lost an overwhelming amount of human capital in the form of millions of men, women, and children who died during the war. However, the powerful combination of skilled workers and technological knowledge, working within a market-oriented economic framework, rebuilt Europe’s productive capacity to an even higher level within less than two decades.</p>
<p>A third lesson is that these three factors of human capital, physical capital, and technology work together. Workers with a higher level of education and skills are often better at coming up with new technological innovations. These technological innovations are often ideas that cannot increase production until they become a part of new investment in physical capital. New machines that embody technological innovations often require additional training, which builds worker skills further. If the recipe for economic growth is to succeed, an economy needs all the ingredients of the aggregate production function. See the following Clear It Up feature for an example of how human capital, physical capital, and technology can combine to significantly impact lives.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>HOW DO GIRLS’ EDUCATION AND ECONOMIC GROWTH RELATE IN LOW-INCOME COUNTRIES?</p>
<p>In the early 2000s, according to the World Bank, about 110 million children between the ages of 6 and 11 were not in school—and about two-thirds of them were girls. In Afghanistan, for example, the literacy rate for those aged 15-24 for the period 2005-2014 was 62% for males and only 32% for females. In Benin, in West Africa, it was 55% for males and 31% for females. In Nigeria, Africa’s most populous country, it was 76% for males and 58 percent for females.</p>
<p>Whenever any child does not receive a basic education, it is both a human and an economic loss. In low-income countries, wages typically increase by an average of 10 to 20% with each additional year of education. There is, however, some intriguing evidence that helping girls in low-income countries to close the education gap with boys may be especially important, because of the social role that many of the girls will play as mothers and homemakers.</p>
<p>Girls in low-income countries who receive more education tend to grow up to have fewer, healthier, better-educated children. Their children are more likely to be better nourished and to receive basic health care like immunizations. Economic research on women in low-income economies backs up these findings. When 20 women obtain one additional year of schooling, as a group they will, on average, have one less child. When 1,000 women obtain one additional year of schooling, on average one to two fewer women from that group will die in childbirth. When a woman stays in school an additional year, that factor alone means that, on average, each of her children will spend an additional half-year in school. Education for girls is a good investment because it is an investment in economic growth with benefits beyond the current generation.</p>
</div>
</div>
</section>
<section id="a-healthy-climate-for-economic-growth" class="level3" data-number="10.3.3">
<h3 data-number="10.3.3" class="anchored" data-anchor-id="a-healthy-climate-for-economic-growth"><span class="header-section-number">10.3.3</span> A Healthy Climate for Economic Growth</h3>
<p>While physical and human capital deepening and better technology are important, equally important to a nation’s well-being is the climate or system within which these inputs are cultivated. Both the type of market economy and a legal system that governs and sustains property rights and contractual rights are important contributors to a healthy economic climate.</p>
<p>A healthy economic climate usually involves some sort of market orientation at the microeconomic, individual, or firm decision-making level. Markets that allow personal and business rewards and incentives for increasing human and physical capital encourage overall macroeconomic growth. For example, when workers participate in a competitive and well-functioning labor market, they have an incentive to acquire additional human capital, because additional education and skills will pay off in higher wages. Firms have an incentive to invest in physical capital and in training workers, because they expect to earn higher profits for their shareholders. Both individuals and firms look for new technologies, because even small inventions can make work easier or lead to product improvement. Collectively, such individual and business decisions made within a market structure add up to macroeconomic growth. Much of the rapid growth since the late nineteenth century has come from harnessing the power of competitive markets to allocate resources. This market orientation typically reaches beyond national borders and includes openness to international trade.</p>
<p>A general orientation toward markets does not rule out important roles for government. There are times when markets fail to allocate capital or technology in a manner that provides the greatest benefit for society as a whole. The government's role is to correct these failures. In addition, government can guide or influence markets toward certain outcomes. The following examples highlight some important areas that governments around the world have chosen to invest in to facilitate capital deepening and technology:</p>
<blockquote class="blockquote">
<dl>
<dt>Education.</dt>
<dd>
<p>The Danish government requires all children under 16 to attend school. They can choose to attend a public school (Folkeskole) or a private school. Students do not pay tuition to attend Folkeskole. Thirteen percent of primary/secondary (elementary/high) school is private, and the government supplies vouchers to citizens who choose private school.</p>
</dd>
<dt>Savings and Investment.</dt>
<dd>
<p>In the United States, as in other countries, the government taxes gains from private investment. Low capital gains taxes encourage investment and so also economic growth.</p>
</dd>
<dt>Infrastructure.</dt>
<dd>
<p>The Japanese government in the mid-1990s undertook significant infrastructure projects to improve roads and public works. This in turn increased the stock of physical capital and ultimately economic growth.</p>
</dd>
<dt>Special Economic Zones.</dt>
<dd>
<p>The island of Mauritius is one of the few African nations to encourage international trade in government-supported special economic zones (SEZ). These are areas of the country, usually with access to a port where, among other benefits, the government does not tax trade. As a result of its SEZ, Mauritius has enjoyed above-average economic growth since the 1980s. Free trade does not have to occur in an SEZ however. Governments can encourage international trade across the board, or surrender to protectionism.</p>
</dd>
<dt>Scientific Research.</dt>
<dd>
<p>The European Union has strong programs to invest in scientific research. The researchers Abraham García and Pierre Mohnen demonstrate that firms which received support from the Austrian government actually increased their research intensity and had more sales. Governments can support scientific research and technical training that helps to create and spread new technologies. Governments can also provide a legal environment that protects the ability of inventors to profit from their inventions.</p>
</dd>
</dl>
</blockquote>
<p>There are many more ways in which the government can play an active role in promoting economic growth. We explore them in other chapters and in particular in Macroeconomic Policy Around the World. A healthy climate for growth in GDP per capita and labor productivity includes human capital deepening, physical capital deepening, and technological gains, operating in a market-oriented economy with supportive government policies.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Key Concepts and Summary
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><p>Over decades and generations, seemingly small differences of a few percentage points in the annual rate of economic growth make an enormous difference in GDP per capita.</p></li>
<li><p>Capital deepening refers to an increase in the amount of capital per worker, either human capital per worker, in the form of higher education or skills, or physical capital per worker.</p></li>
<li><p>Technology, in its economic meaning, refers broadly to all new methods of production, which includes major scientific inventions but also small inventions and even better forms of management or other types of institutions.</p></li>
<li><p>A healthy climate for growth in GDP per capita consists of improvements in human capital, physical capital, and technology, in a market-oriented environment with supportive public policies and institutions.</p></li>
</ul>
</div>
</div>
<div class="callout callout-style-default callout-caution callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-16-contents" aria-controls="callout-16" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Self-Check Questions
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-16" class="callout-16-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ul>
<li>What do the growth accounting studies conclude are the determinants of growth? Which is more important, the determinants or how they are combined?</li>
<li>What policies can the government of a free-market economy implement to stimulate economic growth?</li>
<li>List the areas where government policy can help economic growth.</li>
<li>What is an aggregate production function?</li>
<li>What is capital deepening?</li>
<li>What do economists mean when they refer to improvements in technology?</li>
<li>Education seems to be important for human capital deepening. As people become better educated and more knowledgeable, are there limits to how much additional benefit more education can provide? Why or why not?</li>
<li>Describe some of the political and social tradeoffs that might occur when a less developed country adopts a strategy to promote labor force participation and economic growth via investment in girls’ education.</li>
<li>Why is investing in girls’ education beneficial for growth?</li>
<li>How is the concept of technology, as defined with the aggregate production function, different from our everyday use of the word?</li>
</ul>
</div>
</div>
</div>
<!--Economic Convergence {{{2-->
</section>
</section>
<section id="economic-convergence" class="level2" data-number="10.4">
<h2 data-number="10.4" class="anchored" data-anchor-id="economic-convergence"><span class="header-section-number">10.4</span> Economic Convergence</h2>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Section Learning Objectives
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>Explain economic convergence</li>
<li>Analyze various arguments for and against economic convergence</li>
<li>Evaluate the speed of economic convergence between high-income countries and the rest of the world</li>
</ul>
</div>
</div>
<p>Some low-income and middle-income economies around the world have shown a pattern of convergence, in which their economies grow faster than those of high-income countries. GDP increased by an average rate of 2.7% per year in the 1990s and 2.3% per year from 2000 to 2008 in the high-income countries of the world, which include the United States, Canada, the European Union countries, Japan, Australia, and New Zealand.</p>
<p>The following tables lists 10 countries that belong to an informal “fast growth club.” These countries averaged GDP growth (after adjusting for inflation) of at least 5% per year in both the time periods from 1990 to 2000 and from 2000 to 2008. Since economic growth in these countries has exceeded the average of the world’s high-income economies, these countries may converge with the high-income countries. <a href="#tbl-g_6" class="quarto-xref">Table&nbsp;<span>10.4</span></a> lists the “slow growth club,” which consists of countries that averaged GDP growth of 2% per year or less (after adjusting for inflation) during the same time periods. <a href="#tbl-g_7" class="quarto-xref">Table&nbsp;<span>10.5</span></a> shows GDP growth rates for the countries of the world divided by income.</p>
<p>Economic Growth around the World(Source: <a href="http://databank.worldbank.org/data/views/variableSelection/selectvariables.aspx?source=world-development-indicators#c_u" class="uri">http://databank.worldbank.org/data/views/variableSelection/selectvariables.aspx?source=world-development-indicators#c_u</a>)</p>
<div id="tbl-g_6" class="quarto-float anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-g_6-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;10.4: Fast Growth Club (&gt;= 5% per year in both time periods)
</figcaption>
<div aria-describedby="tbl-g_6-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="table">
<colgroup>
<col style="width: 18%">
<col style="width: 38%">
<col style="width: 38%">
</colgroup>
<thead>
<tr class="header">
<th>Country</th>
<th>Average Growth Rate of Real GDP 1990–2000</th>
<th>Average Growth Rate of Real GDP 2000–2008</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Cambodia</td>
<td>7.1%</td>
<td><blockquote class="blockquote">
<p>9.1%</p>
</blockquote></td>
</tr>
<tr class="even">
<td>China</td>
<td>10.6%</td>
<td><blockquote class="blockquote">
<p>9.9%</p>
</blockquote></td>
</tr>
<tr class="odd">
<td>India</td>
<td>6.0%</td>
<td><blockquote class="blockquote">
<p>7.1%</p>
</blockquote></td>
</tr>
<tr class="even">
<td>Ireland</td>
<td>7.5%</td>
<td><blockquote class="blockquote">
<p>5.1%</p>
</blockquote></td>
</tr>
<tr class="odd">
<td>Jordan</td>
<td>5.0%</td>
<td><blockquote class="blockquote">
<p>6.3%</p>
</blockquote></td>
</tr>
<tr class="even">
<td>Laos</td>
<td>6.5%</td>
<td><blockquote class="blockquote">
<p>6.8 %</p>
</blockquote></td>
</tr>
<tr class="odd">
<td>Mozambique</td>
<td>6.4%</td>
<td><blockquote class="blockquote">
<p>7.3%</p>
</blockquote></td>
</tr>
<tr class="even">
<td>Sudan</td>
<td>5.4%</td>
<td><blockquote class="blockquote">
<p>7.3%</p>
</blockquote></td>
</tr>
<tr class="odd">
<td>Uganda</td>
<td>7.1%</td>
<td><blockquote class="blockquote">
<p>7.3%</p>
</blockquote></td>
</tr>
<tr class="even">
<td>Vietnam</td>
<td>7.9%</td>
<td><blockquote class="blockquote">
<p>7.3%</p>
</blockquote></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<div id="tbl-g_7" class="quarto-float anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-g_7-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;10.5: Slow Growth Club (&lt;= 2% per year in both time periods)
</figcaption>
<div aria-describedby="tbl-g_7-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="table">
<thead>
<tr class="header">
<th style="text-align: left;">Country</th>
<th style="text-align: left;">Average Growth Rate of Real GDP 1990–2000</th>
<th style="text-align: left;">Average Growth Rate of Real GDP 2000–2008</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Central African Republic</td>
<td style="text-align: left;">2.0%</td>
<td style="text-align: left;">0.8%</td>
</tr>
<tr class="even">
<td style="text-align: left;">France</td>
<td style="text-align: left;">2.0%</td>
<td style="text-align: left;">1.8%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Germany</td>
<td style="text-align: left;">1.8%</td>
<td style="text-align: left;">1.3%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Guinea-Bissau</td>
<td style="text-align: left;">1.2%</td>
<td style="text-align: left;">0.2%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Haiti</td>
<td style="text-align: left;">–1.5%</td>
<td style="text-align: left;">0.3%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Italy</td>
<td style="text-align: left;">1.6%</td>
<td style="text-align: left;">1.2%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Jamaica</td>
<td style="text-align: left;">0.9%</td>
<td style="text-align: left;">1.4%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Japan</td>
<td style="text-align: left;">1.3%</td>
<td style="text-align: left;">1.3%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Switzerland</td>
<td style="text-align: left;">1.0%</td>
<td style="text-align: left;">2.0%</td>
</tr>
<tr class="even">
<td style="text-align: left;">United States (for reference)</td>
<td style="text-align: left;">3.2%</td>
<td style="text-align: left;">2.2%</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<table class="table">
<caption>World Overview</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Country Type</th>
<th style="text-align: left;">Average Growth Rate of Real GDP 1990–2000</th>
<th style="text-align: left;">Average Growth Rate of Real GDP 2000–2008</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">High income</td>
<td style="text-align: left;">2.7%</td>
<td style="text-align: left;">2.3%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Low income</td>
<td style="text-align: left;">3.8%</td>
<td style="text-align: left;">5.6%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Middle income</td>
<td style="text-align: left;">4.7%</td>
<td style="text-align: left;">6.1%</td>
</tr>
</tbody>
</table>
<p>Each of the countries in the previous tables has its own unique story of investments in human and physical capital, technological gains, market forces, government policies, and even lucky events, but an overall pattern of convergence is clear. The low-income countries have GDP growth that is faster than that of the middle-income countries, which in turn have GDP growth that is faster than that of the high-income countries. Two prominent members of the fast-growth club are China and India, which between them have nearly 40% of the world’s population. Some prominent members of the slow-growth club are high-income countries like France, Germany, Italy, and Japan.</p>
<p>Will this pattern of economic convergence persist into the future? This is a controversial question among economists that we will consider by looking at some of the main arguments on both sides.</p>
<section id="arguments-favoring-convergence" class="level3" data-number="10.4.1">
<h3 data-number="10.4.1" class="anchored" data-anchor-id="arguments-favoring-convergence"><span class="header-section-number">10.4.1</span> Arguments Favoring Convergence</h3>
<p>Several arguments suggest that low-income countries might have an advantage in achieving greater worker productivity and economic growth in the future.</p>
<p>A first argument is based on diminishing marginal returns. Even though deepening human and physical capital will tend to increase GDP per capita, the law of diminishing returns suggests that as an economy continues to increase its human and physical capital, the marginal gains to economic growth will diminish. For example, raising the average education level of the population by two years from a tenth-grade level to a high school diploma (while holding all other inputs constant) would produce a certain increase in output. An additional two-year increase, so that the average person had a two-year college degree, would increase output further, but the marginal gain would be smaller. Yet another additional two-year increase in the level of education, so that the average person would have a four-year-college bachelor’s degree, would increase output still further, but the marginal increase would again be smaller. A similar lesson holds for physical capital. If the quantity of physical capital available to the average worker increases, by, say, $5,000 to $10,000 (again, while holding all other inputs constant), it will increase the level of output. An additional increase from $10,000 to $15,000 will increase output further, but the marginal increase will be smaller.</p>
<p>Low-income countries like China and India tend to have lower levels of human capital and physical capital, so an investment in capital deepening should have a larger marginal effect in these countries than in high-income countries, where levels of human and physical capital are already relatively high. Diminishing returns implies that low-income economies could converge to the levels that the high-income countries achieve.</p>
<p>A second argument is that low-income countries may find it easier to improve their technologies than high-income countries. High-income countries must continually invent new technologies, whereas low-income countries can often find ways of applying technology that has already been invented and is well understood. The economist Alexander Gerschenkron (1904–1978) gave this phenomenon a memorable name: “the advantages of backwardness.” Of course, he did not literally mean that it is an advantage to have a lower standard of living. He was pointing out that a country that is behind has some extra potential for catching up.</p>
<p>Finally, optimists argue that many countries have observed the experience of those that have grown more quickly and have learned from it. Moreover, once the people of a country begin to enjoy the benefits of a higher standard of living, they may be more likely to build and support the market-friendly institutions that will help provide this standard of living.</p>
</section>
<section id="arguments-that-convergence-is-neither-inevitable-nor-likely" class="level3" data-number="10.4.2">
<h3 data-number="10.4.2" class="anchored" data-anchor-id="arguments-that-convergence-is-neither-inevitable-nor-likely"><span class="header-section-number">10.4.2</span> Arguments That Convergence Is neither Inevitable nor Likely</h3>
<p>If the economy's growth depended only on the deepening of human capital and physical capital, then we would expect that economy's growth rate to slow down over the long run because of diminishing marginal returns. However, there is another crucial factor in the aggregate production function: technology.</p>
<p>Developing new technology can provide a way for an economy to sidestep the diminishing marginal returns of capital deepening. <a href="#fig-G_007" class="quarto-xref">Figure&nbsp;<span>10.9</span></a> shows how. The figure's horizontal axis measures the amount of capital deepening, which on this figure is an overall measure that includes deepening of both physical and human capital.</p>
<p>The amount of human and physical capital per worker increases as you move from left to right, from C1 to C2 to C3. The diagram's vertical axis measures per capita output. Start by considering the lowest line in this diagram, labeled Technology 1. Along this aggregate production function, the level of technology is held constant, so the line shows only the relationship between capital deepening and output. As capital deepens from C1 to C2 to C3 and the economy moves from R to U to W, per capita output does increase—but the way in which the line starts out steeper on the left but then flattens as it moves to the right shows the diminishing marginal returns, as additional marginal amounts of capital deepening increase output by ever-smaller amounts. The shape of the aggregate production line (Technology 1) shows that the ability of capital deepening, by itself, to generate sustained economic growth is limited, since diminishing returns will eventually set in.</p>
<div id="fig-G_007" class="align-center quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-G_007-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="Graphs/Growth/CNX_Econ_C20_006.jpg" class="lightbox" data-glightbox="description: .lightbox-desc-9" data-gallery="quarto-lightbox-gallery-9"><img src="Graphs/Growth/CNX_Econ_C20_006.jpg" class="align-center img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-G_007-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;10.9: Imagine that the economy starts at point R, with the level of physical and human capital C1 and the output per capita at G1. If the economy relies only on capital deepening, while remaining at the technology level shown by the Technology 1 line, then it would face diminishing marginal returns as it moved from point R to point U to point W. However, now imagine that capital deepening is combined with improvements in technology. Then, as capital deepens from C1 to C2, technology improves from Technology 1 to Technology 2, and the economy moves from R to S. Similarly, as capital deepens from C2 to C3, technology increases from Technology 2 to Technology 3, and the economy moves from S to T. With improvements in technology, there is no longer any reason that economic growth must necessarily slow down.
</figcaption>
</figure>
</div>
<p>Now, bring improvements in technology into the picture. Improved technology means that with a given set of inputs, more output is possible. The production function labeled Technology 1 in the figure is based on one level of technology, but Technology 2 is based on an improved level of technology, so for every level of capital deepening on the horizontal axis, it produces a higher level of output on the vertical axis. In turn, production function Technology 3 represents a still higher level of technology, so that for every level of inputs on the horizontal axis, it produces a higher level of output on the vertical axis than either of the other two aggregate production functions.</p>
<p>Most healthy, growing economies are deepening their human and physical capital and increasing technology at the same time. As a result, the economy can move from a choice like point R on the Technology 1 aggregate production line to a point like S on Technology 2 and a point like T on the still higher aggregate production line (Technology 3). With the combination of technology and capital deepening, the rise in GDP per capita in high-income countries does not need to fade away because of diminishing returns. The gains from technology can offset the diminishing returns involved with capital deepening.</p>
<p>Will technological improvements themselves run into diminishing returns over time? That is, will it become continually harder and more costly to discover new technological improvements? Perhaps someday, but, at least over the last two centuries since the beginning of the Industrial Revolution, improvements in technology have not run into diminishing marginal returns. Modern inventions, like the internet or discoveries in genetics or materials science, do not seem to provide smaller gains to output than earlier inventions like the steam engine or the railroad. One reason that technological ideas do not seem to run into diminishing returns is that we often can apply widely the ideas of new technology at a marginal cost that is very low or even zero. A specific worker or group of workers must use a specific additional machine, or an additional year of education. Many workers across the economy can use a new technology or invention at very low marginal cost.</p>
<p>The argument that it is easier for a low-income country to copy and adapt existing technology than it is for a high-income country to invent new technology is not necessarily true, either. When it comes to adapting and using new technology, a society’s performance is not necessarily guaranteed, but is the result of whether the country's economic, educational, and public policy institutions are supportive. In theory, perhaps, low-income countries have many opportunities to copy and adapt technology, but if they lack the appropriate supportive economic infrastructure and institutions, the theoretical possibility that backwardness might have certain advantages is of little practical relevance.</p>
</section>
<section id="the-slowness-of-convergence" class="level3" data-number="10.4.3">
<h3 data-number="10.4.3" class="anchored" data-anchor-id="the-slowness-of-convergence"><span class="header-section-number">10.4.3</span> The Slowness of Convergence</h3>
<p>Although economic convergence between the high-income countries and the rest of the world seems possible and even likely, it will proceed slowly. Consider, for example, a country that starts off with a GDP per capita of $40,000, which would roughly represent a typical high-income country today, and another country that starts out at $4,000, which is roughly the level in low-income but not impoverished countries like Indonesia, Guatemala, or Egypt. Say that the rich country chugs along at a 2% annual growth rate of GDP per capita, while the poorer country grows at the aggressive rate of 7% per year. After 30 years, GDP per capita in the rich country will be $72,455. We get this using</p>
<p><span class="math display">\[$40,000 \times (1 + 0.02)^{30}\]</span></p>
<p>while in the poor country it will be $30,450. This we got by</p>
<p><span class="math display">\[$4,000 \times (1 + 0.07)^{30}.\]</span></p>
<p>Convergence has occurred. The rich country used to be 10 times as wealthy as the poor one, and now it is only about 2.4 times as wealthy. Even after 30 consecutive years of very rapid growth, however, people in the low-income country are still likely to feel quite poor compared to people in the rich country. Moreover, as the poor country catches up, its opportunities for catch-up growth are reduced, and its growth rate may slow down somewhat.</p>
<p>As countries grow, their growth rates usually decrease due to diminishing returns.</p>
<p>The slowness of convergence illustrates again that small differences in annual rates of economic growth become huge differences over time. The high-income countries have been building up their advantage in standard of living over decades—more than a century in some cases. Even in an optimistic scenario, it will take decades for the low-income countries of the world to catch up significantly.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>CALORIES AND ECONOMIC GROWTH</p>
<p>We can tell the story of modern economic growth by looking at calorie consumption over time. The dramatic rise in incomes allowed the average person to eat better and consume more calories. How did these incomes increase? The neoclassical growth consensus uses the aggregate production function to suggest that the period of modern economic growth came about because of increases in inputs such as technology and physical and human capital. Also important was the way in which technological progress combined with physical and human capital deepening to create growth and convergence. The issue of distribution of income notwithstanding, it is clear that the average worker can afford more calories in 2017 than in 1875.</p>
<p>Aside from increases in income, there is another reason why the average person can afford more food. Modern agriculture has allowed many countries to produce more food than they need. Despite having more than enough food, however, many governments and multilateral agencies have not solved the food distribution problem. In fact, food shortages, famine, or general food insecurity are caused more often by the failure of government macroeconomic policy, according to the Nobel Prize-winning economist Amartya Sen.&nbsp;Sen has conducted extensive research into issues of inequality, poverty, and the role of government in improving standards of living. Macroeconomic policies that strive toward stable inflation, full employment, education of women, and preservation of property rights are more likely to eliminate starvation and provide for a more even distribution of food.</p>
<p>Because we have more food per capita, global food prices have decreased since 1875. The prices of some foods, however, have decreased more than the prices of others. For example, researchers from the University of Washington have shown that in the United States, calories from zucchini and lettuce are 100 times more expensive than calories from oil, butter, and sugar. Research from countries like India, China, and the United States suggests that as incomes rise, individuals want more calories from fats and protein and fewer from carbohydrates. This has very interesting implications for global food production, obesity, and environmental consequences. Affluent urban India has an obesity problem much like many parts of the United States. The forces of convergence are at work.</p>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Key Concepts and Summary
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>When countries with lower GDP levels per capita catch up to countries with higher GDP levels per capita, we call the process convergence.</li>
<li>Convergence can occur even when both high- and low-income countries increase investment in physical and human capital with the objective of growing GDP.</li>
<li>This is because the impact of new investment in physical and human capital on a low-income country may result in huge gains as new skills or equipment combine with the labor force.</li>
<li>In higher-income countries, however, a level of investment equal to that of the low income country is not likely to have as big an impact, because the more developed country most likely already has high levels of capital investment.</li>
<li>Therefore, the marginal gain from this additional investment tends to be successively less and less. Higher income countries are more likely to have diminishing returns to their investments and must continually invent new technologies.</li>
<li>This allows lower-income economies to have a chance for convergent growth. However, many high-income economies have developed economic and political institutions that provide a healthy economic climate for an ongoing stream of technological innovations.</li>
<li>Continuous technological innovation can counterbalance diminishing returns to investments in human and physical capital.</li>
</ul>
</div>
</div>
<div class="callout callout-style-default callout-caution callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-20-contents" aria-controls="callout-20" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Self-Check Questions
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-20" class="callout-20-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ul>
<li><p>Use an example to explain why, after periods of rapid growth, a low-income country that has not caught up to a high-income country may feel poor.</p></li>
<li><p>Would the following events usually lead to capital deepening? Why or why not?</p></li>
<li><p>A weak economy in which businesses become reluctant to make long-term investments in physical capital.</p></li>
<li><p>A rise in international trade.</p></li>
<li><p>A trend in which many more adults participate in continuing education courses through their employers and at colleges and universities.</p></li>
<li><p>What are the “advantages of backwardness” for economic growth?</p></li>
<li><p>Would you expect capital deepening to result in diminished returns? Why or why not? Would you expect improvements in technology to result in diminished returns? Why or why not?</p></li>
<li><p>Why does productivity growth in high-income economies not slow down as it runs into diminishing returns from additional investments in physical capital and human capital? Does this show one area where the theory of diminishing returns fails to apply? Why or why not?</p></li>
<li><p>For a high-income economy like the United States, what aggregate production function elements are most important in bringing about growth in GDP per capita? What about a middle-income country such as Brazil? A low-income country such as Niger?</p></li>
<li><p>List some arguments for and against the likelihood of convergence.</p></li>
<li><p>What sorts of policies can governments implement to encourage convergence?</p></li>
<li><p>As technological change makes us more sedentary and food costs increase, obesity is likely. What factors do you think may limit obesity?</p></li>
</ul>
</div>
</div>
</div>
<!--Growth Rates {{{2-->
</section>
</section>
<section id="growth-rates" class="level2" data-number="10.5">
<h2 data-number="10.5" class="anchored" data-anchor-id="growth-rates"><span class="header-section-number">10.5</span> Growth Rates</h2>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Section Learning Objectives
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>Explain growth rates</li>
<li>Discuss the “formula for multiple growth rates”</li>
</ul>
</div>
</div>
<p>If some variable x (for example, the number of gallons of gasoline sold in a week) changes from <span class="math inline">\(x_1\)</span> to <span class="math inline">\(x_2\)</span>, then we can define the change in that variable as <span class="math inline">\(\Delta x = x_2 − x_1\)</span>. But there are difficulties with this simple definition. The number that we calculate will change, depending on the units in which we measure x. If we measure in millions of gallons, x will be a much smaller number than if we measure in gallons. If we measured x in liters rather than gallons (as it is measured in most countries), it would be a bigger number. So the number we calculate depends on the units we choose. To avoid these problems, we look at percentage changes and express the change as a fraction of the individual value. In what follows, we use the notation <span class="math inline">\(\%\Delta x\)</span> to mean the percentage change in x and define it as follows:</p>
<p><span class="math display">\[\%\Delta x = (x_2 − x_1)/x_1.\]</span></p>
<p>A percentage change equal to 0.1 means that gasoline consumption increased by 10 percent. Why? Because 10 percent means 10 “per hundred,” so 10 percent = 10/100 = 0.1.</p>
<p>Very often in economics, we are interested in changes that take place over time. Thus we might want to compare gross domestic product (GDP) between 2012 and 2013. Suppose we know that GDP in the United States in 2012 was $14 trillion and that GDP in 2013 was $14.7 trillion. Using the letter Y to denote GDP measured in trillions, we write Y2012 = 14.0 and Y2013 = 14.7.</p>
<p>If we want to talk about GDP at different points in time without specifying a particular year, we use the notation Yt. We express the change in a variable over time in the form of a growth rate, which is just an example of a percentage change. Thus the growth rate of GDP in 2013 is calculated as follows:</p>
<p><span class="math display">\[%ΔY2013 = (Y2013 − Y2012)/Y2012 = (14.7 − 14)/14 = 0.05.\]</span></p>
<p>The growth rate equals 5 percent. In general, we write %ΔYt+1 = (Yt+1 − Yt)/Yt. Occasionally, we use the gross growth rate, which simply equals 1 + the growth rate. So, for example, the gross growth rate of GDP equals Y2013/Y2012, or 1.05.</p>
<p>There are some useful rules that describe the behavior of percentage changes and growth rates.</p>
<p>The <strong>Product Rule</strong>. Suppose we have three variables, x, y, and z, and suppose <span class="math display">\[x = y \times z.\]</span></p>
<p>Then <span class="math display">\[\%\Delta x = \% \Delta y + \%\Delta z.\]</span></p>
<p>In other words, the growth rate of a product of two variables equals the sum of the growth rates of the individual variables.</p>
<p>The <strong>Quotient Rule</strong>. Now suppose we rearrange our original equation by dividing both sides by z to obtain <span class="math display">\[y=\frac{x}{z}.\]</span></p>
<p>If we take the product rule and subtract %Δz from both sides, we get the following: <span class="math display">\[\%\Delta y = \%\Delta x − \%\Delta z.\]</span></p>
<p>The <strong>Power Rule</strong>. There is one more rule of growth rates that we make use of in some advanced topics, such as growth accounting. Suppose that <span class="math display">\[y = x ^ a.\]</span></p>
<p>Then</p>
<p><span class="math display">\[\%\Delta y = a \times (\% \Delta x).\]</span></p>
<p>For example, if <span class="math inline">\(y = x^2\)</span>, then the growth rate of y is twice the growth rate of x. If y=x, then the growth rate of y is half the growth rate of x (remembering that a square root is the same as a power of <span class="math inline">\(\frac{1}{2}\)</span>.</p>
<p><strong>More Formally</strong></p>
<p>Growth rates compound over time: if the growth rate of a variable is constant, then the change in the variable increases over time. For example, suppose GDP in 2020 is 20.0, and it grows at 10 percent per year. Then in 2021, GDP is 22.0 (an increase of 2.0), but in 2022, GDP is 24.2 (an increase of 2.2). If this compounding takes place every instant, then we say that we have exponential growth. Formally, we write exponential growth using the number e = 2.71828.… If the value of Y at time 0 equals Y0 and if Y grows at the constant rate g (where g is an “annualized” or per year growth rate), then at time t (measured in years), <span class="math display">\[Y_t = e^{g \times t}Y_0.\]</span></p>
<p>A version of this formula can also be used to calculate the average growth rate of a variable if we know its value at two different times. We can write the formula as <span class="math display">\[e^{g \times t} = Y_t/Y_0,\]</span></p>
<p>which also means <span class="math display">\[g \times t = ln(Yt/Y0), \]</span></p>
<p>where <span class="math inline">\(\ln()\)</span> is the natural logarithm. You do not need to know exactly what this means; you can simply calculate a logarithm using a scientific calculator or a spreadsheet. Dividing by t we get the average growth rate <span class="math display">\[g = ln(Y_t/Y_0)/t.\]</span></p>
<p>For example, suppose GDP in 2020 is 20.0 and GDP in 2030 is 28.0. Then Y2030/Y2020 = 28/20 = 1.4. Using a calculator, we can find <span class="math inline">\(ln(1.4) = 0.3364\)</span>. Dividing by 10 (since the two dates are 10 years apart), we get an average growth rate of 0.034, or 3.4 percent per year.</p>
<!--The Solow Growth Model {{{2-->
</section>
<section id="the-solow-growth-model" class="level2" data-number="10.6">
<h2 data-number="10.6" class="anchored" data-anchor-id="the-solow-growth-model"><span class="header-section-number">10.6</span> The Solow Growth Model</h2>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Section Learning Objectives
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>Explain the Solow growth model</li>
</ul>
</div>
</div>
<p>Here we present two formal versions of the mathematics of the model. The first takes as its focus the capital accumulation equation and explains how the capital stock evolves in the economy. This version ignores the role of human capital and ignores the long-run growth path of the economy. The second follows the exposition of the chapter and is based around the derivation of the balanced growth path. They are, however, simply two different ways of approaching the same problem.</p>
<p>There are three components of this presentation of the model: technology, capital accumulation, and saving. The first component of the Solow growth model is the specification of technology and comes from the aggregate production function. We express output per worker (y) as a function of capital per worker (k) and technology (A). A mathematical expression of this relationship is <span class="math display">\[y = A \times f(k)\]</span></p>
<p>where f(k) means that output per worker depends on capital per worker. As in our presentation of production functions, output increases with technology. We assume that f() has the properties that more capital leads to more output per capita at a diminishing rate. As an example, suppose <span class="math display">\[y = A\times k ^{1/3}.\]</span></p>
<p>In this case the marginal product of capital is positive but diminishing.</p>
<p>The second component is capital accumulation. If we let kt be the amount of capital per capita at the start of year t, then we know that <span class="math display">\[k' = (1 − \delta)k + i,\]</span> where the “prime” indicates a variable in period <span class="math inline">\(t+1\)</span>.</p>
<p>This expression shows how the capital stock changes over time. Here <span class="math inline">\(\delta\)</span> is the rate of physical depreciation so that between year t and year t+1, <span class="math inline">\(\delta k\)</span> units of capital are lost from depreciation. But during year t, there is investment (<span class="math inline">\(i\)</span>) that yields new capital in the following year.</p>
<p>The final component of the Solow growth model is saving. In a closed economy, saving is the same as investment. Thus we link it in the accumulation equation to saving. Assume that saving per capita (<span class="math inline">\(s_t\)</span>) is given by <span class="math display">\[s_t = s × y.\]</span></p>
<p>Here <span class="math inline">\(s\)</span> is a constant between zero and one, so only a fraction of total output is saved.</p>
<p>Using the fact that savings equals investment, along with the per capita production function, we can relate investment to the level of capital: <span class="math display">\[i = s\times A \times f(k).\]</span></p>
<p>We can then write the equation for the evolution of the capital stock as follows: <span class="math display">\[k' = k (1 − \delta) + s \times A \times f(k).\]</span></p>
<p>Once we have specified the function <span class="math inline">\(f()\)</span>, we can follow the evolution of the capital stock over time. Generally, the path of the capital stock over time has two important properties:</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Steady state
</div>
</div>
<div class="callout-body-container callout-body">
<p>There is a particular level of the capital stock such that if the economy accumulates that amount of capital, it stays at that level of capital. We call this the steady state level of capital, denoted <span class="math inline">\(k^*\)</span>.</p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Stability
</div>
</div>
<div class="callout-body-container callout-body">
<p>The economy will tend toward the per capita capital stock <span class="math inline">\(k^*\)</span>.</p>
</div>
</div>
<p>To be more specific, the steady state level of capital solves the following equation: <span class="math display">\[k^* = k^* \times (1 − \delta) + s \times A \times f(k^*).\]</span></p>
<p>At the steady state, the amount of capital lost by depreciation is exactly offset by saving. This means that at the steady state, net investment is exactly zero. The property of stability means that if the current capital stock is below k*, the economy will accumulate capital so that <span class="math inline">\(k' &gt; k\)</span>. And if the current capital stock is above <span class="math inline">\(k^*\)</span>, the economy will decumulate capital so that <span class="math inline">\(k' &lt; k\)</span>.</p>
<p>If two countries share the same technology (A) and the same production function <span class="math inline">\(f(k)\)</span>, then over time these two countries will eventually have the same stock of capital per worker. If there are differences in the technology or the production function, then there is no reason for the two countries to converge to the same level of capital stock per worker.</p>
<!--Numerical Implementation of the Solow Growth Model {{{2-->
</section>
<section id="numerical-implementation-of-the-solow-growth-model" class="level2" data-number="10.7">
<h2 data-number="10.7" class="anchored" data-anchor-id="numerical-implementation-of-the-solow-growth-model"><span class="header-section-number">10.7</span> Numerical Implementation of the Solow Growth Model</h2>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Section Learning Objectives
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>Numerical Implementation</li>
</ul>
</div>
</div>
<p>The model consists of the following key components:</p>
<ul>
<li><p><strong>Production Function</strong>: It describes how an economy converts inputs (capital and labor) into output.</p></li>
<li><p><strong>Capital Accumulation</strong>: The process of investment in capital goods, determining the economy’s capital stock over time.</p></li>
<li><p><strong>Population Growth</strong>: Changes in the labor force due to births and deaths.</p></li>
<li><p><strong>Technological Progress</strong>: Enhancements in technology or productivity growth.</p></li>
</ul>
<p>The production function expresses the relationship between the economy’s output and the inputs of capital (<span class="math inline">\(K_t\)</span>) and labor (<span class="math inline">\(N_t\)</span>):</p>
<p><span class="math display">\[ Y_t = A \times F(K_t, N_t) \]</span></p>
<ol start="2" type="1">
<li>The capital accumulation equation:</li>
</ol>
<p>The change in capital per worker over time is defined by the investment in new capital (<span class="math inline">\(sY_t\)</span>) and the depreciation of existing capital (<span class="math inline">\(\delta K_t\)</span>):</p>
<p><span class="math display">\[
\Delta K_t = sY_t - \delta K_t
\]</span></p>
<ol start="3" type="1">
<li>The capital law of motion:</li>
</ol>
<p>This equation characterizes the dynamic accumulation of capital per worker in each period:</p>
<p><span class="math display">\[
K_{t+1} = (1 - \delta)K_t + sF(K_t, N_t)
\]</span></p>
<p>We can express this in per capita terms by dividing both sides with <span class="math inline">\(N_t\)</span> so we get <span class="math display">\[
k_{t+1} \times (1+n) =  s \times A \times F(k_t, 1) + (1 - \delta)k_t
\]</span></p>
<p>where <span class="math inline">\(k=\frac{K}{N}\)</span>. After dividing by <span class="math inline">\(1+n\)</span> and using $f(k_t)=F(k_t,1) we get the <strong>per capita capital</strong> law of motion:</p>
<p><span class="math display">\[
k_{t+1} =  \frac{s \times A \times f(k_t)}{1+n} + \frac{(1 - \delta)}{1+n} \times k_t
\]</span></p>
<ol start="4" type="1">
<li>The steady-state condition:</li>
</ol>
<p>The steady state occurs when the capital per worker no longer changes over time:</p>
<p><span class="math display">\[
k_{t+1} = k_t = k^*
\]</span></p>
<ol start="5" type="1">
<li>The steady-state level of capital per worker:</li>
</ol>
<p>Using a Cobb-Douglas production function</p>
<p><span class="math display">\[ Y_t = A \times F(K_t, N_t) = A \times K_t^\alpha N_t^{(1-\alpha)}\]</span></p>
<p>and expressing it on a per capita basis as:</p>
<p><span class="math display">\[ y_t = A \times k_t^\alpha. \]</span></p>
<p>We then use the law of motion of per-capita-capital:</p>
<p><span class="math display">\[
k_{t+1} =  \frac{s \times A \times k_t^\alpha}{1+n} + \frac{(1 - \delta)}{1+n} \times k_t
\]</span></p>
<p>and impose the steady state condition <span class="math inline">\(k_{t+1}=k_t=k^*\)</span> so that the law of motion becomes</p>
<p><span class="math display">\[
k^* =  \frac{s \times A \times (k^*)^\alpha}{1+n} + \frac{(1 - \delta)}{1+n} \times k^*.
\]</span></p>
<p>We can now solve this for steady-state capital per capita <span class="math inline">\(k^*\)</span>:</p>
<p><span class="math display">\[
k^* = \left(\frac{s \times A}{n+\delta}\right)^{\frac{1}{1-\alpha}}
\]</span></p>
</section>
<section id="python-code-for-plotting-capital-law-of-motion-and-steady-state" class="level2" data-number="10.8">
<h2 data-number="10.8" class="anchored" data-anchor-id="python-code-for-plotting-capital-law-of-motion-and-steady-state"><span class="header-section-number">10.8</span> Python Code for Plotting Capital Law of Motion and Steady State</h2>
<p>Below is the Python code to visualize the capital law of motion and the steady state of per capita capital:</p>
<div id="3bea3bff" class="cell" data-results="hold" data-execution_count="4">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Parameters</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>A <span class="op">=</span> <span class="dv">1</span>       <span class="co"># TFP</span></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>s <span class="op">=</span> <span class="fl">0.2</span>     <span class="co"># savings rate</span></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>alpha <span class="op">=</span> <span class="fl">0.3</span>  <span class="co"># output elasticity of capital</span></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>n <span class="op">=</span> <span class="fl">0.02</span>  <span class="co"># population growth rate</span></span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>d <span class="op">=</span> <span class="fl">0.05</span>  <span class="co"># depreciation rate</span></span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Capital law of motion</span></span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> f_kprime(k):</span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> s <span class="op">*</span>A <span class="op">*</span> k<span class="op">**</span>alpha<span class="op">/</span>(<span class="fl">1.</span><span class="op">+</span>n) <span class="op">+</span> (<span class="dv">1</span><span class="op">-</span>d)<span class="op">/</span>(<span class="dv">1</span><span class="op">+</span>n)<span class="op">*</span>k</span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Steady-state capital per worker</span></span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a>kstar <span class="op">=</span> (s<span class="op">*</span>A<span class="op">/</span>(n<span class="op">+</span>d))<span class="op">**</span>(<span class="dv">1</span><span class="op">/</span>(<span class="dv">1</span><span class="op">-</span>alpha))</span>
<span id="cb5-17"><a href="#cb5-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-18"><a href="#cb5-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Time and capital per worker</span></span>
<span id="cb5-19"><a href="#cb5-19" aria-hidden="true" tabindex="-1"></a>tv <span class="op">=</span> np.arange(<span class="dv">0</span>, <span class="dv">100</span>, <span class="dv">1</span>)</span>
<span id="cb5-20"><a href="#cb5-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-21"><a href="#cb5-21" aria-hidden="true" tabindex="-1"></a>kv <span class="op">=</span> np.zeros(<span class="bu">len</span>(tv))</span>
<span id="cb5-22"><a href="#cb5-22" aria-hidden="true" tabindex="-1"></a>kprimev <span class="op">=</span> np.zeros(<span class="bu">len</span>(tv))</span>
<span id="cb5-23"><a href="#cb5-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-24"><a href="#cb5-24" aria-hidden="true" tabindex="-1"></a>kv[<span class="dv">0</span>] <span class="op">=</span> <span class="fl">3.0</span>  <span class="co"># initial capital per worker</span></span>
<span id="cb5-25"><a href="#cb5-25" aria-hidden="true" tabindex="-1"></a>kprimev[<span class="dv">0</span>] <span class="op">=</span> f_kprime(kv[<span class="dv">0</span>]) <span class="co"># capital tomorrow</span></span>
<span id="cb5-26"><a href="#cb5-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-27"><a href="#cb5-27" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> t <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">1</span>, <span class="bu">len</span>(tv)):</span>
<span id="cb5-28"><a href="#cb5-28" aria-hidden="true" tabindex="-1"></a>    kv[t] <span class="op">=</span> kprimev[t<span class="op">-</span><span class="dv">1</span>]</span>
<span id="cb5-29"><a href="#cb5-29" aria-hidden="true" tabindex="-1"></a>    kprimev[t] <span class="op">=</span> f_kprime(kv[t])</span>
<span id="cb5-30"><a href="#cb5-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-31"><a href="#cb5-31" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(kv[<span class="dv">1</span>:<span class="dv">5</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[3.06674297 3.13071114 3.19199422 3.2506822 ]</code></pre>
</div>
</div>
<p>Print capital over time.</p>
<div id="8bbb758d" class="cell" data-execution_count="5">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots()</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>ax.plot(tv, kv)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>ax.axhline(y<span class="op">=</span>kstar, color<span class="op">=</span><span class="st">'r'</span>, linestyle<span class="op">=</span><span class="st">'--'</span>, label<span class="op">=</span><span class="st">'Steady State'</span>)</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>ax.set_xlabel(<span class="st">'$t$ Time'</span>)</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>ax.set_ylabel(<span class="st">'$k$ Capital per worker'</span>)</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="st">'Capital over time'</span>)</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><a href="ch10-Growth_files/figure-html/cell-6-output-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-10"><img src="ch10-Growth_files/figure-html/cell-6-output-1.png" width="588" height="447" class="figure-img"></a></p>
</figure>
</div>
</div>
</div>
<p>Print the per-capita law of motion and put the capital path into it.</p>
<div id="4768afdf" class="cell" data-execution_count="6">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>kgridv<span class="op">=</span>np.linspace(<span class="dv">0</span>,<span class="dv">5</span>,<span class="dv">50</span>)<span class="op">;</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>knextv<span class="op">=</span>f_kprime(kgridv)<span class="op">;</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots()</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>ax.plot(kgridv, knextv, <span class="st">'b-'</span>)</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>ax.plot(kv[<span class="dv">0</span>:<span class="op">-</span><span class="dv">2</span>:<span class="dv">5</span>], kprimev[<span class="dv">1</span>:<span class="op">-</span><span class="dv">1</span>:<span class="dv">5</span>], <span class="st">'o'</span>)</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>ax.axhline(y<span class="op">=</span>kstar, color<span class="op">=</span><span class="st">'r'</span>, linestyle<span class="op">=</span><span class="st">'--'</span>, label<span class="op">=</span><span class="st">'Steady State'</span>)</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>ax.axvline(x<span class="op">=</span>kstar, color<span class="op">=</span><span class="st">'r'</span>, linestyle<span class="op">=</span><span class="st">'--'</span>, label<span class="op">=</span><span class="st">'Steady State'</span>)</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>ax.set_xlabel(<span class="st">'$k$ Capital per worker present period'</span>)</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>ax.set_ylabel(<span class="st">'$k-prime$ Capital per worker next period'</span>)</span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="st">'Capital Law of Motion and Steady State'</span>)</span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><a href="ch10-Growth_files/figure-html/cell-7-output-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-11"><img src="ch10-Growth_files/figure-html/cell-7-output-1.png" width="577" height="449" class="figure-img"></a></p>
</figure>
</div>
</div>
</div>
<p>This code will produce a plot showing the evolution of capital per worker over time and the horizontal line indicating the steady-state level of capital per worker.</p>
<!--Advanced: The Balanced Growth Path {{{2-->
</section>
<section id="advanced-the-balanced-growth-path" class="level2" data-number="10.9">
<h2 data-number="10.9" class="anchored" data-anchor-id="advanced-the-balanced-growth-path"><span class="header-section-number">10.9</span> Advanced: The Balanced Growth Path</h2>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Section Learning Objectives
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>Balanced growth path</li>
</ul>
</div>
</div>
<p><strong>Balanced Growth Path</strong></p>
<p>In this presentation, we explain the balanced-growth path of the economy and prove some of the claims made in the text. The model takes as given (exogenous) the investment rate; the depreciation rate; and the growth rates of the workforce, human capital, and technology. The endogenous variables are output and physical capital stock.</p>
<p>The notation for the presentation is given in Table 31.11 “Notation in the Solow Growth Model”: We use the notation <span class="math inline">\(g_x\)</span> to represent the growth rate of a variable <span class="math inline">\(x\)</span>; that is, <span class="math display">\[g_x=\frac{x'-x}{x} = \frac{\Delta x}{x}=\%\Delta x.\]</span></p>
<p>There are two key ingredients to the model: the aggregate production function and the equation for capital accumulation.</p>
<div id="tbl-notation" class="quarto-float anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-notation-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;10.6: Notation in the Solow Growth Model
</figcaption>
<div aria-describedby="tbl-notation-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="table">
<thead>
<tr class="header">
<th>Variable</th>
<th>Symbol</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Real gross domestic product</td>
<td>Y</td>
</tr>
<tr class="even">
<td>Capital stock</td>
<td>K</td>
</tr>
<tr class="odd">
<td>Human capital</td>
<td>H</td>
</tr>
<tr class="even">
<td>Workforce</td>
<td>L</td>
</tr>
<tr class="odd">
<td>Technology</td>
<td>A</td>
</tr>
<tr class="even">
<td>Investment rate</td>
<td>i</td>
</tr>
<tr class="odd">
<td>Depreciation rate</td>
<td><span class="math inline">\(\delta\)</span></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<section id="the-production-function" class="level3" data-number="10.9.1">
<h3 data-number="10.9.1" class="anchored" data-anchor-id="the-production-function"><span class="header-section-number">10.9.1</span> The Production Function</h3>
<p>The production function we use is the Cobb-Douglas production function:</p>
<p><span id="eq-311"><span class="math display">\[Y = A \times K^\alpha \times (HL)^{1−\alpha}. \tag{10.1}\]</span></span></p>
<p><strong>Growth Accounting</strong></p>
<p>If we apply the rules of growth rates to <a href="#eq-311" class="quarto-xref">Equation&nbsp;<span>10.1</span></a>, we get the following expression:</p>
<p><span id="eq-312"><span class="math display">\[g_Y = g_A + \alpha g_K + (1 - \alpha)(g_L + g_H). \tag{10.2}\]</span></span></p>
<p><strong>Balanced Growth</strong></p>
<p>The condition for <strong>balanced growth</strong> is that</p>
<p><span class="math display">\[g_Y = g_K.\]</span></p>
<p>When we impose this condition on our equation for the growth rate of output (<a href="#eq-312" class="quarto-xref">Equation&nbsp;<span>10.2</span></a>), we get:</p>
<p><span class="math display">\[g_Y^{BG} = \alpha g_Y^{BG} + (1 - \alpha)(g_L + g_H) + g_A,\]</span></p>
<p>where the superscript “BG” indicates that we are considering the values of variables when the economy is on a balanced growth path. This equation simplifies to:</p>
<p><span id="eq-313"><span class="math display">\[g_Y^{BG} = g_L + g_H + \frac{g_A}{1 - \alpha} . \tag{10.3}\]</span></span></p>
<p>The growth in output on a balanced-growth path depends on the growth rates of the workforce, human capital, and technology.</p>
<p>Using this, we can rewrite <a href="#eq-312" class="quarto-xref">Equation&nbsp;<span>10.2</span></a> as follows:</p>
<p><span id="eq-314"><span class="math display">\[g_Y = \alpha g_K + (1 - \alpha)g_Y^{BG}. \tag{10.4}\]</span></span></p>
<p>The actual growth rate in output is an average of the balanced-growth rate of output and the growth rate of the capital stock.</p>
<p><strong>Capital Accumulation</strong></p>
<p>The second piece of our model is the capital accumulation equation.</p>
<p><span class="math display">\[K' = (1- \delta)K + I,\]</span></p>
<p>The growth rate of the capital stock is given by:</p>
<p><span class="math display">\[\frac{K'}{K} = (1- \delta) + \frac{I}{K}, \]</span></p>
<p>which can be simplified to</p>
<p><span class="math display">\[\frac{K'}{K} -1 = \frac{I}{K}- \delta,  \]</span></p>
<p>or with <span class="math inline">\(g_K = \frac{K'-K}{K} = \frac{K'}{K} -1\)</span> we get</p>
<p><span id="eq-315"><span class="math display">\[g_K = \frac{I}{K}- \delta. \tag{10.5}\]</span></span></p>
<p>Divide the numerator and denominator of the first term by Y, remembering that (i = I/Y).</p>
<p><span id="eq-316"><span class="math display">\[g_K = \frac{i}{K/Y} - \delta. \tag{10.6}\]</span></span></p>
<p>The growth rate of the capital stock depends positively on the investment rate and negatively on the depreciation rate. It also depends negatively on the current capital-output ratio.</p>
<p><strong>The Balanced-Growth Capital-Output Ratio</strong></p>
<p>Now rearrange <a href="#eq-316" class="quarto-xref">Equation&nbsp;<span>10.6</span></a> to give the ratio of capital to gross domestic product (GDP), given the depreciation rate, the investment rate, and the growth rate of the capital stock:</p>
<p><span class="math display">\[\frac{K}{Y} = i\delta + g_K.\]</span></p>
<p>When the economy is on a balanced growth path, <span class="math inline">\(g_K = g_Y^{BG}\)</span>, so:</p>
<p><span class="math display">\[\left(\frac{K}{Y}\right)^{BG} = \frac{i}{\delta + g_Y^{BG}}.\]</span></p>
<p>We can also substitute in our balanced-growth expression for <span class="math inline">\(\left(g_Y^{BG}\right)\)</span> (<a href="#eq-313" class="quarto-xref">Equation&nbsp;<span>10.3</span></a>) to get an expression for the balanced-growth capital output ratio in terms of exogenous variables:</p>
<p><span class="math display">\[\left(\frac{K}{Y}\right)^{BG}= \frac{i}{\delta + g_L + g_H + \frac{1}{1 - \alpha}g_A}.\]</span></p>
<p><strong>Convergence</strong></p>
<p>The proof that economies will converge to the balanced-growth ratio of capital to GDP is relatively straightforward. We want to show that if</p>
<p><span class="math display">\[\frac{K}{Y} &lt; \left(\frac{K}{Y}\right)^{BG},\]</span></p>
<p>then capital grows faster than output. If capital is growing faster than output, <span class="math inline">\(g_K - g_Y &gt; 0\)</span>. First, go back to <a href="#eq-314" class="quarto-xref">Equation&nbsp;<span>10.4</span></a>:</p>
<p><span class="math display">\[g_Y = \alpha g_K + (1 - \alpha)g_Y^{BG}.\]</span></p>
<p>Subtract both sides from the growth rate of capital:</p>
<p><span class="math display">\[g_K - g_Y = g_K - \alpha g_K - (1 - \alpha)g_Y^{BG} = (1 - \alpha)(g_K - g_Y^{BG}).\]</span></p>
<p>Now compare the general expression for the ratio of capital to GDP with its balanced growth value:</p>
<p><span class="math display">\[K/Y = i\delta + g_K\text{ (general expression)}\]</span></p>
<p>and</p>
<p><span class="math display">\[\left(\frac{k}{Y}\right)^{BG} = \frac{i}{\delta + g_Y^{BG}}.\text{ (balanced growth)}\]</span></p>
<p>If <span class="math inline">\((K/Y &lt; \left(\frac{K}{Y}\right)^{BG}\)</span>, then it must be the case that <span class="math inline">\(g_K &gt; g_Y^{BG}\)</span>, which implies (from the previous equation) that <span class="math inline">\(g_K &gt; g_Y\)</span>.</p>
<p><strong>Output per Worker Growth</strong></p>
<p>If we want to examine the growth in output per worker rather than total output, we take the per-worker production function (<a href="#eq-312" class="quarto-xref">Equation&nbsp;<span>10.2</span></a>) and apply the rules of growth rates to that equation:</p>
<p><span class="math display">\[g_{Y/L} = \frac{\alpha}{1 - \alpha} g_{K/Y} + g_H + g_A.\]</span></p>
<p><span class="math display">\[(1 - \alpha)g_Y = \alpha[g_K - g_Y] + (1 - \alpha)[g_L + g_H] + g_A = \alpha[g_K - g_Y] + (1 - \alpha)[g_L + g_H] + g_A.\]</span></p>
<p>We then divide by <span class="math inline">\((1 - \alpha)\)</span> to get:</p>
<p><span class="math display">\[g_Y = \alpha(1 - \alpha)[g_K - g_Y] + g_L + g_H + \frac{1}{1 - \alpha}g_A\]</span></p>
<p>and subtract <span class="math inline">\(g_L\)</span> from each side to obtain:</p>
<p><span class="math display">\[g_Y - g_L = \frac{\alpha}{1 - a}[g_K - g_Y] + g_H + \frac{1}{1 - \alpha}g_A.\]</span></p>
<p>Finally, we note that <span class="math inline">\(g_Y - g_L = g_{Y/L}\)</span>:</p>
<p><span class="math display">\[g_{Y/L} = \frac{\alpha}{1 - \alpha}[g_K - g_Y] + g_H + \frac{1}{1 - \alpha}g_A.\]</span></p>
<p>With balanced growth, the first term is equal to zero, so:</p>
<p><span class="math display">\[g_{Y/L}^{BG} = g_H + \frac{1}{1 - \alpha}g_A.\]</span></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Key Concepts and Summary
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>In a balanced growth path output and capital grow at the same rate.</li>
</ul>
</div>
</div>
<div class="callout callout-style-default callout-caution callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-28-contents" aria-controls="callout-28" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Self-Check Questions
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-28" class="callout-28-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ul>
<li>Set up the Solow growth model and calculate the steady state of per worker capital.</li>
</ul>
</div>
</div>
</div>


<div class="hidden" aria-hidden="true">
<span class="glightbox-desc lightbox-desc-1">Figure&nbsp;10.1: Nominal vs.&nbsp;Real GDP</span>
<span class="glightbox-desc lightbox-desc-2">Figure&nbsp;10.2: Nominal vs.&nbsp;Real GDP Growth Rates</span>
<span class="glightbox-desc lightbox-desc-3">Figure&nbsp;10.3: Not only has the number of calories that people consume per day increased, so has the amount of food calories that people are able to afford based on their working wages. (Credit: modification of work by Lauren Manning/Flickr Creative Commons)</span>
<span class="glightbox-desc lightbox-desc-4">Figure&nbsp;10.4: An aggregate production function shows what goes into producing the output for an overall economy. (a) This aggregate production function has GDP as its output. (b) This aggregate production function has GDP per capita as its output. Because we calculate it on a per-person basis, we already figure the labor input into the other factors and we do not need to list it separately.</span>
<span class="glightbox-desc lightbox-desc-5">Figure&nbsp;10.5: Output per hour worked is a measure of worker productivity. In the U.S. economy, worker productivity rose more quickly in the 1960s and the mid-1990s compared with the 1970s and 1980s. However, these growth-rate differences are only a few percentage points per year. Look carefully to see them in the changing slope of the line. The average U.S. worker produced over twice as much per hour in 2014 than he did in the early 1970s. (Source: U.S. Department of Labor, Bureau of Labor Statistics.)</span>
<span class="glightbox-desc lightbox-desc-6">Figure&nbsp;10.6: U.S. growth in worker productivity was very high between 1950 and 1970. It then declined to lower levels in the 1970s and the 1980s. The late 1990s and early 2000s saw productivity rebound, but then productivity sagged a bit in the 2000s. Some think the productivity rebound of the late 1990s and early 2000s marks the start of a “new economy” built on higher productivity growth, but we cannot determine this until more time has passed. (Source: U.S. Department of Labor, Bureau of Labor Statistics.)</span>
<span class="glightbox-desc lightbox-desc-7">Figure&nbsp;10.7: Rising levels of education for persons 25 and older show the deepening of human capital in the U.S. economy. Even today, under one-third of U.S. adults have completed a four-year college degree. There is clearly room for additional deepening of human capital to occur. (Source: US Department of Education, National Center for Education Statistics)</span>
<span class="glightbox-desc lightbox-desc-8">Figure&nbsp;10.8: The value of the physical capital, measured by plant and equipment, used by the average worker in the U.S. economy has risen over the decades. The increase may have leveled off a bit in the 1970s and 1980s, which were, not coincidentally, times of slower-than-usual growth in worker productivity. We see a renewed increase in physical capital per worker in the late 1990s, followed by a flattening in the early 2000s. (Source: Center for International Comparisons of Production, Income and Prices, University of Pennsylvania)</span>
<span class="glightbox-desc lightbox-desc-9">Figure&nbsp;10.9: Imagine that the economy starts at point R, with the level of physical and human capital C1 and the output per capita at G1. If the economy relies only on capital deepening, while remaining at the technology level shown by the Technology 1 line, then it would face diminishing marginal returns as it moved from point R to point U to point W. However, now imagine that capital deepening is combined with improvements in technology. Then, as capital deepens from C1 to C2, technology improves from Technology 1 to Technology 2, and the economy moves from R to S. Similarly, as capital deepens from C2 to C3, technology increases from Technology 2 to Technology 3, and the economy moves from S to T. With improvements in technology, there is no longer any reason that economic growth must necessarily slow down.</span>
</div>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./ch9-ProductionFullEmployment.html" class="pagination-link" aria-label="Production Technology and Full Employment">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Production Technology and Full Employment</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./ch11-AggregateDemandAggregateSupply.html" class="pagination-link" aria-label="Aggregate Demand and Aggregate Supply">
        <span class="nav-page-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Aggregate Demand and Aggregate Supply</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Copyright 2024, Juergen Jung</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item compact">
    <a class="nav-link" href="https://juejung.github.io/">
      <i class="bi bi-github" role="img">
</i> 
    </a>
  </li>  
</ul>
    </div>
  </div>
</footer>
<script>var lightboxQuarto = GLightbox({"openEffect":"zoom","loop":false,"closeEffect":"zoom","descPosition":"bottom","selector":".lightbox"});
window.onload = () => {
  lightboxQuarto.on('slide_before_load', (data) => {
    const { slideIndex, slideNode, slideConfig, player, trigger } = data;
    const href = trigger.getAttribute('href');
    if (href !== null) {
      const imgEl = window.document.querySelector(`a[href="${href}"] img`);
      if (imgEl !== null) {
        const srcAttr = imgEl.getAttribute("src");
        if (srcAttr && srcAttr.startsWith("data:")) {
          slideConfig.href = srcAttr;
        }
      }
    } 
  });

  lightboxQuarto.on('slide_after_load', (data) => {
    const { slideIndex, slideNode, slideConfig, player, trigger } = data;
    if (window.Quarto?.typesetMath) {
      window.Quarto.typesetMath(slideNode);
    }
  });

};
          </script>




</body></html>