<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.551">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Macroeconomic Principles - 13&nbsp; The Income Expenditure Model</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./ch14-InvestmentsFinancialMarkets.html" rel="next">
<link href="./ch12-FiscalPolicy.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script src="site_libs/quarto-contrib/glightbox/glightbox.min.js"></script>
<link href="site_libs/quarto-contrib/glightbox/glightbox.min.css" rel="stylesheet">
<link href="site_libs/quarto-contrib/glightbox/lightbox.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./ch12-FiscalPolicy.html"><strong>Macroeconomics Part II</strong></a></li><li class="breadcrumb-item"><a href="./ch13-IncomeExpenditureModel.html"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">The Income Expenditure Model</span></a></li></ol></nav>
        <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Macroeconomic Principles</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
 <span class="menu-text"><strong>Introduction</strong></span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ch1-Introduction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ch2-MathIntro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">The Use of Mathematics in Principles of Economics</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ch3-ChoiceScarcity.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Choice in a World of Scarcity</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ch4-DemandSupply.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Demand and Supply</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">
 <span class="menu-text"><strong>Macroeconomics Part I</strong></span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ch5-MacroPerspective.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Intro Macro Perspective</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ch6-InternationalTrade.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">International Trade</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ch7-Unemployment.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Unemployment</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ch8-Inflation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Inflation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ch9-ProductionFullEmployment.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Production Technology and Full Employment</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ch10-Growth.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Economic Growth</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ch11-AggregateDemandAggregateSupply.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Aggregate Demand and Aggregate Supply</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">
 <span class="menu-text"><strong>Macroeconomics Part II</strong></span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ch12-FiscalPolicy.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Government Budgets and Fiscal Policy</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ch13-IncomeExpenditureModel.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">The Income Expenditure Model</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ch14-InvestmentsFinancialMarkets.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Investments and Financial Markets</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ch15-MoneyAndBanking.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Money and Banking</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ch16-MonetaryPolicy.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Monetary Policy</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ch17-ShortToLong.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">From Short-Run to Long-Run</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendix-PythonBasics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">First Steps in Python</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#the-axes-of-the-expenditure-output-diagram" id="toc-the-axes-of-the-expenditure-output-diagram" class="nav-link active" data-scroll-target="#the-axes-of-the-expenditure-output-diagram"><span class="header-section-number">13.1</span> The Axes of the Expenditure-Output Diagram</a>
  <ul class="collapse">
  <li><a href="#the-potential-gdp-line-and-the-45-degree-line" id="toc-the-potential-gdp-line-and-the-45-degree-line" class="nav-link" data-scroll-target="#the-potential-gdp-line-and-the-45-degree-line"><span class="header-section-number">13.1.1</span> The Potential GDP Line and the 45-degree Line</a></li>
  <li><a href="#the-aggregate-expenditure-schedule" id="toc-the-aggregate-expenditure-schedule" class="nav-link" data-scroll-target="#the-aggregate-expenditure-schedule"><span class="header-section-number">13.1.2</span> The Aggregate Expenditure Schedule</a></li>
  </ul></li>
  <li><a href="#building-the-aggregate-expenditure-schedule" id="toc-building-the-aggregate-expenditure-schedule" class="nav-link" data-scroll-target="#building-the-aggregate-expenditure-schedule"><span class="header-section-number">13.2</span> Building the Aggregate Expenditure Schedule</a>
  <ul class="collapse">
  <li><a href="#consumption-as-a-function-of-national-income" id="toc-consumption-as-a-function-of-national-income" class="nav-link" data-scroll-target="#consumption-as-a-function-of-national-income"><span class="header-section-number">13.2.1</span> Consumption as a Function of National Income</a></li>
  <li><a href="#investment-as-a-function-of-national-income" id="toc-investment-as-a-function-of-national-income" class="nav-link" data-scroll-target="#investment-as-a-function-of-national-income"><span class="header-section-number">13.2.2</span> Investment as a Function of National Income</a></li>
  <li><a href="#government-spending-and-taxes-as-a-function-of-national-income" id="toc-government-spending-and-taxes-as-a-function-of-national-income" class="nav-link" data-scroll-target="#government-spending-and-taxes-as-a-function-of-national-income"><span class="header-section-number">13.2.3</span> Government Spending and Taxes as a Function of National Income</a></li>
  <li><a href="#exports-and-imports-as-a-function-of-national-income" id="toc-exports-and-imports-as-a-function-of-national-income" class="nav-link" data-scroll-target="#exports-and-imports-as-a-function-of-national-income"><span class="header-section-number">13.2.4</span> Exports and Imports as a Function of National Income</a></li>
  <li><a href="#using-an-algebraic-approach-to-the-expenditure-output-model" id="toc-using-an-algebraic-approach-to-the-expenditure-output-model" class="nav-link" data-scroll-target="#using-an-algebraic-approach-to-the-expenditure-output-model"><span class="header-section-number">13.2.5</span> USING AN ALGEBRAIC APPROACH TO THE EXPENDITURE-OUTPUT MODEL</a></li>
  <li><a href="#building-the-combined-aggregate-expenditure-function" id="toc-building-the-combined-aggregate-expenditure-function" class="nav-link" data-scroll-target="#building-the-combined-aggregate-expenditure-function"><span class="header-section-number">13.2.6</span> Building the Combined Aggregate Expenditure Function</a></li>
  </ul></li>
  <li><a href="#equilibrium-in-the-keynesian-cross-model" id="toc-equilibrium-in-the-keynesian-cross-model" class="nav-link" data-scroll-target="#equilibrium-in-the-keynesian-cross-model"><span class="header-section-number">13.3</span> Equilibrium in the Keynesian Cross Model</a>
  <ul class="collapse">
  <li><a href="#where-equilibrium-occurs" id="toc-where-equilibrium-occurs" class="nav-link" data-scroll-target="#where-equilibrium-occurs"><span class="header-section-number">13.3.1</span> Where Equilibrium Occurs</a></li>
  <li><a href="#recessionary-and-inflationary-gaps" id="toc-recessionary-and-inflationary-gaps" class="nav-link" data-scroll-target="#recessionary-and-inflationary-gaps"><span class="header-section-number">13.3.2</span> Recessionary and Inflationary Gaps</a></li>
  </ul></li>
  <li><a href="#the-multiplier-effect" id="toc-the-multiplier-effect" class="nav-link" data-scroll-target="#the-multiplier-effect"><span class="header-section-number">13.4</span> The Multiplier Effect</a>
  <ul class="collapse">
  <li><a href="#how-does-the-multiplier-work" id="toc-how-does-the-multiplier-work" class="nav-link" data-scroll-target="#how-does-the-multiplier-work"><span class="header-section-number">13.4.1</span> How Does the Multiplier Work?</a></li>
  <li><a href="#calculating-the-multiplier" id="toc-calculating-the-multiplier" class="nav-link" data-scroll-target="#calculating-the-multiplier"><span class="header-section-number">13.4.2</span> Calculating the Multiplier</a></li>
  <li><a href="#calculating-keynesian-policy-interventions" id="toc-calculating-keynesian-policy-interventions" class="nav-link" data-scroll-target="#calculating-keynesian-policy-interventions"><span class="header-section-number">13.4.3</span> Calculating Keynesian Policy Interventions</a></li>
  <li><a href="#multiplier-tradeoffs-stability-versus-the-power-of-macroeconomic-policy" id="toc-multiplier-tradeoffs-stability-versus-the-power-of-macroeconomic-policy" class="nav-link" data-scroll-target="#multiplier-tradeoffs-stability-versus-the-power-of-macroeconomic-policy"><span class="header-section-number">13.4.4</span> Multiplier Tradeoffs: Stability versus the Power of Macroeconomic Policy</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./ch12-FiscalPolicy.html"><strong>Macroeconomics Part II</strong></a></li><li class="breadcrumb-item"><a href="./ch13-IncomeExpenditureModel.html"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">The Income Expenditure Model</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">The Income Expenditure Model</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<!--The Income Expenditure Model {{{1-->
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Chapter Learning Objectives
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>The Income Expenditure Model</li>
<li>Consumption Function</li>
<li>Keynesian Cross Model</li>
<li>Multiplier Effects</li>
</ul>
</div>
</div>
<p>The fundamental ideas of Keynesian economics were developed before the AD/AS model was popularized. From the 1930s until the 1970s, Keynesian economics was usually explained with a different model, known as the expenditure-output approach. This approach is strongly rooted in the fundamental assumptions of Keynesian economics: it focuses on the total amount of spending in the economy, with no explicit mention of aggregate supply or of the price level (although as you will see, it is possible to draw some inferences about aggregate supply and price levels based on the diagram).</p>
<!--The Axes of the Expenditure-Output Diagram {{{2-->
<section id="the-axes-of-the-expenditure-output-diagram" class="level2" data-number="13.1">
<h2 data-number="13.1" class="anchored" data-anchor-id="the-axes-of-the-expenditure-output-diagram"><span class="header-section-number">13.1</span> The Axes of the Expenditure-Output Diagram</h2>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Chapter Learning Objectives
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>Income Expenditure Model</li>
</ul>
</div>
</div>
<p>The expenditure-output model, sometimes also called the Keynesian cross diagram, determines the equilibrium level of real GDP by the point where the total or aggregate expenditures in the economy are equal to the amount of output produced. The axes of the Keynesian cross diagram presented in <a href="#fig-IE_1" class="quarto-xref">Figure&nbsp;<span>13.1</span></a> show real GDP on the horizontal axis as a measure of output and aggregate expenditures on the vertical axis as a measure of spending.</p>
<div id="fig-IE_1" class="align-center quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-IE_1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="Graphs/IncomeExpenditureModel/CNX_Econ_C25_011.jpg" class="lightbox" data-gallery="quarto-lightbox-gallery-1" data-glightbox="description: .lightbox-desc-1"><img src="Graphs/IncomeExpenditureModel/CNX_Econ_C25_011.jpg" class="align-center img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-IE_1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;13.1: The Expenditure-Output Diagram. The aggregate expenditure-output model shows aggregate expenditures on the vertical axis and real GDP on the horizontal axis. A vertical line shows potential GDP where full employment occurs. The 45-degree line shows all points where aggregate expenditures and output are equal. The aggregate expenditure schedule shows how total spending or aggregate expenditure increases as output or real GDP rises. The intersection of the aggregate expenditure schedule and the 45-degree line will be the equilibrium. Equilibrium occurs at E0, where aggregate expenditure AE0 is equal to the output level Y0.
</figcaption>
</figure>
</div>
<p>The graph shows the aggregate expenditure-output diagram. The x-axis is labeled “real GDP” and the y-axis is labeled aggregate expenditure. An upward sloping 45 degree line extends from the origin and intersects with the aggregate expenditure line at point E sub 0. Potential GDP is a straight vertical line.</p>
<p>Remember that GDP can be thought of in several equivalent ways: it measures both the value of spending on final goods and also the value of the production of final goods. All sales of the final goods and services that make up GDP will eventually end up as income for workers, for managers, and for investors and owners of firms. The sum of all the income received for contributing resources to GDP is called national income (Y). At some points in the discussion that follows, it will be useful to refer to real GDP as “national income.” Both axes are measured in real (inflation-adjusted) terms.</p>
<section id="the-potential-gdp-line-and-the-45-degree-line" class="level3" data-number="13.1.1">
<h3 data-number="13.1.1" class="anchored" data-anchor-id="the-potential-gdp-line-and-the-45-degree-line"><span class="header-section-number">13.1.1</span> The Potential GDP Line and the 45-degree Line</h3>
<p>The Keynesian cross diagram contains two lines that serve as conceptual guideposts to orient the discussion. The first is a vertical line showing the level of potential GDP. Potential GDP means the same thing here that it means in the AD/AS diagrams: it refers to the quantity of output that the economy can produce with full employment of its labor and physical capital.</p>
<p>The second conceptual line on the Keynesian cross diagram is the 45-degree line, which starts at the origin and reaches up and to the right. A line that stretches up at a 45-degree angle represents the set of points (1, 1), (2, 2), (3, 3) and so on, where the measurement on the vertical axis is equal to the measurement on the horizontal axis. In this diagram, the 45-degree line shows the set of points where the level of aggregate expenditure in the economy, measured on the vertical axis, is equal to the level of output or national income in the economy, measured by GDP on the horizontal axis.</p>
<p>When the macroeconomy is in equilibrium, it must be true that the aggregate expenditures in the economy are equal to the real GDP—because by definition, GDP is the measure of what is spent on final sales of goods and services in the economy. Thus, the equilibrium calculated with a Keynesian cross diagram will always end up where aggregate expenditure and output are equal—which will only occur along the 45-degree line.</p>
</section>
<section id="the-aggregate-expenditure-schedule" class="level3" data-number="13.1.2">
<h3 data-number="13.1.2" class="anchored" data-anchor-id="the-aggregate-expenditure-schedule"><span class="header-section-number">13.1.2</span> The Aggregate Expenditure Schedule</h3>
<p>The final ingredient of the Keynesian cross or expenditure-output diagram is the aggregate expenditure schedule, which will show the total expenditures in the economy for each level of real GDP. The intersection of the aggregate expenditure line with the 45-degree line—at point E0 in Figure—will show the equilibrium for the economy, because it is the point where aggregate expenditure is equal to output or real GDP. After developing an understanding of what the aggregate expenditures schedule means, we will return to this equilibrium and how to interpret it.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Key Concepts and Summary
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>The expenditure-output model or Keynesian cross diagram shows how the level of aggregate expenditure (on the vertical axis) varies with the level of economic output (shown on the horizontal axis). Since the value of all macroeconomic output also represents income to someone somewhere else in the economy, the horizontal axis can also be interpreted as national income.</li>
<li>The equilibrium in the diagram will occur where the aggregate expenditure line crosses the 45-degree line, which represents the set of points where aggregate expenditure in the economy is equal to output (or national income). Equilibrium in a Keynesian cross diagram can happen at potential GDP, or below or above that level.</li>
</ul>
</div>
</div>
<div class="callout callout-style-default callout-caution callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Self-Check Questions
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ul>
<li>What is on the axes of an expenditure-output diagram?</li>
<li>What does the 45-degree line show?</li>
<li>What does it mean when the aggregate expenditure line crosses the 45-degree line? In other words, how would you explain the intersection in words?</li>
</ul>
</div>
</div>
</div>
<!--Building the Aggregate Expenditure Schedule {{{2-->
</section>
</section>
<section id="building-the-aggregate-expenditure-schedule" class="level2" data-number="13.2">
<h2 data-number="13.2" class="anchored" data-anchor-id="building-the-aggregate-expenditure-schedule"><span class="header-section-number">13.2</span> Building the Aggregate Expenditure Schedule</h2>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Chapter Learning Objectives
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>Aggregate Expenditure</li>
<li>Consumption Function</li>
<li>Investment and Government Spending</li>
<li>Exports and Imports</li>
</ul>
</div>
</div>
<p>Aggregate expenditure is the key to the expenditure-income model. The aggregate expenditure schedule shows, either in the form of a table or a graph, how aggregate expenditures in the economy rise as real GDP or national income rises. Thus, in thinking about the components of the aggregate expenditure line—consumption, investment, government spending, exports and imports—the key question is how expenditures in each category will adjust as national income rises.</p>
<section id="consumption-as-a-function-of-national-income" class="level3" data-number="13.2.1">
<h3 data-number="13.2.1" class="anchored" data-anchor-id="consumption-as-a-function-of-national-income"><span class="header-section-number">13.2.1</span> Consumption as a Function of National Income</h3>
<p>How do consumption expenditures increase as national income rises? People can do two things with their income: consume it or save it (for the moment, let’s ignore the need to pay taxes with some of it). Each person who receives an additional dollar faces this choice. The marginal propensity to consume (MPC), is the share of the additional dollar of income a person decides to devote to consumption expenditures. The marginal propensity to save (MPS) is the share of the additional dollar a person decides to save. It must always hold true that:</p>
<p><span class="math display">\[MPC + MPS = 1\]</span></p>
<p>For example, if the marginal propensity to consume out of the marginal amount of income earned is 0.9, then the marginal propensity to save is 0.1.</p>
<p>With this relationship in mind, consider the relationship among income, consumption, and savings shown in <a href="#fig-IE_1" class="quarto-xref">Figure&nbsp;<span>13.1</span></a>. (Note that we use “Aggregate Expenditure” on the vertical axis in this and the following figures, because all consumption expenditures are parts of aggregate expenditures.)</p>
<p>An assumption commonly made in this model is that even if income were zero, people would have to consume something. In this example, consumption would be $600 even if income were zero. Then, the MPC is 0.8 and the MPS is 0.2. Thus, when income increases by $1,000, consumption rises by $800 and savings rises by $200. At an income of $4,000, total consumption will be the $600 that would be consumed even without any income, plus $4,000 multiplied by the marginal propensity to consume of 0.8, or $ 3,200, for a total of $ 3,800. The total amount of consumption and saving must always add up to the total amount of income. (Exactly how a situation of zero income and negative savings would work in practice is not important, because even low-income societies are not literally at zero income, so the point is hypothetical.) This relationship between income and consumption, illustrated in <a href="#fig-IE_2" class="quarto-xref">Figure&nbsp;<span>13.2</span></a> and <a href="#tbl-IE_1" class="quarto-xref">Table&nbsp;<span>13.1</span></a>, is called the consumption function.</p>
<div id="fig-IE_2" class="align-center quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-IE_2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="Graphs/IncomeExpenditureModel/CNX_Econ_C25_012.jpg" class="lightbox" data-gallery="quarto-lightbox-gallery-2" data-glightbox="description: .lightbox-desc-2"><img src="Graphs/IncomeExpenditureModel/CNX_Econ_C25_012.jpg" class="align-center img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-IE_2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;13.2: The Consumption Function. In the expenditure-output model, how does consumption increase with the level of national income? Output on the horizontal axis is conceptually the same as national income, since the value of all final output that is produced and sold must be income to someone, somewhere in the economy. At a national income level of zero, $600 is consumed. Then, each time income rises by $1,000, consumption rises by $800, because in this example, the marginal propensity to consume is 0.8.
</figcaption>
</figure>
</div>
<p>The graph shows an upward-sloping line representative of the consumption function.</p>
<p>The pattern of consumption shown in <a href="#tbl-IE_1" class="quarto-xref">Table&nbsp;<span>13.1</span></a> is plotted in <a href="#fig-IE_2" class="quarto-xref">Figure&nbsp;<span>13.2</span></a>. To calculate consumption, multiply the income level by 0.8, for the marginal propensity to consume, and add $600, for the amount that would be consumed even if income was zero. Consumption plus savings must be equal to income.</p>
<div id="tbl-IE_1" class="quarto-float anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-IE_1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;13.1: The Consumption Function
</figcaption>
<div aria-describedby="tbl-IE_1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="table">
<thead>
<tr class="header">
<th style="text-align: left;">Income</th>
<th style="text-align: left;">Consumption</th>
<th style="text-align: left;">Savings</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">$0</td>
<td style="text-align: left;">$600</td>
<td style="text-align: left;">–$600</td>
</tr>
<tr class="even">
<td style="text-align: left;">$1,000</td>
<td style="text-align: left;">$1,400</td>
<td style="text-align: left;">–$400</td>
</tr>
<tr class="odd">
<td style="text-align: left;">$2,000</td>
<td style="text-align: left;">$2,200</td>
<td style="text-align: left;">–$200</td>
</tr>
<tr class="even">
<td style="text-align: left;">$3,000</td>
<td style="text-align: left;">$3,000</td>
<td style="text-align: left;">$0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">$4,000</td>
<td style="text-align: left;">$3,800</td>
<td style="text-align: left;">$200</td>
</tr>
<tr class="even">
<td style="text-align: left;">$5,000</td>
<td style="text-align: left;">$4,600</td>
<td style="text-align: left;">$400</td>
</tr>
<tr class="odd">
<td style="text-align: left;">$6,000</td>
<td style="text-align: left;">$5,400</td>
<td style="text-align: left;">$600</td>
</tr>
<tr class="even">
<td style="text-align: left;">$7,000</td>
<td style="text-align: left;">$6,200</td>
<td style="text-align: left;">$800</td>
</tr>
<tr class="odd">
<td style="text-align: left;">$8,000</td>
<td style="text-align: left;">$7,000</td>
<td style="text-align: left;">$1,000</td>
</tr>
<tr class="even">
<td style="text-align: left;">$9,000</td>
<td style="text-align: left;">$7,800</td>
<td style="text-align: left;">$1,200</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>However, a number of factors other than income can also cause the entire consumption function to shift. These factors were summarized in the earlier discussion of consumption, and listed in <a href="#tbl-IE_1" class="quarto-xref">Table&nbsp;<span>13.1</span></a>. When the consumption function moves, it can shift in two ways: either the entire consumption function can move up or down in a parallel manner, or the slope of the consumption function can shift so that it becomes steeper or flatter.</p>
<p>For example, if a tax cut leads consumers to spend more, but does not affect their marginal propensity to consume, it would cause an upward shift to a new consumption function that is parallel to the original one. However, a change in household preferences for saving that reduced the marginal propensity to save would cause the slope of the consumption function to become steeper: that is, if the savings rate is lower, then every increase in income leads to a larger rise in consumption.</p>
</section>
<section id="investment-as-a-function-of-national-income" class="level3" data-number="13.2.2">
<h3 data-number="13.2.2" class="anchored" data-anchor-id="investment-as-a-function-of-national-income"><span class="header-section-number">13.2.2</span> Investment as a Function of National Income</h3>
<p>Investment decisions are forward-looking, based on expected rates of return. Precisely because investment decisions depend primarily on perceptions about future economic conditions, they do not depend primarily on the level of GDP in the current year. Thus, on a Keynesian cross diagram, the investment function can be drawn as a horizontal line, at a fixed level of expenditure.</p>
<p><a href="#fig-IE_3" class="quarto-xref">Figure&nbsp;<span>13.3</span></a> shows an investment function where the level of investment is, for the sake of concreteness, set at the specific level of 500. Just as a consumption function shows the relationship between consumption levels and real GDP (or national income), the investment function shows the relationship between investment levels and real GDP.</p>
<div id="fig-IE_3" class="align-center quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-IE_3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="Graphs/IncomeExpenditureModel/CNX_Econ_C25_013.jpg" class="lightbox" data-gallery="quarto-lightbox-gallery-3" data-glightbox="description: .lightbox-desc-3"><img src="Graphs/IncomeExpenditureModel/CNX_Econ_C25_013.jpg" class="align-center img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-IE_3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;13.3: The Investment Function. The investment function is drawn as a flat line because investment is based on interest rates and expectations about the future, and so it does not change with the level of current national income. In this example, investment expenditures are at a level of 500. However, changes in factors like technological opportunities, expectations about near-term economic growth, and interest rates would all cause the investment function to shift up or down.
</figcaption>
</figure>
</div>
<p>The graph shows a straight, horizontal line at 500 on the y-axis, representative of the investment function.</p>
<p>The appearance of the investment function as a horizontal line does not mean that the level of investment never moves. It means only that in the context of this two-dimensional diagram, the level of investment on the vertical aggregate expenditure axis does not vary according to the current level of real GDP on the horizontal axis. However, all the other factors that vary investment—new technological opportunities, expectations about near-term economic growth, interest rates, the price of key inputs, and tax incentives for investment—can cause the horizontal investment function to shift up or down.</p>
</section>
<section id="government-spending-and-taxes-as-a-function-of-national-income" class="level3" data-number="13.2.3">
<h3 data-number="13.2.3" class="anchored" data-anchor-id="government-spending-and-taxes-as-a-function-of-national-income"><span class="header-section-number">13.2.3</span> Government Spending and Taxes as a Function of National Income</h3>
<p>In the Keynesian cross diagram, government spending appears as a horizontal line, as in Figure, where government spending is set at a level of 1,300. As in the case of investment spending, this horizontal line does not mean that government spending is unchanging. It means only that government spending changes when Congress decides on a change in the budget, rather than shifting in a predictable way with the current size of the real GDP shown on the horizontal axis.</p>
<div id="fig-IE_4" class="align-center quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-IE_4-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="Graphs/IncomeExpenditureModel/CNX_Econ_C25_014.jpg" class="lightbox" data-gallery="quarto-lightbox-gallery-4" data-glightbox="description: .lightbox-desc-4"><img src="Graphs/IncomeExpenditureModel/CNX_Econ_C25_014.jpg" class="align-center img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-IE_4-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;13.4: The Government Spending Function. The level of government spending is determined by political factors, not by the level of real GDP in a given year. Thus, government spending is drawn as a horizontal line. In this example, government spending is at a level of 1,300. Congressional decisions to increase government spending will cause this horizontal line to shift up, while decisions to reduce spending would cause it to shift down.
</figcaption>
</figure>
</div>
<p>The graph shows a straight, horizontal line at 1,300, representative of the government spending function.</p>
<p>The situation of taxes is different because taxes often rise or fall with the volume of economic activity. For example, income taxes are based on the level of income earned and sales taxes are based on the amount of sales made, and both income and sales tend to be higher when the economy is growing and lower when the economy is in a recession. For the purposes of constructing the basic Keynesian cross diagram, it is helpful to view taxes as a proportionate share of GDP. In the United States, for example, taking federal, state, and local taxes together, government typically collects about 30–35 % of income as taxes.</p>
<p><a href="#tbl-IE_2" class="quarto-xref">Table&nbsp;<span>13.2</span></a> revises the earlier table on the consumption function so that it takes taxes into account. The first column shows national income. The second column calculates taxes, which in this example are set at a rate of 30%, or 0.3. The third column shows after-tax income; that is, total income minus taxes. The fourth column then calculates consumption in the same manner as before: multiply after-tax income by 0.8, representing the marginal propensity to consume, and then add $600, for the amount that would be consumed even if income was zero. When taxes are included, the marginal propensity to consume is reduced by the amount of the tax rate, so each additional dollar of income results in a smaller increase in consumption than before taxes. For this reason, the consumption function, with taxes included, is flatter than the consumption function without taxes, as <a href="#fig-IE_5" class="quarto-xref">Figure&nbsp;<span>13.5</span></a> shows.</p>
<div id="fig-IE_5" class="align-center quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-IE_5-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="Graphs/IncomeExpenditureModel/CNX_Econ_C25_015.jpg" class="lightbox" data-gallery="quarto-lightbox-gallery-5" data-glightbox="description: .lightbox-desc-5"><img src="Graphs/IncomeExpenditureModel/CNX_Econ_C25_015.jpg" class="align-center img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-IE_5-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;13.5: The Consumption Function Before and After Taxes. The upper line repeats the consumption function from Figure. The lower line shows the consumption function if taxes must first be paid on income, and then consumption is based on after-tax income.
</figcaption>
</figure>
</div>
<p>The graph shows two upward-sloping lines. The steeper of the two lines is the consumption before taxes. The more gradual of the two lines is the consumption after taxes.</p>
<div id="tbl-IE_2" class="quarto-float anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-IE_2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;13.2: The Consumption Function Before and After Taxes
</figcaption>
<div aria-describedby="tbl-IE_2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="table">
<thead>
<tr class="header">
<th style="text-align: left;">Income</th>
<th style="text-align: left;">Taxes</th>
<th style="text-align: left;">After-Tax Income</th>
<th style="text-align: left;">Consumption</th>
<th style="text-align: left;">Savings</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">$0</td>
<td style="text-align: left;">$0</td>
<td style="text-align: left;">$0</td>
<td style="text-align: left;">$600</td>
<td style="text-align: left;">–$600</td>
</tr>
<tr class="even">
<td style="text-align: left;">$1,000</td>
<td style="text-align: left;">$300</td>
<td style="text-align: left;">$700</td>
<td style="text-align: left;">$1,160</td>
<td style="text-align: left;">–$460</td>
</tr>
<tr class="odd">
<td style="text-align: left;">$2,000</td>
<td style="text-align: left;">$600</td>
<td style="text-align: left;">$1,400</td>
<td style="text-align: left;">$1,720</td>
<td style="text-align: left;">–$320</td>
</tr>
<tr class="even">
<td style="text-align: left;">$3,000</td>
<td style="text-align: left;">$900</td>
<td style="text-align: left;">$2,100</td>
<td style="text-align: left;">$2,280</td>
<td style="text-align: left;">–$180</td>
</tr>
<tr class="odd">
<td style="text-align: left;">$4,000</td>
<td style="text-align: left;">$1,200</td>
<td style="text-align: left;">$2,800</td>
<td style="text-align: left;">$2,840</td>
<td style="text-align: left;">–$40</td>
</tr>
<tr class="even">
<td style="text-align: left;">$5,000</td>
<td style="text-align: left;">$1,500</td>
<td style="text-align: left;">$3,500</td>
<td style="text-align: left;">$3,400</td>
<td style="text-align: left;">$100</td>
</tr>
<tr class="odd">
<td style="text-align: left;">$6,000</td>
<td style="text-align: left;">$1,800</td>
<td style="text-align: left;">$4,200</td>
<td style="text-align: left;">$3,960</td>
<td style="text-align: left;">$240</td>
</tr>
<tr class="even">
<td style="text-align: left;">$7,000</td>
<td style="text-align: left;">$2,100</td>
<td style="text-align: left;">$4,900</td>
<td style="text-align: left;">$4,520</td>
<td style="text-align: left;">$380</td>
</tr>
<tr class="odd">
<td style="text-align: left;">$8,000</td>
<td style="text-align: left;">$2,400</td>
<td style="text-align: left;">$5,600</td>
<td style="text-align: left;">$5,080</td>
<td style="text-align: left;">$520</td>
</tr>
<tr class="even">
<td style="text-align: left;">$9,000</td>
<td style="text-align: left;">$2,700</td>
<td style="text-align: left;">$6,300</td>
<td style="text-align: left;">$5,640</td>
<td style="text-align: left;">$660</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</section>
<section id="exports-and-imports-as-a-function-of-national-income" class="level3" data-number="13.2.4">
<h3 data-number="13.2.4" class="anchored" data-anchor-id="exports-and-imports-as-a-function-of-national-income"><span class="header-section-number">13.2.4</span> Exports and Imports as a Function of National Income</h3>
<p>The export function, which shows how exports change with the level of a country’s own real GDP, is drawn as a horizontal line, as in the example in <a href="#fig-IE_6" class="quarto-xref">Figure&nbsp;<span>13.6</span></a> (a) where exports are drawn at a level of $840. Again, as in the case of investment spending and government spending, drawing the export function as horizontal does not imply that exports never change. It just means that they do not change because of what is on the horizontal axis—that is, a country’s own level of domestic production—and instead are shaped by the level of aggregate demand in other countries. More demand for exports from other countries would cause the export function to shift up; less demand for exports from other countries would cause it to shift down.</p>
<div id="fig-IE_6" class="align-center quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-IE_6-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="Graphs/IncomeExpenditureModel/CNX_Econ_C25_025.jpg" class="lightbox" data-gallery="quarto-lightbox-gallery-6" data-glightbox="description: .lightbox-desc-6"><img src="Graphs/IncomeExpenditureModel/CNX_Econ_C25_025.jpg" class="align-center img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-IE_6-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;13.6: The Export and Import Functions.Panel (a) The export function is drawn as a horizontal line because exports are determined by the buying power of other countries and thus do not change with the size of the domestic economy. In this example, exports are set at 840. However, exports can shift up or down, depending on buying patterns in other countries. (b) The import function is drawn in negative territory because expenditures on imported products are a subtraction from expenditures in the domestic economy. In this example, the marginal propensity to import is 0.1, so imports are calculated by multiplying the level of income by –0.1.
</figcaption>
</figure>
</div>
<p>The graph on the left show exports as a straight, horizontal line at $840. The graph on the right shows imports as a downward-sloping line beginning at $0.</p>
<p>Imports are drawn in the Keynesian cross diagram as a downward-sloping line, with the downward slope determined by the <strong>marginal propensity to import (MPI)</strong>, out of national income.</p>
<p>In Figure (b), the marginal propensity to import is 0.1. Thus, if real GDP is $5,000, imports are $500; if national income is $6,000, imports are $600, and so on. The import function is drawn as downward sloping and negative, because it represents a subtraction from the aggregate expenditures in the domestic economy. A change in the marginal propensity to import, perhaps as a result of changes in preferences, would alter the slope of the import function.</p>
</section>
<section id="using-an-algebraic-approach-to-the-expenditure-output-model" class="level3" data-number="13.2.5">
<h3 data-number="13.2.5" class="anchored" data-anchor-id="using-an-algebraic-approach-to-the-expenditure-output-model"><span class="header-section-number">13.2.5</span> USING AN ALGEBRAIC APPROACH TO THE EXPENDITURE-OUTPUT MODEL</h3>
<p>In the expenditure-output or Keynesian cross model, the equilibrium occurs where the aggregate expenditure line (AE line) crosses the 45-degree line. Given algebraic equations for two lines, the point where they cross can be readily calculated. Imagine an economy with the following characteristics.</p>
<table class="table">
<thead>
<tr class="header">
<th style="text-align: left;">Variable</th>
<th style="text-align: left;">Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Y</td>
<td style="text-align: left;">= Real GDP or national income</td>
</tr>
<tr class="even">
<td style="text-align: left;">T</td>
<td style="text-align: left;">= Taxes = 0.3Y</td>
</tr>
<tr class="odd">
<td style="text-align: left;">C</td>
<td style="text-align: left;">= Consumption = 140 + 0.9(Y – T)</td>
</tr>
<tr class="even">
<td style="text-align: left;">I</td>
<td style="text-align: left;">= Investment = 400</td>
</tr>
<tr class="odd">
<td style="text-align: left;">G</td>
<td style="text-align: left;">= Government spending = 800</td>
</tr>
<tr class="even">
<td style="text-align: left;">X</td>
<td style="text-align: left;">= Exports = 600</td>
</tr>
<tr class="odd">
<td style="text-align: left;">M</td>
<td style="text-align: left;">= Imports = 0.15Y</td>
</tr>
</tbody>
</table>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<dl>
<dt>Step 1.</dt>
<dd>
<p>Determine the aggregate expenditure function. In this case, it is:</p>
<p><span class="math display">\[AE = C + I + G + X – M\]</span></p>
<p><span class="math display">\[AE = 140 + 0.9(Y – T) + 400 + 800 + 600 – 0.15Y\]</span></p>
</dd>
<dt>Step 2.</dt>
<dd>
<p>The equation for the 45-degree line is the set of points where GDP or national income on the horizontal axis is equal to aggregate expenditure on the vertical axis. Thus, the equation for the 45-degree line is: AE = Y.</p>
</dd>
<dt>Step 3.</dt>
<dd>
<p>The next step is to solve these two equations for Y (or AE, since they will be equal to each other). Substitute Y for AE:</p>
<p><span class="math display">\[Y = 140 + 0.9(Y – T) + 400 + 800 + 600 – 0.15Y\]</span></p>
</dd>
<dt>Step 4.</dt>
<dd>
<p>Insert the term <span class="math inline">\(0.3 \times Y\)</span> for the tax rate T. This produces an equation with only one variable, Y.</p>
</dd>
<dt>Step 5.</dt>
<dd>
<p>Work through the algebra and solve for Y.</p>
<p><span class="math display">\[Y = 140 + 0.9 \times (Y – 0.3 \times Y) + 400 + 800 + 600 – 0.15 \times Y\]</span></p>
<p><span class="math display">\[Y = 140 + 0.9 \times Y – 0.27 \times Y + 1800 – 0.15 \times Y\]</span></p>
<p><span class="math display">\[Y = 1940 + 0.48 \times Y\]</span></p>
<p><span class="math display">\[Y – 0.48 \times Y = 1940\]</span></p>
<p><span class="math display">\[0.52 \times Y = 1940\]</span></p>
<p><span class="math display">\[Y = 3730\]</span></p>
<p>This algebraic framework is flexible and useful in predicting how economic events and policy actions will affect real GDP.</p>
</dd>
<dt>Step 6.</dt>
<dd>
<p>Say, for example, that because of changes in the relative prices of domestic and foreign goods, the marginal propensity to import falls to 0.1. Calculate the equilibrium output when the marginal propensity to import is changed to 0.1.</p>
<p><span class="math display">\[Y = 140 + 0.9(Y – 0.3Y) + 400 + 800 + 600 – 0.1Y\]</span></p>
<p><span class="math display">\[Y = 1940 – 0.53Y\]</span></p>
<p><span class="math display">\[0.47Y = 1940\]</span></p>
<p><span class="math display">\[Y = 4127\]</span></p>
</dd>
<dt>Step 7.</dt>
<dd>
<p>Because of a surge of business confidence, investment rises to 500. Calculate the equilibrium output.</p>
<p><span class="math display">\[Y = 140 + 0.9(Y – 0.3Y) + 500 + 800 + 600 – 0.15Y\]</span></p>
<p><span class="math display">\[Y = 2040 + 0.48Y\]</span></p>
<p><span class="math display">\[Y – 0.48Y = 2040\]</span></p>
<p><span class="math display">\[0.52Y = 2040\]</span></p>
<p><span class="math display">\[Y = 3923\]</span></p>
<p>For issues of policy, the key questions would be how to adjust government spending levels or tax rates so that the equilibrium level of output is the full employment level. In this case, let the economic parameters be:</p>
<table class="table">
<thead>
<tr class="header">
<th style="text-align: left;">Variable</th>
<th style="text-align: left;">Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Y</td>
<td style="text-align: left;">= National income</td>
</tr>
<tr class="even">
<td style="text-align: left;">T</td>
<td style="text-align: left;">= Taxes = 0.3Y</td>
</tr>
<tr class="odd">
<td style="text-align: left;">C</td>
<td style="text-align: left;">= Consumption = 200 + 0.9(Y – T)</td>
</tr>
<tr class="even">
<td style="text-align: left;">I</td>
<td style="text-align: left;">= Investment = 600</td>
</tr>
<tr class="odd">
<td style="text-align: left;">G</td>
<td style="text-align: left;">= Government spending = 1,000</td>
</tr>
<tr class="even">
<td style="text-align: left;">X</td>
<td style="text-align: left;">= Exports = 600</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Y</td>
<td style="text-align: left;">= Imports = 0.1(Y – T)</td>
</tr>
</tbody>
</table>
</dd>
<dt>Step 8.</dt>
<dd>
<p>Calculate the equilibrium for this economy (remember Y = AE).</p>
<p><span class="math display">\[Y = 200 + 0.9(Y – 0.3Y) + 600 + 1000 + 600 – 0.1(Y – 0.3Y)\]</span></p>
<p><span class="math display">\[Y – 0.63Y + 0.07Y = 2400\]</span></p>
<p><span class="math display">\[0.44Y = 2400\]</span></p>
<p><span class="math display">\[Y = 5454\]</span></p>
</dd>
<dt>Step 9.</dt>
<dd>
<p>Assume that the full employment level of output is 6,000. What level of government spending would be necessary to reach that level? To answer this question, plug in 6,000 as equal to Y, but leave G as a variable, and solve for G. Thus:</p>
<p><span class="math display">\[6000 = 200 + 0.9(6000 – 0.3(6000)) + 600 + G + 600 – 0.1(6000 – 0.3(6000))\]</span></p>
</dd>
<dt>Step 10.</dt>
<dd>
<p>Solve this problem arithmetically. The answer is: G = 1,240. In other words, increasing government spending by 240, from its original level of 1,000, to 1,240, would raise output to the full employment level of GDP.</p>
<p>Indeed, the question of how much to increase government spending so that equilibrium output will rise from 5,454 to 6,000 can be answered without working through the algebra, just by using the multiplier formula. The multiplier equation in this case is:</p>
<p><span class="math display">\[\frac{1}{1 – 0.56} = 2.27\]</span></p>
<p>Thus, to raise output by 546 would require an increase in government spending of 546/2.27=240, which is the same as the answer derived from the algebraic calculation.</p>
</dd>
</dl>
</div>
</div>
<p>This algebraic framework is highly flexible. For example, taxes can be treated as a total set by political considerations (like government spending) and not dependent on national income. Imports might be based on before-tax income, not after-tax income. For certain purposes, it may be helpful to analyze the economy without exports and imports. A more complicated approach could divide up consumption, investment, government, exports and imports into smaller categories, or to build in some variability in the rates of taxes, savings, and imports. A wise economist will shape the model to fit the specific question under investigation.</p>
</section>
<section id="building-the-combined-aggregate-expenditure-function" class="level3" data-number="13.2.6">
<h3 data-number="13.2.6" class="anchored" data-anchor-id="building-the-combined-aggregate-expenditure-function"><span class="header-section-number">13.2.6</span> Building the Combined Aggregate Expenditure Function</h3>
<p>All the components of aggregate demand—consumption, investment, government spending, and the trade balance—are now in place to build the Keynesian cross diagram. <a href="#fig-IE_7" class="quarto-xref">Figure&nbsp;<span>13.7</span></a> builds up an aggregate expenditure function, based on the numerical illustrations of C, I, G, X, and M that have been used throughout this text. The first three columns in <a href="#tbl-IE_3" class="quarto-xref">Table&nbsp;<span>13.3</span></a> are lifted from the earlier <a href="#tbl-IE_2" class="quarto-xref">Table&nbsp;<span>13.2</span></a> , which showed how to bring taxes into the consumption function. The first column is real GDP or national income, which is what appears on the horizontal axis of the income-expenditure diagram. The second column calculates after-tax income, based on the assumption, in this case, that 30% of real GDP is collected in taxes.</p>
<p>The third column is based on an MPC of 0.8, so that as after-tax income rises by $700 from one row to the next, consumption rises by $560 (700 × 0.8) from one row to the next. Investment, government spending, and exports do not change with the level of current national income. In the previous discussion, investment was $500, government spending was $1,300, and exports were $840, for a total of $2,640. This total is shown in the fourth column. Imports are 0.1 of real GDP in this example, and the level of imports is calculated in the fifth column. The final column, aggregate expenditures, sums up C + I + G + X – M. This aggregate expenditure line is illustrated in <a href="#fig-IE_7" class="quarto-xref">Figure&nbsp;<span>13.7</span></a>.</p>
<div id="fig-IE_7" class="align-center quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-IE_7-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="Graphs/IncomeExpenditureModel/CNX_Econ_C25_018.jpg" class="lightbox" data-gallery="quarto-lightbox-gallery-7" data-glightbox="description: .lightbox-desc-7"><img src="Graphs/IncomeExpenditureModel/CNX_Econ_C25_018.jpg" class="align-center img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-IE_7-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;13.7: A Keynesian Cross Diagram. Each combination of national income and aggregate expenditure (after-tax consumption, government spending, investment, exports, and imports) is graphed. The equilibrium occurs where aggregate expenditure is equal to national income; this occurs where the aggregate expenditure schedule crosses the 45-degree line, at a real GDP of $6,000. Potential GDP in this example is $7,000, so the equilibrium is occurring at a level of output or real GDP below the potential GDP level.
</figcaption>
</figure>
</div>
<p>The graph shows a Keynesian cross diagram with each combination of national income and aggregate expenditure.</p>
<div id="tbl-IE_3" class="quarto-float anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-IE_3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;13.3: National Income-Aggregate Expenditure Equilibrium
</figcaption>
<div aria-describedby="tbl-IE_3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="table">
<colgroup>
<col style="width: 15%">
<col style="width: 15%">
<col style="width: 15%">
<col style="width: 15%">
<col style="width: 15%">
<col style="width: 19%">
</colgroup>
<tbody>
<tr class="odd">
<td>Nat. Income</td>
<td>After Tax Income</td>
<td>Con sumption</td>
<td><div class="line-block">Govt</div>
<p>Spending + Invest + Exp.</p></td>
<td>Imports</td>
<td>Aggregate Expenditure</td>
</tr>
<tr class="even">
<td>$3,000</td>
<td>$2,100</td>
<td>$2,280</td>
<td>$2,640</td>
<td>$300</td>
<td>$4,620</td>
</tr>
<tr class="odd">
<td>$4,000</td>
<td>$2,800</td>
<td>$2,840</td>
<td>$2,640</td>
<td>$400</td>
<td>$5,080</td>
</tr>
<tr class="even">
<td>$5,000</td>
<td>$3,500</td>
<td>$3,400</td>
<td>$2,640</td>
<td>$500</td>
<td>$5,540</td>
</tr>
<tr class="odd">
<td>$6,000</td>
<td>$4,200</td>
<td>$3,960</td>
<td>$2,640</td>
<td>$600</td>
<td>$6,000</td>
</tr>
<tr class="even">
<td>$7,000</td>
<td>$4,900</td>
<td>$4,520</td>
<td>$2,640</td>
<td>$700</td>
<td>$6,460</td>
</tr>
<tr class="odd">
<td>$8,000</td>
<td>$5,600</td>
<td>$5,080</td>
<td>$2,640</td>
<td>$800</td>
<td>$6,920</td>
</tr>
<tr class="even">
<td>$9,000</td>
<td>$6,300</td>
<td>$5,640</td>
<td>$2,640</td>
<td>$900</td>
<td>$7,380</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>The aggregate expenditure function is formed by stacking on top of each other the consumption function (after taxes), the investment function, the government spending function, the export function, and the import function. The point at which the aggregate expenditure function intersects the vertical axis will be determined by the levels of investment, government, and export expenditures—which do not vary with national income. The upward slope of the aggregate expenditure function will be determined by the marginal propensity to save, the tax rate, and the marginal propensity to import. A higher marginal propensity to save, a higher tax rate, and a higher marginal propensity to import will all make the slope of the aggregate expenditure function flatter—because out of any extra income, more is going to savings or taxes or imports and less to spending on domestic goods and services.</p>
<p>The equilibrium occurs where national income is equal to aggregate expenditure, which is shown on the graph as the point where the aggregate expenditure schedule crosses the 45-degree line. In this example, the equilibrium occurs at 6,000. This equilibrium can also be read off the table under the figure; it is the level of national income where aggregate expenditure is equal to national income.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Key Concepts and Summary
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>The consumption function shows the upward-sloping relationship between national income and consumption.</li>
<li>The marginal propensity to consume (MPC) is the amount consumed out of an additional dollar of income.</li>
<li>A higher marginal propensity to consume means a steeper consumption function; a lower marginal propensity to consume means a flatter consumption function.</li>
<li>The marginal propensity to save (MPS) is the amount saved out of an additional dollar of income. It is necessarily true that MPC + MPS = 1.</li>
<li>The investment function is drawn as a flat line, showing that investment in the current year does not change with regard to the current level of national income. However, the investment function will move up and down based on the expected rate of return in the future.</li>
<li>Government spending is drawn as a horizontal line in the Keynesian cross diagram, because its level is determined by political considerations, not by the current level of income in the economy. Taxes in the basic Keynesian cross diagram are taken into account by adjusting the consumption function.</li>
<li>The export function is drawn as a horizontal line in the Keynesian cross diagram, because exports do not change as a result of changes in domestic income, but they move as a result of changes in foreign income, as well as changes in exchange rates.</li>
<li>The import function is drawn as a downward-sloping line, because imports rise with national income, but imports are a subtraction from aggregate demand. Thus, a higher level of imports means a lower level of expenditure on domestic goods.</li>
</ul>
</div>
</div>
<div class="callout callout-style-default callout-caution callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-8-contents" aria-controls="callout-8" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Self-Check Questions
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-8" class="callout-8-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ul>
<li>What determines the slope of a consumption function?</li>
<li>What is the marginal propensity to consume, and how is it related to the marginal propensity to import?</li>
<li>Why are the investment function, the government spending function, and the export function all drawn as flat lines?</li>
<li>Why does the import function slope down? What is the marginal propensity to import?</li>
<li>What are the components on which the aggregate expenditure function is based?</li>
</ul>
</div>
</div>
</div>
<!--Equilibrium in the Keynesian Cross Model {{{2-->
</section>
</section>
<section id="equilibrium-in-the-keynesian-cross-model" class="level2" data-number="13.3">
<h2 data-number="13.3" class="anchored" data-anchor-id="equilibrium-in-the-keynesian-cross-model"><span class="header-section-number">13.3</span> Equilibrium in the Keynesian Cross Model</h2>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Chapter Learning Objectives
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>Equilibrium</li>
<li>Equilibrium Cross Model</li>
<li>Keynesian Cross Model</li>
<li>Recessionary and Inflationary Gaps</li>
</ul>
</div>
</div>
<p>With the aggregate expenditure line in place, the next step is to relate it to the two other elements of the Keynesian cross diagram. Thus, the first subsection interprets the intersection of the aggregate expenditure function and the 45-degree line, while the next subsection relates this point of intersection to the potential GDP line.</p>
<section id="where-equilibrium-occurs" class="level3" data-number="13.3.1">
<h3 data-number="13.3.1" class="anchored" data-anchor-id="where-equilibrium-occurs"><span class="header-section-number">13.3.1</span> Where Equilibrium Occurs</h3>
<p>The point where the aggregate expenditure line that is constructed from C + I + G + X – M crosses the 45-degree line will be the equilibrium for the economy. It is the only point on the aggregate expenditure line where the total amount being spent on aggregate demand equals the total level of production. In <a href="#fig-IE_7" class="quarto-xref">Figure&nbsp;<span>13.7</span></a>, this point of equilibrium (E0) happens at 6,000, which can also be read off <a href="#tbl-IE_3" class="quarto-xref">Table&nbsp;<span>13.3</span></a>.</p>
<p>The meaning of “equilibrium” remains the same; that is, equilibrium is a point of balance where no incentive exists to shift away from that outcome. To understand why the point of intersection between the aggregate expenditure function and the 45-degree line is a macroeconomic equilibrium, consider what would happen if an economy found itself to the right of the equilibrium point E, say point H in <a href="#fig-IE_8" class="quarto-xref">Figure&nbsp;<span>13.8</span></a>, where output is higher than the equilibrium. At point H, the level of aggregate expenditure is below the 45-degree line, so that the level of aggregate expenditure in the economy is less than the level of output. As a result, at point H, output is piling up unsold—not a sustainable state of affairs.</p>
<div id="fig-IE_8" class="align-center quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-IE_8-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="Graphs/IncomeExpenditureModel/CNX_Econ_C25_019.jpg" class="lightbox" data-gallery="quarto-lightbox-gallery-8" data-glightbox="description: .lightbox-desc-8"><img src="Graphs/IncomeExpenditureModel/CNX_Econ_C25_019.jpg" class="align-center img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-IE_8-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;13.8: Equilibrium in the Keynesian Cross Diagram. If output was above the equilibrium level, at H, then the real output is greater than the aggregate expenditure in the economy. This pattern cannot hold, because it would mean that goods are produced but piling up unsold. If output was below the equilibrium level at L, then aggregate expenditure would be greater than output. This pattern cannot hold either, because it would mean that spending exceeds the number of goods being produced. Only point E can be at equilibrium, where output, or national income and aggregate expenditure, are equal. The equilibrium (E) must lie on the 45-degree line, which is the set of points where national income and aggregate expenditure are equal.
</figcaption>
</figure>
</div>
<p>The graph shows the only point at which there can be equilibrium in the Keynesian cross diagram.</p>
<p>Conversely, consider the situation where the level of output is at point L—where real output is lower than the equilibrium. In that case, the level of aggregate demand in the economy is above the 45-degree line, indicating that the level of aggregate expenditure in the economy is greater than the level of output. When the level of aggregate demand has emptied the store shelves, it cannot be sustained, either. Firms will respond by increasing their level of production. Thus, the equilibrium must be the point where the amount produced and the amount spent are in balance, at the intersection of the aggregate expenditure function and the 45-degree line.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>FINDING EQUILIBRIUM</p>
<p><a href="#tbl-IE_4" class="quarto-xref">Table&nbsp;<span>13.4</span></a> gives some information on an economy. The Keynesian model assumes that there is some level of consumption even without income. That amount is $236 – $216 = $20. $20 will be consumed when national income equals zero. Assume that taxes are 0.2 of real GDP. Let the marginal propensity to save of after-tax income be 0.1. The level of investment is $70, the level of government spending is $80, and the level of exports is $50. Imports are 0.2 of after-tax income. Given these values, you need to complete Table and then answer these questions:</p>
<ul>
<li>What is the consumption function?</li>
<li>What is the equilibrium?</li>
<li>Why is a national income of $300 not at equilibrium?</li>
<li>How do expenditures and output compare at this point?</li>
</ul>
<div id="tbl-IE_4" class="quarto-float anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-IE_4-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;13.4: National Income-Aggregate Expenditure Equilibrium
</figcaption>
<div aria-describedby="tbl-IE_4-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="table">
<colgroup>
<col style="width: 15%">
<col style="width: 15%">
<col style="width: 15%">
<col style="width: 15%">
<col style="width: 15%">
<col style="width: 19%">
</colgroup>
<tbody>
<tr class="odd">
<td>Nat. Income</td>
<td>After Tax Income</td>
<td>Con sumption</td>
<td><div class="line-block">Govt</div>
<p>Spending + Invest + Exp.</p></td>
<td>Imports</td>
<td>Aggregate Expenditure</td>
</tr>
<tr class="even">
<td>$300</td>
<td></td>
<td>$236</td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>$400</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>$500</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>$600</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>$700</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<dl>
<dt>Step 1.</dt>
<dd>
<p>Calculate the amount of taxes for each level of national income(reminder: GDP = national income) for each level of national income using the following as an example:</p>
<table class="table">
<thead>
<tr class="header">
<th style="text-align: left;">Item</th>
<th style="text-align: left;">Amount</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">National Income (Y)</td>
<td style="text-align: left;">$300</td>
</tr>
<tr class="even">
<td style="text-align: left;">Taxes = 0.2 or 20%</td>
<td style="text-align: left;">× 0.2</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Tax amount (T)</td>
<td style="text-align: left;">$60</td>
</tr>
</tbody>
</table>
</dd>
<dt>Step 2.</dt>
<dd>
<p>Calculate after-tax income by subtracting the tax amount from national income for each level of national income using the following as an example:</p>
<p><span class="math display">\[\text{National income minus taxes} = $300–$60\]</span></p>
<p><span class="math display">\[\text{After-tax income} = $240\]</span></p>
</dd>
<dt>Step 3.</dt>
<dd>
<p>Calculate consumption. The marginal propensity to save is given as 0.1. This means that the marginal propensity to consume is 0.9, since MPS + MPC = 1. Therefore, multiply 0.9 by the after-tax income amount using the following as an example:</p>
<table class="table">
<thead>
<tr class="header">
<th style="text-align: left;">Item</th>
<th style="text-align: left;">Amount</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">After-tax Income</td>
<td style="text-align: left;">$240</td>
</tr>
<tr class="even">
<td style="text-align: left;">MPC</td>
<td style="text-align: left;">× 0.9</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Consumption</td>
<td style="text-align: left;">$216</td>
</tr>
</tbody>
</table>
</dd>
<dt>Step 4.</dt>
<dd>
<p>Consider why the table shows consumption of $236 in the first row. As mentioned earlier, the Keynesian model assumes that there is some level of consumption even without income. That amount is $236 – $216 = $20.</p>
</dd>
<dt>Step 5.</dt>
<dd>
<p>There is now enough information to write the consumption function. The consumption function is found by figuring out the level of consumption that will happen when income is zero. Remember that:</p>
<p><span class="math display">\[C = \text{Consumption when national income is zero} + \text{MPC (after-tax income)}\]</span></p>
<p>Let C represent the consumption function, Y represent national income, and T represent taxes.</p>
<p><span class="math display">\[C = $20 + 0.9(Y – T)
= $20 + 0.9($300 – $60)
= $236\]</span></p>
</dd>
<dt>Step 6.</dt>
<dd>
<p>Use the consumption function to find consumption at each level of national income.</p>
</dd>
<dt>Step 7.</dt>
<dd>
<p>Add investment (I), government spending (G), and exports (X). Remember that these do not change as national income changes:</p>
</dd>
<dt>Step 8.</dt>
<dd>
<p>Find imports, which are 0.2 of after-tax income at each level of national income. For example:</p>
<table class="table">
<thead>
<tr class="header">
<th style="text-align: left;">Item</th>
<th style="text-align: left;">Amount</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">After-tax income</td>
<td style="text-align: left;">$240</td>
</tr>
<tr class="even">
<td style="text-align: left;">Imports of 0.2 or 20% of Y – T</td>
<td style="text-align: left;">× 0.2</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Imports</td>
<td style="text-align: left;">$48</td>
</tr>
</tbody>
</table>
</dd>
<dt>Step 9.</dt>
<dd>
<p>Find aggregate expenditure by adding C + I + G + X – I for each level of national income. Your completed table should look like <a href="#tbl-IE_5" class="quarto-xref">Table&nbsp;<span>13.5</span></a>.</p>
<div id="tbl-IE_5" class="quarto-float anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-IE_5-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;13.5: Complete Economy
</figcaption>
<div aria-describedby="tbl-IE_5-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="table">
<colgroup>
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 13%">
</colgroup>
<tbody>
<tr class="odd">
<td>Nat. Inc (Y)</td>
<td><div class="line-block">Tax= 0.2× Y (T)</div></td>
<td>After -tax income (Y – T)</td>
<td><div class="line-block">Cons: C = $20 + 0.9(Y – T)</div></td>
<td><div class="line-block"></div>
<p>I + G + X</p></td>
<td><div class="line-block">Minus</div>
<p>Imports (M)</p></td>
<td><div class="line-block">Agg. Exp. AE = C + I + G + X – M</div></td>
</tr>
<tr class="even">
<td>$300</td>
<td>$60</td>
<td><blockquote class="blockquote">
<p>$240</p>
</blockquote></td>
<td>$236</td>
<td>$200</td>
<td>$48</td>
<td>$388</td>
</tr>
<tr class="odd">
<td>$400</td>
<td>$80</td>
<td><blockquote class="blockquote">
<p>$320</p>
</blockquote></td>
<td>$308</td>
<td>$200</td>
<td>$64</td>
<td>$444</td>
</tr>
<tr class="even">
<td>$500</td>
<td>$100</td>
<td><blockquote class="blockquote">
<p>$400</p>
</blockquote></td>
<td>$380</td>
<td>$200</td>
<td>$80</td>
<td>$500</td>
</tr>
<tr class="odd">
<td>$600</td>
<td>$120</td>
<td><blockquote class="blockquote">
<p>$480</p>
</blockquote></td>
<td>$452</td>
<td>$200</td>
<td>$96</td>
<td>$556</td>
</tr>
<tr class="even">
<td>$700</td>
<td>$140</td>
<td><blockquote class="blockquote">
<p>$560</p>
</blockquote></td>
<td>$524</td>
<td>$200</td>
<td>$112</td>
<td>$612</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</dd>
<dt>Step 10.</dt>
<dd>
<p>Answer the question: What is equilibrium? Equilibrium occurs where AE = Y. Table shows that equilibrium occurs where national income equals aggregate expenditure at $500.</p>
</dd>
<dt>Step 11.</dt>
<dd>
<p>Find equilibrium mathematically, knowing that national income is equal to aggregate expenditure.</p>
<p><span class="math display">\[Y = AE\]</span></p>
<p><span class="math display">\[Y = C + I + G + X – M\]</span></p>
<p><span class="math display">\[Y = $20 + 0.9(Y – T) + $70 + $80 + $50 – 0.2(Y – T)\]</span></p>
<p><span class="math display">\[Y = $220 + 0.9(Y – T) – 0.2(Y – T)\]</span></p>
<p>Since T is 0.2 of national income, substitute T with 0.2 Y so that:</p>
<p><span class="math display">\[Y = $220 + 0.9(Y – 0.2Y) – 0.2(Y – 0.2Y)\]</span></p>
<p><span class="math display">\[Y = $220 + 0.9Y – 0.18Y – 0.2Y + 0.04Y\]</span></p>
<p><span class="math display">\[Y = $220 + 0.56Y\]</span></p>
<p>Solve for Y.</p>
<p><span class="math display">\[Y = $220 + 0.56Y\]</span></p>
<p><span class="math display">\[Y – 0.56Y = $220\]</span></p>
<p><span class="math display">\[0.44Y = $220\]</span></p>
<p><span class="math display">\[Y = $500\]</span></p>
</dd>
<dt>Step 12.</dt>
<dd>
<p>Answer this question: Why is a national income of $300 not an equilibrium? At national income of $300, aggregate expenditures are $388.</p>
</dd>
<dt>Step 13.</dt>
<dd>
<p>Answer this question: How do expenditures and output compare at this point? Aggregate expenditures cannot exceed output (GDP) in the long run, since there would not be enough goods to be bought.</p>
</dd>
</dl>
</div>
</div>
</section>
<section id="recessionary-and-inflationary-gaps" class="level3" data-number="13.3.2">
<h3 data-number="13.3.2" class="anchored" data-anchor-id="recessionary-and-inflationary-gaps"><span class="header-section-number">13.3.2</span> Recessionary and Inflationary Gaps</h3>
<p>In the Keynesian cross diagram, if the aggregate expenditure line intersects the 45-degree line at the level of potential GDP, then the economy is in sound shape. There is no recession, and unemployment is low. But there is no guarantee that the equilibrium will occur at the potential GDP level of output. The equilibrium might be higher or lower.</p>
<p>For example, <a href="#fig-IE_9" class="quarto-xref">Figure&nbsp;<span>13.9</span></a> (a) illustrates a situation where the aggregate expenditure line intersects the 45-degree line at point E0, which is a real GDP of $6,000, and which is below the potential GDP of $7,000. In this situation, the level of aggregate expenditure is too low for GDP to reach its full employment level, and unemployment will occur. The distance between an output level like E0 that is below potential GDP and the level of potential GDP is called a recessionary gap. Because the equilibrium level of real GDP is so low, firms will not wish to hire the full employment number of workers, and unemployment will be high.</p>
<div id="fig-IE_9" class="align-center quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-IE_9-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="Graphs/IncomeExpenditureModel/CNX_Econ_C25_026.jpg" class="lightbox" data-gallery="quarto-lightbox-gallery-9" data-glightbox="description: .lightbox-desc-9"><img src="Graphs/IncomeExpenditureModel/CNX_Econ_C25_026.jpg" class="align-center img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-IE_9-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;13.9: Addressing Recessionary and Inflationary Gaps. Panel (a) If the equilibrium occurs at an output below potential GDP, then a recessionary gap exists. The policy solution to a recessionary gap is to shift the aggregate expenditure schedule up from AE0 to AE1, using policies like tax cuts or government spending increases. Then the new equilibrium E1 occurs at potential GDP. (b) If the equilibrium occurs at an output above potential GDP, then an inflationary gap exists. The policy solution to an inflationary gap is to shift the aggregate expenditure schedule down from AE0 to AE1, using policies like tax increases or spending cuts. Then, the new equilibrium E1 occurs at potential GDP.
</figcaption>
</figure>
</div>
<p>The graph shows two images. Image (a) shows policy solutions to address a recessionary gap. Here, the recessionary gap appears to the left of potential GDP. Image (b) shows policy solutions to address an inflationary gap. Here, the inflationary gap appears to the right of potential GDP.</p>
<p>What might cause a recessionary gap? Anything that shifts the aggregate expenditure line down is a potential cause of recession, including a decline in consumption, a rise in savings, a fall in investment, a drop in government spending or a rise in taxes, or a fall in exports or a rise in imports. Moreover, an economy that is at equilibrium with a recessionary gap may just stay there and suffer high unemployment for a long time; remember, the meaning of equilibrium is that there is no particular adjustment of prices or quantities in the economy to chase the recession away.</p>
<p>The appropriate response to a recessionary gap is for the government to reduce taxes or increase spending so that the aggregate expenditure function shifts up from AE0 to AE1. When this shift occurs, the new equilibrium E1 now occurs at potential GDP as shown in <a href="#fig-IE_9" class="quarto-xref">Figure&nbsp;<span>13.9</span></a> (a).</p>
<p>Conversely, <a href="#fig-IE_9" class="quarto-xref">Figure&nbsp;<span>13.9</span></a> (b) shows a situation where the aggregate expenditure schedule (AE0) intersects the 45-degree line above potential GDP. The gap between the level of real GDP at the equilibrium E0 and potential GDP is called an inflationary gap. The inflationary gap also requires a bit of interpreting. After all, a naïve reading of the Keynesian cross diagram might suggest that if the aggregate expenditure function is just pushed up high enough, real GDP can be as large as desired—even doubling or tripling the potential GDP level of the economy. This implication is clearly wrong. An economy faces some supply-side limits on how much it can produce at a given time with its existing quantities of workers, physical and human capital, technology, and market institutions.</p>
<p>The inflationary gap should be interpreted, not as a literal prediction of how large real GDP will be, but as a statement of how much extra aggregate expenditure is in the economy beyond what is needed to reach potential GDP. An inflationary gap suggests that because the economy cannot produce enough goods and services to absorb this level of aggregate expenditures, the spending will instead cause an inflationary increase in the price level. In this way, even though changes in the price level do not appear explicitly in the Keynesian cross equation, the notion of inflation is implicit in the concept of the inflationary gap.</p>
<p>The appropriate Keynesian response to an inflationary gap is shown in <a href="#fig-IE_9" class="quarto-xref">Figure&nbsp;<span>13.9</span></a> (b). The original intersection of aggregate expenditure line AE0 and the 45-degree line occurs at $8,000, which is above the level of potential GDP at $7,000. If AE0 shifts down to AE1, so that the new equilibrium is at E1, then the economy will be at potential GDP without pressures for inflationary price increases. The government can achieve a downward shift in aggregate expenditure by increasing taxes on consumers or firms, or by reducing government expenditures.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Key Concepts and Summary
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>In a Keynesian cross diagram, the equilibrium may be at a level below potential GDP, which is called a <strong>recessionary gap</strong>, or at a level above potential GDP, which is called an <strong>inflationary gap</strong>.</li>
</ul>
</div>
</div>
<div class="callout callout-style-default callout-caution callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-12-contents" aria-controls="callout-12" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Self-Check Questions
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-12" class="callout-12-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ul>
<li>Is the equilibrium in a Keynesian cross diagram usually expected to be at or near potential GDP?</li>
<li>What is an inflationary gap? A recessionary gap?</li>
</ul>
</div>
</div>
</div>
<!--The Multiplier Effect {{{2-->
</section>
</section>
<section id="the-multiplier-effect" class="level2" data-number="13.4">
<h2 data-number="13.4" class="anchored" data-anchor-id="the-multiplier-effect"><span class="header-section-number">13.4</span> The Multiplier Effect</h2>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Chapter Learning Objectives
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>The Multiplier effect</li>
<li>Calculating the Multiplier</li>
<li>Calculating Keynesian Policy Interventions</li>
<li>Multiplier Tradeoffs</li>
</ul>
</div>
</div>
<p>The Keynesian policy prescription has one final twist. Assume that for a certain economy, the intersection of the aggregate expenditure function and the 45-degree line is at a GDP of 700, while the level of potential GDP for this economy is $800. By how much does government spending need to be increased so that the economy reaches the full employment GDP? The obvious answer might seem to be $800 – $700 = $100; so raise government spending by $100. But that answer is incorrect. A change of, for example, $100 in government expenditures will have an effect of more than $100 on the equilibrium level of real GDP. The reason is that a change in aggregate expenditures circles through the economy: households buy from firms, firms pay workers and suppliers, workers and suppliers buy goods from other firms, those firms pay their workers and suppliers, and so on. In this way, the original change in aggregate expenditures is actually spent more than once. This is called the multiplier effect: An initial increase in spending, cycles repeatedly through the economy and has a larger impact than the initial dollar amount spent.</p>
<section id="how-does-the-multiplier-work" class="level3" data-number="13.4.1">
<h3 data-number="13.4.1" class="anchored" data-anchor-id="how-does-the-multiplier-work"><span class="header-section-number">13.4.1</span> How Does the Multiplier Work?</h3>
<p>To understand how the multiplier effect works, return to the example in which the current equilibrium in the Keynesian cross diagram is a real GDP of $700, or $100 short of the $800 needed to be at full employment, potential GDP. If the government spends $100 to close this gap, someone in the economy receives that spending and can treat it as income. Assume that those who receive this income pay 30% in taxes, save 10% of after-tax income, spend 10% of total income on imports, and then spend the rest on domestically produced goods and services.</p>
<div id="mytopic">
<p><strong>Video - Multiplier</strong></p>
<div style="position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden; max-width: 100%; height: auto;">
    <iframe src="https://www.youtube.com/embed/O_Oozju3RRI" frameborder="0" allowfullscreen="" style="position: absolute; top: 0; left: 0; width: 100%; height: 100%;"></iframe>
</div>
</div>
<p>As shown in the calculations in <a href="#fig-IE_10" class="quarto-xref">Figure&nbsp;<span>13.10</span></a> and <a href="#tbl-M_1" class="quarto-xref">Table&nbsp;<span>13.6</span></a>, out of the original $100 in government spending, $53 is left to spend on domestically produced goods and services. That $53 which was spent, becomes income to someone, somewhere in the economy. Those who receive that income also pay 30% in taxes, save 10% of after-tax income, and spend 10% of total income on imports, as shown in <a href="#fig-IE_10" class="quarto-xref">Figure&nbsp;<span>13.10</span></a>, so that an additional $28.09 (that is, 0.53 × $53) is spent in the third round. The people who receive that income then pay taxes, save, and buy imports, and the amount spent in the fourth round is $14.89 (that is, 0.53 × $28.09).</p>
<div id="fig-IE_10" class="align-center quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-IE_10-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="Graphs/IncomeExpenditureModel/CNX_Econ_C25_022.jpg" class="lightbox" data-gallery="quarto-lightbox-gallery-10" data-glightbox="description: .lightbox-desc-10"><img src="Graphs/IncomeExpenditureModel/CNX_Econ_C25_022.jpg" class="align-center img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-IE_10-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;13.10: The Multiplier Effect. An original increase of government spending of $100 causes a rise in aggregate expenditure of $100. But that $100 is income to others in the economy, and after they save, pay taxes, and buy imports, they spend $53 of that $100 in a second round. In turn, that $53 is income to others. Thus, the original government spending of $100 is multiplied by these cycles of spending, but the impact of each successive cycle gets smaller and smaller. Given the numbers in this example, the original government spending increase of $100 raises aggregate expenditure by $213; therefore, the multiplier in this example is $213/$100 = 2.13.
</figcaption>
</figure>
</div>
<p>The graph shows the multiplier effect as a rapidly upward-sloping line that levels at $200 and continues as a straight, horizontal line.</p>
<div id="tbl-M_1" class="quarto-float anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-M_1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;13.6: Calculating the Multiplier Effect
</figcaption>
<div aria-describedby="tbl-M_1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="table">
<colgroup>
<col style="width: 11%">
<col style="width: 41%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Round</th>
<th>Item</th>
<th>Amount</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td rowspan="4">1</td>
<td><div class="line-block">Original increase in aggregate expenditure from government spending Which is income to people throughout the economy:</div></td>
<td>$100</td>
</tr>
<tr class="even">
<td><ul>
<li>Pay 30% in taxes.</li>
</ul></td>
<td>–$30 (net inc.=$70)</td>
</tr>
<tr class="odd">
<td><ul>
<li>Save 10% of after-tax income.</li>
</ul></td>
<td>–$10</td>
</tr>
<tr class="even">
<td><ul>
<li>Spend 10% of net income on imports.</li>
</ul></td>
<td>–$7</td>
</tr>
<tr class="odd">
<td rowspan="4">2</td>
<td><div class="line-block">Second-round increase of..<br>
Which is $53 of income to people through the economy:</div></td>
<td>$70–$7–$10 = $53</td>
</tr>
<tr class="even">
<td><ul>
<li>Pay 30% in taxes.</li>
</ul></td>
<td>–$15.9 (netinc=$37.1)</td>
</tr>
<tr class="odd">
<td><ul>
<li>Save 10% of after-tax income.</li>
</ul></td>
<td>–$5.3</td>
</tr>
<tr class="even">
<td><ul>
<li>Spend 10% of income on imports.</li>
</ul></td>
<td>–$3.71</td>
</tr>
<tr class="odd">
<td rowspan="4">3</td>
<td><div class="line-block">Third-round increase of…<br>
Which is $28.09 of income to people through the economy:</div></td>
<td>$37.1–$3.71–$5.3 =$28.09</td>
</tr>
<tr class="even">
<td><ul>
<li>Pay 30% in taxes.</li>
</ul></td>
<td></td>
</tr>
<tr class="odd">
<td><ul>
<li>Save 10% of after-tax income.</li>
</ul></td>
<td></td>
</tr>
<tr class="even">
<td><ul>
<li>Spend 10% of income on imports.</li>
</ul></td>
<td></td>
</tr>
<tr class="odd">
<td>4</td>
<td><div class="line-block">Fourth-round increase of…</div></td>
<td>$19.663 – $1.96633 – $2.809 = $14.89</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>Thus, over the first four rounds of aggregate expenditures, the impact of the original increase in government spending of $100 creates a rise in aggregate expenditures of $100 + $53 + $28.09 + $14.89 = $195.98. <a href="#fig-IE_10" class="quarto-xref">Figure&nbsp;<span>13.10</span></a> shows these total aggregate expenditures after these first four rounds, and then the <a href="#fig-IE_10" class="quarto-xref">Figure&nbsp;<span>13.10</span></a> shows the total aggregate expenditures after 30 rounds.</p>
<p>The additional boost to aggregate expenditures is shrinking in each round of consumption. After about 10 rounds, the additional increments are very small indeed—nearly invisible to the naked eye. After 30 rounds, the additional increments in each round are so small that they have no practical consequence. After 30 rounds, the cumulative value of the initial boost in aggregate expenditure is approximately $213.</p>
<p>Thus, the government spending increase of $100 eventually, after many cycles, produced an increase of $213 in aggregate expenditure and real GDP. In this example, the multiplier is $213/$100 = 2.13.</p>
</section>
<section id="calculating-the-multiplier" class="level3" data-number="13.4.2">
<h3 data-number="13.4.2" class="anchored" data-anchor-id="calculating-the-multiplier"><span class="header-section-number">13.4.2</span> Calculating the Multiplier</h3>
<p>Fortunately for everyone who is not carrying around a computer with a spreadsheet program to project the impact of an original increase in expenditures over 20, 50, or 100 rounds of spending, there is a formula for calculating the multiplier.</p>
<p><span class="math display">\[\text{Spending Multiplier} = \frac{1}{1 – (MPC * (1 – tax rate) - MPI)}\]</span></p>
<p>or alternatively</p>
<p><span class="math display">\[\text{Spending Multiplier} = \frac{1}{1 – MPC * (1 – tax rate) + MPI}\]</span></p>
<p>The data from <a href="#fig-IE_10" class="quarto-xref">Figure&nbsp;<span>13.10</span></a> and <a href="#tbl-M_1" class="quarto-xref">Table&nbsp;<span>13.6</span></a> is:</p>
<blockquote class="blockquote">
<ul>
<li>Marginal Propensity to Save (MPS) = 30%</li>
<li>Tax rate = 10%</li>
<li>Marginal Propensity to Import (MPI) = 10%</li>
</ul>
</blockquote>
<p>The MPC is equal to 1 – MPS, or 0.7. Therefore, the spending multiplier is:</p>
<p><span class="math display">\[\text{Spending Multiplier} = \frac{1}{1 – (0.7 – (0.10)(0.7) – 0.10)}\]</span></p>
<p><span class="math display">\[\text{Spending Multiplier} = \frac{1}{0.47} = 2.13\]</span></p>
<p>A change in spending of $100 multiplied by the spending multiplier of 2.13 is equal to a change in GDP of $213. Not coincidentally, this result is exactly what was calculated in <a href="#fig-IE_10" class="quarto-xref">Figure&nbsp;<span>13.10</span></a> after many rounds of expenditures cycling through the economy.</p>
<p>The size of the multiplier is determined by what proportion of the marginal dollar of income goes into taxes, saving, and imports. These three factors are known as “leakages,” because they determine how much demand “leaks out” in each round of the multiplier effect. If the leakages are relatively small, then each successive round of the multiplier effect will have larger amounts of demand, and the multiplier will be high.</p>
<p>Conversely, if the leakages are relatively large, then any initial change in demand will diminish more quickly in the second, third, and later rounds, and the multiplier will be small. Changes in the size of the leakages—a change in the marginal propensity to save, the tax rate, or the marginal propensity to import—will change the size of the multiplier.</p>
</section>
<section id="calculating-keynesian-policy-interventions" class="level3" data-number="13.4.3">
<h3 data-number="13.4.3" class="anchored" data-anchor-id="calculating-keynesian-policy-interventions"><span class="header-section-number">13.4.3</span> Calculating Keynesian Policy Interventions</h3>
<p>Returning to the original question: How much should government spending be increased to produce a total increase in real GDP of $100? If the goal is to increase aggregate demand by $100, and the multiplier is 2.13, then the increase in government spending to achieve that goal would be $100/2.13 = $47. Government spending of approximately $47, when combined with a multiplier of 2.13 (which is, remember, based on the specific assumptions about tax, saving, and import rates), produces an overall increase in real GDP of $100, restoring the economy to potential GDP of $800, as <a href="#fig-IE_11" class="quarto-xref">Figure&nbsp;<span>13.11</span></a> shows.</p>
<div id="fig-IE_11" class="align-center quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-IE_11-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="Graphs/IncomeExpenditureModel/CNX_Econ_C25_023.jpg" class="lightbox" data-gallery="quarto-lightbox-gallery-11" data-glightbox="description: .lightbox-desc-11"><img src="Graphs/IncomeExpenditureModel/CNX_Econ_C25_023.jpg" class="align-center img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-IE_11-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;13.11: The Multiplier Effect in an Expenditure-Output Model. The power of the multiplier effect is that an increase in expenditure has a larger increase on the equilibrium output. The increase in expenditure is the vertical increase from AE0 to AE1. However, the increase in equilibrium output, shown on the horizontal axis, is clearly larger.
</figcaption>
</figure>
</div>
<p>The graph shows the multiplier effect in the expenditure-output model: an increase in expenditure has a larger increase on the equilibrium output.</p>
<p>The multiplier effect is also visible on the Keynesian cross diagram. <a href="#fig-IE_11" class="quarto-xref">Figure&nbsp;<span>13.11</span></a> shows the example we have been discussing: a recessionary gap with an equilibrium of $700, potential GDP of $800, the slope of the aggregate expenditure function (AE0) determined by the assumptions that taxes are 30% of income, savings are 0.1 of after-tax income, and imports are 0.1 of before-tax income. At AE1, the aggregate expenditure function is moved up to reach potential GDP.</p>
<p>Now, compare the vertical shift upward in the aggregate expenditure function, which is $47, with the horizontal shift outward in real GDP, which is $100 (as these numbers were calculated earlier). The rise in real GDP is more than double the rise in the aggregate expenditure function. (Similarly, if you look back at <a href="#fig-IE_9" class="quarto-xref">Figure&nbsp;<span>13.9</span></a>, you will see that the vertical movements in the aggregate expenditure functions are smaller than the change in equilibrium output that is produced on the horizontal axis. Again, this is the multiplier effect at work.) In this way, the power of the multiplier is apparent in the income–expenditure graph, as well as in the arithmetic calculation.</p>
<p>The multiplier does not just affect government spending, but applies to any change in the economy. Say that business confidence declines and investment falls off, or that the economy of a leading trading partner slows down so that export sales decline. These changes will reduce aggregate expenditures, and then will have an even larger effect on real GDP because of the multiplier effect. Read the following Clear It Up feature to learn how the multiplier effect can be applied to analyze the economic impact of professional sports.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>HOW CAN THE MULTIPLIER BE USED TO ANALYZE THE ECONOMIC IMPACT OF PROFESSIONAL SPORTS?</p>
<p>Attracting professional sports teams and building sports stadiums to create jobs and stimulate business growth is an economic development strategy adopted by many communities throughout the United States. In his recent article, “Public Financing of Private Sports Stadiums,” James Joyner of Outside the Beltway looked at public financing for NFL teams. Joyner’s findings confirm the earlier work of John Siegfried of Vanderbilt University and Andrew Zimbalist of Smith College.</p>
<p>Siegfried and Zimbalist used the multiplier to analyze this issue. They considered the amount of taxes paid and dollars spent locally to see if there was a positive multiplier effect. Since most professional athletes and owners of sports teams are rich enough to owe a lot of taxes, let’s say that 40% of any marginal income they earn is paid in taxes. Because athletes are often high earners with short careers, let’s assume that they save one-third of their after-tax income.</p>
<p>However, many professional athletes do not live year-round in the city in which they play, so let’s say that one-half of the money that they do spend is spent outside the local area. One can think of spending outside a local economy, in this example, as the equivalent of imported goods for the national economy.</p>
<p>Now, consider the impact of money spent at local entertainment venues other than professional sports. While the owners of these other businesses may be comfortably middle-income, few of them are in the economic stratosphere of professional athletes. Because their incomes are lower, so are their taxes; say that they pay only 35% of their marginal income in taxes. They do not have the same ability, or need, to save as much as professional athletes, so let’s assume their MPC is just 0.8. Finally, because more of them live locally, they will spend a higher proportion of their income on local goods—say, 65%.</p>
<p>If these general assumptions hold true, then money spent on professional sports will have less local economic impact than money spent on other forms of entertainment. For professional athletes, out of a dollar earned, 40 cents goes to taxes, leaving 60 cents. Of that 60 cents, one-third is saved, leaving 40 cents, and half is spent outside the area, leaving 20 cents. Only 20 cents of each dollar is cycled into the local economy in the first round. For locally-owned entertainment, out of a dollar earned, 35 cents goes to taxes, leaving 65 cents. Of the rest, 20% is saved, leaving 52 cents, and of that amount, 65% is spent in the local area, so that 33.8 cents of each dollar of income is recycled into the local economy.</p>
<p>Siegfried and Zimbalist make the plausible argument that, within their household budgets, people have a fixed amount to spend on entertainment. If this assumption holds true, then money spent attending professional sports events is money that was not spent on other entertainment options in a given metropolitan area. Since the multiplier is lower for professional sports than for other local entertainment options, the arrival of professional sports to a city would reallocate entertainment spending in a way that causes the local economy to shrink, rather than to grow. Thus, their findings seem to confirm what Joyner reports and what newspapers across the country are reporting. A quick Internet search for “economic impact of sports” will yield numerous reports questioning this economic development strategy.</p>
</div>
</div>
</section>
<section id="multiplier-tradeoffs-stability-versus-the-power-of-macroeconomic-policy" class="level3" data-number="13.4.4">
<h3 data-number="13.4.4" class="anchored" data-anchor-id="multiplier-tradeoffs-stability-versus-the-power-of-macroeconomic-policy"><span class="header-section-number">13.4.4</span> Multiplier Tradeoffs: Stability versus the Power of Macroeconomic Policy</h3>
<p>Is an economy healthier with a high multiplier or a low one? With a high multiplier, any change in aggregate demand will tend to be substantially magnified, and so the economy will be more unstable. With a low multiplier, by contrast, changes in aggregate demand will not be multiplied much, so the economy will tend to be more stable.</p>
<p>However, with a low multiplier, government policy changes in taxes or spending will tend to have less impact on the equilibrium level of real output. With a higher multiplier, government policies to raise or reduce aggregate expenditures will have a larger effect. Thus, a low multiplier means a more stable economy, but also weaker government macroeconomic policy, while a high multiplier means a more volatile economy, but also an economy in which government macroeconomic policy is more powerful.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Key Concepts and Summary
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><p>The multiplier effect describes how an initial change in aggregate demand generated several times as much as cumulative GDP. The size of the spending multiplier is determined by three leakages: spending on savings, taxes, and imports. The formula for the multiplier is:</p>
<blockquote class="blockquote">
<p><span class="math display">\[\text{Multiplier} = \frac{1}{1 – (MPC × (1 – tax rate) - MPI)}\]</span></p>
</blockquote>
<p>or also</p>
<blockquote class="blockquote">
<p><span class="math display">\[\text{Multiplier} = \frac{1}{1 – MPC × (1 – tax rate) + MPI}\]</span></p>
</blockquote></li>
<li><p>In the lecture notes we denote the MPC as <span class="math inline">\(b\)</span> and the MPI as <span class="math inline">\(m\)</span>. There are also no taxes in the lecture notes example so that the multiplier there is written as:</p>
<blockquote class="blockquote">
<p><span class="math display">\[\text{Multiplier} = \frac{1}{1 – (b - m)}\]</span></p>
</blockquote></li>
<li><p>An economy with a lower multiplier is more stable—it is less affected either by economic events or by government policy than an economy with a higher multiplier.</p></li>
</ul>
</div>
</div>
<div class="callout callout-style-default callout-caution callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-16-contents" aria-controls="callout-16" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Self-Check Questions
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-16" class="callout-16-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ul>
<li>What is the multiplier effect?</li>
<li>Why are savings, taxes, and imports referred to as “leakages” in calculating the multiplier effect?</li>
<li>Will an economy with a high multiplier be more stable or less stable than an economy with a low multiplier in response to changes in the economy or in government policy?</li>
<li>How do economists use the multiplier?</li>
<li>Which model, the AD/AS or the AE model better explains the relationship between rising price levels and GDP? Why?</li>
<li>What are some reasons that the economy might be in a recession, and what is the appropriate government action to alleviate the recession?</li>
<li>What should the government do to relieve inflationary pressures if the aggregate expenditure is greater than potential GDP?</li>
<li>Two countries are in a recession. Country A has an MPC of 0.8 and Country B has an MPC of 0.6. In which country will government spending have the greatest impact?</li>
<li>Compare two policies: a tax cut on income or an increase in government spending on roads and bridges. What are both the short-term and long-term impacts of such policies on the economy?</li>
<li>What role does government play in stabilizing the economy and what are the tradeoffs that must be considered?</li>
<li>If there is a recessionary gap of $100 billion, should the government increase spending by $100 billion to close the gap? Why? Why not?</li>
<li>What other changes in the economy can be evaluated by using the multiplier?</li>
</ul>
</div>
</div>
</div>


<div class="hidden" aria-hidden="true">
<span class="glightbox-desc lightbox-desc-1">Figure&nbsp;13.1: The Expenditure-Output Diagram. The aggregate expenditure-output model shows aggregate expenditures on the vertical axis and real GDP on the horizontal axis. A vertical line shows potential GDP where full employment occurs. The 45-degree line shows all points where aggregate expenditures and output are equal. The aggregate expenditure schedule shows how total spending or aggregate expenditure increases as output or real GDP rises. The intersection of the aggregate expenditure schedule and the 45-degree line will be the equilibrium. Equilibrium occurs at E0, where aggregate expenditure AE0 is equal to the output level Y0.</span>
<span class="glightbox-desc lightbox-desc-2">Figure&nbsp;13.2: The Consumption Function. In the expenditure-output model, how does consumption increase with the level of national income? Output on the horizontal axis is conceptually the same as national income, since the value of all final output that is produced and sold must be income to someone, somewhere in the economy. At a national income level of zero, $600 is consumed. Then, each time income rises by $1,000, consumption rises by $800, because in this example, the marginal propensity to consume is 0.8.</span>
<span class="glightbox-desc lightbox-desc-3">Figure&nbsp;13.3: The Investment Function. The investment function is drawn as a flat line because investment is based on interest rates and expectations about the future, and so it does not change with the level of current national income. In this example, investment expenditures are at a level of 500. However, changes in factors like technological opportunities, expectations about near-term economic growth, and interest rates would all cause the investment function to shift up or down.</span>
<span class="glightbox-desc lightbox-desc-4">Figure&nbsp;13.4: The Government Spending Function. The level of government spending is determined by political factors, not by the level of real GDP in a given year. Thus, government spending is drawn as a horizontal line. In this example, government spending is at a level of 1,300. Congressional decisions to increase government spending will cause this horizontal line to shift up, while decisions to reduce spending would cause it to shift down.</span>
<span class="glightbox-desc lightbox-desc-5">Figure&nbsp;13.5: The Consumption Function Before and After Taxes. The upper line repeats the consumption function from Figure. The lower line shows the consumption function if taxes must first be paid on income, and then consumption is based on after-tax income.</span>
<span class="glightbox-desc lightbox-desc-6">Figure&nbsp;13.6: The Export and Import Functions.Panel (a) The export function is drawn as a horizontal line because exports are determined by the buying power of other countries and thus do not change with the size of the domestic economy. In this example, exports are set at 840. However, exports can shift up or down, depending on buying patterns in other countries. (b) The import function is drawn in negative territory because expenditures on imported products are a subtraction from expenditures in the domestic economy. In this example, the marginal propensity to import is 0.1, so imports are calculated by multiplying the level of income by –0.1.</span>
<span class="glightbox-desc lightbox-desc-7">Figure&nbsp;13.7: A Keynesian Cross Diagram. Each combination of national income and aggregate expenditure (after-tax consumption, government spending, investment, exports, and imports) is graphed. The equilibrium occurs where aggregate expenditure is equal to national income; this occurs where the aggregate expenditure schedule crosses the 45-degree line, at a real GDP of $6,000. Potential GDP in this example is $7,000, so the equilibrium is occurring at a level of output or real GDP below the potential GDP level.</span>
<span class="glightbox-desc lightbox-desc-8">Figure&nbsp;13.8: Equilibrium in the Keynesian Cross Diagram. If output was above the equilibrium level, at H, then the real output is greater than the aggregate expenditure in the economy. This pattern cannot hold, because it would mean that goods are produced but piling up unsold. If output was below the equilibrium level at L, then aggregate expenditure would be greater than output. This pattern cannot hold either, because it would mean that spending exceeds the number of goods being produced. Only point E can be at equilibrium, where output, or national income and aggregate expenditure, are equal. The equilibrium (E) must lie on the 45-degree line, which is the set of points where national income and aggregate expenditure are equal.</span>
<span class="glightbox-desc lightbox-desc-9">Figure&nbsp;13.9: Addressing Recessionary and Inflationary Gaps. Panel (a) If the equilibrium occurs at an output below potential GDP, then a recessionary gap exists. The policy solution to a recessionary gap is to shift the aggregate expenditure schedule up from AE0 to AE1, using policies like tax cuts or government spending increases. Then the new equilibrium E1 occurs at potential GDP. (b) If the equilibrium occurs at an output above potential GDP, then an inflationary gap exists. The policy solution to an inflationary gap is to shift the aggregate expenditure schedule down from AE0 to AE1, using policies like tax increases or spending cuts. Then, the new equilibrium E1 occurs at potential GDP.</span>
<span class="glightbox-desc lightbox-desc-10">Figure&nbsp;13.10: The Multiplier Effect. An original increase of government spending of $100 causes a rise in aggregate expenditure of $100. But that $100 is income to others in the economy, and after they save, pay taxes, and buy imports, they spend $53 of that $100 in a second round. In turn, that $53 is income to others. Thus, the original government spending of $100 is multiplied by these cycles of spending, but the impact of each successive cycle gets smaller and smaller. Given the numbers in this example, the original government spending increase of $100 raises aggregate expenditure by $213; therefore, the multiplier in this example is $213/$100 = 2.13.</span>
<span class="glightbox-desc lightbox-desc-11">Figure&nbsp;13.11: The Multiplier Effect in an Expenditure-Output Model. The power of the multiplier effect is that an increase in expenditure has a larger increase on the equilibrium output. The increase in expenditure is the vertical increase from AE0 to AE1. However, the increase in equilibrium output, shown on the horizontal axis, is clearly larger.</span>
</div>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./ch12-FiscalPolicy.html" class="pagination-link" aria-label="Government Budgets and Fiscal Policy">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Government Budgets and Fiscal Policy</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./ch14-InvestmentsFinancialMarkets.html" class="pagination-link" aria-label="Investments and Financial Markets">
        <span class="nav-page-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Investments and Financial Markets</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Copyright 2024, Juergen Jung</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item compact">
    <a class="nav-link" href="https://juejung.github.io/">
      <i class="bi bi-github" role="img">
</i> 
    </a>
  </li>  
</ul>
    </div>
  </div>
</footer>
<script>var lightboxQuarto = GLightbox({"loop":false,"openEffect":"zoom","closeEffect":"zoom","selector":".lightbox","descPosition":"bottom"});
window.onload = () => {
  lightboxQuarto.on('slide_before_load', (data) => {
    const { slideIndex, slideNode, slideConfig, player, trigger } = data;
    const href = trigger.getAttribute('href');
    if (href !== null) {
      const imgEl = window.document.querySelector(`a[href="${href}"] img`);
      if (imgEl !== null) {
        const srcAttr = imgEl.getAttribute("src");
        if (srcAttr && srcAttr.startsWith("data:")) {
          slideConfig.href = srcAttr;
        }
      }
    } 
  });

  lightboxQuarto.on('slide_after_load', (data) => {
    const { slideIndex, slideNode, slideConfig, player, trigger } = data;
    if (window.Quarto?.typesetMath) {
      window.Quarto.typesetMath(slideNode);
    }
  });

};
          </script>




</body></html>