<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.56">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>7&nbsp; Unemployment – Macroeconomic Principles</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./ch8-Inflation.html" rel="next">
<link href="./ch6-InternationalTrade.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script src="site_libs/quarto-contrib/glightbox/glightbox.min.js"></script>
<link href="site_libs/quarto-contrib/glightbox/glightbox.min.css" rel="stylesheet">
<link href="site_libs/quarto-contrib/glightbox/lightbox.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./ch5-MacroPerspective.html"><strong>Macroeconomics Part I</strong></a></li><li class="breadcrumb-item"><a href="./ch7-Unemployment.html"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Unemployment</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Macroeconomic Principles</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text"><strong>Introduction</strong></span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ch1-Introduction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ch2-MathIntro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">The Use of Mathematics in Principles of Economics</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ch3-ChoiceScarcity.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Choice in a World of Scarcity</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ch4-DemandSupply.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Demand and Supply</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text"><strong>Macroeconomics Part I</strong></span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ch5-MacroPerspective.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Intro Macro Perspective</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ch6-InternationalTrade.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">International Trade</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ch7-Unemployment.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Unemployment</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ch8-Inflation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Inflation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ch9-ProductionFullEmployment.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Production Technology and Full Employment</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ch10-Growth.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Economic Growth</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ch11-AggregateDemandAggregateSupply.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Aggregate Demand and Aggregate Supply</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text"><strong>Macroeconomics Part II</strong></span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ch12-FiscalPolicy.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Government Budgets and Fiscal Policy</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ch13-IncomeExpenditureModel.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">The Income Expenditure Model</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ch14-InvestmentsFinancialMarkets.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Investments and Financial Markets</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ch15-MoneyAndBanking.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Money and Banking</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ch16-MonetaryPolicy.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Monetary Policy</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ch17-ShortToLong.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">From Short-Run to Long-Run</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendix-PythonBasics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">First Steps in Python</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#how-economists-define-and-compute-unemployment-rate" id="toc-how-economists-define-and-compute-unemployment-rate" class="nav-link active" data-scroll-target="#how-economists-define-and-compute-unemployment-rate"><span class="header-section-number">7.2</span> How Economists Define and Compute Unemployment Rate</a>
  <ul class="collapse">
  <li><a href="#whos-in-or-out-of-the-labor-force" id="toc-whos-in-or-out-of-the-labor-force" class="nav-link" data-scroll-target="#whos-in-or-out-of-the-labor-force"><span class="header-section-number">7.2.1</span> Who’s In or Out of the Labor Force?</a></li>
  <li><a href="#calculating-the-unemployment-rate" id="toc-calculating-the-unemployment-rate" class="nav-link" data-scroll-target="#calculating-the-unemployment-rate"><span class="header-section-number">7.2.2</span> Calculating the Unemployment Rate</a></li>
  <li><a href="#hidden-unemployment" id="toc-hidden-unemployment" class="nav-link" data-scroll-target="#hidden-unemployment"><span class="header-section-number">7.2.3</span> Hidden Unemployment</a></li>
  <li><a href="#labor-force-participation-rate" id="toc-labor-force-participation-rate" class="nav-link" data-scroll-target="#labor-force-participation-rate"><span class="header-section-number">7.2.4</span> Labor Force Participation Rate</a></li>
  <li><a href="#the-establishment-payroll-survey" id="toc-the-establishment-payroll-survey" class="nav-link" data-scroll-target="#the-establishment-payroll-survey"><span class="header-section-number">7.2.5</span> The Establishment Payroll Survey</a></li>
  </ul></li>
  <li><a href="#how-does-the-u.s.-bureau-of-labor-statistics-collect-the-u.s.-unemployment-data" id="toc-how-does-the-u.s.-bureau-of-labor-statistics-collect-the-u.s.-unemployment-data" class="nav-link" data-scroll-target="#how-does-the-u.s.-bureau-of-labor-statistics-collect-the-u.s.-unemployment-data"><span class="header-section-number">7.3</span> How Does the U.S. Bureau of Labor Statistics Collect the U.S. Unemployment Data?</a>
  <ul class="collapse">
  <li><a href="#criticisms-of-measuring-unemployment" id="toc-criticisms-of-measuring-unemployment" class="nav-link" data-scroll-target="#criticisms-of-measuring-unemployment"><span class="header-section-number">7.3.1</span> Criticisms of Measuring Unemployment</a></li>
  <li><a href="#alternative-measures-of-unemployment" id="toc-alternative-measures-of-unemployment" class="nav-link" data-scroll-target="#alternative-measures-of-unemployment"><span class="header-section-number">7.3.2</span> Alternative Measures of Unemployment</a></li>
  </ul></li>
  <li><a href="#patterns-of-unemployment" id="toc-patterns-of-unemployment" class="nav-link" data-scroll-target="#patterns-of-unemployment"><span class="header-section-number">7.4</span> Patterns of Unemployment</a>
  <ul class="collapse">
  <li><a href="#the-historical-u.s.-unemployment-rate" id="toc-the-historical-u.s.-unemployment-rate" class="nav-link" data-scroll-target="#the-historical-u.s.-unemployment-rate"><span class="header-section-number">7.4.1</span> The Historical U.S. Unemployment Rate</a></li>
  <li><a href="#unemployment-rates-by-group" id="toc-unemployment-rates-by-group" class="nav-link" data-scroll-target="#unemployment-rates-by-group"><span class="header-section-number">7.4.2</span> Unemployment Rates by Group</a></li>
  <li><a href="#breaking-down-unemployment-in-other-ways" id="toc-breaking-down-unemployment-in-other-ways" class="nav-link" data-scroll-target="#breaking-down-unemployment-in-other-ways"><span class="header-section-number">7.4.3</span> Breaking Down Unemployment in Other Ways</a></li>
  <li><a href="#international-unemployment-comparisons" id="toc-international-unemployment-comparisons" class="nav-link" data-scroll-target="#international-unemployment-comparisons"><span class="header-section-number">7.4.4</span> International Unemployment Comparisons</a></li>
  </ul></li>
  <li><a href="#what-causes-changes-in-unemployment-over-the-short-run" id="toc-what-causes-changes-in-unemployment-over-the-short-run" class="nav-link" data-scroll-target="#what-causes-changes-in-unemployment-over-the-short-run"><span class="header-section-number">7.5</span> What Causes Changes in Unemployment over the Short Run</a>
  <ul class="collapse">
  <li><a href="#cyclical-unemployment" id="toc-cyclical-unemployment" class="nav-link" data-scroll-target="#cyclical-unemployment"><span class="header-section-number">7.5.1</span> Cyclical Unemployment</a></li>
  <li><a href="#why-wages-might-be-sticky-downward" id="toc-why-wages-might-be-sticky-downward" class="nav-link" data-scroll-target="#why-wages-might-be-sticky-downward"><span class="header-section-number">7.5.2</span> Why Wages Might Be Sticky Downward</a></li>
  </ul></li>
  <li><a href="#what-causes-changes-in-unemployment-over-the-long-run" id="toc-what-causes-changes-in-unemployment-over-the-long-run" class="nav-link" data-scroll-target="#what-causes-changes-in-unemployment-over-the-long-run"><span class="header-section-number">7.6</span> What Causes Changes in Unemployment over the Long Run</a>
  <ul class="collapse">
  <li><a href="#the-long-run-the-natural-rate-of-unemployment" id="toc-the-long-run-the-natural-rate-of-unemployment" class="nav-link" data-scroll-target="#the-long-run-the-natural-rate-of-unemployment"><span class="header-section-number">7.6.1</span> The Long Run: The Natural Rate of Unemployment</a></li>
  <li><a href="#frictional-unemployment" id="toc-frictional-unemployment" class="nav-link" data-scroll-target="#frictional-unemployment"><span class="header-section-number">7.6.2</span> Frictional Unemployment</a></li>
  <li><a href="#structural-unemployment" id="toc-structural-unemployment" class="nav-link" data-scroll-target="#structural-unemployment"><span class="header-section-number">7.6.3</span> Structural Unemployment</a></li>
  <li><a href="#natural-unemployment-and-potential-real-gdp" id="toc-natural-unemployment-and-potential-real-gdp" class="nav-link" data-scroll-target="#natural-unemployment-and-potential-real-gdp"><span class="header-section-number">7.6.4</span> Natural Unemployment and Potential Real GDP</a></li>
  <li><a href="#productivity-shifts-and-the-natural-rate-of-unemployment" id="toc-productivity-shifts-and-the-natural-rate-of-unemployment" class="nav-link" data-scroll-target="#productivity-shifts-and-the-natural-rate-of-unemployment"><span class="header-section-number">7.6.5</span> Productivity Shifts and the Natural Rate of Unemployment</a></li>
  <li><a href="#public-policy-and-the-natural-rate-of-unemployment" id="toc-public-policy-and-the-natural-rate-of-unemployment" class="nav-link" data-scroll-target="#public-policy-and-the-natural-rate-of-unemployment"><span class="header-section-number">7.6.6</span> Public Policy and the Natural Rate of Unemployment</a></li>
  <li><a href="#the-role-of-minimum-wages-do-they-cause-unemployment" id="toc-the-role-of-minimum-wages-do-they-cause-unemployment" class="nav-link" data-scroll-target="#the-role-of-minimum-wages-do-they-cause-unemployment"><span class="header-section-number">7.6.7</span> The Role of Minimum Wages: Do They Cause Unemployment?</a></li>
  <li><a href="#the-natural-rate-of-unemployment-in-recent-years" id="toc-the-natural-rate-of-unemployment-in-recent-years" class="nav-link" data-scroll-target="#the-natural-rate-of-unemployment-in-recent-years"><span class="header-section-number">7.6.8</span> The Natural Rate of Unemployment in Recent Years</a></li>
  <li><a href="#the-natural-rate-of-unemployment-in-europe" id="toc-the-natural-rate-of-unemployment-in-europe" class="nav-link" data-scroll-target="#the-natural-rate-of-unemployment-in-europe"><span class="header-section-number">7.6.9</span> The Natural Rate of Unemployment in Europe</a></li>
  <li><a href="#a-preview-of-policies-to-fight-unemployment" id="toc-a-preview-of-policies-to-fight-unemployment" class="nav-link" data-scroll-target="#a-preview-of-policies-to-fight-unemployment"><span class="header-section-number">7.6.10</span> A Preview of Policies to Fight Unemployment</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./ch5-MacroPerspective.html"><strong>Macroeconomics Part I</strong></a></li><li class="breadcrumb-item"><a href="./ch7-Unemployment.html"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Unemployment</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Unemployment</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<!--Unemployment {{{1-->
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Chapter Learning Objectives
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>How Economists Define and Compute Unemployment Rate</li>
<li>Patterns of Unemployment</li>
<li>What Causes Changes in Unemployment over the Short Run</li>
<li>What Causes Changes in Unemployment over the Long Run</li>
</ul>
</div>
</div>
<p>Unemployment can be a terrible and wrenching life experience—like a serious automobile accident or a messy divorce—whose consequences only someone who has gone through it can fully understand. For unemployed individuals and their families, there is the day-to-day financial stress of not knowing from where the next paycheck is coming. There are painful adjustments, like watching your savings account dwindle, selling a car and buying a cheaper one, or moving to a less expensive place to live. Even when the unemployed person finds a new job, it may pay less than the previous one. For many people, their job is an important part of their self worth. When unemployment separates people from the workforce, it can affect family relationships as well as mental and physical health.</p>
<p>The human costs of unemployment alone would justify making a low level of unemployment an important public policy priority. However, unemployment also includes economic costs to the broader society. When millions of unemployed but willing workers cannot find jobs, economic resource are unused. An economy with high unemployment is like a company operating with a functional but unused factory. The opportunity cost of unemployment is the output that the unemployed workers could have produced.</p>
<p>This chapter will discuss how economists define and compute the unemployment rate. It will examine the patterns of unemployment over time, for the U.S. economy as a whole, for different demographic groups in the U.S. economy, and for other countries. It will then consider an economic explanation for unemployment, and how it explains the patterns of unemployment and suggests public policies for reducing it.</p>
<div id="fig-U_001" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-U_001-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="Graphs/Unemployment/CNX_Econ_C21_016.jpg" class="lightbox" data-gallery="quarto-lightbox-gallery-1" title="Figure&nbsp;7.1: Borders was one of the many companies unable to recover from the 2008-2009 economic recession. (Credit: modification of work by Luis Villa del Campo/Flickr Creative Commons)"><img src="Graphs/Unemployment/CNX_Econ_C21_016.jpg" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-U_001-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7.1: Borders was one of the many companies unable to recover from the 2008-2009 economic recession. (Credit: modification of work by Luis Villa del Campo/Flickr Creative Commons)
</figcaption>
</figure>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<!--UNEMPLOYMENT AND THE GREAT RECESSION {{{2-->
<section id="unemployment-and-the-great-recession" class="level2" data-number="7.1">
<h2 data-number="7.1" class="anchored" data-anchor-id="unemployment-and-the-great-recession"><span class="header-section-number">7.1</span> UNEMPLOYMENT AND THE GREAT RECESSION</h2>
<p>Nearly eight million U.S. jobs were lost as a consequence of the Great Recession, which lasted from December 2007 to June 2009. At the outset of the recession, the unemployment rate was 5.0%. The rate began rising several months after the recession began, and it peaked at 10.0% in October 2009, several months after the recession ended, according to the Bureau of Labor Statistics (BLS). The job loss represented a huge number of positions gone. Subsequently, the recovery was tepid. Companies added some positions, but as of summer 2013, four years after the end of the recession, unemployment was about 7.5%, well above the pre-recession rate. Employment began increasing at the outset of 2010, and reached its pre-recession level in mid-2014. However, because of population and labor force growth, the unemployment rate at that point was still slightly above 6%. The economy only returned to an unemployment rate of 5.0% in September 2015, and it has remained at or slightly below that level since then, up through January 2017.</p>
<p>This brief overview of unemployment during and after the Great Recession highlights a few important points. First, unemployment is a lagging indicator of business activity. It didn’t begin to increase until a few months after the onset of the recession, and it didn’t begin to decline until several months after the recovery. Second, the decline in the unemployment rate was quite slow, with the pre-recession unemployment rate only reaching a higher level than six years after the recession ended. This reflects a combination of slow increase in the number of jobs and ongoing increases in the size of the population and the labor force.</p>
<p>It turns out that recent recessions, going back to the early 1990s, have been characterized by longer periods of recovery than their predecessors. We will return to this point at the end of the chapter. However, first we need to examine unemployment. What constitutes it, and how do we measure it?</p>
</section>
</div>
</div>
<!--How Economists Define and Compute Unemployment Rate {{{2-->
<section id="how-economists-define-and-compute-unemployment-rate" class="level2" data-number="7.2">
<h2 data-number="7.2" class="anchored" data-anchor-id="how-economists-define-and-compute-unemployment-rate"><span class="header-section-number">7.2</span> How Economists Define and Compute Unemployment Rate</h2>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Section Learning Objectives
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>Calculate the labor force participation rate and the unemployment rate</li>
<li>Explain hidden unemployment and what it means to be in or out of the labor force</li>
<li>Evaluate the collection and interpretation of unemployment data</li>
</ul>
</div>
</div>
<p>Newspaper or television reports typically describe unemployment as a percentage or a rate. A recent report might have said, for example, from August 2009 to November 2009, the U.S. unemployment rate rose from 9.7% to 10.0%, but by June 2010, it had fallen to 9.5%. At a glance, the changes between the percentages may seem small.</p>
<p>However, remember that the U.S. economy has about 160 million adults (as of the beginning of 2017) who either have jobs or are looking for them. A rise or fall of just 0.1% in the unemployment rate of 160 million potential workers translates into 160,000 people, which is roughly the total population of a city like Syracuse, New York, Brownsville, Texas, or Pasadena, California.</p>
<p>Large rises in the unemployment rate mean large numbers of job losses. In November 2009, at the peak of the recession, about 15 million people were out of work. Even with the unemployment rate now at 4.8% as of January 2017, about 7.6 million people who would like to have jobs are out of work.</p>
<section id="whos-in-or-out-of-the-labor-force" class="level3" data-number="7.2.1">
<h3 data-number="7.2.1" class="anchored" data-anchor-id="whos-in-or-out-of-the-labor-force"><span class="header-section-number">7.2.1</span> Who’s In or Out of the Labor Force?</h3>
<p>Should we count everyone without a job as unemployed? Of course not. For example, we should not count children as unemployed. Surely, we should not count the retired as unemployed. Many full-time college students have only a part-time job, or no job at all, but it seems inappropriate to count them as suffering the pains of unemployment. Some people are not working because they are rearing children, ill, on vacation, or on parental leave.</p>
<p>The point is that we do not just divide the adult population into employed and unemployed. A third group exists: people who do not have a job, and for some reason—retirement, looking after children, taking a voluntary break before a new job—are not interested in having a job, either. It also includes those who do want a job but have quit looking, often due to discouragement due to their inability to find suitable employment. Economists refer to this third group of those who are not working and not looking for work as out of the labor force or not in the labor force.</p>
<p>The U.S. unemployment rate, which is based on a monthly survey carried out by the U.S. Bureau of the Census, asks a series of questions to divide the adult population into employed, unemployed, or not in the labor force. To be classified as unemployed, a person must be without a job, currently available to work, and actively looking for work in the previous four weeks. Thus, a person who does not have a job but who is not currently available to work or has not actively looked for work in the last four weeks is counted as out of the labor force.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Employed: currently working for pay
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><p>Unemployed: Out of work and actively looking for a job</p></li>
<li><p>Out of the labor force: Out of paid work and not actively looking for a job</p></li>
<li><p>Labor force: The number of employed plus the unemployed</p></li>
</ul>
</div>
</div>
</section>
<section id="calculating-the-unemployment-rate" class="level3" data-number="7.2.2">
<h3 data-number="7.2.2" class="anchored" data-anchor-id="calculating-the-unemployment-rate"><span class="header-section-number">7.2.2</span> Calculating the Unemployment Rate</h3>
<p><a href="#fig-U_002" class="quarto-xref">Figure&nbsp;<span>7.2</span></a> shows the three-way division of the 16-and-over population. In January 2017, about 62.9% of the adult population was "in the labor force"; that is, people are either employed or without a job but looking for work. We can divide those in the labor force into the employed and the unemployed.</p>
<p><a href="#tbl-U-001" class="quarto-xref">Table&nbsp;<span>7.1</span></a> shows those values. The unemployment rate is not the percentage of the total adult population without jobs, but rather the percentage of adults who are in the labor force but who do not have jobs:</p>
<p><span class="math display">\[\boxed{\text{Unemployment rate} = \frac{\text{Unemployed people}}{\text{Total labor force}}\times 100}\]</span></p>
<div id="fig-U_002" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-U_002-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="Graphs/Unemployment/CNX_Econ2e_C21_02.jpg" class="lightbox" data-gallery="quarto-lightbox-gallery-2" title="Figure&nbsp;7.2: Employed, Unemployed, and Out of the Labor Force Distribution of Adult Population (age 16 and older), January 2017. The total adult, working-age population in January 2017 was 254.1 million. Out of this total population, 152.1 were classified as employed, and 7.6 million were classified as unemployed. The remaining 94.4 were classified as out of the labor force. As you will learn, however, this seemingly simple chart does not tell the whole story."><img src="Graphs/Unemployment/CNX_Econ2e_C21_02.jpg" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-U_002-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7.2: Employed, Unemployed, and Out of the Labor Force Distribution of Adult Population (age 16 and older), January 2017. The total adult, working-age population in January 2017 was 254.1 million. Out of this total population, 152.1 were classified as employed, and 7.6 million were classified as unemployed. The remaining 94.4 were classified as out of the labor force. As you will learn, however, this seemingly simple chart does not tell the whole story.
</figcaption>
</figure>
</div>
<p><a href="#tbl-U-001" class="quarto-xref">Table&nbsp;<span>7.1</span></a> shows the corresponding figures for the US.</p>
<div id="tbl-U-001" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-U-001-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;7.1: U.S. Employment and Unemployment, January 2017 (Source: <a href="https://data.bls.gov" class="uri">https://data.bls.gov</a>)
</figcaption>
<div aria-describedby="tbl-U-001-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Component</th>
<th style="text-align: left;">Count</th>
<th style="text-align: left;">Percent</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Total adult population over the age of 16</td>
<td style="text-align: left;">254.082 million</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">In the labor force Employed Unemployed</td>
<td style="text-align: left;">159.716 million 152.081 million 7.635 million</td>
<td style="text-align: left;">62.9%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Out of the labor force</td>
<td style="text-align: left;">94.366 million</td>
<td style="text-align: left;">37.1%</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>In this example, we can calculate the unemployment rate as 7.635 million unemployed people divided by 159.716 million people in the labor force, which works out to a 4.8% rate of unemployment. The following Work It Out feature will walk you through the steps of this calculation.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
CALCULATING LABOR FORCE PERCENTAGES
</div>
</div>
<div class="callout-body-container callout-body">
<p>How do economists arrive at the percentages in and out of the labor force and the unemployment rate? We will use the values in <a href="#tbl-U-001" class="quarto-xref">Table&nbsp;<span>7.1</span></a> to illustrate the steps.</p>
<p>To determine the percentage in the labor force:</p>
<dl>
<dt>Step 1.</dt>
<dd>
<p>Divide the number of people in the labor force (159.716 million) by the total adult (working-age) population (254.082 million).</p>
</dd>
<dt>Step 2.</dt>
<dd>
<p>Multiply by 100 to obtain the percentage.</p>
</dd>
</dl>
<p><span class="math display">\[\text{Percentage in the labor forcer}=159.716/254.082=0.6286=62.9\%\]</span></p>
<p>To determine the percentage out of the labor force:</p>
<dl>
<dt>Step 1.</dt>
<dd>
<p>Divide the number of people out the labor force (94.366 million) by the total adult (working-age) population (254.082 million).</p>
</dd>
<dt>Step 2.</dt>
<dd>
<p>Multiply by 100 to obtain the percentage.</p>
</dd>
</dl>
<p><span class="math display">\[\text{Percentage in the labor force} = 94.366/254.082=0.3714=37.1\%\]</span></p>
<p>To determine the unemployment rate:</p>
<dl>
<dt>Step 1.</dt>
<dd>
<p>Divide the number of unemployed people (7.635 million) by the total labor force (157 million).</p>
</dd>
<dt>Step 2.</dt>
<dd>
<p>Multiply by 100 to obtain the rate.</p>
</dd>
</dl>
<p><span class="math display">\[\text{Unemployment rate}=7.635/159.716 = 0.0478 = 4.8\%\]</span></p>
</div>
</div>
</section>
<section id="hidden-unemployment" class="level3" data-number="7.2.3">
<h3 data-number="7.2.3" class="anchored" data-anchor-id="hidden-unemployment"><span class="header-section-number">7.2.3</span> Hidden Unemployment</h3>
<p>Even with the “out of the labor force” category, there are still some people who are mislabeled in the categorization of employed, unemployed, or out of the labor force. There are some people who have only part time or temporary jobs, and they are looking for full time and permanent employment that are counted as employed, although they are not employed in the way they would like or need to be. Additionally, there are individuals who are underemployed.</p>
<p>This includes those who are trained or skilled for one type or level of work but are working in a lower paying job or one that does not utilize their skills. For example, we would consider an individual with a college degree in finance who is working as a sales clerk underemployed.</p>
<p>They are, however, also counted in the employed group. All of these individuals fall under the umbrella of the term “hidden unemployment.” Discouraged workers, those who have stopped looking for employment and, hence, are no longer counted in the unemployed also fall into this group</p>
</section>
<section id="labor-force-participation-rate" class="level3" data-number="7.2.4">
<h3 data-number="7.2.4" class="anchored" data-anchor-id="labor-force-participation-rate"><span class="header-section-number">7.2.4</span> Labor Force Participation Rate</h3>
<p>Another important statistic is the labor force participation rate. This is the percentage of adults in an economy who are either employed or who are unemployed and looking for a job. Using the data in Figure and Table, those included in this calculation would be the 159.716 million individuals in the labor force.</p>
<p>We calculate the rate by taking the number of people in the labor force, that is, the number employed and the number unemployed, divided by the total adult population and multiplying by 100 to get the percentage. For the data from January 2017, the labor force participation rate is 62.9%. Historically, the civilian labor force participation rate in the United States climbed beginning in the 1960s as women increasingly entered the workforce, and it peaked at just over 67% in late 1999 to early 2000.</p>
<p>Since then, the labor force participation rate has steadily declined, slowly to about 66% in 2008, early in the Great Recession, and then more rapidly during and after that recession, reaching its present level, where it has remained stable, near the end of 2013.</p>
</section>
<section id="the-establishment-payroll-survey" class="level3" data-number="7.2.5">
<h3 data-number="7.2.5" class="anchored" data-anchor-id="the-establishment-payroll-survey"><span class="header-section-number">7.2.5</span> The Establishment Payroll Survey</h3>
<p>When the unemployment report comes out each month, the Bureau of Labor Statistics (BLS) also reports on the number of jobs created—which comes from the establishment payroll survey. The payroll survey is based on a survey of about 147,000 businesses and government agencies throughout the United States.</p>
<p>It generates payroll employment estimates by the following criteria:</p>
<blockquote class="blockquote">
<ul>
<li>all employees,</li>
<li>average weekly hours worked, and</li>
<li>average hourly, weekly, and overtime earnings.</li>
</ul>
</blockquote>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Warning
</div>
</div>
<div class="callout-body-container callout-body">
<p>One of the criticisms of this survey is that it does not count the <strong>self-employed</strong>. It also does not make a distinction between new, minimum wage, part time or temporary jobs and full time jobs with “decent” pay.</p>
</div>
</div>
<!--How Does the U.S. Bureau of Labor Statistics Collect the U.S.  Unemployment Data? {{{2-->
</section>
</section>
<section id="how-does-the-u.s.-bureau-of-labor-statistics-collect-the-u.s.-unemployment-data" class="level2" data-number="7.3">
<h2 data-number="7.3" class="anchored" data-anchor-id="how-does-the-u.s.-bureau-of-labor-statistics-collect-the-u.s.-unemployment-data"><span class="header-section-number">7.3</span> How Does the U.S. Bureau of Labor Statistics Collect the U.S. Unemployment Data?</h2>
<p>The unemployment rate announced by the U.S. Bureau of Labor Statistics on the first Friday of each month for the previous month is based on the Current Population Survey (CPS), which the Bureau has carried out every month since 1940. The Bureau takes great care to make this survey representative of the country as a whole. The country is first divided into 3,137 areas. The U.S. Bureau of the Census then selects 729 of these areas to survey. It divides the 729 areas into districts of about 300 households each, and divides each district into clusters of about four dwelling units. Every month, Census Bureau employees call about 15,000 of the four-household clusters, for a total of 60,000 households. Employees interview households for four consecutive months, then rotate them out of the survey for eight months, and then interview them again for the same four months the following year, before leaving the sample permanently.</p>
<p>Based on this survey, state, industry, urban and rural areas, gender, age, race or ethnicity, and level of education statistics comprise components that contribute to unemployment rates. A wide variety of other information is available, too. For example, how long have people been unemployed? Did they become unemployed because they quit, or were laid off, or their employer went out of business? Is the unemployed person the only wage earner in the family? The Current Population Survey is a treasure trove of information about employment and unemployment. If you are wondering what the difference is between the CPS and EPS, read the following Clear it Up feature.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
WHAT IS THE DIFFERENCE BETWEEN CPS AND EPS?
</div>
</div>
<div class="callout-body-container callout-body">
<p>The United States Census Bureau conducts the Current Population Survey (CPS), which measures the percentage of the labor force that is unemployed. The Bureau of Labor Statistics' establishment payroll survey (EPS) is a payroll survey that measures the net change in jobs created for the month.</p>
</div>
</div>
<section id="criticisms-of-measuring-unemployment" class="level3" data-number="7.3.1">
<h3 data-number="7.3.1" class="anchored" data-anchor-id="criticisms-of-measuring-unemployment"><span class="header-section-number">7.3.1</span> Criticisms of Measuring Unemployment</h3>
<p>There are always complications in measuring the number of unemployed. For example, what about people who do not have jobs and would be available to work, but are <strong>discouraged</strong> by the lack of available jobs in their area and stopped looking? Such people, and their families, may be suffering the pains of unemployment. However, the survey counts them as out of the labor force because they are not actively looking for work. Other people may tell the Census Bureau that they are ready to work and looking for a job but, truly, they are not that eager to work and are not looking very hard at all. They are counted as unemployed, although they might more accurately be classified as out of the labor force. Still other people may have a job, perhaps doing something like yard work, child care, or cleaning houses, but are not reporting the income earned to the tax authorities. They may report being unemployed, when they actually are working.</p>
<p>Although the unemployment rate gets most of the public and media attention, economic researchers at the Bureau of Labor Statistics publish a wide array of surveys and reports that try to measure these kinds of issues and to develop a more nuanced and complete view of the labor market. It is not exactly a hot news flash that economic statistics are imperfect. Even imperfect measures like the unemployment rate, however, can still be quite informative, when interpreted knowledgeably and sensibly.</p>
</section>
<section id="alternative-measures-of-unemployment" class="level3" data-number="7.3.2">
<h3 data-number="7.3.2" class="anchored" data-anchor-id="alternative-measures-of-unemployment"><span class="header-section-number">7.3.2</span> Alternative Measures of Unemployment</h3>
<p>As just discussed, the official statistics for unemployment do not include the full range of individuals who would like to participate fully in the labor market</p>
<ul>
<li>Individuals who want to work, have searched for work in the prior year, but are not currently looking for work because they believe they won’t be able to find a job are called <strong>discouraged workers</strong></li>
<li>Individuals who would like to work, have searched for work in the recent past, but have stopped looking for work for a variety of reasons are known as <strong>marginally attached workers</strong> (e.g., temporary caretakers of children or parents)</li>
<li>Workers who would like to be employed full-time but hold part-time jobs are known as individuals <strong>working part-time for economic reasons</strong></li>
</ul>
<p>Adding these categories to the number of unemployed workers would result in a much higher rate of unemployment than the official unemployment statistic.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Key Concepts and Summary
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><p>Unemployment imposes high costs. Unemployed individuals suffer from loss of income and from stress. An economy with high unemployment suffers an opportunity cost of unused resources. We can divide the adult population into those in the labor force and those out of the labor force. In turn, we divide those in the labor force into employed and unemployed.</p></li>
<li><p>A person without a job must be willing and able to work and actively looking for work to be counted as unemployed; otherwise, a person without a job is counted as out of the labor force. Economists define the unemployment rate as the number of unemployed persons divided by the number of persons in the labor force (not the overall adult population).</p></li>
<li><p>The Current Population Survey (CPS) conducted by the United States Census Bureau measures the percentage of the labor force that is unemployed. The establishment payroll survey by the Bureau of Labor Statistics measures the net change in jobs created for the month.</p></li>
</ul>
</div>
</div>
<div class="callout callout-style-default callout-caution callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-9-contents" aria-controls="callout-9" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Self-Check Questions
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-9" class="callout-9-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ul>
<li>Suppose the adult population over the age of 16 is 237.8 million and the labor force is 153.9 million (of whom 139.1 million are employed). How many people are “not in the labor force?” What are the proportions of employed, unemployed and not in the labor force in the population? Hint: Proportions are percentages.</li>
<li>Using the above data, what is the unemployment rate? These data are U.S. statistics from 2010. How does it compare to the February 2015 unemployment rate computed earlier?</li>
<li>What is the difference between being unemployed and being out of the labor force?</li>
<li>How do you calculate the unemployment rate? How do you calculate the labor force participation rate?</li>
<li>Are all adults who do not hold jobs counted as unemployed?</li>
<li>If you are out of school but working part time, are you considered employed or unemployed in U.S. labor statistics? If you are a full time student and working 12 hours a week at the college cafeteria are you considered employed or not in the labor force? If you are a senior citizen who is collecting social security and a pension and working as a greeter at Wal-Mart are you considered employed or not in the labor force?</li>
<li>What happens to the unemployment rate when unemployed workers are reclassified as discouraged workers?</li>
<li>What happens to the labor force participation rate when employed individuals are reclassified as unemployed? What happens when they are reclassified as discouraged workers?</li>
<li>What are some of the problems with using the unemployment rate as an accurate measure of overall joblessness?</li>
<li>What criteria do the BLS use to count someone as employed? As unemployed?</li>
</ul>
</div>
</div>
</div>
<!--Patterns of Unemployment {{{2-->
</section>
</section>
<section id="patterns-of-unemployment" class="level2" data-number="7.4">
<h2 data-number="7.4" class="anchored" data-anchor-id="patterns-of-unemployment"><span class="header-section-number">7.4</span> Patterns of Unemployment</h2>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Section Learning Objectives
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>Explain historical patterns of unemployment in the U.S.</li>
<li>Identify trends of unemployment based on demographics</li>
<li>Evaluate global unemployment rates</li>
</ul>
</div>
</div>
<p>Let’s look at how unemployment rates have changed over time and how various groups of people are affected by unemployment differently.</p>
<section id="the-historical-u.s.-unemployment-rate" class="level3" data-number="7.4.1">
<h3 data-number="7.4.1" class="anchored" data-anchor-id="the-historical-u.s.-unemployment-rate"><span class="header-section-number">7.4.1</span> The Historical U.S. Unemployment Rate</h3>
<div id="3d28ebdc" class="cell" data-execution_count="1">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> os</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> seaborn <span class="im">as</span> sns</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>titleSize <span class="op">=</span> <span class="dv">16</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>sns.set_style(<span class="st">"whitegrid"</span>, {<span class="st">'grid.linestyle'</span>: <span class="st">':'</span>})</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="co"># -----------------------------------------------------------------------------</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Load data</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>df_a <span class="op">=</span> pd.read_csv(<span class="st">'Graphs/Annual_FRED.csv'</span>, header<span class="op">=</span><span class="dv">0</span>, index_col<span class="op">=</span><span class="dv">0</span>, parse_dates<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>df_q <span class="op">=</span> pd.read_csv(<span class="st">'Graphs/Quarterly_FRED.csv'</span>, header<span class="op">=</span><span class="dv">0</span>, index_col<span class="op">=</span><span class="dv">0</span>, parse_dates<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>df_m <span class="op">=</span> pd.read_csv(<span class="st">'Graphs/Monthly_FRED.csv'</span>, header<span class="op">=</span><span class="dv">0</span>, index_col<span class="op">=</span><span class="dv">0</span>, parse_dates<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a><span class="co"># -----------------------------------------------------------------------------</span></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>df_q[<span class="st">'ExportsTrill'</span>] <span class="op">=</span> df_q[<span class="st">'Exports'</span>]<span class="op">/</span><span class="dv">1000000</span></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>df_q[<span class="st">'ImportsTrill'</span>] <span class="op">=</span> df_q[<span class="st">'Imports'</span>]<span class="op">/</span><span class="dv">1000000</span></span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>df_q[<span class="st">'GDPTrill'</span>] <span class="op">=</span> df_q[<span class="st">'GDP'</span>]<span class="op">/</span><span class="dv">1000</span></span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>df_q[<span class="st">'GNPTrill'</span>] <span class="op">=</span> df_q[<span class="st">'GNP'</span>]<span class="op">/</span><span class="dv">1000</span></span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a>df_q[<span class="st">'realGDPTrill'</span>] <span class="op">=</span> df_q[<span class="st">'rGDP'</span>]<span class="op">/</span><span class="dv">1000</span></span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a>df_q[<span class="st">'ExportsGDP'</span>] <span class="op">=</span> (df_q[<span class="st">'Exports'</span>]<span class="op">/</span><span class="dv">1000</span>)<span class="op">/</span>df_q[<span class="st">'GDP'</span>]<span class="op">*</span><span class="dv">100</span></span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a>df_q[<span class="st">'ImportsGDP'</span>] <span class="op">=</span> (df_q[<span class="st">'Imports'</span>]<span class="op">/</span><span class="dv">1000</span>)<span class="op">/</span>df_q[<span class="st">'GDP'</span>]<span class="op">*</span><span class="dv">100</span></span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a>df_q[<span class="st">'TradeBalance'</span>] <span class="op">=</span> ((df_q[<span class="st">'Exports'</span>]<span class="op">-</span>df_q[<span class="st">'Imports'</span>])<span class="op">/</span><span class="dv">1000</span>)<span class="op">/</span>df_q[<span class="st">'GDP'</span>]<span class="op">*</span><span class="dv">100</span></span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a><span class="co"># -----------------------------------------------------------------------------</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div id="94688ec6" class="cell" data-execution_count="2">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>df_m[<span class="st">'Unemployment'</span>].plot(ylim<span class="op">=</span>(<span class="dv">0</span>,<span class="dv">15</span>))</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Unemployment Rate'</span>, fontsize<span class="op">=</span>titleSize)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'%'</span>)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><a href="ch7-Unemployment_files/figure-html/cell-3-output-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-3"><img src="ch7-Unemployment_files/figure-html/cell-3-output-1.png" width="582" height="451" class="figure-img"></a></p>
</figure>
</div>
</div>
</div>
<p>From this figure we see that the U.S. unemployment rate moves up and down as the economy moves in and out of recessions. However, over time, the unemployment rate seems to return to a range of 4% to 6%. There does not seem to be a long-term trend toward the rate moving generally higher or generally lower. (Source: Federal Reserve Economic Data (FRED) <a href="https://research.stlouisfed.org/fred2/series/LRUN64TTUSA156S0" class="uri">https://research.stlouisfed.org/fred2/series/LRUN64TTUSA156S0</a>)</p>
<p>As we look at this data, several patterns stand out:</p>
<ul>
<li>Unemployment rates do fluctuate over time. During the deep recessions of the early 1980s and of 2007–2009, unemployment reached roughly 10%. For comparison, during the 1930s Great Depression, the unemployment rate reached almost 25% of the labor force.</li>
<li>Unemployment rates in the late 1990s and into the mid-2000s were rather low by historical standards. The unemployment rate was below 5% from 1997 to 2000, and near 5% during almost all of 2006–2007, and 5% or slightly less from September 2015 through January 2017 (the latest date for which data are available as of this writing). The previous time unemployment had been less than 5% for three consecutive years was three decades earlier, from 1968 to 1970.</li>
<li>The unemployment rate never falls all the way to zero. It almost never seems to get below 3%—and it stays that low only for very short periods. (We discuss reasons why this is the case later in this chapter.)</li>
<li>The timing of rises and falls in unemployment matches fairly well with the timing of upswings and downswings in the overall economy, except that unemployment tends to lag changes in economic activity, and especially so during upswings of the economy following a recession. During periods of recession and depression, unemployment is high. During periods of economic growth, unemployment tends to be lower.</li>
<li>No significant upward or downward trend in unemployment rates is apparent. This point is especially worth noting because the U.S. population more than quadrupled from 76 million in 1900 to over 324 million by 2017. Moreover, a higher proportion of U.S. adults are now in the paid workforce, because women have entered the paid labor force in significant numbers in recent decades. Women comprised 18% of the paid workforce in 1900 and nearly half of the paid workforce in 2017. However, despite the increased number of workers, as well as other economic events like globalization and the continuous invention of new technologies, the economy has provided jobs without causing any long-term upward or downward trend in unemployment rates.</li>
</ul>
</section>
<section id="unemployment-rates-by-group" class="level3" data-number="7.4.2">
<h3 data-number="7.4.2" class="anchored" data-anchor-id="unemployment-rates-by-group"><span class="header-section-number">7.4.2</span> Unemployment Rates by Group</h3>
<p>Unemployment is not distributed evenly across the U.S. population. <a href="#fig-U004a" class="quarto-xref">Figure&nbsp;<span>7.3</span></a> – <a href="#fig-U004d" class="quarto-xref">Figure&nbsp;<span>7.7</span></a> show unemployment rates broken down in various ways: by gender, age, race/ethnicity, and education.</p>
<div id="fig-U004a" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-U004a-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="Graphs/Unemployment_Gender.svg" class="lightbox" data-gallery="quarto-lightbox-gallery-4" title="Figure&nbsp;7.3: Unemployment by gender since 1950. Unemployment rates for men used to be lower than unemployment rates for women, but in recent decades, the two rates have been very close, often–and especially during and soon after the Great Recession–with the unemployment rate for men somewhat higher. (b) By age, 1972–2016. Unemployment rates are highest for the very young and become lower with age. (c) By race and ethnicity, 1972–2016. Although unemployment rates for all groups tend to rise and fall together, the unemployment rate for blacks is typically about twice as high as that for whites, while the unemployment rate for Hispanics is in between. (Source: www.bls.gov)"><img src="Graphs/Unemployment_Gender.svg" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-U004a-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7.3: Unemployment by gender since 1950. Unemployment rates for men used to be lower than unemployment rates for women, but in recent decades, the two rates have been very close, often–and especially during and soon after the Great Recession–with the unemployment rate for men somewhat higher. (b) By age, 1972–2016. Unemployment rates are highest for the very young and become lower with age. (c) By race and ethnicity, 1972–2016. Although unemployment rates for all groups tend to rise and fall together, the unemployment rate for blacks is typically about twice as high as that for whites, while the unemployment rate for Hispanics is in between. (Source: www.bls.gov)
</figcaption>
</figure>
</div>
<div id="fig-U004b" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-U004b-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="Graphs/Unemployment_Age.svg" class="lightbox" data-gallery="quarto-lightbox-gallery-5" title="Figure&nbsp;7.4: Unemployment age since 1950. Unemployment rates are highest for the very young and become lower with age. (Source: www.bls.gov)"><img src="Graphs/Unemployment_Age.svg" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-U004b-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7.4: Unemployment age since 1950. Unemployment rates are highest for the very young and become lower with age. (Source: www.bls.gov)
</figcaption>
</figure>
</div>
<div id="fig-U004c" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-U004c-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="Graphs/Unemployment_Race.svg" class="lightbox" data-gallery="quarto-lightbox-gallery-6" title="Figure&nbsp;7.5: Unemployment by race and ethnicity since 1950. Although unemployment rates for all groups tend to rise and fall together, the unemployment rate for blacks is typically about twice as high as that for whites, while the unemployment rate for Hispanics is in between. (Source: www.bls.gov)"><img src="Graphs/Unemployment_Race.svg" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-U004c-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7.5: Unemployment by race and ethnicity since 1950. Although unemployment rates for all groups tend to rise and fall together, the unemployment rate for blacks is typically about twice as high as that for whites, while the unemployment rate for Hispanics is in between. (Source: www.bls.gov)
</figcaption>
</figure>
</div>
<div id="fig-U004bc" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-U004bc-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="Graphs/Unemployment_RaceGender.svg" class="lightbox" data-gallery="quarto-lightbox-gallery-7" title="Figure&nbsp;7.6: Unemployment by race and gender since 1950. (Source: www.bls.gov)"><img src="Graphs/Unemployment_RaceGender.svg" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-U004bc-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7.6: Unemployment by race and gender since 1950. (Source: www.bls.gov)
</figcaption>
</figure>
</div>
<div id="fig-U004d" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-U004d-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="Graphs/Unemployment_Education.svg" class="lightbox" data-gallery="quarto-lightbox-gallery-8" title="Figure&nbsp;7.7: Unemployment by education since 1950. (Source: www.bls.gov)"><img src="Graphs/Unemployment_Education.svg" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-U004d-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7.7: Unemployment by education since 1950. (Source: www.bls.gov)
</figcaption>
</figure>
</div>
<p>The unemployment rate for women had historically tended to be higher than the unemployment rate for men, perhaps reflecting the historical pattern that women were seen as “secondary” earners. By about 1980, however, the unemployment rate for women was essentially the same as that for men, as <a href="#fig-U004a" class="quarto-xref">Figure&nbsp;<span>7.3</span></a> shows. During the 2008-2009 recession and in the immediate aftermath, the unemployment rate for men exceeded the unemployment rate for women. Subsequently, however, the gap has narrowed.</p>
<p>Younger workers tend to have higher unemployment, while middle-aged workers tend to have lower unemployment, probably because the middle-aged workers feel the responsibility of needing to have a job more heavily. Younger workers move in and out of jobs more than middle-aged workers, as part of the process of matching of workers and jobs, and this contributes to their higher unemployment rates. In addition, middle-aged workers are more likely to feel the responsibility of needing to have a job more heavily. Elderly workers have extremely low rates of unemployment, because those who do not have jobs often exit the labor force by retiring, and thus are not counted in the unemployment statistics. <a href="#fig-U004b" class="quarto-xref">Figure&nbsp;<span>7.4</span></a> shows unemployment rates for women divided by age. The pattern for men is similar.</p>
<p>The unemployment rate for African-Americans is substantially higher than the rate for other racial or ethnic groups, a fact that surely reflects, to some extent, a pattern of discrimination that has constrained blacks’ labor market opportunities. However, the gaps between unemployment rates for whites and for blacks and Hispanics diminished in the 1990s, as <a href="#fig-U004c" class="quarto-xref">Figure&nbsp;<span>7.5</span></a> shows. In fact, unemployment rates for blacks and Hispanics were at the lowest levels for several decades in the mid-2000s before rising during the recent Great Recession.</p>
<p>Finally, those with less education typically suffer higher unemployment. In January 2017, for example, the unemployment rate for those with a college degree was 2.5%; for those with some college but not a four year degree, the unemployment rate was 3.8%; for high school graduates with no additional degree, the unemployment rate was 5.3%; and for those without a high school diploma, the unemployment rate was 7.7%. This pattern arises because additional education typically offers better connections to the labor market and higher demand. With less attractive labor market opportunities for low-skilled workers compared to the opportunities for the more highly-skilled, including lower pay, low-skilled workers may be less motivated to find jobs.</p>
</section>
<section id="breaking-down-unemployment-in-other-ways" class="level3" data-number="7.4.3">
<h3 data-number="7.4.3" class="anchored" data-anchor-id="breaking-down-unemployment-in-other-ways"><span class="header-section-number">7.4.3</span> Breaking Down Unemployment in Other Ways</h3>
<p>The Bureau of Labor Statistics also gives information about the reasons for unemployment, as well as the length of time individuals have been unemployed. <a href="#tbl-U_001b" class="quarto-xref">Table&nbsp;<span>7.2</span></a>, for example, shows the four reasons for unemployment and the percentages of the currently unemployed that fall into each category.</p>
<div id="tbl-U_001b" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-U_001b-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;7.2: Reasons for Unemployment, January 2017
</figcaption>
<div aria-describedby="tbl-U_001b-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Reason</th>
<th style="text-align: left;">Percentage</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">New Entrants</td>
<td style="text-align: left;">10.8%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Re-entrants</td>
<td style="text-align: left;">28.7%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Job Leavers</td>
<td style="text-align: left;">11.4%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Job Losers: Temporary</td>
<td style="text-align: left;">14.0%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Job Losers: Non Temporary</td>
<td style="text-align: left;">35.1%</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p><a href="#tbl-U_002" class="quarto-xref">Table&nbsp;<span>7.3</span></a> shows the length of unemployment. For both of these, the data is from January 2017.(bls.gov)</p>
<div id="tbl-U_002" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-U_002-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;7.3: Length of Unemployment, January 2017
</figcaption>
<div aria-describedby="tbl-U_002-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Length of Time</th>
<th style="text-align: left;">Percentage</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Under 5 weeks</td>
<td style="text-align: left;">32.5%</td>
</tr>
<tr class="even">
<td style="text-align: left;">5 to 14 weeks</td>
<td style="text-align: left;">27.5%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">15 to 26 weeks</td>
<td style="text-align: left;">15.7%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Over 27 weeks</td>
<td style="text-align: left;">27.4%</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</section>
<section id="international-unemployment-comparisons" class="level3" data-number="7.4.4">
<h3 data-number="7.4.4" class="anchored" data-anchor-id="international-unemployment-comparisons"><span class="header-section-number">7.4.4</span> International Unemployment Comparisons</h3>
<p>From an international perspective, the U.S. unemployment rate typically has looked a little better than average. <a href="#tbl-U_003" class="quarto-xref">Table&nbsp;<span>7.4</span></a> compares unemployment rates for 1991, 1996, 2001, 2006 (just before the recession), and 2012 (somewhat after the recession) from several other high-income countries.</p>
<div id="tbl-U_003" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-U_003-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;7.4: International Comparisons of Unemployment Rates
</figcaption>
<div aria-describedby="tbl-U_003-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Country</th>
<th style="text-align: left;">1991</th>
<th style="text-align: left;">1996</th>
<th style="text-align: left;">2001</th>
<th style="text-align: left;">2006</th>
<th style="text-align: left;">2012</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">United States</td>
<td style="text-align: left;">6.8%</td>
<td style="text-align: left;">5.4%</td>
<td style="text-align: left;">4.8%</td>
<td style="text-align: left;">4.4%</td>
<td style="text-align: left;">8.1%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Canada</td>
<td style="text-align: left;">9.8%</td>
<td style="text-align: left;">8.8%</td>
<td style="text-align: left;">6.4%</td>
<td style="text-align: left;">6.2%</td>
<td style="text-align: left;">6.3%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Japan</td>
<td style="text-align: left;">2.1%</td>
<td style="text-align: left;">3.4%</td>
<td style="text-align: left;">5.1%</td>
<td style="text-align: left;">4.5%</td>
<td style="text-align: left;">3.9%</td>
</tr>
<tr class="even">
<td style="text-align: left;">France</td>
<td style="text-align: left;">9.5%</td>
<td style="text-align: left;">12.5%</td>
<td style="text-align: left;">8.7%</td>
<td style="text-align: left;">10.1%</td>
<td style="text-align: left;">10.0%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Germany</td>
<td style="text-align: left;">5.6%</td>
<td style="text-align: left;">9.0%</td>
<td style="text-align: left;">8.9%</td>
<td style="text-align: left;">9.8%</td>
<td style="text-align: left;">5.5%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Italy</td>
<td style="text-align: left;">6.9%</td>
<td style="text-align: left;">11.7%</td>
<td style="text-align: left;">9.6%</td>
<td style="text-align: left;">7.8%</td>
<td style="text-align: left;">10.8%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Sweden</td>
<td style="text-align: left;">3.1%</td>
<td style="text-align: left;">9.9%</td>
<td style="text-align: left;">5.0%</td>
<td style="text-align: left;">5.2%</td>
<td style="text-align: left;">7.9%</td>
</tr>
<tr class="even">
<td style="text-align: left;">United Kingdom</td>
<td style="text-align: left;">8.8%</td>
<td style="text-align: left;">8.1%</td>
<td style="text-align: left;">5.1%</td>
<td style="text-align: left;">5.5%</td>
<td style="text-align: left;">8.0%</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>However, we need to treat cross-country comparisons of unemployment rates with care, because each country has slightly different definitions of unemployment, survey tools for measuring unemployment, and also different labor markets. For example, Japan’s unemployment rates appear quite low, but Japan’s economy has been mired in slow growth and recession since the late 1980s, and Japan’s unemployment rate probably paints too rosy a picture of its labor market. In Japan, workers who lose their jobs are often quick to exit the labor force and not look for a new job, in which case they are not counted as unemployed. In addition, Japanese firms are often quite reluctant to fire workers, and so firms have substantial numbers of workers who are on reduced hours or officially employed, but doing very little. We can view this Japanese pattern as an unusual method for society to provide support for the unemployed, rather than a sign of a healthy economy.</p>
<p>Comparing unemployment rates in the United States and other high-income economies with unemployment rates in Latin America, Africa, Eastern Europe, and Asia is very difficult. One reason is that the statistical agencies in many poorer countries lack the resources and technical capabilities of the U.S. Bureau of the Census. However, a more difficult problem with international comparisons is that in many low-income countries, most workers are not involved in the labor market through an employer who pays them regularly. Instead, workers in these countries are engaged in short-term work, subsistence activities, and barter. Moreover, the effect of unemployment is very different in high-income and low-income countries. Unemployed workers in the developed economies have access to various government programs like unemployment insurance, welfare, and food stamps. Such programs may barely exist in poorer countries. Although unemployment is a serious problem in many low-income countries, it manifests itself in a different way than in high-income countries.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Key Concepts and Summary
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>The U.S. unemployment rate rises during periods of recession and depression, but falls back to the range of 4% to 6% when the economy is strong. The unemployment rate never falls to zero. Despite enormous growth in the size of the U.S. population and labor force in the twentieth century, along with other major trends like globalization and new technology, the unemployment rate shows no long-term rising trend.</li>
<li>Unemployment rates differ by group: higher for African-Americans and Hispanics than for whites; higher for less educated than more educated; higher for the young than the middle-aged. Women’s unemployment rates used to be higher than men’s, but in recent years men’s and women’s unemployment rates have been very similar. In recent years, unemployment rates in the United States have compared favorably with unemployment rates in most other high-income economies.</li>
</ul>
</div>
</div>
<div class="callout callout-style-default callout-caution callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-12-contents" aria-controls="callout-12" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Self-Check Questions
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-12" class="callout-12-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ul>
<li><p>Over the long term, has the U.S. unemployment rate generally trended up, trended down, or remained at basically the same level?</p></li>
<li><p>Whose unemployment rates are commonly higher in the U.S. economy: a. Whites or nonwhites? b. The young or the middle-aged? c.&nbsp;College graduates or high school graduates?</p></li>
<li><p>Are U.S. unemployment rates typically higher, lower, or about the same as unemployment rates in other high-income countries?</p></li>
<li><p>Are U.S. unemployment rates distributed evenly across the population?</p></li>
<li><p>Is the higher unemployment rates for minority workers necessarily an indication of discrimination? What could be some other reasons for the higher unemployment rate?</p></li>
<li><p>While unemployment is highly negatively correlated with the level of economic activity, in the real world it responds with a lag. In other words, firms do not immediately lay off workers in response to a sales decline. They wait a while before responding. Similarly, firms do not immediately hire workers when sales pick up. What do you think accounts for the lag in response time?</p></li>
<li><p>Why do you think that unemployment rates are lower for individuals with more education?</p></li>
</ul>
</div>
</div>
</div>
<!--What Causes Changes in Unemployment over the Short Run {{{2-->
</section>
</section>
<section id="what-causes-changes-in-unemployment-over-the-short-run" class="level2" data-number="7.5">
<h2 data-number="7.5" class="anchored" data-anchor-id="what-causes-changes-in-unemployment-over-the-short-run"><span class="header-section-number">7.5</span> What Causes Changes in Unemployment over the Short Run</h2>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Section Learning Objectives
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>Analyze cyclical unemployment</li>
<li>Explain the relationship between sticky wages and employment using various economic arguments</li>
<li>Apply supply and demand models to unemployment and wages</li>
</ul>
</div>
</div>
<p>We have seen that unemployment varies across times and places. What causes changes in unemployment? There are different answers in the short run and in the long run. Let's look at the short run first.</p>
<section id="cyclical-unemployment" class="level3" data-number="7.5.1">
<h3 data-number="7.5.1" class="anchored" data-anchor-id="cyclical-unemployment"><span class="header-section-number">7.5.1</span> Cyclical Unemployment</h3>
<p>Let’s make the plausible assumption that in the short run, from a few months to a few years, the quantity of hours that the average person is willing to work for a given wage does not change much, so the labor supply curve does not shift much. In addition, make the standard ceteris paribus assumption that there is no substantial short-term change in the age structure of the labor force, institutions and laws affecting the labor market, or other possibly relevant factors.</p>
<p>One primary determinant of the demand for labor from firms is how they perceive the state of the macro economy. If firms believe that business is expanding, then at any given wage they will desire to hire a greater quantity of labor, and the labor demand curve shifts to the right. Conversely, if firms perceive that the economy is slowing down or entering a recession, then they will wish to hire a lower quantity of labor at any given wage, and the labor demand curve will shift to the left. Economists call the variation in unemployment that the economy causes moving from expansion to recession or from recession to expansion (i.e.&nbsp;the business cycle) cyclical unemployment.</p>
<p>From the standpoint of the supply-and-demand model of competitive and flexible labor markets, unemployment represents something of a puzzle. In a supply-and-demand model of a labor market, as <a href="#fig-U_004b" class="quarto-xref">Figure&nbsp;<span>7.8</span></a> illustrates, the labor market should move toward an equilibrium wage and quantity. At the equilibrium wage (We), the equilibrium quantity (Qe) of labor supplied by workers should be equal to the quantity of labor demanded by employers.</p>
<div id="fig-U_004b" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-U_004b-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="Graphs/Unemployment/CNX_Econ_C21_006.jpg" class="lightbox" data-gallery="quarto-lightbox-gallery-9" title="Figure&nbsp;7.8: In a labor market with flexible wages, the equilibrium will occur at wage We and quantity Qe, where the number of people who want jobs (shown by S) equals the number of jobs available (shown by D)."><img src="Graphs/Unemployment/CNX_Econ_C21_006.jpg" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-U_004b-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7.8: In a labor market with flexible wages, the equilibrium will occur at wage We and quantity Qe, where the number of people who want jobs (shown by S) equals the number of jobs available (shown by D).
</figcaption>
</figure>
</div>
<p>One possibility for unemployment is that people who are unemployed are those who are not willing to work at the current equilibrium wage, say $10 an hour, but would be willing to work at a higher wage, like $20 per hour. The monthly Current Population Survey would count these people as unemployed, because they say they are ready and looking for work (at $20 per hour). However, from an economist’s perspective, these people are choosing to be unemployed.</p>
<p>Probably a few people are unemployed because of unrealistic expectations about wages, but they do not represent the majority of the unemployed. Instead, unemployed people often have friends or acquaintances of similar skill levels who are employed, and the unemployed would be willing to work at the jobs and wages similar to what those people are receiving. However, the employers of their friends and acquaintances do not seem to be hiring. In other words, these people are involuntarily unemployed. What causes involuntary unemployment?</p>
</section>
<section id="why-wages-might-be-sticky-downward" class="level3" data-number="7.5.2">
<h3 data-number="7.5.2" class="anchored" data-anchor-id="why-wages-might-be-sticky-downward"><span class="header-section-number">7.5.2</span> Why Wages Might Be Sticky Downward</h3>
<p>If a labor market model with flexible wages does not describe unemployment very well—because it predicts that anyone willing to work at the going wage can always find a job—then it may prove useful to consider economic models in which wages are not flexible or adjust only very slowly. In particular, even though wage increases may occur with relative ease, wage decreases are few and far between.</p>
<p>One set of reasons why wages may be “sticky downward,” as economists put it, involves economic laws and institutions. For low-skilled workers receiving minimum wage, it is illegal to reduce their wages. For union workers operating under a multiyear contract with a company, wage cuts might violate the contract and create a labor dispute or a strike. However, minimum wages and union contracts are not a sufficient reason why wages would be sticky downward for the U.S. economy as a whole. After all, out of the 150 million or so employed workers in the U.S. economy, only about 2.6 million—less than 2% of the total—do not receive compensation above the minimum wage. Similarly, labor unions represent only about 11% of American wage and salary workers. In other high-income countries, more workers may have their wages determined by unions or the minimum wage may be set at a level that applies to a larger share of workers. However, for the United States, these two factors combined affect only about 15% or less of the labor force.</p>
<p>Economists looking for reasons why wages might be sticky downwards have focused on factors that may characterize most labor relationships in the economy, not just a few. Many have proposed a number of different theories, but they share a common tone.</p>
<p>One argument is that even employees who are not union members often work under an implicit contract, which is that the employer will try to keep wages from falling when the economy is weak or the business is having trouble, and the employee will not expect huge salary increases when the economy or the business is strong. This wage-setting behavior acts like a form of insurance: the employee has some protection against wage declines in bad times, but pays for that protection with lower wages in good times. Clearly, this sort of implicit contract means that firms will be hesitant to cut wages, lest workers feel betrayed and work less hard or even leave the firm.</p>
<p>Efficiency wage theory argues that workers' productivity depends on their pay, and so employers will often find it worthwhile to pay their employees somewhat more than market conditions might dictate. One reason is that employees who receive better pay than others will be more productive because they recognize that if they were to lose their current jobs, they would suffer a decline in salary. As a result, they are motivated to work harder and to stay with the current employer. In addition, employers know that it is costly and time-consuming to hire and train new employees, so they would prefer to pay workers a little extra now rather than to lose them and have to hire and train new workers. Thus, by avoiding wage cuts, the employer minimizes costs of training and hiring new workers, and reaps the benefits of well-motivated employees.</p>
<p>The adverse selection of wage cuts argument points out that if an employer reacts to poor business conditions by reducing wages for all workers, then the best workers, those with the best employment alternatives at other firms, are the most likely to leave. The least attractive workers, with fewer employment alternatives, are more likely to stay. Consequently, firms are more likely to choose which workers should depart, through layoffs and firings, rather than trimming wages across the board. Sometimes companies that are experiencing difficult times can persuade workers to take a pay cut for the short term, and still retain most of the firm’s workers. However, it is far more typical for companies to lay off some workers, rather than to cut wages for everyone.</p>
<p>The insider-outsider model of the labor force, in simple terms, argues that those already working for firms are “insiders,” while new employees, at least for a time, are “outsiders.” A firm depends on its insiders to keep the organization running smoothly, to be familiar with routine procedures, and to train new employees. However, cutting wages will alienate the insiders and damage the firm’s productivity and prospects.</p>
<p>Finally, the relative wage coordination argument points out that even if most workers were hypothetically willing to see a decline in their own wages in bad economic times as long as everyone else also experiences such a decline, there is no obvious way for a decentralized economy to implement such a plan. Instead, workers confronted with the possibility of a wage cut will worry that other workers will not have such a wage cut, and so a wage cut means being worse off both in absolute terms and relative to others. As a result, workers fight hard against wage cuts.</p>
<p>These theories of why wages tend not to move downward differ in their logic and their implications, and figuring out the strengths and weaknesses of each theory is an ongoing subject of research and controversy among economists. All tend to imply that wages will decline only very slowly, if at all, even when the economy or a business is having tough times. When wages are inflexible and unlikely to fall, then either short-run or long-run unemployment can result. <a href="#fig-U_005" class="quarto-xref">Figure&nbsp;<span>7.9</span></a> illustrates this.</p>
<div id="fig-U_005" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-U_005-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="Graphs/Unemployment/CNX_Econ_C21_013.jpg" class="lightbox" data-gallery="quarto-lightbox-gallery-10" title="Figure&nbsp;7.9: Because the wage rate is stuck at W, above the equilibrium, the number of those who want jobs (Qs) is greater than the number of job openings (Qd). The result is unemployment, shown by the bracket in the figure."><img src="Graphs/Unemployment/CNX_Econ_C21_013.jpg" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-U_005-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7.9: Because the wage rate is stuck at W, above the equilibrium, the number of those who want jobs (Qs) is greater than the number of job openings (Qd). The result is unemployment, shown by the bracket in the figure.
</figcaption>
</figure>
</div>
<p><a href="#fig-U_006" class="quarto-xref">Figure&nbsp;<span>7.10</span></a> shows the interaction between shifts in labor demand and wages that are sticky downward. <a href="#fig-U_006" class="quarto-xref">Figure&nbsp;<span>7.10</span></a> (a) illustrates the situation in which the demand for labor shifts to the right from <span class="math inline">\(D_0\)</span> to <span class="math inline">\(D_1\)</span>. In this case, the equilibrium wage rises from W0 to <span class="math inline">\(W_1\)</span> and the equilibrium quantity of labor hired increases from <span class="math inline">\(Q_0\)</span> to <span class="math inline">\(Q_1\)</span>. It does not hurt employee morale at all for wages to rise.</p>
<p><a href="#fig-U_006" class="quarto-xref">Figure&nbsp;<span>7.10</span></a> (b) shows the situation in which the demand for labor shifts to the left, from <span class="math inline">\(D_0\)</span> to <span class="math inline">\(D_1\)</span>, as it would tend to do in a recession. Because wages are sticky downward, they do not adjust toward what would have been the new equilibrium wage (<span class="math inline">\(W_1\)</span>), at least not in the short run. Instead, after the shift in the labor demand curve, the same quantity of workers is willing to work at that wage as before; however, the quantity of workers demanded at that wage has declined from the original equilibrium (<span class="math inline">\(Q_0\)</span>) to <span class="math inline">\(Q_2\)</span>. The gap between the original equilibrium quantity (<span class="math inline">\(Q_0\)</span>) and the new quantity demanded of labor (<span class="math inline">\(Q_2\)</span>) represents workers who would be willing to work at the going wage but cannot find jobs. The gap represents the economic meaning of unemployment.</p>
<div id="fig-U_006" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-U_006-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="Graphs/Unemployment/CNX_Econ_C21_014.jpg" class="lightbox" data-gallery="quarto-lightbox-gallery-11" title="Figure&nbsp;7.10: Panel (a) in a labor market where wages are able to rise, an increase in the demand for labor from D_0 to D_1 leads to an increase in equilibrium quantity of labor hired from Q_0 to Q_1 and a rise in the equilibrium wage from W0 to W_1. (b) In a labor market where wages do not decline, a fall in the demand for labor from D_0 to D_1 leads to a decline in the quantity of labor demanded at the original wage (W0) from Q_0 to Q_2. These workers will want to work at the prevailing wage (W0), but will not be able to find jobs."><img src="Graphs/Unemployment/CNX_Econ_C21_014.jpg" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-U_006-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7.10: Panel (a) in a labor market where wages are able to rise, an increase in the demand for labor from <span class="math inline">\(D_0\)</span> to <span class="math inline">\(D_1\)</span> leads to an increase in equilibrium quantity of labor hired from <span class="math inline">\(Q_0\)</span> to <span class="math inline">\(Q_1\)</span> and a rise in the equilibrium wage from W0 to <span class="math inline">\(W_1\)</span>. (b) In a labor market where wages do not decline, a fall in the demand for labor from <span class="math inline">\(D_0\)</span> to <span class="math inline">\(D_1\)</span> leads to a decline in the quantity of labor demanded at the original wage (W0) from <span class="math inline">\(Q_0\)</span> to <span class="math inline">\(Q_2\)</span>. These workers will want to work at the prevailing wage (W0), but will not be able to find jobs.
</figcaption>
</figure>
</div>
<p>This analysis helps to explain the connection that we noted earlier: that unemployment tends to rise in recessions and to decline during expansions. The overall state of the economy shifts the labor demand curve and, combined with wages that are sticky downwards, unemployment changes. The rise in unemployment that occurs because of a recession is cyclical unemployment.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Key Concepts and Summary
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>Cyclical unemployment rises and falls with the business cycle.</li>
<li>In a labor market with flexible wages, wages will adjust in such a market so that quantity demanded of labor always equals the quantity supplied of labor at the equilibrium wage.</li>
<li>Economists have proposed many theories for why wages might not be flexible, but instead may adjust only in a “sticky” way, especially when it comes to downward adjustments: implicit contracts, efficiency wage theory, adverse selection of wage cuts, insider-outsider model, and relative wage coordination.</li>
</ul>
</div>
</div>
<div class="callout callout-style-default callout-caution callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-15-contents" aria-controls="callout-15" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Self-Check Questions
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-15" class="callout-15-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ul>
<li>When would you expect cyclical unemployment to be rising? Falling?</li>
<li>Why is there unemployment in a labor market with flexible wages?</li>
<li>Name and explain some of the reasons why wages are likely to be sticky, especially in downward adjustments.</li>
<li>Do you think it is rational for workers to prefer sticky wages to wage cuts, when the consequence of sticky wages is unemployment for some workers? Why or why not? How do the reasons for sticky wages explained in this section apply to your argument?</li>
</ul>
</div>
</div>
</div>
<!--What Causes Changes in Unemployment over the Long Run {{{2-->
</section>
</section>
<section id="what-causes-changes-in-unemployment-over-the-long-run" class="level2" data-number="7.6">
<h2 data-number="7.6" class="anchored" data-anchor-id="what-causes-changes-in-unemployment-over-the-long-run"><span class="header-section-number">7.6</span> What Causes Changes in Unemployment over the Long Run</h2>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Section Learning Objectives
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>Explain frictional and structural unemployment</li>
<li>Assess relationships between the natural rate of employment and potential real GDP, productivity, and public policy</li>
<li>Identify recent patterns in the natural rate of employment</li>
<li>Propose ways to combat unemployment</li>
</ul>
</div>
</div>
<p>Cyclical unemployment explains why unemployment rises during a recession and falls during an economic expansion, but what explains the remaining level of unemployment even in good economic times? Why is the unemployment rate never zero? Even when the U.S. economy is growing strongly, the unemployment rate only rarely dips as low as 4%. Moreover, the discussion earlier in this chapter pointed out that unemployment rates in many European countries like Italy, France, and Germany have often been remarkably high at various times in the last few decades. Why does some level of unemployment persist even when economies are growing strongly? Why are unemployment rates continually higher in certain economies, through good economic years and bad? Economists have a term to describe the remaining level of unemployment that occurs even when the economy is healthy: they call it the natural rate of unemployment.</p>
<section id="the-long-run-the-natural-rate-of-unemployment" class="level3" data-number="7.6.1">
<h3 data-number="7.6.1" class="anchored" data-anchor-id="the-long-run-the-natural-rate-of-unemployment"><span class="header-section-number">7.6.1</span> The Long Run: The Natural Rate of Unemployment</h3>
<p>The natural rate of unemployment is not “natural” in the sense that water freezes at 32 degrees Fahrenheit or boils at 212 degrees Fahrenheit. It is not a physical and unchanging law of nature. Instead, it is only the “natural” rate because it is the unemployment rate that would result from the combination of economic, social, and political factors that exist at a time—assuming the economy was neither booming nor in recession.</p>
<p>These forces include the usual pattern of companies expanding and contracting their workforces in a dynamic economy, social and economic forces that affect the labor market, or public policies that affect either the eagerness of people to work or the willingness of businesses to hire. Let’s discuss these factors in more detail.</p>
</section>
<section id="frictional-unemployment" class="level3" data-number="7.6.2">
<h3 data-number="7.6.2" class="anchored" data-anchor-id="frictional-unemployment"><span class="header-section-number">7.6.2</span> Frictional Unemployment</h3>
<p>In a market economy, some companies are always going broke for a variety of reasons: old technology; poor management; good management that happened to make bad decisions; shifts in tastes of consumers so that less of the firm’s product is desired; a large customer who went broke; or tough domestic or foreign competitors. Conversely, other companies will be doing very well for just the opposite reasons and looking to hire more employees. In a perfect world, all of those who lost jobs would immediately find new ones. However, in the real world, even if the number of job seekers is equal to the number of job vacancies, it takes time to find out about new jobs, to interview and figure out if the new job is a good match, or perhaps to sell a house and buy another in proximity to a new job. Economists call the unemployment that occurs in the meantime, as workers move between jobs, frictional unemployment. Frictional unemployment is not inherently a bad thing. It takes time on part of both the employer and the individual to match those looking for employment with the correct job openings. For individuals and companies to be successful and productive, you want people to find the job for which they are best suited, not just the first job offered.</p>
<p>In the mid-2000s, before the 2008–2009 recession, it was true that about 7% of U.S. workers saw their jobs disappear in any three-month period. However, in periods of economic growth, these destroyed jobs are counterbalanced for the economy as a whole by a larger number of jobs created. In 2005, for example, there were typically about 7.5 million unemployed people at any given time in the U.S. economy. Even though about two-thirds of those unemployed people found a job in 14 weeks or fewer, the unemployment rate did not change much during the year, because those who found new jobs were largely offset by others who lost jobs.</p>
<p>Of course, it would be preferable if people who were losing jobs could immediately and easily move into newly created jobs, but in the real world, that is not possible. Someone who is laid off by a textile mill in South Carolina cannot turn around and immediately start working for a textile mill in California. Instead, the adjustment process happens in ripples. Some people find new jobs near their old ones, while others find that they must move to new locations. Some people can do a very similar job with a different company, while others must start new career paths. Some people may be near retirement and decide to look only for part-time work, while others want an employer that offers a long-term career path. The frictional unemployment that results from people moving between jobs in a dynamic economy may account for one to two percentage points of total unemployment.</p>
<p>The level of frictional unemployment will depend on how easy it is for workers to learn about alternative jobs, which may reflect the ease of communications about job prospects in the economy. The extent of frictional unemployment will also depend to some extent on how willing people are to move to new areas to find jobs—which in turn may depend on history and culture.</p>
<p>Frictional unemployment and the natural rate of unemployment also seem to depend on the age distribution of the population. [link] (b) showed that unemployment rates are typically lower for people between 25–54 years of age or aged 55 and over than they are for those who are younger. “Prime-age workers,” as those in the 25–54 age bracket are sometimes called, are typically at a place in their lives when they want to have a job and income arriving at all times. In addition, older workers who lose jobs may prefer to opt for retirement. By contrast, it is likely that a relatively high proportion of those who are under 25 will be trying out jobs and life options, and this leads to greater job mobility and hence higher frictional unemployment. Thus, a society with a relatively high proportion of young workers, like the U.S. beginning in the mid-1960s when Baby Boomers began entering the labor market, will tend to have a higher unemployment rate than a society with a higher proportion of its workers in older ages.</p>
</section>
<section id="structural-unemployment" class="level3" data-number="7.6.3">
<h3 data-number="7.6.3" class="anchored" data-anchor-id="structural-unemployment"><span class="header-section-number">7.6.3</span> Structural Unemployment</h3>
<p>Another factor that influences the natural rate of unemployment is the amount of structural unemployment. The structurally unemployed are individuals who have no jobs because they lack skills valued by the labor market, either because demand has shifted away from the skills they do have, or because they never learned any skills. An example of the former would be the unemployment among aerospace engineers after the U.S. space program downsized in the 1970s. An example of the latter would be high school dropouts.</p>
<p>Some people worry that technology causes structural unemployment. In the past, new technologies have put lower skilled employees out of work, but at the same time they create demand for higher skilled workers to use the new technologies. Education seems to be the key in minimizing the amount of structural unemployment. Individuals who have degrees can be retrained if they become structurally unemployed. For people with no skills and little education, that option is more limited.</p>
</section>
<section id="natural-unemployment-and-potential-real-gdp" class="level3" data-number="7.6.4">
<h3 data-number="7.6.4" class="anchored" data-anchor-id="natural-unemployment-and-potential-real-gdp"><span class="header-section-number">7.6.4</span> Natural Unemployment and Potential Real GDP</h3>
<p>The natural unemployment rate is related to two other important concepts: full employment and potential real GDP. Economists consider the economy to be at full employment when the actual unemployment rate is equal to the natural unemployment rate. When the economy is at full employment, real GDP is equal to potential real GDP.</p>
<p>By contrast, when the economy is below full employment, the unemployment rate is greater than the natural unemployment rate and real GDP is less than potential. Finally, when the economy is above full employment, then the unemployment rate is less than the natural unemployment rate and real GDP is greater than potential. Operating above potential is only possible for a short while, since it is analogous to all workers working overtime.</p>
</section>
<section id="productivity-shifts-and-the-natural-rate-of-unemployment" class="level3" data-number="7.6.5">
<h3 data-number="7.6.5" class="anchored" data-anchor-id="productivity-shifts-and-the-natural-rate-of-unemployment"><span class="header-section-number">7.6.5</span> Productivity Shifts and the Natural Rate of Unemployment</h3>
<p>Unexpected shifts in productivity can have a powerful effect on the natural rate of unemployment. Over time, workers' productivity determines the level of wages in an economy. After all, if a business paid workers more than could be justified by their productivity, the business will ultimately lose money and go bankrupt. Conversely, if a business tries to pay workers less than their productivity then, in a competitive labor market, other businesses will find it worthwhile to hire away those workers and pay them more.</p>
<p>However, adjustments of wages to productivity levels will not happen quickly or smoothly. Employers typically review wages only once or twice a year. In many modern jobs, it is difficult to measure productivity at the individual level. For example, how precisely would one measure the quantity produced by an accountant who is one of many people working in the tax department of a large corporation? Because productivity is difficult to observe, employers often determine wage increases based on recent experience with productivity. If productivity has been rising at, say, 2% per year, then wages rise at that level as well. However, when productivity changes unexpectedly, it can affect the natural rate of unemployment for a time.</p>
<p>The U.S. economy in the 1970s and 1990s provides two vivid examples of this process. In the 1970s, productivity growth slowed down unexpectedly (as we discussed in Economic Growth). For example, output per hour of U.S. workers in the business sector increased at an annual rate of 3.3% per year from 1960 to 1973, but only 0.8% from 1973 to 1982. <a href="#fig-U_007" class="quarto-xref">Figure&nbsp;<span>7.11</span></a> (a) illustrates the situation where the demand for labor—that is, the quantity of labor that business is willing to hire at any given wage—has been shifting out a little each year because of rising productivity, from <span class="math inline">\(D_0\)</span> to <span class="math inline">\(D_1\)</span> to <span class="math inline">\(D_2\)</span>.</p>
<p>As a result, equilibrium wages have been rising each year from W0 to <span class="math inline">\(W_1\)</span> to <span class="math inline">\(W_2\)</span>. However, when productivity unexpectedly slows down, the pattern of wage increases does not adjust right away. Wages keep rising each year from <span class="math inline">\(W_2\)</span> to <span class="math inline">\(W_3\)</span> to <span class="math inline">\(W_4\)</span>, but the demand for labor is no longer shifting up. A gap opens where the quantity of labor supplied at wage level <span class="math inline">\(W_4\)</span> is greater than the quantity demanded. The natural rate of unemployment rises. In the aftermath of this unexpectedly low productivity in the 1970s, the national unemployment rate did not fall below 7% from May, 1980 until 1986. Over time, the rise in wages will adjust to match the slower gains in productivity, and the unemployment rate will ease back down, but this process may take years.</p>
<div id="fig-U_007" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-U_007-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="Graphs/Unemployment/CNX_Econ_C21_015.jpg" class="lightbox" data-gallery="quarto-lightbox-gallery-12" title="Figure&nbsp;7.11: Panel (a) productivity is rising, increasing the demand for labor. Employers and workers become used to the pattern of wage increases. Then productivity suddenly stops increasing. However, the expectations of employers and workers for wage increases do not shift immediately, so wages keep rising as before. However, the demand for labor has not increased, so at wage W_4, unemployment exists where the quantity supplied of labor exceeds the quantity demanded. (b) The rate of productivity increase has been zero for a time, so employers and workers have come to accept the equilibrium wage level (W). Then productivity increases unexpectedly, shifting demand for labor from D_0 to D_1. At the wage (W), this means that the quantity demanded of labor exceeds the quantity supplied, and with job offers plentiful, the unemployment rate will be low."><img src="Graphs/Unemployment/CNX_Econ_C21_015.jpg" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-U_007-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7.11: Panel (a) productivity is rising, increasing the demand for labor. Employers and workers become used to the pattern of wage increases. Then productivity suddenly stops increasing. However, the expectations of employers and workers for wage increases do not shift immediately, so wages keep rising as before. However, the demand for labor has not increased, so at wage <span class="math inline">\(W_4\)</span>, unemployment exists where the quantity supplied of labor exceeds the quantity demanded. (b) The rate of productivity increase has been zero for a time, so employers and workers have come to accept the equilibrium wage level (W). Then productivity increases unexpectedly, shifting demand for labor from <span class="math inline">\(D_0\)</span> to <span class="math inline">\(D_1\)</span>. At the wage (W), this means that the quantity demanded of labor exceeds the quantity supplied, and with job offers plentiful, the unemployment rate will be low.
</figcaption>
</figure>
</div>
<p>The late 1990s provide an opposite example: instead of the surprise decline in productivity that occurred in the 1970s, productivity unexpectedly rose in the mid-1990s. The annual growth rate of real output per hour of labor increased from 1.7% from 1980–1995, to an annual rate of 2.6% from 1995–2001. Let’s simplify the situation a bit, so that the economic lesson of the story is easier to see graphically, and say that productivity had not been increasing at all in earlier years, so the intersection of the labor market was at point E in <a href="#fig-U_007" class="quarto-xref">Figure&nbsp;<span>7.11</span></a> (b), where the demand curve for labor (<span class="math inline">\(D_0\)</span>) intersects the supply curve for labor.</p>
<p>As a result, real wages were not increasing. Now, productivity jumps upward, which shifts the demand for labor out to the right, from <span class="math inline">\(D_0\)</span> to <span class="math inline">\(D_1\)</span>. At least for a time, however, wages are still set according to the earlier expectations of no productivity growth, so wages do not rise. The result is that at the prevailing wage level (W), the quantity of labor demanded (Qd) will for a time exceed the quantity of labor supplied (Qs), and unemployment will be very low—actually below the natural level of unemployment for a time. This pattern of unexpectedly high productivity helps to explain why the unemployment rate stayed below 4.5%—quite a low level by historical standards—from 1998 until after the U.S. economy had entered a recession in 2001.</p>
<p>Levels of unemployment will tend to be somewhat higher on average when productivity is unexpectedly low, and conversely, will tend to be somewhat lower on average when productivity is unexpectedly high. However, over time, wages do eventually adjust to reflect productivity levels.</p>
</section>
<section id="public-policy-and-the-natural-rate-of-unemployment" class="level3" data-number="7.6.6">
<h3 data-number="7.6.6" class="anchored" data-anchor-id="public-policy-and-the-natural-rate-of-unemployment"><span class="header-section-number">7.6.6</span> Public Policy and the Natural Rate of Unemployment</h3>
<p>Public policy can also have a powerful effect on the natural rate of unemployment. On the supply side of the labor market, public policies to assist the unemployed can affect how eager people are to find work. For example, if a worker who loses a job is guaranteed a generous package of unemployment insurance, welfare benefits, food stamps, and government medical benefits, then the opportunity cost of unemployment is lower and that worker will be less eager to seek a new job.</p>
<p>What seems to matter most is not just the amount of these benefits, but how long they last. A society that provides generous help for the unemployed that cuts off after, say, six months, may provide less of an incentive for unemployment than a society that provides less generous help that lasts for several years. Conversely, government assistance for job search or retraining can in some cases encourage people back to work sooner. See the Clear it Up to learn how the U.S. handles unemployment insurance.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>HOW DOES U.S. UNEMPLOYMENT INSURANCE WORK?</p>
<p>Unemployment insurance is a joint federal–state program that the federal government enacted in 1935. While the federal government sets minimum standards for the program, state governments conduct most of the administration.</p>
<p>The funding for the program is a federal tax collected from employers. The federal government requires tax collection on the first $7,000 in wages paid to each worker; however, states can choose to collect the tax on a higher amount if they wish, and 41 states have set a higher limit.</p>
<p>States can choose the length of time that they pay benefits, although most states limit unemployment benefits to 26 weeks—with extensions possible in times of especially high unemployment. The states then use the fund to pay benefits to those who become unemployed. Average unemployment benefits are equal to about one-third of the wage that the person earned in his or her previous job, but the level of unemployment benefits varies considerably across states.</p>
<table class="caption-top table">
<caption>Maximum Weekly Unemployment Benefits by State in 2017(Source: <a href="http://www.savingtoinvest.com/maximum-weekly-unemployment-benefits-by-state/" class="uri">http://www.savingtoinvest.com/maximum-weekly-unemployment-benefits-by-state/</a>)</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Bottom 10 States:</th>
<th style="text-align: left;">Lowest Benefit per Week</th>
<th style="text-align: left;">Top 10 States:</th>
<th style="text-align: left;">Highest Benefit per Week</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Delaware</td>
<td style="text-align: left;">$330</td>
<td style="text-align: left;">Massachusetts</td>
<td style="text-align: left;">$672</td>
</tr>
<tr class="even">
<td style="text-align: left;">Georgia</td>
<td style="text-align: left;">$330</td>
<td style="text-align: left;">Minnesota</td>
<td style="text-align: left;">$683</td>
</tr>
<tr class="odd">
<td style="text-align: left;">South Carolina</td>
<td style="text-align: left;">$326</td>
<td style="text-align: left;">Washington</td>
<td style="text-align: left;">$681</td>
</tr>
<tr class="even">
<td style="text-align: left;">Missouri</td>
<td style="text-align: left;">$320</td>
<td style="text-align: left;">New Jersey</td>
<td style="text-align: left;">$657</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Florida</td>
<td style="text-align: left;">$275</td>
<td style="text-align: left;">North Dakota</td>
<td style="text-align: left;">$633</td>
</tr>
<tr class="even">
<td style="text-align: left;">Tennessee</td>
<td style="text-align: left;">$275</td>
<td style="text-align: left;">Connecticut</td>
<td style="text-align: left;">$598</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Alabama</td>
<td style="text-align: left;">$265</td>
<td style="text-align: left;">Oregon</td>
<td style="text-align: left;">$590</td>
</tr>
<tr class="even">
<td style="text-align: left;">Louisiana</td>
<td style="text-align: left;">$247</td>
<td style="text-align: left;">Pennsylvania</td>
<td style="text-align: left;">$573</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Arizona</td>
<td style="text-align: left;">$240</td>
<td style="text-align: left;">Colorado</td>
<td style="text-align: left;">$568</td>
</tr>
<tr class="even">
<td style="text-align: left;">Mississippi</td>
<td style="text-align: left;">$235</td>
<td style="text-align: left;">Rhode Island</td>
<td style="text-align: left;">$566</td>
</tr>
</tbody>
</table>
<p>One other interesting thing to note about the classifications of unemployment—an individual does not have to collect unemployment benefits to be classified as unemployed. While there are statistics kept and studied relating to how many people are collecting unemployment insurance, this is not the source of unemployment rate information.</p>
</div>
</div>
<p>On the demand side of the labor market, government rules social institutions, and the presence of unions can affect the willingness of firms to hire. For example, if a government makes it hard for businesses to start up or to expand, by wrapping new businesses in bureaucratic red tape, then businesses will become more discouraged about hiring. Government regulations can make it harder to start a business by requiring that a new business obtain many permits and pay many fees, or by restricting the types and quality of products that a company can sell. Other government regulations, like zoning laws, may limit where companies can conduct business, or whether businesses are allowed to be open during evenings or on Sunday.</p>
<p>Whatever defenses may be offered for such laws in terms of social value—like the value some Christians place on not working on Sunday, or Orthodox Jews or highly observant Muslims on Saturday—these kinds of restrictions impose a barrier between some willing workers and other willing employers, and thus contribute to a higher natural rate of unemployment. Similarly, if government makes it difficult to fire or lay off workers, businesses may react by trying not to hire more workers than strictly necessary—since laying these workers off would be costly and difficult. High minimum wages may discourage businesses from hiring low-skill workers. Government rules may encourage and support powerful unions, which can then push up wages for union workers, but at a cost of discouraging businesses from hiring those workers.</p>
</section>
<section id="the-role-of-minimum-wages-do-they-cause-unemployment" class="level3" data-number="7.6.7">
<h3 data-number="7.6.7" class="anchored" data-anchor-id="the-role-of-minimum-wages-do-they-cause-unemployment"><span class="header-section-number">7.6.7</span> The Role of Minimum Wages: Do They Cause Unemployment?</h3>
<p>The discussion about the role of minimum wages is extremely controversial and there is no consensus in the economics profession about whether a minimum wage ultimately increases unemployment by "destroying" low wage paying jobs.</p>
<p>As of this writing (Jan.&nbsp;2021) President Biden is calling for an increase of the Federal minimum wage from USD 7.25 to USD 15.00. The Federal minimum wage has not changed in 12 years despite efforts under President Barack Obama to raise it from USD 7.25 to USD 8.50.</p>
<p>Under the Federal Fair Labor Standards Act, states and localities are permitted to set their own minimum wage rates, which will take precedence over the Federal minimum wage rate if they are higher. For this reason there are now a variety of minimum wages by State but also local municipality. If a municipality sets a minimum wage, it takes precedent over the Federal and State minimum wage as long as it is higher of course.</p>
<p>You can find a list of the current minimum wages by State on <a href="https://www.minimum-wage.org" class="uri">https://www.minimum-wage.org</a></p>
<p>Here are some municipalities with the highest minimum wages.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">State Name</th>
<th style="text-align: left;">Locality Name</th>
<th style="text-align: left;">Minimum Wage Rate</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Maine</td>
<td style="text-align: left;">Portland</td>
<td style="text-align: left;">$18.00 per hour</td>
</tr>
<tr class="even">
<td style="text-align: left;">California</td>
<td style="text-align: left;">Emeryville</td>
<td style="text-align: left;">$16.84 per hour</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Washington</td>
<td style="text-align: left;">Sea Tac</td>
<td style="text-align: left;">$16.57 per hour</td>
</tr>
<tr class="even">
<td style="text-align: left;">California</td>
<td style="text-align: left;">Mountain View</td>
<td style="text-align: left;">$16.30 per hour</td>
</tr>
<tr class="odd">
<td style="text-align: left;">California</td>
<td style="text-align: left;">San Francisco</td>
<td style="text-align: left;">$16.07 per hour</td>
</tr>
<tr class="even">
<td style="text-align: left;">California</td>
<td style="text-align: left;">Belmont</td>
<td style="text-align: left;">$15.90 per hour</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Washington</td>
<td style="text-align: left;">Seattle</td>
<td style="text-align: left;">$15.75 per hour</td>
</tr>
<tr class="even">
<td style="text-align: left;">California</td>
<td style="text-align: left;">Palo Alto</td>
<td style="text-align: left;">$15.65 per hour</td>
</tr>
<tr class="odd">
<td style="text-align: left;">California</td>
<td style="text-align: left;">San Mateo</td>
<td style="text-align: left;">$15.62 per hour</td>
</tr>
<tr class="even">
<td style="text-align: left;">California</td>
<td style="text-align: left;">El Cerrito</td>
<td style="text-align: left;">$15.61 per hour</td>
</tr>
<tr class="odd">
<td style="text-align: left;">California</td>
<td style="text-align: left;">San Jose</td>
<td style="text-align: left;">$15.45 per hour</td>
</tr>
<tr class="even">
<td style="text-align: left;">California</td>
<td style="text-align: left;">Milpitas</td>
<td style="text-align: left;">$15.40 per hour</td>
</tr>
<tr class="odd">
<td style="text-align: left;">California</td>
<td style="text-align: left;">Redwood City</td>
<td style="text-align: left;">$15.38 per hour</td>
</tr>
<tr class="even">
<td style="text-align: left;">California</td>
<td style="text-align: left;">Menlo Park</td>
<td style="text-align: left;">$15.25 per hour</td>
</tr>
<tr class="odd">
<td style="text-align: left;">California</td>
<td style="text-align: left;">Sonoma</td>
<td style="text-align: left;">$15.00 per hour</td>
</tr>
<tr class="even">
<td style="text-align: left;">New York</td>
<td style="text-align: left;">New York City</td>
<td style="text-align: left;">$15.00 per hour</td>
</tr>
<tr class="odd">
<td style="text-align: left;">California</td>
<td style="text-align: left;">Daily City</td>
<td style="text-align: left;">$15.00 per hour</td>
</tr>
<tr class="even">
<td style="text-align: left;">California</td>
<td style="text-align: left;">Richmond</td>
<td style="text-align: left;">$15.00 per hour</td>
</tr>
<tr class="odd">
<td style="text-align: left;">California</td>
<td style="text-align: left;">Half Moon Bay</td>
<td style="text-align: left;">$15.00 per hour</td>
</tr>
<tr class="even">
<td style="text-align: left;">D.C.</td>
<td style="text-align: left;">Washington DC</td>
<td style="text-align: left;">$15.00 per hour</td>
</tr>
</tbody>
</table>
<p>And here is a list of States that either have no State minimum wage or have simply adopted the Federal minimum wage rate:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">State Name</th>
<th style="text-align: left;">Minimum Wage Rate</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Alabama</td>
<td style="text-align: left;">$7.25 per hour</td>
</tr>
<tr class="even">
<td style="text-align: left;">Georgia</td>
<td style="text-align: left;">$7.25 per hour</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Idaho</td>
<td style="text-align: left;">$7.25 per hour</td>
</tr>
<tr class="even">
<td style="text-align: left;">Indiana</td>
<td style="text-align: left;">$7.25 per hour</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Iowa</td>
<td style="text-align: left;">$7.25 per hour</td>
</tr>
<tr class="even">
<td style="text-align: left;">Kansas</td>
<td style="text-align: left;">$7.25 per hour</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Kentucky</td>
<td style="text-align: left;">$7.25 per hour</td>
</tr>
<tr class="even">
<td style="text-align: left;">Louisiana</td>
<td style="text-align: left;">$7.25 per hour</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Mississippi</td>
<td style="text-align: left;">$7.25 per hour</td>
</tr>
<tr class="even">
<td style="text-align: left;">New Hampshire</td>
<td style="text-align: left;">$7.25 per hour</td>
</tr>
<tr class="odd">
<td style="text-align: left;">North Carolina</td>
<td style="text-align: left;">$7.25 per hour</td>
</tr>
<tr class="even">
<td style="text-align: left;">North Dakota</td>
<td style="text-align: left;">$7.25 per hour</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Oklahoma</td>
<td style="text-align: left;">$7.25 per hour</td>
</tr>
<tr class="even">
<td style="text-align: left;">Pennsylvania</td>
<td style="text-align: left;">$7.25 per hour</td>
</tr>
<tr class="odd">
<td style="text-align: left;">South Carolina</td>
<td style="text-align: left;">$7.25 per hour</td>
</tr>
<tr class="even">
<td style="text-align: left;">Tennessee</td>
<td style="text-align: left;">$7.25 per hour</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Texas</td>
<td style="text-align: left;">$7.25 per hour</td>
</tr>
<tr class="even">
<td style="text-align: left;">Utah</td>
<td style="text-align: left;">$7.25 per hour</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Virginia</td>
<td style="text-align: left;">$7.25 per hour</td>
</tr>
<tr class="even">
<td style="text-align: left;">Wisconsin</td>
<td style="text-align: left;">$7.25 per hour</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Wyoming</td>
<td style="text-align: left;">$7.25 per hour</td>
</tr>
<tr class="even">
<td style="text-align: left;">Puerto Rico</td>
<td style="text-align: left;">$6.55 per hour</td>
</tr>
</tbody>
</table>
<p>Economists are divided about the role of the minimum wage. Traditionally, the camp that is against the minimum wage is more rooted in economic theory while the camp that is in support of minimum wages tend to be economists that work more empirically (i.e., with data).</p>
<div id="mytopic">
<p><strong>Video - Monopsony Employers and Minimum Wages</strong></p>
<div style="position: relative; padding-bottom: 54.25%; height: 0; overflow: hidden; max-width: 100%; height: auto;">
    <iframe src="https://www.youtube.com/embed/FIiVE-mzmqY" frameborder="0" allowfullscreen="" style="position: absolute; top: 0; left: 0; width: 100%; height: 100%;"></iframe>
</div>
</div>
<p>The argument against a minimum wage is usually that it destroys jobs as a high minimum wage would make it unprofitable for employers to hire workers to do certain low productivity tasks (e.g., bagging groceries, wait staff at restaurants, ...). This would then hurt the poor, exactly the group that a minimum wage is supposed to support. There is also an important distinction to be made about the short term and the long term effects of minimum wages. See for instance the discussion here: <a href="https://voxeu.org/article/long-run-employment-effects-minimum-wage" class="uri">https://voxeu.org/article/long-run-employment-effects-minimum-wage</a></p>
<div id="mytopic">
<p><strong>Background Video 1 - Introduction to Labor Markets</strong></p>
<div style="position: relative; padding-bottom: 54.25%; height: 0; overflow: hidden; max-width: 100%; height: auto;">
    <iframe src="https://www.youtube.com/embed/Cm69zTuUzMI" frameborder="0" allowfullscreen="" style="position: absolute; top: 0; left: 0; width: 100%; height: 100%;"></iframe>
</div>
</div>
<p>In the Video you see a description of these theoretical arguments. You will also find a somewhat surprising result that if the government forces a wage increase (that is not too large) rational firms may end up hiring <strong>more</strong> workers IF the firm is a monopsony! Keep in mind that you only find this somewhat surprising result if the increase in the wage is not TOO large. It is clearly the case that if the government were to increase the minimum wage to say USD 1000, many jobs would disappear and firms would of course NOT hire more workers. If you need more background on how labor markets work, please check out these two additional videos or consult your Econ 201 (Microeconomics) textbooks.</p>
<div id="mytopic">
<p><strong>Background Video 2 - A Monopsonistic Market for Labor</strong></p>
<div style="position: relative; padding-bottom: 54.25%; height: 0; overflow: hidden; max-width: 100%; height: auto;">
    <iframe src="https://www.youtube.com/embed/vAaW15vwKUU" frameborder="0" allowfullscreen="" style="position: absolute; top: 0; left: 0; width: 100%; height: 100%;"></iframe>
</div>
</div>
<p>The argument in favor of minimum wages is that work should allow an employee to be able to afford a certain minimum living standard.This is often combined with equity arguments and discussions of fairness and dignity. There is a closely related discussion on <strong>living wages</strong> which are wages required to meet minimum standards given the local cost of living. MIT has developed a living wage calculator: <a href="https://livingwage.mit.edu" class="uri">https://livingwage.mit.edu</a> In addition, paying higher wages can also increase local economic activity as low income households are more likely to spend additional income which stimulates the economy.</p>
<p>While nobody is arguing that very large increases in minimum wages are "good", recent empirical work seems to suggest that more moderate increases of the minimum wage did not have negative labor market effects in the US between 1979--2016. (See the work by Cengiz, Dube, Lindner, and Zipperer in The Quarterly Journal of Economics, 2019, Volume 134, Issue 3 at <a href="https://doi.org/10.1093/qje/qjz014" class="uri">https://doi.org/10.1093/qje/qjz014</a>).</p>
<p>Some economists therefore suggest to link the minimum wage to average or median wages automatically so that repeatedly fighting over the minimum wage, which distracts attention from other important labor issues, can be avoided.</p>
<p>However, it is still true that overall the minimum wage literature seems to find negative employmentment effects from minimum wage increases. For workers who already work in low wage sectors, the effect of minimum wage increases on their employment is less clear cut though. (See the work by Neumark, D. &amp; Shirley, P. Myth or Measurement: What Does the New Minimum Wage Research Say about Minimum Wages and Job Loss in the United States? 2021, NBER Working Paper No.&nbsp;28388 at <a href="https://www.nber.org/papers/w28388" class="uri">https://www.nber.org/papers/w28388</a>).</p>
</section>
<section id="the-natural-rate-of-unemployment-in-recent-years" class="level3" data-number="7.6.8">
<h3 data-number="7.6.8" class="anchored" data-anchor-id="the-natural-rate-of-unemployment-in-recent-years"><span class="header-section-number">7.6.8</span> The Natural Rate of Unemployment in Recent Years</h3>
<p>The underlying economic, social, and political factors that determine the natural rate of unemployment can change over time, which means that the natural rate of unemployment can change over time, too.</p>
<p>Estimates by economists of the natural rate of unemployment in the U.S. economy in the early 2000s run at about 4.5 to 5.5%. This is a lower estimate than earlier. We outline three of the common reasons that economists propose for this change below.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>The internet has provided a remarkable new tool through which job seekers can find out about jobs at different companies and can make contact with relative ease. An internet search is far easier than trying to find a list of local employers and then hunting up phone numbers for all of their human resources departments, and requesting a list of jobs and application forms. Social networking sites such as LinkedIn have changed how people find work as well.</p>
<p>The growth of the temporary worker industry has probably helped to reduce the natural rate of unemployment. In the early 1980s, only about 0.5% of all workers held jobs through temp agencies. By the early 2000s, the figure had risen above 2%. Temp agencies can provide jobs for workers while they are looking for permanent work. They can also serve as a clearinghouse, helping workers find out about jobs with certain employers and getting a tryout with the employer. For many workers, a temp job is a stepping-stone to a permanent job that they might not have heard about or obtained any other way, so the growth of temp jobs will also tend to reduce frictional unemployment.</p>
<p>The aging of the “baby boom generation”—the especially large generation of Americans born between 1946 and 1964—meant that the proportion of young workers in the economy was relatively high in the 1970s, as the boomers entered the labor market, but is relatively low today. As we noted earlier, middle-aged and older workers are far more likely to experience low unemployment than younger workers, a factor that tends to reduce the natural rate of unemployment as the baby boomers age.</p>
</div>
</div>
<p>The combined result of these factors is that the natural rate of unemployment was on average lower in the 1990s and the early 2000s than in the 1980s. The 2008–2009 Great Recession pushed monthly unemployment rates up to 10% in late 2009. However, even at that time, the Congressional Budget Office was forecasting that by 2015, unemployment rates would fall back to about 5%. During the last four months of 2015 the unemployment rate held steady at 5.0%. Throughout 2016 and up through January 2017, the unemployment rate has remained at or slightly below 5%. As of the first quarter of 2017, the Congressional Budget Office estimates the natural rate to be 4.74%, and the measured unemployment rate for January 2017 is 4.8%.</p>
</section>
<section id="the-natural-rate-of-unemployment-in-europe" class="level3" data-number="7.6.9">
<h3 data-number="7.6.9" class="anchored" data-anchor-id="the-natural-rate-of-unemployment-in-europe"><span class="header-section-number">7.6.9</span> The Natural Rate of Unemployment in Europe</h3>
<p>By the standards of other high-income economies, the natural rate of unemployment in the U.S. economy appears relatively low. Through good economic years and bad, many European economies have had unemployment rates hovering near 10%, or even higher, since the 1970s. European rates of unemployment have been higher not because recessions in Europe have been deeper, but rather because the conditions underlying supply and demand for labor have been different in Europe, in a way that has created a much higher natural rate of unemployment.</p>
<p>Many European countries have a combination of generous welfare and unemployment benefits, together with nests of rules that impose additional costs on businesses when they hire. In addition, many countries have laws that require firms to give workers months of notice before laying them off and to provide substantial severance or retraining packages after laying them off. The legally required notice before laying off a worker can be more than three months in Spain, Germany, Denmark, and Belgium, and the legally required severance package can be as high as a year’s salary or more in Austria, Spain, Portugal, Italy, and Greece. Such laws will surely discourage laying off or firing current workers. However, when companies know that it will be difficult to fire or lay off workers, they also become hesitant about hiring in the first place.</p>
<p>We can attribute the typically higher levels of unemployment in many European countries in recent years, which have prevailed even when economies are growing at a solid pace, to the fact that the sorts of laws and regulations that lead to a high natural rate of unemployment are much more prevalent in Europe than in the United States.</p>
</section>
<section id="a-preview-of-policies-to-fight-unemployment" class="level3" data-number="7.6.10">
<h3 data-number="7.6.10" class="anchored" data-anchor-id="a-preview-of-policies-to-fight-unemployment"><span class="header-section-number">7.6.10</span> A Preview of Policies to Fight Unemployment</h3>
<p>The Government Budgets and Fiscal Policy and Macroeconomic Policy Around the World chapters provide a detailed discussion of how to fight unemployment, when we can discuss these policies in the context of the full array of macroeconomic goals and frameworks for analysis. However, even at this preliminary stage, it is useful to preview the main issues concerning policies to fight unemployment.</p>
<p>The remedy for unemployment will depend on the diagnosis. Cyclical unemployment is a short-term problem, caused because the economy is in a recession. Thus, the preferred solution will be to avoid or minimize recessions. As Government Budgets and Fiscal Policy discusses, governments can enact this policy by stimulating the overall buying power in the economy, so that firms perceive that sales and profits are possible, which makes them eager to hire.</p>
<p>Dealing with the natural rate of unemployment is trickier. In a market-oriented economy, firms will hire and fire workers. Governments cannot control this. Furthermore, the evolving age structure of the economy's population, or unexpected shifts in productivity are beyond a government's control and, will affect the natural rate of unemployment for a time. However, as the example of high ongoing unemployment rates for many European countries illustrates, government policy clearly can affect the natural rate of unemployment that will persist even when GDP is growing.</p>
<p>When a government enacts policies that will affect workers or employers, it must examine how these policies will affect the information and incentives employees and employers have to find one another. For example, the government may have a role to play in helping some of the unemployed with job searches. Governments may need to rethink the design of their programs that offer assistance to unemployed workers and protections to employed workers so that they will not unduly discourage the supply of labor. Similarly, governments may need to reassess rules that make it difficult for businesses to begin or to expand so that they will not unduly discourage the demand for labor. The message is not that governments should repeal all laws affecting labor markets, but only that when they enact such laws, a society that cares about unemployment will need to consider the tradeoffs involved.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
UNEMPLOYMENT AND THE GREAT RECESSION
</div>
</div>
<div class="callout-body-container callout-body">
<p>In the review of unemployment during and after the Great Recession at the outset of this chapter, we noted that unemployment tends to be a lagging indicator of business activity. This has historically been the case, and it is evident for all recessions that have taken place since the end of World War II. In brief, this results from the costs to employers of recruitment, hiring, and training workers. Those costs represent investments by firms in their work forces.</p>
<p>At the outset of a recession, when a firm realizes that demand for its product or service is not as strong as anticipated, it has an incentive to lay off workers. However, doing so runs the risk of losing those workers, and if the weak demand proves to be only temporary, the firm will be obliged to recruit, hire, and train new workers. Thus, firms tend to retain workers initially in a downturn. Similarly, as business begins to pick up when a recession is over, firms are not sure if the improvement will last. Rather than incur the costs of hiring and training new workers, they will wait, and perhaps resort to overtime work for existing workers, until they are confident that the recession is over.</p>
<p>Another point that we noted at the outset is that the duration of recoveries in employment following recessions has been longer following the last three recessions (going back to the early 1990s) than previously. Nir Jaimovich and Henry Siu have argued that these “jobless recoveries” are a consequence of job polarization – the disappearance of employment opportunities focused on “routine” tasks. Job polarization refers to the increasing concentration of employment in the highest- and lowest-wage occupations, as jobs in middle-skill occupations disappear. Job polarization is an outcome of technological progress in robotics, computing, and information and communication technology. The result of this progress is a decline in demand for labor in occupations that perform “routine” tasks – tasks that are limited in scope and can be performed by following a well-defined set of procedures – and hence a decline in the share of total employment that is composed of routine occupations. Jaimovich and Siu have shown that job polarization characterizes the aftermath of the last three recessions, and this appears to be responsible for the jobless recoveries.</p>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Key Concepts and Summary
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>The natural rate of unemployment is the rate of unemployment that the economic, social, and political forces in the economy would cause even when the economy is not in a recession.</li>
<li>These factors include the frictional unemployment that occurs when people either choose to change jobs or are put out of work for a time by the shifts of a dynamic and changing economy.</li>
<li>They also include any laws concerning conditions of hiring and firing that have the undesired side effect of discouraging job formation.</li>
<li>They also include structural unemployment, which occurs when demand shifts permanently away from a certain type of job skill.</li>
</ul>
</div>
</div>
<div class="callout callout-style-default callout-caution callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-21-contents" aria-controls="callout-21" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Self-Check Questions
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-21" class="callout-21-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ul>
<li><p>Is the increase in labor force participation rates among women better thought of as causing an increase in cyclical unemployment or an increase in the natural rate of unemployment? Why?</p></li>
<li><p>Many college students graduate from college before they have found a job. When graduates begin to look for a job, they are counted as what category of unemployed?</p></li>
<li><p>What term describes the remaining level of unemployment that occurs even when the economy is healthy?</p></li>
<li><p>What forces create the natural rate of unemployment for an economy?</p></li>
<li><p>Would you expect the natural rate of unemployment to be roughly the same in different countries?</p></li>
<li><p>Would you expect the natural rate of unemployment to remain the same within one country over the long run of several decades?</p></li>
<li><p>What is frictional unemployment? Give examples of frictional unemployment.</p></li>
<li><p>What is structural unemployment? Give examples of structural unemployment.</p></li>
<li><p>After several years of economic growth, would you expect the unemployment in an economy to be mainly cyclical or mainly due to the natural rate of unemployment? Why?</p></li>
<li><p>What type of unemployment (cyclical, frictional, or structural) applies to each of the following:</p>
<ul>
<li>landscapers laid off in response to drop in new housing construction during a recession.</li>
<li>coal miners laid off due to EPA regulations that shut down coal fired power</li>
<li>a financial analyst who quits his/her job in Chicago and is pursing similar work in Arizona</li>
<li>printers laid off due to drop in demand for printed catalogues and flyers as firms go the internet to promote an advertise their products.</li>
<li>factory workers in the U.S. laid off as the plants shut down and move to Mexico and Ireland.</li>
</ul></li>
<li><p>Under what condition would a decrease in unemployment be bad for the economy?</p></li>
<li><p>Under what condition would an increase in the unemployment rate be a positive sign?</p></li>
<li><p>As the baby boom generation retires, the ratio of retirees to workers will increase noticeably. How will this affect the Social Security program? How will this affect the standard of living of the average American?</p></li>
<li><p>Unemployment rates have been higher in many European countries in recent decades than in the United States. Is the main reason for this long-term difference in unemployment rates more likely to be cyclical unemployment or the natural rate of unemployment? Explain briefly.</p></li>
<li><p>Is it desirable to pursue a goal of zero unemployment? Why or why not?</p></li>
<li><p>Is it desirable to eliminate natural unemployment? Why or why not? Hint: Think about what our economy would look like today and what assumptions would have to be met to have a zero rate of natural unemployment.</p></li>
<li><p>The U.S. unemployment rate increased from 4.6% in July 2001 to 5.9% by June 2002. Without studying the subject in any detail, would you expect that a change of this kind is more likely to be due to cyclical unemployment or a change in the natural rate of unemployment? Why?</p></li>
</ul>
</div>
</div>
</div>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./ch6-InternationalTrade.html" class="pagination-link" aria-label="International Trade">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">International Trade</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./ch8-Inflation.html" class="pagination-link" aria-label="Inflation">
        <span class="nav-page-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Inflation</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Copyright 2024, Juergen Jung</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item compact">
    <a class="nav-link" href="https://juejung.github.io/">
      <i class="bi bi-github" role="img">
</i> 
    </a>
  </li>  
</ul>
    </div>
  </div>
</footer>
<script>var lightboxQuarto = GLightbox({"selector":".lightbox","openEffect":"zoom","loop":false,"closeEffect":"zoom","descPosition":"bottom"});
(function() {
  let previousOnload = window.onload;
  window.onload = () => {
    if (previousOnload) {
      previousOnload();
    }
    lightboxQuarto.on('slide_before_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      const href = trigger.getAttribute('href');
      if (href !== null) {
        const imgEl = window.document.querySelector(`a[href="${href}"] img`);
        if (imgEl !== null) {
          const srcAttr = imgEl.getAttribute("src");
          if (srcAttr && srcAttr.startsWith("data:")) {
            slideConfig.href = srcAttr;
          }
        }
      } 
    });
  
    lightboxQuarto.on('slide_after_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(slideNode);
      }
    });
  
  };
  
})();
          </script>




</body></html>