# Course Structure


-------------------------------------------------------------------------------------
# 1. Intro to R and Python
[R vs. Python comparison sheet](./Lecture1/Slides/RvsNumpy.html)

## 1.1 Installing and first steps 

[Slides](./Lecture1/Slides/Slides1_Basics.html)

* [r-script](./Lecture1/Slides/R/Script1.txt) 
* [python-script](./Lecture1/Slides/Python/Script1.txt)
* [Homework](./Lecture1/Homework/Homework1.html)  and homework solutions: [r-script](./Lecture1/Homework/R/Homework1.txt) and [python-script](./Lecture1/Homework/Python/Homework1.txt)

## 1.2 Plotting vectors and matrices
[Slides R](./Lecture2/Slides/Slides2_Plot_R.html),  [Slides Python](./Lecture2/Slides/Slides2_Plot_Python.html)
* [r-script](./Lecture2/Slides/R/Script2.txt) 
* [python-script](./Lecture2/Slides/Python/Script2.txt) 
* [Homework](./Lecture2/Homework/Homework2.html)  and homework solutions: [r-script](./Lecture2/Homework/R/Homework2.txt) and [python-script](./Lecture2/Homework/Python/Homework2.txt)
   
## 1.3 Repeating and branching: Loops and if-then commands   
[Slides R](./Lecture3/Slides/Slides3_Loop_R.html),  [Slides Python](./Lecture3/Slides/Slides3_Loop_Python.html)
* [r-script](./Lecture3/Slides/R/Script3.txt) 
* [python-script](./Lecture3/Slides/Python/Script3.txt)
* [Homework](./Lecture3/Homework/Homework3.html)  and homework solutions: [r-script](./Lecture3/Homework/R/Homework3.txt) and [python-script](./Lecture3/Homework/Python/Homework3.txt)
   
## 1.4 Import data from Excel or text files
[Slides](./Lecture4/Slides/Slides4_Data.html) 

* [Data_a.csv](./Lecture4/Slides/Lecture_4_Excel_a.csv), [Data_b.csv](./Lecture4/Slides/Lecture_4_Excel_b.csv), [Data_b.xlsx](./Lecture4/Slides/Lecture_4_Excel_b.xlsx)
* [r-script](./Lecture4/Slides/R/Script4.txt) 
* [python-script](./Lecture4/Slides/Python/Script4.txt), OLS function script: [myOLS.txt](./Lecture4/Slides/Python/myOLS.txt)
* [Homework](./Lecture4/Homework/Homework4.html)  and homework solutions: [r-script](./Lecture4/Homework/R/Homework4.txt) and [python-script](./Lecture4/Homework/Python/Homework4.txt)

## 1.5 Functions
[Slides](./Lecture5/Slides/Slides5_Functions.html) 

* [r-script](./Lecture5/Slides/R/Script5.txt)   [myFunctions.R](./Lecture5/Slides/R/myFunctions.txt)
* [python-script](./Lecture5/Slides/Python/Script5.txt) [myFunctions.py](./Lecture5/Slides/Python/myFunctions.txt)
* [Homework](./Lecture5/Homework/Homework5.html)  and homework solutions: [r-script](./Lecture5/Homework/R/Homework5.txt), [r-functions](./Lecture5/Homework/R/myfuncs.txt) and [python-script](./Lecture5/Homework/Python/Homework5.txt), [python-functions](./Lecture5/Homework/Python/myfuncs.txt)
 
   
-------------------------------------------------------------------------------------
# 2. Scientific programming 
   
   
## 2.1 Vector and matrix manipulation

[Slides R](./Lecture6/Slides/Slides6_Matrix_R.html),  [Slides Python](./Lecture6/Slides/Slides6_Matrix_Python.html)
* [r-script](./Lecture6/Slides/R/Script6.txt)   
* [python-script](./Lecture6/Slides/Python/Script6.txt) 
* [Homework](./Lecture6/Homework/Homework6.html)  and homework solutions: [r-script](./Lecture6/Homework/R/Homework6.txt) and [python-script](./Lecture6/Homework/Python/Homework6.txt)


## 2.2 Generating random numbers

[Slides R](./Lecture7/Slides/Slides7_Random_R.html),  [Slides Python](./Lecture7/Slides/Slides7_Random_Python.html)
* [r-script](./Lecture7/Slides/R/Script7.txt)   
* [python-script](./Lecture7/Slides/Python/Script7.txt) 
* [Homework](./Lecture7/Homework/Homework7.html)  and homework solutions: [r-script](./Lecture7/Homework/R/Homework7.txt) and [python-script](./Lecture6/Homework/Python/Homework7.txt)


## 2.3 Root-finding (Newton Raphson, Secant method, Bisection) 

[Slides R](./Lecture8/Slides/Slides8_Root_R.html),  [Slides Python](./Lecture8/Slides/Slides8_Root_Python.html)
* [r-script](./Lecture8/Slides/R/Script8.txt)   
* [python-script](./Lecture8/Slides/Python/Script8.txt) 
* [Homework](./Lecture8/Homework/Homework8.html)  and homework solutions: [r-script](./Lecture8/Homework/R/Homework8.txt) and [python-script](./Lecture8/Homework/Python/Homework8.txt)

## 2.4 Optimization routines (Newton, golden section, multivariate optimization)

[Slides R](./Lecture9/Slides/Slides9_Optimization_R.html),  [Slides Python](./Lecture9/Slides/Slides9_Optimization_Python.html)
* [r-script](./Lecture9/Slides/R/Script9.txt)   
* [python-script](./Lecture9/Slides/Python/Script9.txt)
* [Homework](./Lecture9/Homework/Homework9.html)  and homework solutions: [r-script](./Lecture9/Homework/R/Homework9.txt) and [python-script](./Lecture9/Homework/Python/Homework9.txt)

-------------------------------------------------------------------------------
# 3. Economic Applications
   
## 3.1 The cake eating problem

[Slides](./Lecture10/Slides/Slides10_Cake.html)
* [r-script](./Lecture10/Slides/R/Script10.txt)   
* [python-script](./Lecture10/Slides/Python/Script10.txt)
* [Homework](./Lecture10/Homework/Homework10.html)  and homework solutions: [r-script](./Lecture10/Homework/R/Homework10.txt) and [python-script](./Lecture10/Homework/Python/Homework10.txt)

## 3.2 Overlapping generations economy (Dynamic General Equilibrium)

[Slides](./Lecture11/Slides/Slides11_OLG_I.html)
* [r-script](./Lecture11/Slides/R/Script11.txt)   
* [python-script](./Lecture11/Slides/Python/Script11.txt)
* [Homework](./Lecture11/Homework/Homework11.html)  and homework solutions: [r-script](./Lecture11/Homework/R/Homework11.txt)