% Econ I Module
% Juergen Jung
% Towson University, 2012

--------------------------------------------------------------------------------
# An OLG model with labor-leisure choice

* OLG stands for overlapping generations
* This model allows for young and old agents
* We start with
    * Preferences
    * Technology
    * Government
    * Equilibrium
    
--------------------------------------------------------------------------------
# Preferences

* Agents live for 2 periods: young and old
* They value consumption when young $c_y$, leisure when young $1-l$ and
consumption when old $c_o$
* Their preferences are given via utility functions: $u_t(c_t)$
* Agents discount time with factor $\beta$
* Their life-time utility is:

$$ V(c_y, l,c_o) = u(c_y,l) + \beta \times u(c_o) $$

--------------------------------------------------------------------------------
# Technology

* Firms produce output $Y$ using input capital $K$ and labor $L$:

$$ Y(K,L) = A \times K^{0.3} \times L^{0.7} $$

--------------------------------------------------------------------------------
# Government

* The government collects lump sum taxes from households $\tau_{Lump}$, 
taxes on labor $\tau_L$ and capital $\tau_K$
* The government pays for gov't consumption $G$ and transfers to households 
$T_y$ and $T_o$

$$ G + T_y + T_o = L \times \tau_L + K \times \tau_K + \tau_{Lump} $$


--------------------------------------------------------------------------------
# Household problem

* HHs maximize $V(c_y,l,c_o)$ subject to their budget constraint in each period
$$ c_y + s = w  l + T_y $$
$$ c_o     = R  s + T_o $$

--------------------------------------------------------------------------------
# Equilibrium definition

* Given sequences of 
    * prices $\left\{w_t, R_t \right\}$ 
    * government policies $\left\{\tau_L, \tau_K, \tau_{Lump} \right\}$
and equilibrium is defined as an allocation of:
* sequences of $\left\{c_{y,t},l_t,c_{o,t},s_t\right\}$ so that
    * the HH max problem is solved
    * the firm maximization problem is solve
    * the gov't budget constraint clears


--------------------------------------------------------------------------------
# Functional forms and solutions

* Preferences are given as: $u(c_y,l) = log(c_y)+log(l)$ and $u(c_o)=log(c_o)$
* We can either set up a Lagrangian with two constraints or simply substitute
consumption out of the utilities using the BC. 
* We follow the second approach, since the form of the utility functions 
guarantees interior solutions
* Therefor we don't have to worry about corner solutions a la Kuhn-Tucker

--------------------------------------------------------------------------------
# Substitute in preferences

$$ max_s log(w  l + T_y - s) + log(1-l) + \beta  log(R  s + T_o) $$

* This is now a function in 2 choice variables $s$ and labor $l$
* Derive this function w.r.t. $s$ and labor $l$

$$ \frac{\partial V}{\partial s}: \frac{1}{w  l + T_y - s} =
\frac{\beta R}{R  s + T_o}$$

$$ \frac{\partial V}{\partial l}: \frac{w}{w  l + T_y - s} =
\frac{1}{1-l}$$

--------------------------------------------------------------------------------
# Solve for optimal $s^*$ and $l^*$

* 















































