<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.40">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>4&nbsp; Lab Chapter 4: Logistic Regression, LDA, QDA, and KNN – Machine Learning for Economics</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script><script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./ch5-resample-lab.html" rel="next">
<link href="./ch3-linreg-lab.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-549806ee2085284f45b00abea8c6df48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-58e300ad65a7421ed8ae8ddcd63ec7c5.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script src="site_libs/quarto-contrib/jquery-3.6.3/jquery-3.6.3.min.js"></script>
<script src="site_libs/quarto-contrib/code-fullscreen-1.0.0/code-fullscreen.js" defer="true"></script>
<link href="site_libs/quarto-contrib/code-fullscreen-1.0.0/code-fullscreen.css" rel="stylesheet">
<script src="site_libs/quarto-contrib/glightbox/glightbox.min.js"></script>
<link href="site_libs/quarto-contrib/glightbox/glightbox.min.css" rel="stylesheet">
<link href="site_libs/quarto-contrib/glightbox/lightbox.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./ch2-statlearning-lab.html"><strong>ISL LABS</strong></a></li><li class="breadcrumb-item"><a href="./ch4-classification-lab.html"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Lab Chapter 4: Logistic Regression, LDA, QDA, and KNN</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Machine Learning for Economics</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text"><strong>INTRODUCTION</strong></span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Course Administration and Introduction</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text"><strong>ISL LABS</strong></span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ch2-statlearning-lab.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Lab Chapter 2: Introduction to Python</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ch3-linreg-lab.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Lab Chapter 3: Linear Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ch4-classification-lab.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Lab Chapter 4: Logistic Regression, LDA, QDA, and KNN</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ch5-resample-lab.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Lab Chapter 5: Cross-Validation and the Bootstrap</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ch6-varselect-lab.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Lab Chapter 6: Linear Models and Regularization Methods</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ch7-nonlin-lab.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Lab Chapter 7: Non-Linear Modeling</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ch8-baggboost-lab.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Lab Chapter 8: Tree-Based Methods</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ch9-svm-lab.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Lab Chapter 9: Support Vector Machines</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ch10-deeplearning-lab.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Lab Chapter 10: Deep Learning</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ch11-surv-lab.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Lab Chapter 11: Survival Analysis</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ch12-unsup-lab.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Lab Chapter 12: Unsupervised Learning</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ch13-multipletest-lab.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Lab Chapter 13: Multiple Testing</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ch14-reinforcementlearning-lab.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Lab Chapter 14: Reinforcement Learning</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text"><strong>ML APPLICATIONS</strong></span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ml_ex_OLS.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Machine Learning: A First Example with OLS</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ml_ex_DoubleRobust.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Double Robust Estimation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ml_ex_DoubleDebiasedML.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Double Debiased Machine Learning</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false">
 <span class="menu-text"><strong>ML FRAMEWORKS</strong></span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ml_PytorchKeras.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Section Learning Objectives</span></span></a>
  </div>
</li>
      </ul>
  </li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#the-stock-market-data" id="toc-the-stock-market-data" class="nav-link active" data-scroll-target="#the-stock-market-data"><span class="header-section-number">4.1</span> The Stock Market Data</a></li>
  <li><a href="#logistic-regression" id="toc-logistic-regression" class="nav-link" data-scroll-target="#logistic-regression"><span class="header-section-number">4.2</span> Logistic Regression</a></li>
  <li><a href="#linear-discriminant-analysis" id="toc-linear-discriminant-analysis" class="nav-link" data-scroll-target="#linear-discriminant-analysis"><span class="header-section-number">4.3</span> Linear Discriminant Analysis</a></li>
  <li><a href="#quadratic-discriminant-analysis" id="toc-quadratic-discriminant-analysis" class="nav-link" data-scroll-target="#quadratic-discriminant-analysis"><span class="header-section-number">4.4</span> Quadratic Discriminant Analysis</a></li>
  <li><a href="#naive-bayes" id="toc-naive-bayes" class="nav-link" data-scroll-target="#naive-bayes"><span class="header-section-number">4.5</span> Naive Bayes</a></li>
  <li><a href="#k-nearest-neighbors" id="toc-k-nearest-neighbors" class="nav-link" data-scroll-target="#k-nearest-neighbors"><span class="header-section-number">4.6</span> K-Nearest Neighbors</a>
  <ul class="collapse">
  <li><a href="#tuning-parameters" id="toc-tuning-parameters" class="nav-link" data-scroll-target="#tuning-parameters"><span class="header-section-number">4.6.1</span> Tuning Parameters</a></li>
  <li><a href="#comparison-to-logistic-regression" id="toc-comparison-to-logistic-regression" class="nav-link" data-scroll-target="#comparison-to-logistic-regression"><span class="header-section-number">4.6.2</span> Comparison to Logistic Regression</a></li>
  </ul></li>
  <li><a href="#linear-and-poisson-regression-on-the-bikeshare-data" id="toc-linear-and-poisson-regression-on-the-bikeshare-data" class="nav-link" data-scroll-target="#linear-and-poisson-regression-on-the-bikeshare-data"><span class="header-section-number">4.7</span> Linear and Poisson Regression on the Bikeshare Data</a>
  <ul class="collapse">
  <li><a href="#linear-regression" id="toc-linear-regression" class="nav-link" data-scroll-target="#linear-regression"><span class="header-section-number">4.7.1</span> Linear Regression</a></li>
  <li><a href="#poisson-regression" id="toc-poisson-regression" class="nav-link" data-scroll-target="#poisson-regression"><span class="header-section-number">4.7.2</span> Poisson Regression</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./ch2-statlearning-lab.html"><strong>ISL LABS</strong></a></li><li class="breadcrumb-item"><a href="./ch4-classification-lab.html"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Lab Chapter 4: Logistic Regression, LDA, QDA, and KNN</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Lab Chapter 4: Logistic Regression, LDA, QDA, and KNN</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<!-- Lab Chapter 4: Logistic Regression, LDA, QDA, and KNN {{{1-->
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Section Learning Objectives
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>Logistic regression</li>
<li>LDA</li>
<li>QDA</li>
<li>KNN</li>
</ul>
</div>
</div>
<!--The Stock Market Data {{{2-->
<section id="the-stock-market-data" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="the-stock-market-data"><span class="header-section-number">4.1</span> The Stock Market Data</h2>
<p>In this lab we will examine the <code>Smarket</code> data, which is part of the <code>ISLP</code> library. This data set consists of percentage returns for the S&amp;P 500 stock index over 1,250 days, from the beginning of 2001 until the end of 2005. For each date, we have recorded the percentage returns for each of the five previous trading days, <code>Lag1</code> through <code>Lag5</code>. We have also recorded <code>Volume</code> (the number of shares traded on the previous day, in billions), <code>Today</code> (the percentage return on the date in question) and <code>Direction</code> (whether the market was <code>Up</code> or <code>Down</code> on this date).</p>
<p>We start by importing our libraries at this top level; these are all imports we have seen in previous labs.</p>
<div id="340e779f" class="cell" data-execution_count="1">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> matplotlib.pyplot <span class="im">import</span> subplots</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> statsmodels.api <span class="im">as</span> sm</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> ISLP <span class="im">import</span> load_data</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> ISLP.models <span class="im">import</span> (ModelSpec <span class="im">as</span> MS,</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>                         summarize)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We also collect together the new imports needed for this lab.</p>
<div id="3b50eda8" class="cell" data-execution_count="2">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> ISLP <span class="im">import</span> confusion_table</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> ISLP.models <span class="im">import</span> contrast</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.discriminant_analysis <span class="im">import</span> <span class="op">\</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>     (LinearDiscriminantAnalysis <span class="im">as</span> LDA,</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>      QuadraticDiscriminantAnalysis <span class="im">as</span> QDA)</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.naive_bayes <span class="im">import</span> GaussianNB</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.neighbors <span class="im">import</span> KNeighborsClassifier</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.preprocessing <span class="im">import</span> StandardScaler</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.model_selection <span class="im">import</span> train_test_split</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.linear_model <span class="im">import</span> LogisticRegression</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now we are ready to load the <code>Smarket</code> data.</p>
<div id="ed05069f" class="cell" data-execution_count="3">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>Smarket <span class="op">=</span> load_data(<span class="st">'Smarket'</span>)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>Smarket</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="3">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Year</th>
<th data-quarto-table-cell-role="th">Lag1</th>
<th data-quarto-table-cell-role="th">Lag2</th>
<th data-quarto-table-cell-role="th">Lag3</th>
<th data-quarto-table-cell-role="th">Lag4</th>
<th data-quarto-table-cell-role="th">Lag5</th>
<th data-quarto-table-cell-role="th">Volume</th>
<th data-quarto-table-cell-role="th">Today</th>
<th data-quarto-table-cell-role="th">Direction</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>2001</td>
<td>0.381</td>
<td>-0.192</td>
<td>-2.624</td>
<td>-1.055</td>
<td>5.010</td>
<td>1.19130</td>
<td>0.959</td>
<td>Up</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>2001</td>
<td>0.959</td>
<td>0.381</td>
<td>-0.192</td>
<td>-2.624</td>
<td>-1.055</td>
<td>1.29650</td>
<td>1.032</td>
<td>Up</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>2001</td>
<td>1.032</td>
<td>0.959</td>
<td>0.381</td>
<td>-0.192</td>
<td>-2.624</td>
<td>1.41120</td>
<td>-0.623</td>
<td>Down</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>2001</td>
<td>-0.623</td>
<td>1.032</td>
<td>0.959</td>
<td>0.381</td>
<td>-0.192</td>
<td>1.27600</td>
<td>0.614</td>
<td>Up</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>2001</td>
<td>0.614</td>
<td>-0.623</td>
<td>1.032</td>
<td>0.959</td>
<td>0.381</td>
<td>1.20570</td>
<td>0.213</td>
<td>Up</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">1245</td>
<td>2005</td>
<td>0.422</td>
<td>0.252</td>
<td>-0.024</td>
<td>-0.584</td>
<td>-0.285</td>
<td>1.88850</td>
<td>0.043</td>
<td>Up</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1246</td>
<td>2005</td>
<td>0.043</td>
<td>0.422</td>
<td>0.252</td>
<td>-0.024</td>
<td>-0.584</td>
<td>1.28581</td>
<td>-0.955</td>
<td>Down</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">1247</td>
<td>2005</td>
<td>-0.955</td>
<td>0.043</td>
<td>0.422</td>
<td>0.252</td>
<td>-0.024</td>
<td>1.54047</td>
<td>0.130</td>
<td>Up</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1248</td>
<td>2005</td>
<td>0.130</td>
<td>-0.955</td>
<td>0.043</td>
<td>0.422</td>
<td>0.252</td>
<td>1.42236</td>
<td>-0.298</td>
<td>Down</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">1249</td>
<td>2005</td>
<td>-0.298</td>
<td>0.130</td>
<td>-0.955</td>
<td>0.043</td>
<td>0.422</td>
<td>1.38254</td>
<td>-0.489</td>
<td>Down</td>
</tr>
</tbody>
</table>

<p>1250 rows × 9 columns</p>
</div>
</div>
</div>
<p>This gives a truncated listing of the data. We can see what the variable names are.</p>
<div id="99159bed" class="cell" data-execution_count="4">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>Smarket.columns</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="4">
<pre><code>Index(['Year', 'Lag1', 'Lag2', 'Lag3', 'Lag4', 'Lag5', 'Volume', 'Today',
       'Direction'],
      dtype='object')</code></pre>
</div>
</div>
<p>We compute the correlation matrix using the <code>corr()</code> method for data frames, which produces a matrix that contains all of the pairwise correlations among the variables.</p>
<p>The <code>pandas</code> library does not report a correlation for the <code>Direction</code> variable because it is qualitative. This is why <code>Smarket.corr()</code> by itself would throw a value error that looks something like:</p>
<pre><code>ValueError: could not convert string to float: 'Up'</code></pre>
<p>We therefore need to specify that correlations should only be calculated for <code>numeric</code> variables.</p>
<div id="dcfff3e4" class="cell" data-execution_count="5">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>Smarket.corr(numeric_only<span class="op">=</span><span class="va">True</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="5">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Year</th>
<th data-quarto-table-cell-role="th">Lag1</th>
<th data-quarto-table-cell-role="th">Lag2</th>
<th data-quarto-table-cell-role="th">Lag3</th>
<th data-quarto-table-cell-role="th">Lag4</th>
<th data-quarto-table-cell-role="th">Lag5</th>
<th data-quarto-table-cell-role="th">Volume</th>
<th data-quarto-table-cell-role="th">Today</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">Year</td>
<td>1.000000</td>
<td>0.029700</td>
<td>0.030596</td>
<td>0.033195</td>
<td>0.035689</td>
<td>0.029788</td>
<td>0.539006</td>
<td>0.030095</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Lag1</td>
<td>0.029700</td>
<td>1.000000</td>
<td>-0.026294</td>
<td>-0.010803</td>
<td>-0.002986</td>
<td>-0.005675</td>
<td>0.040910</td>
<td>-0.026155</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Lag2</td>
<td>0.030596</td>
<td>-0.026294</td>
<td>1.000000</td>
<td>-0.025897</td>
<td>-0.010854</td>
<td>-0.003558</td>
<td>-0.043383</td>
<td>-0.010250</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Lag3</td>
<td>0.033195</td>
<td>-0.010803</td>
<td>-0.025897</td>
<td>1.000000</td>
<td>-0.024051</td>
<td>-0.018808</td>
<td>-0.041824</td>
<td>-0.002448</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Lag4</td>
<td>0.035689</td>
<td>-0.002986</td>
<td>-0.010854</td>
<td>-0.024051</td>
<td>1.000000</td>
<td>-0.027084</td>
<td>-0.048414</td>
<td>-0.006900</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Lag5</td>
<td>0.029788</td>
<td>-0.005675</td>
<td>-0.003558</td>
<td>-0.018808</td>
<td>-0.027084</td>
<td>1.000000</td>
<td>-0.022002</td>
<td>-0.034860</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Volume</td>
<td>0.539006</td>
<td>0.040910</td>
<td>-0.043383</td>
<td>-0.041824</td>
<td>-0.048414</td>
<td>-0.022002</td>
<td>1.000000</td>
<td>0.014592</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Today</td>
<td>0.030095</td>
<td>-0.026155</td>
<td>-0.010250</td>
<td>-0.002448</td>
<td>-0.006900</td>
<td>-0.034860</td>
<td>0.014592</td>
<td>1.000000</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>As one would expect, the correlations between the lagged return variables and today’s return are close to zero. The only substantial correlation is between <code>Year</code> and <code>Volume</code>. By plotting the data we see that <code>Volume</code> is increasing over time. In other words, the average number of shares traded daily increased from 2001 to 2005.</p>
<div id="54bac03d" class="cell" data-execution_count="6">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>Smarket.plot(y<span class="op">=</span><span class="st">'Volume'</span>)<span class="op">;</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><a href="ch4-classification-lab_files/figure-html/cell-7-output-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-1"><img src="ch4-classification-lab_files/figure-html/cell-7-output-1.png" width="571" height="411" class="figure-img"></a></p>
</figure>
</div>
</div>
</div>
<!--Logistic Regression {{{2-->
</section>
<section id="logistic-regression" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="logistic-regression"><span class="header-section-number">4.2</span> Logistic Regression</h2>
<p>Next, we will fit a logistic regression model in order to predict <code>Direction</code> using <code>Lag1</code> through <code>Lag5</code> and <code>Volume</code>. The <code>sm.GLM()</code> function fits <em>generalized linear models</em>, a class of models that includes logistic regression. Alternatively, the function <code>sm.Logit()</code> fits a logistic regression model directly. The syntax of <code>sm.GLM()</code> is similar to that of <code>sm.OLS()</code>, except that we must pass in the argument <code>family=sm.families.Binomial()</code> in order to tell <code>statsmodels</code> to run a logistic regression rather than some other type of generalized linear model.</p>
<div id="94efe426" class="cell" data-execution_count="7">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>allvars <span class="op">=</span> Smarket.columns.drop([<span class="st">'Today'</span>, <span class="st">'Direction'</span>, <span class="st">'Year'</span>])</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>design <span class="op">=</span> MS(allvars)</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> design.fit_transform(Smarket)</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>y <span class="op">=</span> Smarket.Direction <span class="op">==</span> <span class="st">'Up'</span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>glm <span class="op">=</span> sm.GLM(y,</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>             X,</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>             family<span class="op">=</span>sm.families.Binomial())</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>results <span class="op">=</span> glm.fit()</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>summarize(results)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="7">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">coef</th>
<th data-quarto-table-cell-role="th">std err</th>
<th data-quarto-table-cell-role="th">z</th>
<th data-quarto-table-cell-role="th">P&gt;|z|</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">intercept</td>
<td>-0.1260</td>
<td>0.241</td>
<td>-0.523</td>
<td>0.601</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Lag1</td>
<td>-0.0731</td>
<td>0.050</td>
<td>-1.457</td>
<td>0.145</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Lag2</td>
<td>-0.0423</td>
<td>0.050</td>
<td>-0.845</td>
<td>0.398</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Lag3</td>
<td>0.0111</td>
<td>0.050</td>
<td>0.222</td>
<td>0.824</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Lag4</td>
<td>0.0094</td>
<td>0.050</td>
<td>0.187</td>
<td>0.851</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Lag5</td>
<td>0.0103</td>
<td>0.050</td>
<td>0.208</td>
<td>0.835</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Volume</td>
<td>0.1354</td>
<td>0.158</td>
<td>0.855</td>
<td>0.392</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>The smallest <em>p</em>-value here is associated with <code>Lag1</code>. The negative coefficient for this predictor suggests that if the market had a positive return yesterday, then it is less likely to go up today. However, at a value of 0.15, the <em>p</em>-value is still relatively large, and so there is no clear evidence of a real association between <code>Lag1</code> and <code>Direction</code>.</p>
<p>We use the <code>params</code> attribute of <code>results</code> in order to access just the coefficients for this fitted model.</p>
<div id="9958c151" class="cell" data-execution_count="8">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>results.params</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="8">
<pre><code>intercept   -0.126000
Lag1        -0.073074
Lag2        -0.042301
Lag3         0.011085
Lag4         0.009359
Lag5         0.010313
Volume       0.135441
dtype: float64</code></pre>
</div>
</div>
<p>Likewise we can use the <code>pvalues</code> attribute to access the <em>p</em>-values for the coefficients.</p>
<div id="c9d45aea" class="cell" data-execution_count="9">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>results.pvalues</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="9">
<pre><code>intercept    0.600700
Lag1         0.145232
Lag2         0.398352
Lag3         0.824334
Lag4         0.851445
Lag5         0.834998
Volume       0.392404
dtype: float64</code></pre>
</div>
</div>
<p>The <code>predict()</code> method of <code>results</code> can be used to predict the probability that the market will go up, given values of the predictors. This method returns predictions on the probability scale. If no data set is supplied to the <code>predict()</code> function, then the probabilities are computed for the training data that was used to fit the logistic regression model. As with linear regression, one can pass an optional <code>exog</code> argument consistent with a design matrix if desired. Here we have printed only the first ten probabilities.</p>
<div id="b0033709" class="cell" data-execution_count="10">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>probs <span class="op">=</span> results.predict()</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>probs[:<span class="dv">10</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="10">
<pre><code>array([0.50708413, 0.48146788, 0.48113883, 0.51522236, 0.51078116,
       0.50695646, 0.49265087, 0.50922916, 0.51761353, 0.48883778])</code></pre>
</div>
</div>
<p>In order to make a prediction as to whether the market will go up or down on a particular day, we must convert these predicted probabilities into class labels, <code>Up</code> or <code>Down</code>. The following two commands create a vector of class predictions based on whether the predicted probability of a market increase is greater than or less than 0.5.</p>
<div id="9f750f51" class="cell" data-execution_count="11">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>labels <span class="op">=</span> np.array([<span class="st">'Down'</span>]<span class="op">*</span><span class="dv">1250</span>)</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>labels[probs<span class="op">&gt;</span><span class="fl">0.5</span>] <span class="op">=</span> <span class="st">"Up"</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The <code>confusion_table()</code> function from the <code>ISLP</code> package summarizes these predictions, showing how many observations were correctly or incorrectly classified. Our function, which is adapted from a similar function in the module <code>sklearn.metrics</code>, transposes the resulting matrix and includes row and column labels. The <code>confusion_table()</code> function takes as first argument the predicted labels, and second argument the true labels.</p>
<div id="08fa5be6" class="cell" data-execution_count="12">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>confusion_table(labels, Smarket.Direction)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="12">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">Truth</th>
<th data-quarto-table-cell-role="th">Down</th>
<th data-quarto-table-cell-role="th">Up</th>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">Predicted</th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">Down</td>
<td>145</td>
<td>141</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Up</td>
<td>457</td>
<td>507</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>The diagonal elements of the confusion matrix indicate correct predictions, while the off-diagonals represent incorrect predictions. Hence our model correctly predicted that the market would go up on 507 days and that it would go down on 145 days, for a total of 507 + 145 = 652 correct predictions. The <code>np.mean()</code> function can be used to compute the fraction of days for which the prediction was correct. In this case, logistic regression correctly predicted the movement of the market 52.2% of the time.</p>
<div id="7f7b4c8a" class="cell" data-execution_count="13">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>(<span class="dv">507</span><span class="op">+</span><span class="dv">145</span>)<span class="op">/</span><span class="dv">1250</span>, np.mean(labels <span class="op">==</span> Smarket.Direction)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="13">
<pre><code>(0.5216, 0.5216)</code></pre>
</div>
</div>
<p>At first glance, it appears that the logistic regression model is working a little better than random guessing. However, this result is misleading because we trained and tested the model on the same set of 1,250 observations. In other words, <span class="math inline">\(100-52.2=47.8%\)</span> is the <em>training</em> error rate. As we have seen previously, the training error rate is often overly optimistic — it tends to underestimate the test error rate. In order to better assess the accuracy of the logistic regression model in this setting, we can fit the model using part of the data, and then examine how well it predicts the <em>held out</em> data. This will yield a more realistic error rate, in the sense that in practice we will be interested in our model’s performance not on the data that we used to fit the model, but rather on days in the future for which the market’s movements are unknown.</p>
<p>To implement this strategy, we first create a Boolean vector corresponding to the observations from 2001 through 2004. We then use this vector to create a held out data set of observations from 2005.</p>
<div id="0297d2d1" class="cell" data-execution_count="14">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>train <span class="op">=</span> (Smarket.Year <span class="op">&lt;</span> <span class="dv">2005</span>)</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>Smarket_train <span class="op">=</span> Smarket.loc[train]</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>Smarket_test <span class="op">=</span> Smarket.loc[<span class="op">~</span>train]</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>Smarket_test.shape</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="14">
<pre><code>(252, 9)</code></pre>
</div>
</div>
<p>The object <code>train</code> is a vector of 1,250 elements, corresponding to the observations in our data set. The elements of the vector that correspond to observations that occurred before 2005 are set to <code>True</code>, whereas those that correspond to observations in 2005 are set to <code>False</code>. Hence <code>train</code> is a <em>boolean</em> array, since its elements are <code>True</code> and <code>False</code>. Boolean arrays can be used to obtain a subset of the rows or columns of a data frame using the <code>loc</code> method. For instance, the command <code>Smarket.loc[train]</code> would pick out a submatrix of the stock market data set, corresponding only to the dates before 2005, since those are the ones for which the elements of <code>train</code> are <code>True</code>. The <code>~</code> symbol can be used to negate all of the elements of a Boolean vector. That is, <code>~train</code> is a vector similar to <code>train</code>, except that the elements that are <code>True</code> in <code>train</code> get swapped to <code>False</code> in <code>~train</code>, and vice versa. Therefore, <code>Smarket.loc[~train]</code> yields a subset of the rows of the data frame of the stock market data containing only the observations for which <code>train</code> is <code>False</code>. The output above indicates that there are 252 such observations.</p>
<p>We now fit a logistic regression model using only the subset of the observations that correspond to dates before 2005. We then obtain predicted probabilities of the stock market going up for each of the days in our test set — that is, for the days in 2005.</p>
<div id="2837a3bd" class="cell" data-execution_count="15">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>X_train, X_test <span class="op">=</span> X.loc[train], X.loc[<span class="op">~</span>train]</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>y_train, y_test <span class="op">=</span> y.loc[train], y.loc[<span class="op">~</span>train]</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>glm_train <span class="op">=</span> sm.GLM(y_train,</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>                   X_train,</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>                   family<span class="op">=</span>sm.families.Binomial())</span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>results <span class="op">=</span> glm_train.fit()</span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>probs <span class="op">=</span> results.predict(exog<span class="op">=</span>X_test)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Notice that we have trained and tested our model on two completely separate data sets: training was performed using only the dates before 2005, and testing was performed using only the dates in 2005.</p>
<p>Finally, we compare the predictions for 2005 to the actual movements of the market over that time period. We will first store the test and training labels (recall <code>y_test</code> is binary).</p>
<div id="d9cbbcaf" class="cell" data-execution_count="16">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>D <span class="op">=</span> Smarket.Direction</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>L_train, L_test <span class="op">=</span> D.loc[train], D.loc[<span class="op">~</span>train]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now we threshold the fitted probability at 50% to form our predicted labels.</p>
<div id="ecd292f4" class="cell" data-execution_count="17">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>labels <span class="op">=</span> np.array([<span class="st">'Down'</span>]<span class="op">*</span><span class="dv">252</span>)</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>labels[probs<span class="op">&gt;</span><span class="fl">0.5</span>] <span class="op">=</span> <span class="st">'Up'</span></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>confusion_table(labels, L_test)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="17">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">Truth</th>
<th data-quarto-table-cell-role="th">Down</th>
<th data-quarto-table-cell-role="th">Up</th>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">Predicted</th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">Down</td>
<td>77</td>
<td>97</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Up</td>
<td>34</td>
<td>44</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>The test accuracy is about 48% while the error rate is about 52%</p>
<div id="aa5d7e26" class="cell" data-execution_count="18">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>np.mean(labels <span class="op">==</span> L_test), np.mean(labels <span class="op">!=</span> L_test)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="18">
<pre><code>(0.4801587301587302, 0.5198412698412699)</code></pre>
</div>
</div>
<p>The <code>!=</code> notation means <em>not equal to</em>, and so the last command computes the test set error rate. The results are rather disappointing: the test error rate is 52%, which is worse than random guessing! Of course this result is not all that surprising, given that one would not generally expect to be able to use previous days’ returns to predict future market performance. (After all, if it were possible to do so, then the authors of this book would be out striking it rich rather than writing a statistics textbook.)</p>
<p>We recall that the logistic regression model had very underwhelming <em>p</em>-values associated with all of the predictors, and that the smallest <em>p</em>-value, though not very small, corresponded to <code>Lag1</code>. Perhaps by removing the variables that appear not to be helpful in predicting <code>Direction</code>, we can obtain a more effective model. After all, using predictors that have no relationship with the response tends to cause a deterioration in the test error rate (since such predictors cause an increase in variance without a corresponding decrease in bias), and so removing such predictors may in turn yield an improvement. Below we refit the logistic regression using just <code>Lag1</code> and <code>Lag2</code>, which seemed to have the highest predictive power in the original logistic regression model.</p>
<div id="42d560b6" class="cell" data-execution_count="19">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>model <span class="op">=</span> MS([<span class="st">'Lag1'</span>, <span class="st">'Lag2'</span>]).fit(Smarket)</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> model.transform(Smarket)</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>X_train, X_test <span class="op">=</span> X.loc[train], X.loc[<span class="op">~</span>train]</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>glm_train <span class="op">=</span> sm.GLM(y_train,</span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>                   X_train,</span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>                   family<span class="op">=</span>sm.families.Binomial())</span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a>results <span class="op">=</span> glm_train.fit()</span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a>probs <span class="op">=</span> results.predict(exog<span class="op">=</span>X_test)</span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a>labels <span class="op">=</span> np.array([<span class="st">'Down'</span>]<span class="op">*</span><span class="dv">252</span>)</span>
<span id="cb27-10"><a href="#cb27-10" aria-hidden="true" tabindex="-1"></a>labels[probs<span class="op">&gt;</span><span class="fl">0.5</span>] <span class="op">=</span> <span class="st">'Up'</span></span>
<span id="cb27-11"><a href="#cb27-11" aria-hidden="true" tabindex="-1"></a>confusion_table(labels, L_test)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="19">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">Truth</th>
<th data-quarto-table-cell-role="th">Down</th>
<th data-quarto-table-cell-role="th">Up</th>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">Predicted</th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">Down</td>
<td>35</td>
<td>35</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Up</td>
<td>76</td>
<td>106</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>Let’s evaluate the overall accuracy as well as the accuracy within the days when logistic regression predicts an increase.</p>
<div id="7e56b70c" class="cell" data-execution_count="20">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>(<span class="dv">35</span><span class="op">+</span><span class="dv">106</span>)<span class="op">/</span><span class="dv">252</span>,<span class="dv">106</span><span class="op">/</span>(<span class="dv">106</span><span class="op">+</span><span class="dv">76</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="20">
<pre><code>(0.5595238095238095, 0.5824175824175825)</code></pre>
</div>
</div>
<p>Now the results appear to be a little better: 56% of the daily movements have been correctly predicted. It is worth noting that in this case, a much simpler strategy of predicting that the market will increase every day will also be correct 56% of the time! Hence, in terms of overall error rate, the logistic regression method is no better than the naive approach. However, the confusion matrix shows that on days when logistic regression predicts an increase in the market, it has a 58% accuracy rate. This suggests a possible trading strategy of buying on days when the model predicts an increasing market, and avoiding trades on days when a decrease is predicted. Of course one would need to investigate more carefully whether this small improvement was real or just due to random chance.</p>
<p>Suppose that we want to predict the returns associated with particular values of <code>Lag1</code> and <code>Lag2</code>. In particular, we want to predict <code>Direction</code> on a day when <code>Lag1</code> and <code>Lag2</code> equal <span class="math inline">\(1.2\)</span> and <span class="math inline">\(1.1\)</span>, respectively, and on a day when they equal <span class="math inline">\(1.5\)</span> and <span class="math inline">\(-0.8\)</span>. We do this using the <code>predict()</code> function.</p>
<div id="0469bbb9" class="cell" data-execution_count="21">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>newdata <span class="op">=</span> pd.DataFrame({<span class="st">'Lag1'</span>:[<span class="fl">1.2</span>, <span class="fl">1.5</span>],</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>                        <span class="st">'Lag2'</span>:[<span class="fl">1.1</span>, <span class="op">-</span><span class="fl">0.8</span>]})<span class="op">;</span></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>newX <span class="op">=</span> model.transform(newdata)</span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>results.predict(newX)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="21">
<pre><code>0    0.479146
1    0.496094
dtype: float64</code></pre>
</div>
</div>
<!--Linear Discriminant Analysis {{{2-->
</section>
<section id="linear-discriminant-analysis" class="level2" data-number="4.3">
<h2 data-number="4.3" class="anchored" data-anchor-id="linear-discriminant-analysis"><span class="header-section-number">4.3</span> Linear Discriminant Analysis</h2>
<p>We begin by performing LDA on the <code>Smarket</code> data, using the function <code>LinearDiscriminantAnalysis()</code>, which we have abbreviated <code>LDA()</code>. We fit the model using only the observations before 2005.</p>
<div id="f19ec6cf" class="cell" data-execution_count="22">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>lda <span class="op">=</span> LDA(store_covariance<span class="op">=</span><span class="va">True</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Since the <code>LDA</code> estimator automatically adds an intercept, we should remove the column corresponding to the intercept in both <code>X_train</code> and <code>X_test</code>. We can also directly use the labels rather than the Boolean vectors <code>y_train</code>.</p>
<div id="6dd7a57d" class="cell" data-execution_count="23">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>X_train, X_test <span class="op">=</span> [M.drop(columns<span class="op">=</span>[<span class="st">'intercept'</span>])</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>                   <span class="cf">for</span> M <span class="kw">in</span> [X_train, X_test]]</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>lda.fit(X_train, L_train)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="23">
<style>#sk-container-id-1 {color: black;background-color: white;}#sk-container-id-1 pre{padding: 0;}#sk-container-id-1 div.sk-toggleable {background-color: white;}#sk-container-id-1 label.sk-toggleable__label {cursor: pointer;display: block;width: 100%;margin-bottom: 0;padding: 0.3em;box-sizing: border-box;text-align: center;}#sk-container-id-1 label.sk-toggleable__label-arrow:before {content: "▸";float: left;margin-right: 0.25em;color: #696969;}#sk-container-id-1 label.sk-toggleable__label-arrow:hover:before {color: black;}#sk-container-id-1 div.sk-estimator:hover label.sk-toggleable__label-arrow:before {color: black;}#sk-container-id-1 div.sk-toggleable__content {max-height: 0;max-width: 0;overflow: hidden;text-align: left;background-color: #f0f8ff;}#sk-container-id-1 div.sk-toggleable__content pre {margin: 0.2em;color: black;border-radius: 0.25em;background-color: #f0f8ff;}#sk-container-id-1 input.sk-toggleable__control:checked~div.sk-toggleable__content {max-height: 200px;max-width: 100%;overflow: auto;}#sk-container-id-1 input.sk-toggleable__control:checked~label.sk-toggleable__label-arrow:before {content: "▾";}#sk-container-id-1 div.sk-estimator input.sk-toggleable__control:checked~label.sk-toggleable__label {background-color: #d4ebff;}#sk-container-id-1 div.sk-label input.sk-toggleable__control:checked~label.sk-toggleable__label {background-color: #d4ebff;}#sk-container-id-1 input.sk-hidden--visually {border: 0;clip: rect(1px 1px 1px 1px);clip: rect(1px, 1px, 1px, 1px);height: 1px;margin: -1px;overflow: hidden;padding: 0;position: absolute;width: 1px;}#sk-container-id-1 div.sk-estimator {font-family: monospace;background-color: #f0f8ff;border: 1px dotted black;border-radius: 0.25em;box-sizing: border-box;margin-bottom: 0.5em;}#sk-container-id-1 div.sk-estimator:hover {background-color: #d4ebff;}#sk-container-id-1 div.sk-parallel-item::after {content: "";width: 100%;border-bottom: 1px solid gray;flex-grow: 1;}#sk-container-id-1 div.sk-label:hover label.sk-toggleable__label {background-color: #d4ebff;}#sk-container-id-1 div.sk-serial::before {content: "";position: absolute;border-left: 1px solid gray;box-sizing: border-box;top: 0;bottom: 0;left: 50%;z-index: 0;}#sk-container-id-1 div.sk-serial {display: flex;flex-direction: column;align-items: center;background-color: white;padding-right: 0.2em;padding-left: 0.2em;position: relative;}#sk-container-id-1 div.sk-item {position: relative;z-index: 1;}#sk-container-id-1 div.sk-parallel {display: flex;align-items: stretch;justify-content: center;background-color: white;position: relative;}#sk-container-id-1 div.sk-item::before, #sk-container-id-1 div.sk-parallel-item::before {content: "";position: absolute;border-left: 1px solid gray;box-sizing: border-box;top: 0;bottom: 0;left: 50%;z-index: -1;}#sk-container-id-1 div.sk-parallel-item {display: flex;flex-direction: column;z-index: 1;position: relative;background-color: white;}#sk-container-id-1 div.sk-parallel-item:first-child::after {align-self: flex-end;width: 50%;}#sk-container-id-1 div.sk-parallel-item:last-child::after {align-self: flex-start;width: 50%;}#sk-container-id-1 div.sk-parallel-item:only-child::after {width: 0;}#sk-container-id-1 div.sk-dashed-wrapped {border: 1px dashed gray;margin: 0 0.4em 0.5em 0.4em;box-sizing: border-box;padding-bottom: 0.4em;background-color: white;}#sk-container-id-1 div.sk-label label {font-family: monospace;font-weight: bold;display: inline-block;line-height: 1.2em;}#sk-container-id-1 div.sk-label-container {text-align: center;}#sk-container-id-1 div.sk-container {/* jupyter's `normalize.less` sets `[hidden] { display: none; }` but bootstrap.min.css set `[hidden] { display: none !important; }` so we also need the `!important` here to be able to override the default hidden behavior on the sphinx rendered scikit-learn.org. See: https://github.com/scikit-learn/scikit-learn/issues/21755 */display: inline-block !important;position: relative;}#sk-container-id-1 div.sk-text-repr-fallback {display: none;}</style><div id="sk-container-id-1" class="sk-top-container"><div class="sk-text-repr-fallback"><pre>LinearDiscriminantAnalysis(store_covariance=True)</pre><b>In a Jupyter environment, please rerun this cell to show the HTML representation or trust the notebook. <br>On GitHub, the HTML representation is unable to render, please try loading this page with nbviewer.org.</b></div><div class="sk-container" hidden=""><div class="sk-item"><div class="sk-estimator sk-toggleable"><input class="sk-toggleable__control sk-hidden--visually" id="sk-estimator-id-1" type="checkbox" checked=""><label for="sk-estimator-id-1" class="sk-toggleable__label sk-toggleable__label-arrow">LinearDiscriminantAnalysis</label><div class="sk-toggleable__content"><pre>LinearDiscriminantAnalysis(store_covariance=True)</pre></div></div></div></div></div>
</div>
</div>
<p>Here we have used the list comprehensions introduced in Section 3.6.4. Looking at our first line above, we see that the right-hand side is a list of length two. This is because the code <code>for M in [X_train, X_test]</code> iterates over a list of length two. While here we loop over a list, the list comprehension method works when looping over any iterable object. We then apply the <code>drop()</code> method to each element in the iteration, collecting the result in a list. The left-hand side tells <code>Python</code> to unpack this list of length two, assigning its elements to the variables <code>X_train</code> and <code>X_test</code>. Of course, this overwrites the previous values of <code>X_train</code> and <code>X_test</code>.</p>
<p>Having fit the model, we can extract the means in the two classes with the <code>means_</code> attribute. These are the average of each predictor within each class, and are used by LDA as estimates of <span class="math inline">\(\mu_k\)</span>. These suggest that there is a tendency for the previous 2 days’ returns to be negative on days when the market increases, and a tendency for the previous days’ returns to be positive on days when the market declines.</p>
<div id="c1df8283" class="cell" data-execution_count="24">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>lda.means_</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="24">
<pre><code>array([[ 0.04279022,  0.03389409],
       [-0.03954635, -0.03132544]])</code></pre>
</div>
</div>
<p>The estimated prior probabilities are stored in the <code>priors_</code> attribute. The package <code>sklearn</code> typically uses this trailing <code>_</code> to denote a quantity estimated when using the <code>fit()</code> method. We can be sure of which entry corresponds to which label by looking at the <code>classes_</code> attribute.</p>
<div id="2c2ef7b7" class="cell" data-execution_count="25">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>lda.classes_</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="25">
<pre><code>array(['Down', 'Up'], dtype='&lt;U4')</code></pre>
</div>
</div>
<p>The LDA output indicates that <span class="math inline">\(\hat\pi_{Down}=0.492\)</span> and <span class="math inline">\(\hat\pi_{Up}=0.508\)</span>.</p>
<div id="0d64adc3" class="cell" data-execution_count="26">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>lda.priors_</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="26">
<pre><code>array([0.49198397, 0.50801603])</code></pre>
</div>
</div>
<p>The linear discriminant vectors can be found in the <code>scalings_</code> attribute:</p>
<div id="e074e80e" class="cell" data-execution_count="27">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>lda.scalings_</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="27">
<pre><code>array([[-0.64201904],
       [-0.51352928]])</code></pre>
</div>
</div>
<p>These values provide the linear combination of <code>Lag1</code> and <code>Lag2</code> that are used to form the LDA decision rule. In other words, these are the multipliers of the elements of <span class="math inline">\(X=x\)</span> in (4.24). If $-0.64<code>Lag1</code> - 0.51 <code>Lag2</code> $ is large, then the LDA classifier will predict a market increase, and if it is small, then the LDA classifier will predict a market decline.</p>
<div id="77fb1f11" class="cell" data-execution_count="28">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>lda_pred <span class="op">=</span> lda.predict(X_test)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>As we observed in our comparison of classification methods (Section 4.5), the LDA and logistic regression predictions are almost identical.</p>
<div id="b4654394" class="cell" data-execution_count="29">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>confusion_table(lda_pred, L_test)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="29">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">Truth</th>
<th data-quarto-table-cell-role="th">Down</th>
<th data-quarto-table-cell-role="th">Up</th>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">Predicted</th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">Down</td>
<td>35</td>
<td>35</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Up</td>
<td>76</td>
<td>106</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>We can also estimate the probability of each class for each point in a training set. Applying a 50% threshold to the posterior probabilities of being in class 1 allows us to recreate the predictions contained in <code>lda_pred</code>.</p>
<div id="11f3eaf9" class="cell" data-execution_count="30">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>lda_prob <span class="op">=</span> lda.predict_proba(X_test)</span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>np.<span class="bu">all</span>(</span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>       np.where(lda_prob[:,<span class="dv">1</span>] <span class="op">&gt;=</span> <span class="fl">0.5</span>, <span class="st">'Up'</span>,<span class="st">'Down'</span>) <span class="op">==</span> lda_pred</span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a>       )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="30">
<pre><code>True</code></pre>
</div>
</div>
<p>Above, we used the <code>np.where()</code> function that creates an array with value <code>'Up'</code> for indices where the second column of <code>lda_prob</code> (the estimated posterior probability of <code>'Up'</code>) is greater than 0.5. For problems with more than two classes the labels are chosen as the class whose posterior probability is highest:</p>
<div id="021d431e" class="cell" data-execution_count="31">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>np.<span class="bu">all</span>(</span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>       [lda.classes_[i] <span class="cf">for</span> i <span class="kw">in</span> np.argmax(lda_prob, <span class="dv">1</span>)] <span class="op">==</span> lda_pred</span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a>       )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="31">
<pre><code>True</code></pre>
</div>
</div>
<p>If we wanted to use a posterior probability threshold other than 50% in order to make predictions, then we could easily do so. For instance, suppose that we wish to predict a market decrease only if we are very certain that the market will indeed decrease on that day — say, if the posterior probability is at least 90%. We know that the first column of <code>lda_prob</code> corresponds to the label <code>Down</code> after having checked the <code>classes_</code> attribute, hence we use the column index 0 rather than 1 as we did above.</p>
<div id="24314eb2" class="cell" data-execution_count="32">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>np.<span class="bu">sum</span>(lda_prob[:,<span class="dv">0</span>] <span class="op">&gt;</span> <span class="fl">0.9</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="32">
<pre><code>0</code></pre>
</div>
</div>
<p>No days in 2005 meet that threshold! In fact, the greatest posterior probability of decrease in all of 2005 was 52.02%.</p>
<p>The LDA classifier above is the first classifier from the <code>sklearn</code> library. We will use several other objects from this library. The objects follow a common structure that simplifies tasks such as cross-validation, which we will see in Chapter 5. Specifically, the methods first create a generic classifier without referring to any data. This classifier is then fit to data with the <code>fit()</code> method and predictions are always produced with the <code>predict()</code> method. This pattern of first instantiating the classifier, followed by fitting it, and then producing predictions is an explicit design choice of <code>sklearn</code>. This uniformity makes it possible to cleanly copy the classifier so that it can be fit on different data; e.g.&nbsp;different training sets arising in cross-validation. This standard pattern also allows for a predictable formation of workflows.</p>
<!--Quadratic Discriminant Analysis {{{2-->
</section>
<section id="quadratic-discriminant-analysis" class="level2" data-number="4.4">
<h2 data-number="4.4" class="anchored" data-anchor-id="quadratic-discriminant-analysis"><span class="header-section-number">4.4</span> Quadratic Discriminant Analysis</h2>
<p>We will now fit a QDA model to the <code>Smarket</code> data. QDA is implemented via <code>QuadraticDiscriminantAnalysis()</code> in the <code>sklearn</code> package, which we abbreviate to <code>QDA()</code>. The syntax is very similar to <code>LDA()</code>.</p>
<div id="e8fda5f3" class="cell" data-execution_count="33">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>qda <span class="op">=</span> QDA(store_covariance<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>qda.fit(X_train, L_train)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="33">
<style>#sk-container-id-2 {color: black;background-color: white;}#sk-container-id-2 pre{padding: 0;}#sk-container-id-2 div.sk-toggleable {background-color: white;}#sk-container-id-2 label.sk-toggleable__label {cursor: pointer;display: block;width: 100%;margin-bottom: 0;padding: 0.3em;box-sizing: border-box;text-align: center;}#sk-container-id-2 label.sk-toggleable__label-arrow:before {content: "▸";float: left;margin-right: 0.25em;color: #696969;}#sk-container-id-2 label.sk-toggleable__label-arrow:hover:before {color: black;}#sk-container-id-2 div.sk-estimator:hover label.sk-toggleable__label-arrow:before {color: black;}#sk-container-id-2 div.sk-toggleable__content {max-height: 0;max-width: 0;overflow: hidden;text-align: left;background-color: #f0f8ff;}#sk-container-id-2 div.sk-toggleable__content pre {margin: 0.2em;color: black;border-radius: 0.25em;background-color: #f0f8ff;}#sk-container-id-2 input.sk-toggleable__control:checked~div.sk-toggleable__content {max-height: 200px;max-width: 100%;overflow: auto;}#sk-container-id-2 input.sk-toggleable__control:checked~label.sk-toggleable__label-arrow:before {content: "▾";}#sk-container-id-2 div.sk-estimator input.sk-toggleable__control:checked~label.sk-toggleable__label {background-color: #d4ebff;}#sk-container-id-2 div.sk-label input.sk-toggleable__control:checked~label.sk-toggleable__label {background-color: #d4ebff;}#sk-container-id-2 input.sk-hidden--visually {border: 0;clip: rect(1px 1px 1px 1px);clip: rect(1px, 1px, 1px, 1px);height: 1px;margin: -1px;overflow: hidden;padding: 0;position: absolute;width: 1px;}#sk-container-id-2 div.sk-estimator {font-family: monospace;background-color: #f0f8ff;border: 1px dotted black;border-radius: 0.25em;box-sizing: border-box;margin-bottom: 0.5em;}#sk-container-id-2 div.sk-estimator:hover {background-color: #d4ebff;}#sk-container-id-2 div.sk-parallel-item::after {content: "";width: 100%;border-bottom: 1px solid gray;flex-grow: 1;}#sk-container-id-2 div.sk-label:hover label.sk-toggleable__label {background-color: #d4ebff;}#sk-container-id-2 div.sk-serial::before {content: "";position: absolute;border-left: 1px solid gray;box-sizing: border-box;top: 0;bottom: 0;left: 50%;z-index: 0;}#sk-container-id-2 div.sk-serial {display: flex;flex-direction: column;align-items: center;background-color: white;padding-right: 0.2em;padding-left: 0.2em;position: relative;}#sk-container-id-2 div.sk-item {position: relative;z-index: 1;}#sk-container-id-2 div.sk-parallel {display: flex;align-items: stretch;justify-content: center;background-color: white;position: relative;}#sk-container-id-2 div.sk-item::before, #sk-container-id-2 div.sk-parallel-item::before {content: "";position: absolute;border-left: 1px solid gray;box-sizing: border-box;top: 0;bottom: 0;left: 50%;z-index: -1;}#sk-container-id-2 div.sk-parallel-item {display: flex;flex-direction: column;z-index: 1;position: relative;background-color: white;}#sk-container-id-2 div.sk-parallel-item:first-child::after {align-self: flex-end;width: 50%;}#sk-container-id-2 div.sk-parallel-item:last-child::after {align-self: flex-start;width: 50%;}#sk-container-id-2 div.sk-parallel-item:only-child::after {width: 0;}#sk-container-id-2 div.sk-dashed-wrapped {border: 1px dashed gray;margin: 0 0.4em 0.5em 0.4em;box-sizing: border-box;padding-bottom: 0.4em;background-color: white;}#sk-container-id-2 div.sk-label label {font-family: monospace;font-weight: bold;display: inline-block;line-height: 1.2em;}#sk-container-id-2 div.sk-label-container {text-align: center;}#sk-container-id-2 div.sk-container {/* jupyter's `normalize.less` sets `[hidden] { display: none; }` but bootstrap.min.css set `[hidden] { display: none !important; }` so we also need the `!important` here to be able to override the default hidden behavior on the sphinx rendered scikit-learn.org. See: https://github.com/scikit-learn/scikit-learn/issues/21755 */display: inline-block !important;position: relative;}#sk-container-id-2 div.sk-text-repr-fallback {display: none;}</style><div id="sk-container-id-2" class="sk-top-container"><div class="sk-text-repr-fallback"><pre>QuadraticDiscriminantAnalysis(store_covariance=True)</pre><b>In a Jupyter environment, please rerun this cell to show the HTML representation or trust the notebook. <br>On GitHub, the HTML representation is unable to render, please try loading this page with nbviewer.org.</b></div><div class="sk-container" hidden=""><div class="sk-item"><div class="sk-estimator sk-toggleable"><input class="sk-toggleable__control sk-hidden--visually" id="sk-estimator-id-2" type="checkbox" checked=""><label for="sk-estimator-id-2" class="sk-toggleable__label sk-toggleable__label-arrow">QuadraticDiscriminantAnalysis</label><div class="sk-toggleable__content"><pre>QuadraticDiscriminantAnalysis(store_covariance=True)</pre></div></div></div></div></div>
</div>
</div>
<p>The <code>QDA()</code> function will again compute <code>means_</code> and <code>priors_</code>.</p>
<div id="88cfa917" class="cell" data-execution_count="34">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>qda.means_, qda.priors_</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="34">
<pre><code>(array([[ 0.04279022,  0.03389409],
        [-0.03954635, -0.03132544]]),
 array([0.49198397, 0.50801603]))</code></pre>
</div>
</div>
<p>The <code>QDA()</code> classifier will estimate one covariance per class. Here is the estimated covariance in the first class:</p>
<div id="7794d3bd" class="cell" data-execution_count="35">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a>qda.covariance_[<span class="dv">0</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="35">
<pre><code>array([[ 1.50662277, -0.03924806],
       [-0.03924806,  1.53559498]])</code></pre>
</div>
</div>
<p>The output contains the group means. But it does not contain the coefficients of the linear discriminants, because the QDA classifier involves a quadratic, rather than a linear, function of the predictors. The <code>predict()</code> function works in exactly the same fashion as for LDA.</p>
<div id="aa82cabe" class="cell" data-execution_count="36">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a>qda_pred <span class="op">=</span> qda.predict(X_test)</span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a>confusion_table(qda_pred, L_test)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="36">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">Truth</th>
<th data-quarto-table-cell-role="th">Down</th>
<th data-quarto-table-cell-role="th">Up</th>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">Predicted</th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">Down</td>
<td>30</td>
<td>20</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Up</td>
<td>81</td>
<td>121</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>Interestingly, the QDA predictions are accurate almost 60% of the time, even though the 2005 data was not used to fit the model.</p>
<div id="a6733dd7" class="cell" data-execution_count="37">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a>np.mean(qda_pred <span class="op">==</span> L_test)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="37">
<pre><code>0.5992063492063492</code></pre>
</div>
</div>
<p>This level of accuracy is quite impressive for stock market data, which is known to be quite hard to model accurately. This suggests that the quadratic form assumed by QDA may capture the true relationship more accurately than the linear forms assumed by LDA and logistic regression. However, we recommend evaluating this method’s performance on a larger test set before betting that this approach will consistently beat the market!</p>
<!--Naive Bayes {{{2-->
</section>
<section id="naive-bayes" class="level2" data-number="4.5">
<h2 data-number="4.5" class="anchored" data-anchor-id="naive-bayes"><span class="header-section-number">4.5</span> Naive Bayes</h2>
<p>Next, we fit a naive Bayes model to the <code>Smarket</code> data. The syntax is similar to that of <code>LDA()</code> and <code>QDA()</code>. By default, this implementation <code>GaussianNB()</code> of the naive Bayes classifier models each quantitative feature using a Gaussian distribution. However, a kernel density method can also be used to estimate the distributions.</p>
<div id="50b54057" class="cell" data-execution_count="38">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a>NB <span class="op">=</span> GaussianNB()</span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a>NB.fit(X_train, L_train)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="38">
<style>#sk-container-id-3 {color: black;background-color: white;}#sk-container-id-3 pre{padding: 0;}#sk-container-id-3 div.sk-toggleable {background-color: white;}#sk-container-id-3 label.sk-toggleable__label {cursor: pointer;display: block;width: 100%;margin-bottom: 0;padding: 0.3em;box-sizing: border-box;text-align: center;}#sk-container-id-3 label.sk-toggleable__label-arrow:before {content: "▸";float: left;margin-right: 0.25em;color: #696969;}#sk-container-id-3 label.sk-toggleable__label-arrow:hover:before {color: black;}#sk-container-id-3 div.sk-estimator:hover label.sk-toggleable__label-arrow:before {color: black;}#sk-container-id-3 div.sk-toggleable__content {max-height: 0;max-width: 0;overflow: hidden;text-align: left;background-color: #f0f8ff;}#sk-container-id-3 div.sk-toggleable__content pre {margin: 0.2em;color: black;border-radius: 0.25em;background-color: #f0f8ff;}#sk-container-id-3 input.sk-toggleable__control:checked~div.sk-toggleable__content {max-height: 200px;max-width: 100%;overflow: auto;}#sk-container-id-3 input.sk-toggleable__control:checked~label.sk-toggleable__label-arrow:before {content: "▾";}#sk-container-id-3 div.sk-estimator input.sk-toggleable__control:checked~label.sk-toggleable__label {background-color: #d4ebff;}#sk-container-id-3 div.sk-label input.sk-toggleable__control:checked~label.sk-toggleable__label {background-color: #d4ebff;}#sk-container-id-3 input.sk-hidden--visually {border: 0;clip: rect(1px 1px 1px 1px);clip: rect(1px, 1px, 1px, 1px);height: 1px;margin: -1px;overflow: hidden;padding: 0;position: absolute;width: 1px;}#sk-container-id-3 div.sk-estimator {font-family: monospace;background-color: #f0f8ff;border: 1px dotted black;border-radius: 0.25em;box-sizing: border-box;margin-bottom: 0.5em;}#sk-container-id-3 div.sk-estimator:hover {background-color: #d4ebff;}#sk-container-id-3 div.sk-parallel-item::after {content: "";width: 100%;border-bottom: 1px solid gray;flex-grow: 1;}#sk-container-id-3 div.sk-label:hover label.sk-toggleable__label {background-color: #d4ebff;}#sk-container-id-3 div.sk-serial::before {content: "";position: absolute;border-left: 1px solid gray;box-sizing: border-box;top: 0;bottom: 0;left: 50%;z-index: 0;}#sk-container-id-3 div.sk-serial {display: flex;flex-direction: column;align-items: center;background-color: white;padding-right: 0.2em;padding-left: 0.2em;position: relative;}#sk-container-id-3 div.sk-item {position: relative;z-index: 1;}#sk-container-id-3 div.sk-parallel {display: flex;align-items: stretch;justify-content: center;background-color: white;position: relative;}#sk-container-id-3 div.sk-item::before, #sk-container-id-3 div.sk-parallel-item::before {content: "";position: absolute;border-left: 1px solid gray;box-sizing: border-box;top: 0;bottom: 0;left: 50%;z-index: -1;}#sk-container-id-3 div.sk-parallel-item {display: flex;flex-direction: column;z-index: 1;position: relative;background-color: white;}#sk-container-id-3 div.sk-parallel-item:first-child::after {align-self: flex-end;width: 50%;}#sk-container-id-3 div.sk-parallel-item:last-child::after {align-self: flex-start;width: 50%;}#sk-container-id-3 div.sk-parallel-item:only-child::after {width: 0;}#sk-container-id-3 div.sk-dashed-wrapped {border: 1px dashed gray;margin: 0 0.4em 0.5em 0.4em;box-sizing: border-box;padding-bottom: 0.4em;background-color: white;}#sk-container-id-3 div.sk-label label {font-family: monospace;font-weight: bold;display: inline-block;line-height: 1.2em;}#sk-container-id-3 div.sk-label-container {text-align: center;}#sk-container-id-3 div.sk-container {/* jupyter's `normalize.less` sets `[hidden] { display: none; }` but bootstrap.min.css set `[hidden] { display: none !important; }` so we also need the `!important` here to be able to override the default hidden behavior on the sphinx rendered scikit-learn.org. See: https://github.com/scikit-learn/scikit-learn/issues/21755 */display: inline-block !important;position: relative;}#sk-container-id-3 div.sk-text-repr-fallback {display: none;}</style><div id="sk-container-id-3" class="sk-top-container"><div class="sk-text-repr-fallback"><pre>GaussianNB()</pre><b>In a Jupyter environment, please rerun this cell to show the HTML representation or trust the notebook. <br>On GitHub, the HTML representation is unable to render, please try loading this page with nbviewer.org.</b></div><div class="sk-container" hidden=""><div class="sk-item"><div class="sk-estimator sk-toggleable"><input class="sk-toggleable__control sk-hidden--visually" id="sk-estimator-id-3" type="checkbox" checked=""><label for="sk-estimator-id-3" class="sk-toggleable__label sk-toggleable__label-arrow">GaussianNB</label><div class="sk-toggleable__content"><pre>GaussianNB()</pre></div></div></div></div></div>
</div>
</div>
<p>The classes are stored as <code>classes_</code>.</p>
<div id="a2ce594f" class="cell" data-execution_count="39">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a>NB.classes_</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="39">
<pre><code>array(['Down', 'Up'], dtype='&lt;U4')</code></pre>
</div>
</div>
<p>The class prior probabilities are stored in the <code>class_prior_</code> attribute.</p>
<div id="44f44409" class="cell" data-execution_count="40">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a>NB.class_prior_</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="40">
<pre><code>array([0.49198397, 0.50801603])</code></pre>
</div>
</div>
<p>The parameters of the features can be found in the <code>theta_</code> and <code>var_</code> attributes. The number of rows is equal to the number of classes, while the number of columns is equal to the number of features. We see below that the mean for feature <code>Lag1</code> in the <code>Down</code> class is 0.043.</p>
<div id="617cb2d9" class="cell" data-execution_count="41">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a>NB.theta_</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="41">
<pre><code>array([[ 0.04279022,  0.03389409],
       [-0.03954635, -0.03132544]])</code></pre>
</div>
</div>
<p>Its variance is 1.503.</p>
<div id="ad65c8b3" class="cell" data-execution_count="42">
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a>NB.var_</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="42">
<pre><code>array([[1.50355429, 1.53246749],
       [1.51401364, 1.48732877]])</code></pre>
</div>
</div>
<p>How do we know the names of these attributes? We use <code>NB?</code> (or ?NB}).</p>
<p>We can easily verify the mean computation:</p>
<div id="b50f3442" class="cell" data-execution_count="43">
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a>X_train[L_train <span class="op">==</span> <span class="st">'Down'</span>].mean()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="43">
<pre><code>Lag1    0.042790
Lag2    0.033894
dtype: float64</code></pre>
</div>
</div>
<p>Similarly for the variance:</p>
<div id="ea95f82a" class="cell" data-execution_count="44">
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a>X_train[L_train <span class="op">==</span> <span class="st">'Down'</span>].var(ddof<span class="op">=</span><span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="44">
<pre><code>Lag1    1.503554
Lag2    1.532467
dtype: float64</code></pre>
</div>
</div>
<p>Since <code>NB()</code> is a classifier in the <code>sklearn</code> library, making predictions uses the same syntax as for <code>LDA()</code> and <code>QDA()</code> above.</p>
<div id="c4e7bce9" class="cell" data-execution_count="45">
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a>nb_labels <span class="op">=</span> NB.predict(X_test)</span>
<span id="cb71-2"><a href="#cb71-2" aria-hidden="true" tabindex="-1"></a>confusion_table(nb_labels, L_test)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="45">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">Truth</th>
<th data-quarto-table-cell-role="th">Down</th>
<th data-quarto-table-cell-role="th">Up</th>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">Predicted</th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">Down</td>
<td>29</td>
<td>20</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Up</td>
<td>82</td>
<td>121</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>Naive Bayes performs well on these data, with accurate predictions over 59% of the time. This is slightly worse than QDA, but much better than LDA.</p>
<p>As for <code>LDA</code>, the <code>predict_proba()</code> method estimates the probability that each observation belongs to a particular class.</p>
<div id="35a8bf67" class="cell" data-execution_count="46">
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a>NB.predict_proba(X_test)[:<span class="dv">5</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="46">
<pre><code>array([[0.4873288 , 0.5126712 ],
       [0.47623584, 0.52376416],
       [0.46529531, 0.53470469],
       [0.47484469, 0.52515531],
       [0.49020587, 0.50979413]])</code></pre>
</div>
</div>
<!--K-Nearest Neighbors {{{2-->
</section>
<section id="k-nearest-neighbors" class="level2" data-number="4.6">
<h2 data-number="4.6" class="anchored" data-anchor-id="k-nearest-neighbors"><span class="header-section-number">4.6</span> K-Nearest Neighbors</h2>
<p>We will now perform KNN using the <code>KNeighborsClassifier()</code> function. This function works similarly to the other model-fitting functions that we have encountered thus far.</p>
<p>As is the case for LDA and QDA, we fit the classifier using the <code>fit</code> method. New predictions are formed using the <code>predict</code> method of the object returned by <code>fit()</code>.</p>
<div id="79d0e9b4" class="cell" data-execution_count="47">
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a>knn1 <span class="op">=</span> KNeighborsClassifier(n_neighbors<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb74-2"><a href="#cb74-2" aria-hidden="true" tabindex="-1"></a>knn1.fit(X_train, L_train)</span>
<span id="cb74-3"><a href="#cb74-3" aria-hidden="true" tabindex="-1"></a>knn1_pred <span class="op">=</span> knn1.predict(X_test)</span>
<span id="cb74-4"><a href="#cb74-4" aria-hidden="true" tabindex="-1"></a>confusion_table(knn1_pred, L_test)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="47">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">Truth</th>
<th data-quarto-table-cell-role="th">Down</th>
<th data-quarto-table-cell-role="th">Up</th>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">Predicted</th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">Down</td>
<td>43</td>
<td>58</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Up</td>
<td>68</td>
<td>83</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>The results using <span class="math inline">\(K=1\)</span> are not very good, since only <span class="math inline">\(50%\)</span> of the observations are correctly predicted. Of course, it may be that <span class="math inline">\(K=1\)</span> results in an overly-flexible fit to the data.</p>
<div id="812b207b" class="cell" data-execution_count="48">
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a>(<span class="dv">83</span><span class="op">+</span><span class="dv">43</span>)<span class="op">/</span><span class="dv">252</span>, np.mean(knn1_pred <span class="op">==</span> L_test)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="48">
<pre><code>(0.5, 0.5)</code></pre>
</div>
</div>
<p>Below, we repeat the analysis using <span class="math inline">\(K=3\)</span>.</p>
<div id="4117678f" class="cell" data-execution_count="49">
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a>knn3 <span class="op">=</span> KNeighborsClassifier(n_neighbors<span class="op">=</span><span class="dv">3</span>)</span>
<span id="cb77-2"><a href="#cb77-2" aria-hidden="true" tabindex="-1"></a>knn3_pred <span class="op">=</span> knn3.fit(X_train, L_train).predict(X_test)</span>
<span id="cb77-3"><a href="#cb77-3" aria-hidden="true" tabindex="-1"></a>np.mean(knn3_pred <span class="op">==</span> L_test)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="49">
<pre><code>0.5317460317460317</code></pre>
</div>
</div>
<p>The results have improved slightly. But increasing <em>K</em> further provides no further improvements. It appears that for these data, and this train/test split, QDA gives the best results of the methods that we have examined so far.</p>
<p>KNN does not perform well on the <code>Smarket</code> data, but it often does provide impressive results. As an example we will apply the KNN approach to the <code>Caravan</code> data set, which is part of the <code>ISLP</code> library. This data set includes 85 predictors that measure demographic characteristics for 5,822 individuals. The response variable is <code>Purchase</code>, which indicates whether or not a given individual purchases a caravan insurance policy. In this data set, only 6% of people purchased caravan insurance.</p>
<div id="a632dd8d" class="cell" data-execution_count="50">
<div class="sourceCode cell-code" id="cb79"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a>Caravan <span class="op">=</span> load_data(<span class="st">'Caravan'</span>)</span>
<span id="cb79-2"><a href="#cb79-2" aria-hidden="true" tabindex="-1"></a>Purchase <span class="op">=</span> Caravan.Purchase</span>
<span id="cb79-3"><a href="#cb79-3" aria-hidden="true" tabindex="-1"></a>Purchase.value_counts()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="50">
<pre><code>No     5474
Yes     348
Name: Purchase, dtype: int64</code></pre>
</div>
</div>
<p>The method <code>value_counts()</code> takes a <code>pd.Series</code> or <code>pd.DataFrame</code> and returns a <code>pd.Series</code> with the corresponding counts for each unique element. In this case <code>Purchase</code> has only <code>Yes</code> and <code>No</code> values and returns how many values of each there are.</p>
<div id="19638bb5" class="cell" data-execution_count="51">
<div class="sourceCode cell-code" id="cb81"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a><span class="dv">348</span> <span class="op">/</span> <span class="dv">5822</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="51">
<pre><code>0.05977327378907592</code></pre>
</div>
</div>
<p>Our features will include all columns except <code>Purchase</code>.</p>
<div id="9071b302" class="cell" data-execution_count="52">
<div class="sourceCode cell-code" id="cb83"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb83-1"><a href="#cb83-1" aria-hidden="true" tabindex="-1"></a>feature_df <span class="op">=</span> Caravan.drop(columns<span class="op">=</span>[<span class="st">'Purchase'</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Because the KNN classifier predicts the class of a given test observation by identifying the observations that are nearest to it, the scale of the variables matters. Any variables that are on a large scale will have a much larger effect on the <em>distance</em> between the observations, and hence on the KNN classifier, than variables that are on a small scale. For instance, imagine a data set that contains two variables, <code>salary</code> and <code>age</code> (measured in dollars and years, respectively). As far as KNN is concerned, a difference of 1,000 USD in salary is enormous compared to a difference of 50 years in age. Consequently, <code>salary</code> will drive the KNN classification results, and <code>age</code> will have almost no effect. This is contrary to our intuition that a salary difference of 1,000 USD is quite small compared to an age difference of 50 years. Furthermore, the importance of scale to the KNN classifier leads to another issue: if we measured <code>salary</code> in Japanese yen, or if we measured <code>age</code> in minutes, then we’d get quite different classification results from what we get if these two variables are measured in dollars and years.</p>
<p>A good way to handle this problem is to <em>standardize</em> the data so that all variables are given a mean of zero and a standard deviation of one. Then all variables will be on a comparable scale. This is accomplished using the <code>StandardScaler()</code> transformation.</p>
<div id="fa40b86d" class="cell" data-execution_count="53">
<div class="sourceCode cell-code" id="cb84"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb84-1"><a href="#cb84-1" aria-hidden="true" tabindex="-1"></a>scaler <span class="op">=</span> StandardScaler(with_mean<span class="op">=</span><span class="va">True</span>,</span>
<span id="cb84-2"><a href="#cb84-2" aria-hidden="true" tabindex="-1"></a>                        with_std<span class="op">=</span><span class="va">True</span>,</span>
<span id="cb84-3"><a href="#cb84-3" aria-hidden="true" tabindex="-1"></a>                        copy<span class="op">=</span><span class="va">True</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The argument <code>with_mean</code> indicates whether or not we should subtract the mean, while <code>with_std</code> indicates whether or not we should scale the columns to have standard deviation of 1 or not. Finally, the argument <code>copy=True</code> indicates that we will always copy data, rather than trying to do calculations in place where possible.</p>
<p>This transformation can be fit and then applied to arbitrary data. In the first line below, the parameters for the scaling are computed and stored in <code>scaler</code>, while the second line actually constructs the standardized set of features.</p>
<div id="0e5d67d9" class="cell" data-execution_count="54">
<div class="sourceCode cell-code" id="cb85"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb85-1"><a href="#cb85-1" aria-hidden="true" tabindex="-1"></a>scaler.fit(feature_df)</span>
<span id="cb85-2"><a href="#cb85-2" aria-hidden="true" tabindex="-1"></a>X_std <span class="op">=</span> scaler.transform(feature_df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now every column of <code>feature_std</code> below has a standard deviation of one and a mean of zero.</p>
<div id="96b8c1d6" class="cell" data-execution_count="55">
<div class="sourceCode cell-code" id="cb86"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb86-1"><a href="#cb86-1" aria-hidden="true" tabindex="-1"></a>feature_std <span class="op">=</span> pd.DataFrame(</span>
<span id="cb86-2"><a href="#cb86-2" aria-hidden="true" tabindex="-1"></a>                 X_std,</span>
<span id="cb86-3"><a href="#cb86-3" aria-hidden="true" tabindex="-1"></a>                 columns<span class="op">=</span>feature_df.columns)<span class="op">;</span></span>
<span id="cb86-4"><a href="#cb86-4" aria-hidden="true" tabindex="-1"></a>feature_std.std()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="55">
<pre><code>MOSTYPE     1.000086
MAANTHUI    1.000086
MGEMOMV     1.000086
MGEMLEEF    1.000086
MOSHOOFD    1.000086
              ...   
AZEILPL     1.000086
APLEZIER    1.000086
AFIETS      1.000086
AINBOED     1.000086
ABYSTAND    1.000086
Length: 85, dtype: float64</code></pre>
</div>
</div>
<p>Notice that the standard deviations are not quite <span class="math inline">\(1\)</span> here; this is again due to some procedures using the <span class="math inline">\(1/n\)</span> convention for variances (in this case <code>scaler()</code>), while others use <span class="math inline">\(1/(n-1)\)</span> (the <code>std()</code> method). See the footnote on page 198. In this case it does not matter, as long as the variables are all on the same scale.</p>
<p>Using the function <code>train_test_split()</code> we now split the observations into a test set, containing 1000 observations, and a training set containing the remaining observations. The argument <code>random_state=0</code> ensures that we get the same split each time we rerun the code.</p>
<div id="8e43fe6e" class="cell" data-execution_count="56">
<div class="sourceCode cell-code" id="cb88"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb88-1"><a href="#cb88-1" aria-hidden="true" tabindex="-1"></a>(X_train,</span>
<span id="cb88-2"><a href="#cb88-2" aria-hidden="true" tabindex="-1"></a> X_test,</span>
<span id="cb88-3"><a href="#cb88-3" aria-hidden="true" tabindex="-1"></a> y_train,</span>
<span id="cb88-4"><a href="#cb88-4" aria-hidden="true" tabindex="-1"></a> y_test) <span class="op">=</span> train_test_split(feature_std,</span>
<span id="cb88-5"><a href="#cb88-5" aria-hidden="true" tabindex="-1"></a>                            Purchase,</span>
<span id="cb88-6"><a href="#cb88-6" aria-hidden="true" tabindex="-1"></a>                            test_size<span class="op">=</span><span class="dv">1000</span>,</span>
<span id="cb88-7"><a href="#cb88-7" aria-hidden="true" tabindex="-1"></a>                            random_state<span class="op">=</span><span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><code>?train_test_split</code> reveals that the non-keyword arguments can be <code>lists</code>, <code>arrays</code>, <code>pandas dataframes</code> etc that all have the same length (<code>shape[0]</code>) and hence are <em>indexable</em>. In this case they are the dataframe <code>feature_std</code> and the response variable <code>Purchase</code>. We fit a KNN model on the training data using <span class="math inline">\(K=1\)</span>, and evaluate its performance on the test data.</p>
<div id="cbfacd4c" class="cell" data-execution_count="57">
<div class="sourceCode cell-code" id="cb89"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb89-1"><a href="#cb89-1" aria-hidden="true" tabindex="-1"></a>knn1 <span class="op">=</span> KNeighborsClassifier(n_neighbors<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb89-2"><a href="#cb89-2" aria-hidden="true" tabindex="-1"></a>knn1_pred <span class="op">=</span> knn1.fit(X_train, y_train).predict(X_test)</span>
<span id="cb89-3"><a href="#cb89-3" aria-hidden="true" tabindex="-1"></a>np.mean(y_test <span class="op">!=</span> knn1_pred), np.mean(y_test <span class="op">!=</span> <span class="st">"No"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="57">
<pre><code>(0.111, 0.067)</code></pre>
</div>
</div>
<p>The KNN error rate on the 1,000 test observations is about <span class="math inline">\(11%\)</span>. At first glance, this may appear to be fairly good. However, since just over 6% of customers purchased insurance, we could get the error rate down to almost 6% by always predicting <code>No</code> regardless of the values of the predictors! This is known as the <em>null rate</em>.}</p>
<p>Suppose that there is some non-trivial cost to trying to sell insurance to a given individual. For instance, perhaps a salesperson must visit each potential customer. If the company tries to sell insurance to a random selection of customers, then the success rate will be only 6%, which may be far too low given the costs involved. Instead, the company would like to try to sell insurance only to customers who are likely to buy it. So the overall error rate is not of interest. Instead, the fraction of individuals that are correctly predicted to buy insurance is of interest.</p>
<div id="49eb6fb1" class="cell" data-execution_count="58">
<div class="sourceCode cell-code" id="cb91"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb91-1"><a href="#cb91-1" aria-hidden="true" tabindex="-1"></a>confusion_table(knn1_pred, y_test)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="58">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">Truth</th>
<th data-quarto-table-cell-role="th">No</th>
<th data-quarto-table-cell-role="th">Yes</th>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">Predicted</th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">No</td>
<td>880</td>
<td>58</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Yes</td>
<td>53</td>
<td>9</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>It turns out that KNN with <span class="math inline">\(K=1\)</span> does far better than random guessing among the customers that are predicted to buy insurance. Among 62 such customers, 9, or 14.5%, actually do purchase insurance. This is double the rate that one would obtain from random guessing.</p>
<div id="5a6fdc83" class="cell" data-execution_count="59">
<div class="sourceCode cell-code" id="cb92"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb92-1"><a href="#cb92-1" aria-hidden="true" tabindex="-1"></a><span class="dv">9</span><span class="op">/</span>(<span class="dv">53</span><span class="op">+</span><span class="dv">9</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="59">
<pre><code>0.14516129032258066</code></pre>
</div>
</div>
<section id="tuning-parameters" class="level3" data-number="4.6.1">
<h3 data-number="4.6.1" class="anchored" data-anchor-id="tuning-parameters"><span class="header-section-number">4.6.1</span> Tuning Parameters</h3>
<p>The number of neighbors in KNN is referred to as a <em>tuning parameter</em>, also referred to as a <em>hyperparameter</em>. We do not know <em>a priori</em> what value to use. It is therefore of interest to see how the classifier performs on test data as we vary these parameters. This can be achieved with a <code>for</code> loop, described in Section 2.3.8. Here we use a for loop to look at the accuracy of our classifier in the group predicted to purchase insurance as we vary the number of neighbors from 1 to 5:</p>
<div id="e4be18e1" class="cell" data-execution_count="60">
<div class="sourceCode cell-code" id="cb94"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb94-1"><a href="#cb94-1" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> K <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">1</span>,<span class="dv">6</span>):</span>
<span id="cb94-2"><a href="#cb94-2" aria-hidden="true" tabindex="-1"></a>    knn <span class="op">=</span> KNeighborsClassifier(n_neighbors<span class="op">=</span>K)</span>
<span id="cb94-3"><a href="#cb94-3" aria-hidden="true" tabindex="-1"></a>    knn_pred <span class="op">=</span> knn.fit(X_train, y_train).predict(X_test)</span>
<span id="cb94-4"><a href="#cb94-4" aria-hidden="true" tabindex="-1"></a>    C <span class="op">=</span> confusion_table(knn_pred, y_test)</span>
<span id="cb94-5"><a href="#cb94-5" aria-hidden="true" tabindex="-1"></a>    templ <span class="op">=</span> (<span class="st">'K=</span><span class="sc">{0:d}</span><span class="st">: # predicted to rent: </span><span class="sc">{1:&gt;2}</span><span class="st">,'</span> <span class="op">+</span></span>
<span id="cb94-6"><a href="#cb94-6" aria-hidden="true" tabindex="-1"></a>            <span class="st">'  # who did rent </span><span class="sc">{2:d}</span><span class="st">, accuracy </span><span class="sc">{3:.1%}</span><span class="st">'</span>)</span>
<span id="cb94-7"><a href="#cb94-7" aria-hidden="true" tabindex="-1"></a>    pred <span class="op">=</span> C.loc[<span class="st">'Yes'</span>].<span class="bu">sum</span>()</span>
<span id="cb94-8"><a href="#cb94-8" aria-hidden="true" tabindex="-1"></a>    did_rent <span class="op">=</span> C.loc[<span class="st">'Yes'</span>,<span class="st">'Yes'</span>]</span>
<span id="cb94-9"><a href="#cb94-9" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(templ.<span class="bu">format</span>(</span>
<span id="cb94-10"><a href="#cb94-10" aria-hidden="true" tabindex="-1"></a>          K,</span>
<span id="cb94-11"><a href="#cb94-11" aria-hidden="true" tabindex="-1"></a>          pred,</span>
<span id="cb94-12"><a href="#cb94-12" aria-hidden="true" tabindex="-1"></a>          did_rent,</span>
<span id="cb94-13"><a href="#cb94-13" aria-hidden="true" tabindex="-1"></a>          did_rent <span class="op">/</span> pred))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>K=1: # predicted to rent: 62,  # who did rent 9, accuracy 14.5%
K=2: # predicted to rent:  6,  # who did rent 1, accuracy 16.7%
K=3: # predicted to rent: 20,  # who did rent 3, accuracy 15.0%
K=4: # predicted to rent:  4,  # who did rent 0, accuracy 0.0%
K=5: # predicted to rent:  7,  # who did rent 1, accuracy 14.3%</code></pre>
</div>
</div>
<p>We see some variability — the numbers for <code>K=4</code> are very different from the rest.</p>
</section>
<section id="comparison-to-logistic-regression" class="level3" data-number="4.6.2">
<h3 data-number="4.6.2" class="anchored" data-anchor-id="comparison-to-logistic-regression"><span class="header-section-number">4.6.2</span> Comparison to Logistic Regression</h3>
<p>As a comparison, we can also fit a logistic regression model to the data. This can also be done with <code>sklearn</code>, though by default it fits something like the <em>ridge regression</em> version of logistic regression, which we introduce in Chapter 6. This can be modified by appropriately setting the argument <code>C</code> below. Its default value is 1 but by setting it to a very large number, the algorithm converges to the same solution as the usual (unregularized) logistic regression estimator discussed above.</p>
<p>Unlike the <code>statsmodels</code> package, <code>sklearn</code> focuses less on inference and more on classification. Hence, the <code>summary</code> methods seen in <code>statsmodels</code> and our simplified version seen with <code>summarize</code> are not generally available for the classifiers in <code>sklearn</code>.</p>
<div id="9c4c3726" class="cell" data-execution_count="61">
<div class="sourceCode cell-code" id="cb96"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb96-1"><a href="#cb96-1" aria-hidden="true" tabindex="-1"></a>logit <span class="op">=</span> LogisticRegression(C<span class="op">=</span><span class="fl">1e10</span>, solver<span class="op">=</span><span class="st">'liblinear'</span>)</span>
<span id="cb96-2"><a href="#cb96-2" aria-hidden="true" tabindex="-1"></a>logit.fit(X_train, y_train)</span>
<span id="cb96-3"><a href="#cb96-3" aria-hidden="true" tabindex="-1"></a>logit_pred <span class="op">=</span> logit.predict_proba(X_test)</span>
<span id="cb96-4"><a href="#cb96-4" aria-hidden="true" tabindex="-1"></a>logit_labels <span class="op">=</span> np.where(logit_pred[:,<span class="dv">1</span>] <span class="op">&gt;</span> <span class="dv">5</span>, <span class="st">'Yes'</span>, <span class="st">'No'</span>)</span>
<span id="cb96-5"><a href="#cb96-5" aria-hidden="true" tabindex="-1"></a>confusion_table(logit_labels, y_test)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="61">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">Truth</th>
<th data-quarto-table-cell-role="th">No</th>
<th data-quarto-table-cell-role="th">Yes</th>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">Predicted</th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">No</td>
<td>933</td>
<td>67</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Yes</td>
<td>0</td>
<td>0</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>We used the argument <code>solver='liblinear'</code> above to avoid a warning with the default solver which would indicate that the algorithm does not converge.</p>
<p>If we use <span class="math inline">\(0.5\)</span> as the predicted probability cut-off for the classifier, then we have a problem: none of the test observations are predicted to purchase insurance. However, we are not required to use a cut-off of <span class="math inline">\(0.5\)</span>. If we instead predict a purchase any time the predicted probability of purchase exceeds <span class="math inline">\(0.25\)</span>, we get much better results: we predict that 29 people will purchase insurance, and we are correct for about 31% of these people. This is almost five times better than random guessing!</p>
<div id="d0044a0e" class="cell" data-execution_count="62">
<div class="sourceCode cell-code" id="cb97"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb97-1"><a href="#cb97-1" aria-hidden="true" tabindex="-1"></a>logit_labels <span class="op">=</span> np.where(logit_pred[:,<span class="dv">1</span>]<span class="op">&gt;</span><span class="fl">0.25</span>, <span class="st">'Yes'</span>, <span class="st">'No'</span>)</span>
<span id="cb97-2"><a href="#cb97-2" aria-hidden="true" tabindex="-1"></a>confusion_table(logit_labels, y_test)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="62">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">Truth</th>
<th data-quarto-table-cell-role="th">No</th>
<th data-quarto-table-cell-role="th">Yes</th>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">Predicted</th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">No</td>
<td>913</td>
<td>58</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Yes</td>
<td>20</td>
<td>9</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div id="8628ac8f" class="cell" data-execution_count="63">
<div class="sourceCode cell-code" id="cb98"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb98-1"><a href="#cb98-1" aria-hidden="true" tabindex="-1"></a><span class="dv">9</span><span class="op">/</span>(<span class="dv">20</span><span class="op">+</span><span class="dv">9</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="63">
<pre><code>0.3103448275862069</code></pre>
</div>
</div>
<!--Linear and Poisson Regression on the Bikeshare Data {{{2-->
</section>
</section>
<section id="linear-and-poisson-regression-on-the-bikeshare-data" class="level2" data-number="4.7">
<h2 data-number="4.7" class="anchored" data-anchor-id="linear-and-poisson-regression-on-the-bikeshare-data"><span class="header-section-number">4.7</span> Linear and Poisson Regression on the Bikeshare Data</h2>
<p>Here we fit linear and Poisson regression models to the <code>Bikeshare</code> data, as described in Section 4.6. The response <code>bikers</code> measures the number of bike rentals per hour in Washington, DC in the period 2010–2012.</p>
<div id="74a94024" class="cell" data-execution_count="64">
<div class="sourceCode cell-code" id="cb100"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb100-1"><a href="#cb100-1" aria-hidden="true" tabindex="-1"></a>Bike <span class="op">=</span> load_data(<span class="st">'Bikeshare'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Let’s have a peek at the dimensions and names of the variables in this dataframe.</p>
<div id="c1701782" class="cell" data-execution_count="65">
<div class="sourceCode cell-code" id="cb101"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb101-1"><a href="#cb101-1" aria-hidden="true" tabindex="-1"></a>Bike.shape, Bike.columns</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="65">
<pre><code>((8645, 15),
 Index(['season', 'mnth', 'day', 'hr', 'holiday', 'weekday', 'workingday',
        'weathersit', 'temp', 'atemp', 'hum', 'windspeed', 'casual',
        'registered', 'bikers'],
       dtype='object'))</code></pre>
</div>
</div>
<section id="linear-regression" class="level3" data-number="4.7.1">
<h3 data-number="4.7.1" class="anchored" data-anchor-id="linear-regression"><span class="header-section-number">4.7.1</span> Linear Regression</h3>
<p>We begin by fitting a linear regression model to the data.</p>
<div id="3a9e4391" class="cell" data-execution_count="66">
<div class="sourceCode cell-code" id="cb103"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb103-1"><a href="#cb103-1" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> MS([<span class="st">'mnth'</span>,</span>
<span id="cb103-2"><a href="#cb103-2" aria-hidden="true" tabindex="-1"></a>        <span class="st">'hr'</span>,</span>
<span id="cb103-3"><a href="#cb103-3" aria-hidden="true" tabindex="-1"></a>        <span class="st">'workingday'</span>,</span>
<span id="cb103-4"><a href="#cb103-4" aria-hidden="true" tabindex="-1"></a>        <span class="st">'temp'</span>,</span>
<span id="cb103-5"><a href="#cb103-5" aria-hidden="true" tabindex="-1"></a>        <span class="st">'weathersit'</span>]).fit_transform(Bike)</span>
<span id="cb103-6"><a href="#cb103-6" aria-hidden="true" tabindex="-1"></a>Y <span class="op">=</span> Bike[<span class="st">'bikers'</span>]</span>
<span id="cb103-7"><a href="#cb103-7" aria-hidden="true" tabindex="-1"></a>M_lm <span class="op">=</span> sm.OLS(Y, X).fit()</span>
<span id="cb103-8"><a href="#cb103-8" aria-hidden="true" tabindex="-1"></a>summarize(M_lm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="66">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">coef</th>
<th data-quarto-table-cell-role="th">std err</th>
<th data-quarto-table-cell-role="th">t</th>
<th data-quarto-table-cell-role="th">P&gt;|t|</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">intercept</td>
<td>-27.2068</td>
<td>6.715</td>
<td>-4.052</td>
<td>0.000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">mnth[Aug]</td>
<td>11.8181</td>
<td>4.698</td>
<td>2.515</td>
<td>0.012</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">mnth[Dec]</td>
<td>5.0328</td>
<td>4.280</td>
<td>1.176</td>
<td>0.240</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">mnth[Feb]</td>
<td>-34.5797</td>
<td>4.575</td>
<td>-7.558</td>
<td>0.000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">mnth[Jan]</td>
<td>-41.4249</td>
<td>4.972</td>
<td>-8.331</td>
<td>0.000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">mnth[July]</td>
<td>3.8996</td>
<td>5.003</td>
<td>0.779</td>
<td>0.436</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">mnth[June]</td>
<td>26.3938</td>
<td>4.642</td>
<td>5.686</td>
<td>0.000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">mnth[March]</td>
<td>-24.8735</td>
<td>4.277</td>
<td>-5.815</td>
<td>0.000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">mnth[May]</td>
<td>31.1322</td>
<td>4.150</td>
<td>7.501</td>
<td>0.000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">mnth[Nov]</td>
<td>18.8851</td>
<td>4.099</td>
<td>4.607</td>
<td>0.000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">mnth[Oct]</td>
<td>34.4093</td>
<td>4.006</td>
<td>8.589</td>
<td>0.000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">mnth[Sept]</td>
<td>25.2534</td>
<td>4.293</td>
<td>5.883</td>
<td>0.000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">hr[1]</td>
<td>-14.5793</td>
<td>5.699</td>
<td>-2.558</td>
<td>0.011</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">hr[2]</td>
<td>-21.5791</td>
<td>5.733</td>
<td>-3.764</td>
<td>0.000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">hr[3]</td>
<td>-31.1408</td>
<td>5.778</td>
<td>-5.389</td>
<td>0.000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">hr[4]</td>
<td>-36.9075</td>
<td>5.802</td>
<td>-6.361</td>
<td>0.000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">hr[5]</td>
<td>-24.1355</td>
<td>5.737</td>
<td>-4.207</td>
<td>0.000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">hr[6]</td>
<td>20.5997</td>
<td>5.704</td>
<td>3.612</td>
<td>0.000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">hr[7]</td>
<td>120.0931</td>
<td>5.693</td>
<td>21.095</td>
<td>0.000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">hr[8]</td>
<td>223.6619</td>
<td>5.690</td>
<td>39.310</td>
<td>0.000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">hr[9]</td>
<td>120.5819</td>
<td>5.693</td>
<td>21.182</td>
<td>0.000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">hr[10]</td>
<td>83.8013</td>
<td>5.705</td>
<td>14.689</td>
<td>0.000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">hr[11]</td>
<td>105.4234</td>
<td>5.722</td>
<td>18.424</td>
<td>0.000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">hr[12]</td>
<td>137.2837</td>
<td>5.740</td>
<td>23.916</td>
<td>0.000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">hr[13]</td>
<td>136.0359</td>
<td>5.760</td>
<td>23.617</td>
<td>0.000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">hr[14]</td>
<td>126.6361</td>
<td>5.776</td>
<td>21.923</td>
<td>0.000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">hr[15]</td>
<td>132.0865</td>
<td>5.780</td>
<td>22.852</td>
<td>0.000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">hr[16]</td>
<td>178.5206</td>
<td>5.772</td>
<td>30.927</td>
<td>0.000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">hr[17]</td>
<td>296.2670</td>
<td>5.749</td>
<td>51.537</td>
<td>0.000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">hr[18]</td>
<td>269.4409</td>
<td>5.736</td>
<td>46.976</td>
<td>0.000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">hr[19]</td>
<td>186.2558</td>
<td>5.714</td>
<td>32.596</td>
<td>0.000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">hr[20]</td>
<td>125.5492</td>
<td>5.704</td>
<td>22.012</td>
<td>0.000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">hr[21]</td>
<td>87.5537</td>
<td>5.693</td>
<td>15.378</td>
<td>0.000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">hr[22]</td>
<td>59.1226</td>
<td>5.689</td>
<td>10.392</td>
<td>0.000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">hr[23]</td>
<td>26.8376</td>
<td>5.688</td>
<td>4.719</td>
<td>0.000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">workingday</td>
<td>1.2696</td>
<td>1.784</td>
<td>0.711</td>
<td>0.477</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">temp</td>
<td>157.2094</td>
<td>10.261</td>
<td>15.321</td>
<td>0.000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">weathersit[cloudy/misty]</td>
<td>-12.8903</td>
<td>1.964</td>
<td>-6.562</td>
<td>0.000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">weathersit[heavy rain/snow]</td>
<td>-109.7446</td>
<td>76.667</td>
<td>-1.431</td>
<td>0.152</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">weathersit[light rain/snow]</td>
<td>-66.4944</td>
<td>2.965</td>
<td>-22.425</td>
<td>0.000</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>There are 24 levels in <code>hr</code> and 40 rows in all. In <code>M_lm</code>, the first levels <code>hr[0]</code> and <code>mnth[Jan]</code> are treated as the baseline values, and so no coefficient estimates are provided for them: implicitly, their coefficient estimates are zero, and all other levels are measured relative to these baselines. For example, the Feb coefficient of <span class="math inline">\(6.845\)</span> signifies that, holding all other variables constant, there are on average about 7 more riders in February than in January. Similarly there are about 16.5 more riders in March than in January.</p>
<p>The results seen in Section 4.6.1 used a slightly different coding of the variables <code>hr</code> and <code>mnth</code>, as follows:</p>
<div id="1d97d40b" class="cell" data-execution_count="67">
<div class="sourceCode cell-code" id="cb104"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb104-1"><a href="#cb104-1" aria-hidden="true" tabindex="-1"></a>hr_encode <span class="op">=</span> contrast(<span class="st">'hr'</span>, <span class="st">'sum'</span>)</span>
<span id="cb104-2"><a href="#cb104-2" aria-hidden="true" tabindex="-1"></a>mnth_encode <span class="op">=</span> contrast(<span class="st">'mnth'</span>, <span class="st">'sum'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Refitting again:</p>
<div id="985513ad" class="cell" data-execution_count="68">
<div class="sourceCode cell-code" id="cb105"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb105-1"><a href="#cb105-1" aria-hidden="true" tabindex="-1"></a>X2 <span class="op">=</span> MS([mnth_encode,</span>
<span id="cb105-2"><a href="#cb105-2" aria-hidden="true" tabindex="-1"></a>         hr_encode,</span>
<span id="cb105-3"><a href="#cb105-3" aria-hidden="true" tabindex="-1"></a>        <span class="st">'workingday'</span>,</span>
<span id="cb105-4"><a href="#cb105-4" aria-hidden="true" tabindex="-1"></a>        <span class="st">'temp'</span>,</span>
<span id="cb105-5"><a href="#cb105-5" aria-hidden="true" tabindex="-1"></a>        <span class="st">'weathersit'</span>]).fit_transform(Bike)</span>
<span id="cb105-6"><a href="#cb105-6" aria-hidden="true" tabindex="-1"></a>M2_lm <span class="op">=</span> sm.OLS(Y, X2).fit()</span>
<span id="cb105-7"><a href="#cb105-7" aria-hidden="true" tabindex="-1"></a>S2 <span class="op">=</span> summarize(M2_lm)</span>
<span id="cb105-8"><a href="#cb105-8" aria-hidden="true" tabindex="-1"></a>S2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="68">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">coef</th>
<th data-quarto-table-cell-role="th">std err</th>
<th data-quarto-table-cell-role="th">t</th>
<th data-quarto-table-cell-role="th">P&gt;|t|</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">intercept</td>
<td>73.5974</td>
<td>5.132</td>
<td>14.340</td>
<td>0.000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">mnth[Jan]</td>
<td>-46.0871</td>
<td>4.085</td>
<td>-11.281</td>
<td>0.000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">mnth[Feb]</td>
<td>-39.2419</td>
<td>3.539</td>
<td>-11.088</td>
<td>0.000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">mnth[March]</td>
<td>-29.5357</td>
<td>3.155</td>
<td>-9.361</td>
<td>0.000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">mnth[April]</td>
<td>-4.6622</td>
<td>2.741</td>
<td>-1.701</td>
<td>0.089</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">mnth[May]</td>
<td>26.4700</td>
<td>2.851</td>
<td>9.285</td>
<td>0.000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">mnth[June]</td>
<td>21.7317</td>
<td>3.465</td>
<td>6.272</td>
<td>0.000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">mnth[July]</td>
<td>-0.7626</td>
<td>3.908</td>
<td>-0.195</td>
<td>0.845</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">mnth[Aug]</td>
<td>7.1560</td>
<td>3.535</td>
<td>2.024</td>
<td>0.043</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">mnth[Sept]</td>
<td>20.5912</td>
<td>3.046</td>
<td>6.761</td>
<td>0.000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">mnth[Oct]</td>
<td>29.7472</td>
<td>2.700</td>
<td>11.019</td>
<td>0.000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">mnth[Nov]</td>
<td>14.2229</td>
<td>2.860</td>
<td>4.972</td>
<td>0.000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">hr[0]</td>
<td>-96.1420</td>
<td>3.955</td>
<td>-24.307</td>
<td>0.000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">hr[1]</td>
<td>-110.7213</td>
<td>3.966</td>
<td>-27.916</td>
<td>0.000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">hr[2]</td>
<td>-117.7212</td>
<td>4.016</td>
<td>-29.310</td>
<td>0.000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">hr[3]</td>
<td>-127.2828</td>
<td>4.081</td>
<td>-31.191</td>
<td>0.000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">hr[4]</td>
<td>-133.0495</td>
<td>4.117</td>
<td>-32.319</td>
<td>0.000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">hr[5]</td>
<td>-120.2775</td>
<td>4.037</td>
<td>-29.794</td>
<td>0.000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">hr[6]</td>
<td>-75.5424</td>
<td>3.992</td>
<td>-18.925</td>
<td>0.000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">hr[7]</td>
<td>23.9511</td>
<td>3.969</td>
<td>6.035</td>
<td>0.000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">hr[8]</td>
<td>127.5199</td>
<td>3.950</td>
<td>32.284</td>
<td>0.000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">hr[9]</td>
<td>24.4399</td>
<td>3.936</td>
<td>6.209</td>
<td>0.000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">hr[10]</td>
<td>-12.3407</td>
<td>3.936</td>
<td>-3.135</td>
<td>0.002</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">hr[11]</td>
<td>9.2814</td>
<td>3.945</td>
<td>2.353</td>
<td>0.019</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">hr[12]</td>
<td>41.1417</td>
<td>3.957</td>
<td>10.397</td>
<td>0.000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">hr[13]</td>
<td>39.8939</td>
<td>3.975</td>
<td>10.036</td>
<td>0.000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">hr[14]</td>
<td>30.4940</td>
<td>3.991</td>
<td>7.641</td>
<td>0.000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">hr[15]</td>
<td>35.9445</td>
<td>3.995</td>
<td>8.998</td>
<td>0.000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">hr[16]</td>
<td>82.3786</td>
<td>3.988</td>
<td>20.655</td>
<td>0.000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">hr[17]</td>
<td>200.1249</td>
<td>3.964</td>
<td>50.488</td>
<td>0.000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">hr[18]</td>
<td>173.2989</td>
<td>3.956</td>
<td>43.806</td>
<td>0.000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">hr[19]</td>
<td>90.1138</td>
<td>3.940</td>
<td>22.872</td>
<td>0.000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">hr[20]</td>
<td>29.4071</td>
<td>3.936</td>
<td>7.471</td>
<td>0.000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">hr[21]</td>
<td>-8.5883</td>
<td>3.933</td>
<td>-2.184</td>
<td>0.029</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">hr[22]</td>
<td>-37.0194</td>
<td>3.934</td>
<td>-9.409</td>
<td>0.000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">workingday</td>
<td>1.2696</td>
<td>1.784</td>
<td>0.711</td>
<td>0.477</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">temp</td>
<td>157.2094</td>
<td>10.261</td>
<td>15.321</td>
<td>0.000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">weathersit[cloudy/misty]</td>
<td>-12.8903</td>
<td>1.964</td>
<td>-6.562</td>
<td>0.000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">weathersit[heavy rain/snow]</td>
<td>-109.7446</td>
<td>76.667</td>
<td>-1.431</td>
<td>0.152</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">weathersit[light rain/snow]</td>
<td>-66.4944</td>
<td>2.965</td>
<td>-22.425</td>
<td>0.000</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>What is the difference between the two codings? In <code>M2_lm</code>, a coefficient estimate is reported for all but level <code>23</code> of <code>hr</code> and level <code>Dec</code> of <code>mnth</code>. Importantly, in <code>M2_lm</code>, the (unreported) coefficient estimate for the last level of <code>mnth</code> is not zero: instead, it equals the negative of the sum of the coefficient estimates for all of the other levels. Similarly, in <code>M2_lm</code>, the coefficient estimate for the last level of <code>hr</code> is the negative of the sum of the coefficient estimates for all of the other levels. This means that the coefficients of <code>hr</code> and <code>mnth</code> in <code>M2_lm</code> will always sum to zero, and can be interpreted as the difference from the mean level. For example, the coefficient for January of <span class="math inline">\(-46.087\)</span> indicates that, holding all other variables constant, there are typically 46 fewer riders in January relative to the yearly average.</p>
<p>It is important to realize that the choice of coding really does not matter, provided that we interpret the model output correctly in light of the coding used. For example, we see that the predictions from the linear model are the same regardless of coding:</p>
<div id="12705913" class="cell" data-execution_count="69">
<div class="sourceCode cell-code" id="cb106"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb106-1"><a href="#cb106-1" aria-hidden="true" tabindex="-1"></a>np.<span class="bu">sum</span>((M_lm.fittedvalues <span class="op">-</span> M2_lm.fittedvalues)<span class="op">**</span><span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="69">
<pre><code>1.1303660379052135e-20</code></pre>
</div>
</div>
<p>The sum of squared differences is zero. We can also see this using the <code>np.allclose()</code> function:</p>
<div id="99726f2a" class="cell" data-execution_count="70">
<div class="sourceCode cell-code" id="cb108"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb108-1"><a href="#cb108-1" aria-hidden="true" tabindex="-1"></a>np.allclose(M_lm.fittedvalues, M2_lm.fittedvalues)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="70">
<pre><code>True</code></pre>
</div>
</div>
<p>To reproduce the left-hand side of Figure 4.13 we must first obtain the coefficient estimates associated with <code>mnth</code>. The coefficients for January through November can be obtained directly from the <code>M2_lm</code> object. The coefficient for December must be explicitly computed as the negative sum of all the other months. We first extract all the coefficients for month from the coefficients of <code>M2_lm</code>.</p>
<div id="4e59d097" class="cell" data-execution_count="71">
<div class="sourceCode cell-code" id="cb110"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb110-1"><a href="#cb110-1" aria-hidden="true" tabindex="-1"></a>coef_month <span class="op">=</span> S2[S2.index.<span class="bu">str</span>.contains(<span class="st">'mnth'</span>)][<span class="st">'coef'</span>]</span>
<span id="cb110-2"><a href="#cb110-2" aria-hidden="true" tabindex="-1"></a>coef_month</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="71">
<pre><code>mnth[Jan]     -46.0871
mnth[Feb]     -39.2419
mnth[March]   -29.5357
mnth[April]    -4.6622
mnth[May]      26.4700
mnth[June]     21.7317
mnth[July]     -0.7626
mnth[Aug]       7.1560
mnth[Sept]     20.5912
mnth[Oct]      29.7472
mnth[Nov]      14.2229
Name: coef, dtype: float64</code></pre>
</div>
</div>
<p>Next, we append <code>Dec</code> as the negative of the sum of all other months.</p>
<div id="24fa1d0c" class="cell" data-execution_count="72">
<div class="sourceCode cell-code" id="cb112"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb112-1"><a href="#cb112-1" aria-hidden="true" tabindex="-1"></a>months <span class="op">=</span> Bike[<span class="st">'mnth'</span>].dtype.categories</span>
<span id="cb112-2"><a href="#cb112-2" aria-hidden="true" tabindex="-1"></a>coef_month <span class="op">=</span> pd.concat([</span>
<span id="cb112-3"><a href="#cb112-3" aria-hidden="true" tabindex="-1"></a>                       coef_month,</span>
<span id="cb112-4"><a href="#cb112-4" aria-hidden="true" tabindex="-1"></a>                       pd.Series([<span class="op">-</span>coef_month.<span class="bu">sum</span>()],</span>
<span id="cb112-5"><a href="#cb112-5" aria-hidden="true" tabindex="-1"></a>                                  index<span class="op">=</span>[<span class="st">'mnth[Dec]'</span></span>
<span id="cb112-6"><a href="#cb112-6" aria-hidden="true" tabindex="-1"></a>                                 ])</span>
<span id="cb112-7"><a href="#cb112-7" aria-hidden="true" tabindex="-1"></a>                       ])</span>
<span id="cb112-8"><a href="#cb112-8" aria-hidden="true" tabindex="-1"></a>coef_month</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="72">
<pre><code>mnth[Jan]     -46.0871
mnth[Feb]     -39.2419
mnth[March]   -29.5357
mnth[April]    -4.6622
mnth[May]      26.4700
mnth[June]     21.7317
mnth[July]     -0.7626
mnth[Aug]       7.1560
mnth[Sept]     20.5912
mnth[Oct]      29.7472
mnth[Nov]      14.2229
mnth[Dec]       0.3705
dtype: float64</code></pre>
</div>
</div>
<p>Finally, to make the plot neater, we’ll just use the first letter of each month, which is the <span class="math inline">\(6\)</span>th entry of each of the labels in the index.</p>
<div id="b9b83ef2" class="cell" data-execution_count="73">
<div class="sourceCode cell-code" id="cb114"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb114-1"><a href="#cb114-1" aria-hidden="true" tabindex="-1"></a>fig_month, ax_month <span class="op">=</span> subplots(figsize<span class="op">=</span>(<span class="dv">8</span>,<span class="dv">8</span>))</span>
<span id="cb114-2"><a href="#cb114-2" aria-hidden="true" tabindex="-1"></a>x_month <span class="op">=</span> np.arange(coef_month.shape[<span class="dv">0</span>])</span>
<span id="cb114-3"><a href="#cb114-3" aria-hidden="true" tabindex="-1"></a>ax_month.plot(x_month, coef_month, marker<span class="op">=</span><span class="st">'o'</span>, ms<span class="op">=</span><span class="dv">10</span>)</span>
<span id="cb114-4"><a href="#cb114-4" aria-hidden="true" tabindex="-1"></a>ax_month.set_xticks(x_month)</span>
<span id="cb114-5"><a href="#cb114-5" aria-hidden="true" tabindex="-1"></a>ax_month.set_xticklabels([l[<span class="dv">5</span>] <span class="cf">for</span> l <span class="kw">in</span> coef_month.index], fontsize<span class="op">=</span><span class="dv">20</span>)</span>
<span id="cb114-6"><a href="#cb114-6" aria-hidden="true" tabindex="-1"></a>ax_month.set_xlabel(<span class="st">'Month'</span>, fontsize<span class="op">=</span><span class="dv">20</span>)</span>
<span id="cb114-7"><a href="#cb114-7" aria-hidden="true" tabindex="-1"></a>ax_month.set_ylabel(<span class="st">'Coefficient'</span>, fontsize<span class="op">=</span><span class="dv">20</span>)<span class="op">;</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><a href="ch4-classification-lab_files/figure-html/cell-74-output-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-2"><img src="ch4-classification-lab_files/figure-html/cell-74-output-1.png" width="683" height="677" class="figure-img"></a></p>
</figure>
</div>
</div>
</div>
<p>Reproducing the right-hand plot in Figure 4.13 follows a similar process.</p>
<div id="0789810c" class="cell" data-execution_count="74">
<div class="sourceCode cell-code" id="cb115"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb115-1"><a href="#cb115-1" aria-hidden="true" tabindex="-1"></a>coef_hr <span class="op">=</span> S2[S2.index.<span class="bu">str</span>.contains(<span class="st">'hr'</span>)][<span class="st">'coef'</span>]</span>
<span id="cb115-2"><a href="#cb115-2" aria-hidden="true" tabindex="-1"></a>coef_hr <span class="op">=</span> coef_hr.reindex([<span class="st">'hr[</span><span class="sc">{0}</span><span class="st">]'</span>.<span class="bu">format</span>(h) <span class="cf">for</span> h <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">23</span>)])</span>
<span id="cb115-3"><a href="#cb115-3" aria-hidden="true" tabindex="-1"></a>coef_hr <span class="op">=</span> pd.concat([coef_hr,</span>
<span id="cb115-4"><a href="#cb115-4" aria-hidden="true" tabindex="-1"></a>                     pd.Series([<span class="op">-</span>coef_hr.<span class="bu">sum</span>()], index<span class="op">=</span>[<span class="st">'hr[23]'</span>])</span>
<span id="cb115-5"><a href="#cb115-5" aria-hidden="true" tabindex="-1"></a>                    ])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We now make the hour plot.</p>
<div id="e0a3b4a6" class="cell" data-execution_count="75">
<div class="sourceCode cell-code" id="cb116"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb116-1"><a href="#cb116-1" aria-hidden="true" tabindex="-1"></a>fig_hr, ax_hr <span class="op">=</span> subplots(figsize<span class="op">=</span>(<span class="dv">8</span>,<span class="dv">8</span>))</span>
<span id="cb116-2"><a href="#cb116-2" aria-hidden="true" tabindex="-1"></a>x_hr <span class="op">=</span> np.arange(coef_hr.shape[<span class="dv">0</span>])</span>
<span id="cb116-3"><a href="#cb116-3" aria-hidden="true" tabindex="-1"></a>ax_hr.plot(x_hr, coef_hr, marker<span class="op">=</span><span class="st">'o'</span>, ms<span class="op">=</span><span class="dv">10</span>)</span>
<span id="cb116-4"><a href="#cb116-4" aria-hidden="true" tabindex="-1"></a>ax_hr.set_xticks(x_hr[::<span class="dv">2</span>])</span>
<span id="cb116-5"><a href="#cb116-5" aria-hidden="true" tabindex="-1"></a>ax_hr.set_xticklabels(<span class="bu">range</span>(<span class="dv">24</span>)[::<span class="dv">2</span>], fontsize<span class="op">=</span><span class="dv">20</span>)</span>
<span id="cb116-6"><a href="#cb116-6" aria-hidden="true" tabindex="-1"></a>ax_hr.set_xlabel(<span class="st">'Hour'</span>, fontsize<span class="op">=</span><span class="dv">20</span>)</span>
<span id="cb116-7"><a href="#cb116-7" aria-hidden="true" tabindex="-1"></a>ax_hr.set_ylabel(<span class="st">'Coefficient'</span>, fontsize<span class="op">=</span><span class="dv">20</span>)<span class="op">;</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><a href="ch4-classification-lab_files/figure-html/cell-76-output-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-3"><img src="ch4-classification-lab_files/figure-html/cell-76-output-1.png" width="692" height="677" class="figure-img"></a></p>
</figure>
</div>
</div>
</div>
</section>
<section id="poisson-regression" class="level3" data-number="4.7.2">
<h3 data-number="4.7.2" class="anchored" data-anchor-id="poisson-regression"><span class="header-section-number">4.7.2</span> Poisson Regression</h3>
<p>Now we fit instead a Poisson regression model to the <code>Bikeshare</code> data. Very little changes, except that we now use the function <code>sm.GLM()</code> with the Poisson family specified:</p>
<div id="f93d7343" class="cell" data-execution_count="76">
<div class="sourceCode cell-code" id="cb117"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb117-1"><a href="#cb117-1" aria-hidden="true" tabindex="-1"></a>M_pois <span class="op">=</span> sm.GLM(Y, X2, family<span class="op">=</span>sm.families.Poisson()).fit()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We can plot the coefficients associated with <code>mnth</code> and <code>hr</code>, in order to reproduce Figure 4.15. We first complete these coefficients as before.</p>
<div id="7429583e" class="cell" data-execution_count="77">
<div class="sourceCode cell-code" id="cb118"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb118-1"><a href="#cb118-1" aria-hidden="true" tabindex="-1"></a>S_pois <span class="op">=</span> summarize(M_pois)</span>
<span id="cb118-2"><a href="#cb118-2" aria-hidden="true" tabindex="-1"></a>coef_month <span class="op">=</span> S_pois[S_pois.index.<span class="bu">str</span>.contains(<span class="st">'mnth'</span>)][<span class="st">'coef'</span>]</span>
<span id="cb118-3"><a href="#cb118-3" aria-hidden="true" tabindex="-1"></a>coef_month <span class="op">=</span> pd.concat([coef_month,</span>
<span id="cb118-4"><a href="#cb118-4" aria-hidden="true" tabindex="-1"></a>                        pd.Series([<span class="op">-</span>coef_month.<span class="bu">sum</span>()],</span>
<span id="cb118-5"><a href="#cb118-5" aria-hidden="true" tabindex="-1"></a>                                   index<span class="op">=</span>[<span class="st">'mnth[Dec]'</span>])])</span>
<span id="cb118-6"><a href="#cb118-6" aria-hidden="true" tabindex="-1"></a>coef_hr <span class="op">=</span> S_pois[S_pois.index.<span class="bu">str</span>.contains(<span class="st">'hr'</span>)][<span class="st">'coef'</span>]</span>
<span id="cb118-7"><a href="#cb118-7" aria-hidden="true" tabindex="-1"></a>coef_hr <span class="op">=</span> pd.concat([coef_hr,</span>
<span id="cb118-8"><a href="#cb118-8" aria-hidden="true" tabindex="-1"></a>                     pd.Series([<span class="op">-</span>coef_hr.<span class="bu">sum</span>()],</span>
<span id="cb118-9"><a href="#cb118-9" aria-hidden="true" tabindex="-1"></a>                     index<span class="op">=</span>[<span class="st">'hr[23]'</span>])])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The plotting is as before.</p>
<div id="55a1ceac" class="cell" data-execution_count="78">
<div class="sourceCode cell-code" id="cb119"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb119-1"><a href="#cb119-1" aria-hidden="true" tabindex="-1"></a>fig_pois, (ax_month, ax_hr) <span class="op">=</span> subplots(<span class="dv">1</span>, <span class="dv">2</span>, figsize<span class="op">=</span>(<span class="dv">16</span>,<span class="dv">8</span>))</span>
<span id="cb119-2"><a href="#cb119-2" aria-hidden="true" tabindex="-1"></a>ax_month.plot(x_month, coef_month, marker<span class="op">=</span><span class="st">'o'</span>, ms<span class="op">=</span><span class="dv">10</span>)</span>
<span id="cb119-3"><a href="#cb119-3" aria-hidden="true" tabindex="-1"></a>ax_month.set_xticks(x_month)</span>
<span id="cb119-4"><a href="#cb119-4" aria-hidden="true" tabindex="-1"></a>ax_month.set_xticklabels([l[<span class="dv">5</span>] <span class="cf">for</span> l <span class="kw">in</span> coef_month.index], fontsize<span class="op">=</span><span class="dv">20</span>)</span>
<span id="cb119-5"><a href="#cb119-5" aria-hidden="true" tabindex="-1"></a>ax_month.set_xlabel(<span class="st">'Month'</span>, fontsize<span class="op">=</span><span class="dv">20</span>)</span>
<span id="cb119-6"><a href="#cb119-6" aria-hidden="true" tabindex="-1"></a>ax_month.set_ylabel(<span class="st">'Coefficient'</span>, fontsize<span class="op">=</span><span class="dv">20</span>)</span>
<span id="cb119-7"><a href="#cb119-7" aria-hidden="true" tabindex="-1"></a>ax_hr.plot(x_hr, coef_hr, marker<span class="op">=</span><span class="st">'o'</span>, ms<span class="op">=</span><span class="dv">10</span>)</span>
<span id="cb119-8"><a href="#cb119-8" aria-hidden="true" tabindex="-1"></a>ax_hr.set_xticklabels(<span class="bu">range</span>(<span class="dv">24</span>)[::<span class="dv">2</span>], fontsize<span class="op">=</span><span class="dv">20</span>)</span>
<span id="cb119-9"><a href="#cb119-9" aria-hidden="true" tabindex="-1"></a>ax_hr.set_xlabel(<span class="st">'Hour'</span>, fontsize<span class="op">=</span><span class="dv">20</span>)</span>
<span id="cb119-10"><a href="#cb119-10" aria-hidden="true" tabindex="-1"></a>ax_hr.set_ylabel(<span class="st">'Coefficient'</span>, fontsize<span class="op">=</span><span class="dv">20</span>)<span class="op">;</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>/tmp/ipykernel_2792394/3779510511.py:8: UserWarning: FixedFormatter should only be used together with FixedLocator
  ax_hr.set_xticklabels(range(24)[::2], fontsize=20)</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><a href="ch4-classification-lab_files/figure-html/cell-79-output-2.png" class="lightbox" data-gallery="quarto-lightbox-gallery-4"><img src="ch4-classification-lab_files/figure-html/cell-79-output-2.png" width="1283" height="677" class="figure-img"></a></p>
</figure>
</div>
</div>
</div>
<p>We compare the fitted values of the two models. The fitted values are stored in the <code>fittedvalues</code> attribute returned by the <code>fit()</code> method for both the linear regression and the Poisson fits. The linear predictors are stored as the attribute <code>lin_pred</code>.</p>
<div id="19e73df5" class="cell" data-execution_count="79">
<div class="sourceCode cell-code" id="cb121"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb121-1"><a href="#cb121-1" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> subplots(figsize<span class="op">=</span>(<span class="dv">8</span>, <span class="dv">8</span>))</span>
<span id="cb121-2"><a href="#cb121-2" aria-hidden="true" tabindex="-1"></a>ax.scatter(M2_lm.fittedvalues,</span>
<span id="cb121-3"><a href="#cb121-3" aria-hidden="true" tabindex="-1"></a>           M_pois.fittedvalues,</span>
<span id="cb121-4"><a href="#cb121-4" aria-hidden="true" tabindex="-1"></a>           s<span class="op">=</span><span class="dv">20</span>)</span>
<span id="cb121-5"><a href="#cb121-5" aria-hidden="true" tabindex="-1"></a>ax.set_xlabel(<span class="st">'Linear Regression Fit'</span>, fontsize<span class="op">=</span><span class="dv">20</span>)</span>
<span id="cb121-6"><a href="#cb121-6" aria-hidden="true" tabindex="-1"></a>ax.set_ylabel(<span class="st">'Poisson Regression Fit'</span>, fontsize<span class="op">=</span><span class="dv">20</span>)</span>
<span id="cb121-7"><a href="#cb121-7" aria-hidden="true" tabindex="-1"></a>ax.axline([<span class="dv">0</span>,<span class="dv">0</span>], c<span class="op">=</span><span class="st">'black'</span>, linewidth<span class="op">=</span><span class="dv">3</span>,</span>
<span id="cb121-8"><a href="#cb121-8" aria-hidden="true" tabindex="-1"></a>          linestyle<span class="op">=</span><span class="st">'--'</span>, slope<span class="op">=</span><span class="dv">1</span>)<span class="op">;</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><a href="ch4-classification-lab_files/figure-html/cell-80-output-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-5"><img src="ch4-classification-lab_files/figure-html/cell-80-output-1.png" width="681" height="664" class="figure-img"></a></p>
</figure>
</div>
</div>
</div>
<p>The predictions from the Poisson regression model are correlated with those from the linear model; however, the former are non-negative. As a result the Poisson regression predictions tend to be larger than those from the linear model for either very low or very high levels of ridership.</p>
<p>In this section, we fit Poisson regression models using the <code>sm.GLM()</code> function with the argument <code>family=sm.families.Poisson()</code>. Earlier in this lab we used the <code>sm.GLM()</code> function with <code>family=sm.families.Binomial()</code> to perform logistic regression. Other choices for the <code>family</code> argument can be used to fit other types of GLMs. For instance, <code>family=sm.families.Gamma()</code> fits a Gamma regression model.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./ch3-linreg-lab.html" class="pagination-link" aria-label="Lab Chapter 3: Linear Regression">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Lab Chapter 3: Linear Regression</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./ch5-resample-lab.html" class="pagination-link" aria-label="Lab Chapter 5: Cross-Validation and the Bootstrap">
        <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Lab Chapter 5: Cross-Validation and the Bootstrap</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Copyright 2025, Juergen Jung</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item compact">
    <a class="nav-link" href="https://juejung.github.io/">
      <i class="bi bi-github" role="img">
</i> 
    </a>
  </li>  
</ul>
    </div>
  </div>
</footer>
<script>var lightboxQuarto = GLightbox({"closeEffect":"zoom","descPosition":"bottom","loop":false,"openEffect":"zoom","selector":".lightbox"});
(function() {
  let previousOnload = window.onload;
  window.onload = () => {
    if (previousOnload) {
      previousOnload();
    }
    lightboxQuarto.on('slide_before_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      const href = trigger.getAttribute('href');
      if (href !== null) {
        const imgEl = window.document.querySelector(`a[href="${href}"] img`);
        if (imgEl !== null) {
          const srcAttr = imgEl.getAttribute("src");
          if (srcAttr && srcAttr.startsWith("data:")) {
            slideConfig.href = srcAttr;
          }
        }
      } 
    });
  
    lightboxQuarto.on('slide_after_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(slideNode);
      }
    });
  
  };
  
})();
          </script>




</body></html>